### ISSUE TITLE
oronavirus: richiesta di disponibilità alle aziende e indicazioni tecniche per la produzione di masc

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1002]
<pre><yamldata>
Cosa: 'oronavirus: richiesta di disponibilità alle aziende e indicazioni tecniche
  per la produzione di mascherine e dispositivi di protezione individuale (DPI)'
Descrizione: Regione Lombardia cerca urgentemente aziende produttrici di mascherine
Destinatari: Aziende
Email: DPIcoronavirus@regione.lombardia.it
Indirizzo: 45.508753 9.17676 0 0
Link: https://www.regione.lombardia.it/wps/portal/istituzionale/HP/DettaglioAvviso/istituzione/attivita-istituzionali/avv-mascherine-made-in-italy
</yamldata></pre>

**Comment by chiccap** [comment]
presente #996
