### ISSUE TITLE
VitaminaG

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1015]
<pre><yamldata>
Da_chi_offerta: Regione Lazio
Descrizione: Vitamina G - Il bando delle idee, è la nuova iniziativa della Regione
  Lazio che vuole dare energia alle idee degli under 35 con un contributo fino a 25
  mila euro a fondo perduto
Destinatari: gruppi giovanili e associazioni giovanili
Link: http://www.regione.lazio.it/rl/vitaminag/
Natura: sostegno-lavor
Titolo: VitaminaG
</yamldata></pre>

**Comment by chiccap** [comment]
@cristigalas dal sito mi sembra che le presentazioni pubbliche siano (ovviamente) state annulate e comunque non bando legato a situazione covid19, non accetterei

**Comment by cristigalas** [comment]
Sì, non accettare.
