### ISSUE TITLE
#iorestoacasa

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1019]
<pre><yamldata>
Da_chi_offerta: confesercenti Torino e provincia
Descrizione: consegne  domincilio negozianti sul territori di torino e province limitrofe
Link: https://www.confesercenti-to.it/generale/iorestoacasa-riduci-al-minimo-i-tuoi-spostamenti-ai-tuoi-acquisti-ci-pensiamo-noi-consegne-a-domicilio-dal-tuo-negoziante-di-fiducia/
Natura: solidale
Tipo_di_soggetto: privato
Titolo: '#iorestoacasa'
</yamldata></pre>

**Comment by Saraveg** [comment]
Già presente https://github.com/emergenzeHack/covid19italia_segnalazioni/issues/760
