### ISSUE TITLE
Probabile bufala video dal Giappone

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1021]
<pre><yamldata>
Cosa: Probabile bufala video dal Giappone
Descrizione: 'Il video circola su Facebook, di seguito il link.

  https://m.facebook.com/story.php?story_fbid=1493246167503753&id=100004551510967?sfnsn=scwspwa&d=w&vh=i&extid=GaMfYFUjVJqYj066&d=w&vh=i'
</yamldata></pre>

**Comment by chiccap** [comment]
presente #1012
