### ISSUE TITLE
Video circolante su facebook senza basi scientifiche

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1033]
<pre><yamldata>
Cosa: Video circolante su facebook senza basi scientifiche
Descrizione: Mi è stato fatto notare il video in link. Ci sono speculazioni sulla
  diffusione del virus. Non ci sono vere basi scientifiche e rischia di minare la
  tranquillità degli italiani, soprattutto in un momento così delicato per tutti.
Link: https://www.facebook.com/1840253805/posts/10212873244746140/?sfnsn=scwspwa&extid=k8naE8r2Pr5DvW2Y&d=w&vh=i
</yamldata></pre>

**Comment by chiccap** [comment]
presente #1016
