### ISSUE TITLE
Video di disinformazione

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1036]
<pre><yamldata>
Cosa: Video di disinformazione
Descrizione: "Questo video, ormai virale, sta raggiungendo molti e scatenando pericolose\
  \ reazioni. Non è supportato da alcuna evidenza scientifica, mira a creare insicurezza\
  \ e a diffondere notizie false. \nIl personaggio in questione, tra l’altro, non\
  \ è nuovo a video riguardanti complotti di ogni sorta. Per rispetto delle vittime,\
  \ di chi è in prima linea per questa emergenza e per la scienza vi prego di farne\
  \ una revisione e segnalarlo. \nIn questo momento insinuazioni di questo genere\
  \ possono essere molto pericolose. Grazie"
Link: https://youtu.be/t_ub8R5l73w
</yamldata></pre>

**Comment by chiccap** [comment]
presente #1016
