### ISSUE TITLE
Non è vero che il COVID-19 non esiste 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1040]
<pre><yamldata>
Cosa: Bufala non esiste coronavirus
Descrizione: https://www.ingannati.it/2020/03/06/ancora-su-border-nights-martedi-17-marzo-2020/
Link: https://www.ingannati.it/2020/03/06/ancora-su-border-nights-martedi-17-marzo-2020/
</yamldata></pre>

**Comment by cristigalas** [comment]
@chiccap il link non si capisce dove porti... non accetterei.
