### ISSUE TITLE
Raccolta Fondi Cityplex Palermo per Ospedale Cervello #Palermo

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1052]
<pre><yamldata>
Descrizione: "L'emergenza COVID-19 sta creando serie difficoltà al nostro sistema\
  \ sanitario nazionale. Siamo vicini al personale medico sanitario che ogni giorno\
  \ lotta per salvare delle vite e vogliamo fare la nostra parte per potenziare il\
  \ reparto di Pneumologia COVID-19 dell'Ospedale Cervello di Palermo. \n\nDi seguito\
  \ una lettera aperta che abbiamo ricevuto dal Dott. Giuseppe Arcoleo, che si occupa\
  \ della direzione del nuovo reparto di Pneumologia semintensiva Covid19:   \"Mi\
  \ chiamo Giuseppe Arcoleo, sono uno pneumologo dell' Ospedale \"Cervello\" di Palermo\
  \ e mi occupo della direzione del nuovo reparto di Pneumologia semintensiva Covid19.\
  \ Siamo tutti impegnati, pneumologi, anestesisti, infermieri, OSS, allo stremo delle\
  \ nostre forze, in turni massacranti che sovvertono la nostra routine quotidiana\
  \ e che ci tengono lontani dai nostri bambini e dalla nostra famiglia. Abbiamo paura,\
  \ prima che per noi, per i nostri cari, così tanto da non riuscire a dormire la\
  \ notte nemmeno dopo 12 estenuanti ore di turno in corsia, ma ci facciamo coraggio\
  \ e combattiamo, giorno dopo giorno, contro questo subdolo e meschino nemico che\
  \ ci toglie il fiato. Toglie il fiato a noi sanitari, trincerati dietro queste soffocanti\
  \ mascherine e tute che ci tutelano dal contagio. Toglie il fiato a tutti coloro\
  \ che ne rimangono vittime e che vediamo annaspare e chiedere aiuto. Li supportiamo,\
  \ oltre che umanamente, soprattutto fornendo loro quell’aria che gli manca. Se siamo\
  \ fortunati basta solo un supplemento di ossigeno. Gli altri, meno fortunati, richiedono\
  \ l’aiuto di un ventilatore che fornisce loro, durante l’inspirazione e l’espirazione,\
  \ una pressione positiva. I malati sono tanti e i posti letto in reparto si riempiono\
  \ di ora in ora. \n\nI ventilatori già in dotazione dell’azienda, seppur incrementati\
  \ in vista dell’emergenza sanitaria, non basteranno per tutti. Fate anche voi la\
  \ vostra parte, restando a casa e, se potete, donando un piccolo contributo che\
  \ potrebbe essere importante per salvare delle vite. Aiutateci ad aiutarvi.\" Il\
  \ nostro obiettivo è di unire le forze e di sfruttare la visibilità dei nostri multisala\
  \ per raccogliere quanti più fondi possibile con i quali compreremo ventilatori,\
  \ dispositivi di protezione e tutto quello che può essere necessario al reparto\
  \ il prima possibile. Ciò che acquisteremo verrà direttamente inviato all'ospedale\
  \ Cervello e i donatori verranno informati con le ricevute di acquisto dei beni\
  \ e con foto comprovanti l'effettivo utilizzo. \n\nChi si occuperà degli acquisti\
  \ è l'azienda Karisma Srl, con sede a Palermo, che gestisce i cinema multisala Cityplex.\
  \ \n\nUna piccola donazione, che può anche corrispondere al costo del biglietto\
  \ che solitamente acquistate per entrare in sala, può fare tanto e salvare vite\
  \ umane.  PER ESSERE DEI SUPEREROI BASTA UN CLICK! DONATE!"
Link: https://www.gofundme.com/f/covid-19-diamo-una-mano-all039ospedale-cervello
Nome: Covid 19 - Raccolta Fondi Cityplex Palermo per Ospedale Cervello Palermo
Posizione: 38.155026 13.31279 0 0
</yamldata></pre>

**Comment by luciaroma** [comment]
raccolta fondi chiusa
