### ISSUE TITLE
Raccolta fondi Policlinico Paolo Giaccone #Palermo 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1053]
<pre><yamldata>
Descrizione: 'Questa raccolta fondi per il Policlinico "Paolo Giaccone" di Palermo
  e'' supportata e coadiuvata dall''ASSOCIAZIONE PALERMO MEDITERRANEA del Dott. Andrea
  Parlato e approvata da medici responsabili dell''area finanziaria dell’ospedale
  (Dott. Guadagnino e D.ssa Salerno).

  SERVE URGENTEMENTE:

  - MATERIALE DI PROTEZIONE INDIVIDUALE (MASCHERINE, GUANTI, TUTE E CAMICI STERILI)

  - MONITOR MULTIPARAMETRICI

  - VENTILATORI POLMONARI

  Per contatti: +39 347 45 62 359'
Link: https://www.gofundme.com/f/aiutiamolospedalepoliclinicodipalermo
Nome: Raccolta Fondi -Aiutiamo l'Ospedale Policlinico di Palermo
Posizione: 38.104879 13.36077 0 0
</yamldata></pre>

**Comment by luciaroma** [comment]
donazione chiusa
