### ISSUE TITLE
Bufala degli sconti da 200 euro nei supermercati

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1056]
<pre><yamldata>
Cosa: Bufala degli sconti da 200 euro nei supermercati
Descrizione: "Salve, volevo segnalare questa bufala che sta girando in rete in questi\
  \ giorni, e, soprattutto, chiedere un consiglio se possibile, riguardo a cosa fare\
  \ nel caso siano stati inseriti dei dati. \nIn pratica, i miei genitori hanno ricevuto\
  \ questo link, e uno di loro lo ha cliccato, cascandoci in pieno. All'insaputa di\
  \ tutti, ha inserito i dati del coniuge (nome e cognome, età, mail, codice fiscale\
  \ e la via dell'abitazione). Per fortuna, sono intervenuto prima che riuscisse a\
  \ completare l'iscrizione, presumo. Tuttavia non so se il mio intervento sia stato\
  \ in tempo oppure no, perché i dati sono stati inseriti e nel momento nel quale\
  \ mi sono accorto di quanto stesse accadendo, il mio genitore stava procedendo a\
  \ compilare un sondaggio. \nC'è qualche rischio di cui preoccuparsi oltre all'invio\
  \ di spam o solita chiamata telefonica dei truffatori? Il fatto che più mi preoccupa\
  \ è l'inserimento della via abitativa."
Posizione: 45.546755 10.225525 0 0
</yamldata></pre>

**Comment by chiccap** [comment]
presente #968
