### ISSUE TITLE
Help with COVID Offers

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1057]
<pre><yamldata>
Da_chi_offerta: Help with COVID
Descrizione: Offers, deals, and benefits from organizations that want to help out
  with COVID-19.
Destinatari: Tutti
Link: https://helpwithcovid.com/offers
Natura: solidale
Posizione: 37.775345 -122.418981 0 0
Tipo_di_soggetto: privato
Titolo: Help with COVID Offers
</yamldata></pre>

**Comment by chiccap** [comment]
presente #1054
