### ISSUE TITLE
Coronavirus: richiesta di disponibilità alle aziende per la produzione di materiale per l'emergenza 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1058]
<pre><yamldata>
Cosa: 'Coronavirus: richiesta di disponibilità alle aziende per la produzione di materiale
  per l''emergenza Coronavirus'
Descrizione: Si cercano aziende che siano in grado di produrre mascherine e/o DPI
  (Dispositivi di Protezione Individuale) idonei anche alla luce di quanto disposto
  dagli artt. 15 e 16 del D.L. 18/2020.
Link: https://www.regione.lombardia.it/wps/portal/istituzionale/HP/DettaglioAvviso/istituzione/attivita-istituzionali/avv-mascherine-made-in-italy
Posizione: 0 0 0 0
</yamldata></pre>

**Comment by chiccap** [comment]
presente #996
