### ISSUE TITLE
Indagine del CNR sui Mutamenti Sociali in Atto (MSA COVID19)

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1059]
<pre><yamldata>
Cosa: Indagine del CNR sui Mutamenti Sociali in Atto (MSA COVID19)
Descrizione: 'Richiesta di compilare un QUESTIONARIO ON LINE

  “Mutamenti Sociali in Atto-COVID19” (MSA-COVID19) è un’indagine del Consiglio Nazionale
  delle Ricerche (CNR-Irpps) su atteggiamenti e comportamenti della popolazione nell’emergenza
  COVID19 in relazione al “distanziamento sociale”. L’emanazione dei decreti #IoRestoaCasa
  da parte del Consiglio dei Ministri in materia di spostamento delle persone fisiche
  all’interno del territorio nazionale ha richiesto un cambiamento improvviso e radicale
  delle abitudini e degli stili di vita degli italiani producendo una drastica riduzione
  di ogni forma di lavoro e socialità.

  L’indagine ha lo scopo di analizzare gli atteggiamenti e i comportamenti della popolazione
  dovuti al “distanziamento sociale” al fine di valutarne le conseguenze e i correttivi
  nel breve e medio periodo per arginare l’insorgenza di stati critici a livello psicofisico
  prodotti dall’assenza di lavoro e socialità.'
Link: https://www.irpps.cnr.it/eventi/indagine-sui-mutamenti-sociali-in-atto-msa-covid19/
</yamldata></pre>

**Comment by chiccap** [comment]
@cristigalas non pubblicherei

**Comment by cristigalas** [comment]
Ok chiudi.
