### ISSUE TITLE
Le attività spaziano per il tipo e il target a cui sono rivolti.
Attraverso una piattaforma online s

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1068]
<pre><yamldata>
Da_chi_offerta: Malegno Comunità Che Edu a
Descrizione: 'Le attività spaziano per il tipo e il target a cui sono rivolti.

  Attraverso una piattaforma online si cerca di ritrovare una comunità per vedersi,
  parlare e divertirsi. Un modo per prendersi cura della salute mentale dei cittadini.

  Le attività: la preghiera del don, letture per bambini, mindfulness, laboratori
  creativi, spazi per raccontare esperienze positive, laboratori di pittura, gioco
  con enigmi, palestra di ginnastica dolce, fitness, trucco'
Destinatari: Famiglie
Link: https://www.facebook.com/malegnocomunitaeduca/?ref=aymt_homepage_panel&eid=ARABWZPmp7LHwn3T98s_S6EG0w7xOVpgsJL_CQ26Aei7_vi7gN1HTxzVjuSziJa6oOmv2RXHY3emhg2v
Natura: culturale-ricr
Posizione: 45.951103 10.270522 0 0
</yamldata></pre>

**Comment by cristigalas** [comment]
Non è chiaro cosa offrono e quale sia questa piattaforma...
