### ISSUE TITLE
Ortomercato Milano

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1074]
<pre><yamldata>
Cosa: Ortomercato Milano
Descrizione: 'Gentilissimi, è possibile sensibilizzare i vertici di Sogemi affinché
  aiutino gli operatori nella gestione quotidiana in questo momento di emergenza?
  Sono necessarie delle modifiche agli orari e agli ingressi al fine di tutelare operai
  e clienti.

  Grazie'
Destinatari: Organi direttivi
Email: danibif@hotmail.com
Indirizzo: 45.46679408 9.1903474
Telefono: '3406420446'
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 45.46679408 9.1903474 (Milano) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=45.46679408+9.1903474&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by claudiamazzantiact** [comment]
Che facciamo con questa segnalazione?

**Comment by luciaroma** [comment]
potremmo invitarli a fare una richiesta più specifica e magari poi la segnaliamo taggando la società (un pò come facevamo in centro italia)?
Potremmo parallelamente verificare con qualche milanese actionaider

**Comment by cristigalas** [comment]
@luciaroma inviamo una email chiedendo più info per capire meglio quale sia il problema e chi è che scrive?

**Comment by claudiamazzantiact** [comment]
@cristigalas e @luciaroma a questa segnalazione non è stato dato èpiù seguito?

**Comment by claudiamazzantiact** [comment]
Riprendiamo questa issue, @chiccap @luciaroma e @cristigalas ?

**Comment by cristigalas** [comment]
@claudiamazzantiact l’unica e inviare email con richiesta di maggiori info... può darsi che nel frattempo la situazione sia migliorata...

**Comment by luciaroma** [comment]
sì concordo, procedi tu @claudiamazzantiact ?

**Comment by cristigalas** [comment]
@chiccap @luciaroma @claudiamazzantiact io direi di chiudere, che dite?

**Comment by chiccap** [comment]
sì sono d'accordo!
