### ISSUE TITLE
gli extracomunitari non prendono il virus

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1079]
<pre><yamldata>
Cosa: gli extracomunitari non prendono il virus
Descrizione: 'gira su whatsapp questo messaggio.. cosa ne pensate?

  "Ringraziandoti perche'' sei sempre attento su quello che ci circonda, pregherei
  di prendere in considerazione questa ipotesi sul Coronavirus. Sequi ed approfondisci
  questa pista.

  In tutta la Lombardia, dove abito, ho interpellato gli Ospedali Civili di Brescia,
  Cremona, Chiari, e...in quasi 2000 ricoverati in terapia intensiva, sorpresa! non
  c''e'' un extraocmunitario!!! Che abbia il Coronavirus. Possibile? che sono tutti
  sani? Allora: a BorgoSan Giacomo, sdolo gli italiani hanno preso il Corona. Come
  mai? Sono 5000 abitanti di cui 3500 indiani e 1500 italiani, giovani e vecchi. Gli
  indiani giovani e vecchi: 50 e 60 enni in numero importante. Cosa mi dicono gli
  indiani: noi non la prendiamo la polmonite. Il corona si, ma e'' una normale influenza,
  a noi non viene la polmonite perche'' siamo vaccinati contro la Tubercolosi. Un
  giorno e passa. Solo voi italiani che non siete piu'' vaccinati (il vaccino dura
  20 anni e se non c''e'' richiamo vaccinale si rende di nuovo esposti a polmonite)
  dalla tubercolosi vi ammalate, prima di influenza ma poi di polmonite. Soprattutto
  gli anziani, che ormai e'' da 40 anni che non fanno richiami. Cosi i bambini italiani
  non si ammalano (non di Corona...che attiva la Tubercolosi) di polmonite perche''
  sono vaccinati contro la TBC. Vaccino che dura fino a 19/20 anni. Ovviamente anche
  i vostri ventenni cominciano ad ammalarsi di Cov e Tubercolosi. Perche'' da Voi
  non c''e'' piu l''obbligo di fare il richiamo. Ma Pensa!!!! La Lombardia ha la piu''
  alta concentrazione di Extracomunitari, Senegalesi, Bengalesi, Egiziani, Marocchini,
  Rumeni, Albanesi, Tunisini, Algerini...MAH....non c''e'' uno con la polmonite?!?!?!
  Perche'' sono giovani???? Noooooooo....perche'' sono tutti coperti da vaccino Tubercolosi,
  che e'' un protocollo di copertura previsto (DALLE ASL) per gli extracomunitari!!!!!

  Ho chiamo tutti gli ospedali, non c''e'' un extracomunitario di qualsiasi eta''
  positivo o ricoverato per COV19!!!!!!!!!! Come e'' possibile!?!?!? Solo gli italiani....ovvio..."'
Posizione: 45.365172 10.432205 0 0
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Segnalazione inaccettabile!
