### ISSUE TITLE
Foto

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1081]
<pre><yamldata>
Cosa: Foto
Descrizione: Gira su FB una foto che ritrae lunghe file di macchine all'imbarco dello
  Stretto di Messina verso la Sicilia. E' mai possibile? Potrebbe trattarsi di una
  bufala o di una foto scattata in altro periodo e contesto? Grazie
</yamldata></pre>

**Comment by favoeva** [comment]
Manca la foto
