### ISSUE TITLE
#Palermo, coronavirus: Consegna #libri a #domicilio-#ModusExpress

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1083]
<pre><yamldata>
Da_chi_offerta: Modusvivendi Libreria -Palermo
Descrizione: "#Modusvivendi invece attiva il servizio “Modus express”: \nsi può prenotare\
  \ dalle 9,30 alle 12,30 e dalle 16,30 alle 19,30 attraverso i numeri \n389 13 91\
  \ 289, \n349 21 63 533  \n349 41 56957 \noppure attraverso i #social.\n\n Le consegne\
  \ sono gratuite per gli ordini superiori ai 30 euro e vengono garantite in 24 ore."
Destinatari: lettori
Link: https://www.facebook.com/modusvivendi.libreria/
Natura: culturale-ricr
Posizione: 38.126849 13.354791 0 0
Titolo: '#Palermo, coronavirus: Consegna #libri a #domicilio-#ModusExpress'
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Già inserita #1082
