### ISSUE TITLE
Fondazione Èbbene lancia campagna di solidarietà a supporto di iniziative contro coronavirus (English)

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1090]
<pre><yamldata>
Descrizione: 'Even in emergency the proximity doesn''t stop. Across the national territory
  the welfare system is suffering the difficulties and consequences of the crisis
  generated by Covid-19: the assistance and hospitality centres are on the balance,
  people without fixed abode are at risk of contagion and families living disability
  is left alone.

  Foundation Well responds by not stopping the proximity and continuing, together
  with its centres, the listening and accompaniment action of the most fragile people
  to prevent this isolation time from excluding them more.

  All this requires a non-indifferent organizational and economic effort and that''s
  why we also need your contribution.

  Neighborhood doesn''t stop, support it.

  To deepen the campaign: bit.ly/laprossimitànonsifermaebbene'
Link: https://www.facebook.com/donate/205509194049391/2781719468542312/
Nome: Fondazione Ebbene
</yamldata></pre>

**Comment by chiccap** [comment]
Raccolta fondi terminata!
