### ISSUE TITLE
Your donation to this Fundraiser will go further, thanks to Facebook's matching contribution of US$1

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1091]
<pre><yamldata>
Descrizione: 'Your donation to this Fundraiser will go further, thanks to Facebook''s
  matching contribution of US$10 million.

  Your donation to the COVID-19 Solidarity Response Fund supports the World Health
  Organization''s global efforts to combat the COVID-19 pandemic.

  Donations support efforts to track and understand the spread of the virus; to ensure
  patients get the care they need and frontline workers get essential supplies and
  information; and to accelerate efforts to develop vaccines, tests, and treatments.
  We''re all in this fight together. The COVID-19 Solidarity Response Fund is powered
  by the UN Foundation and Swiss Philanthropy Foundation.'
Link: https://www.facebook.com/donate/1564752357011737/
Nome: United Nations Foundation
</yamldata></pre>

**Comment by cristigalas** [comment]
Lascerei perdere...
