### ISSUE TITLE
Bufala che gira su WA

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1098]
<pre><yamldata>
Cosa: Bufala che gira su WA
Descrizione: "Buongiorno,\nho ricevuto il testo qui sotto gia` due volte questa mattina.\
  \ Credo vada segnalato e bloccato sul nascere. Due cose da notare:\n1) il vaccino\
  \ per la tb e` obbligatorio in Cina (riferitomi da un amico cinese, magari da confermare)\n\
  2) La tb e` una malattia batterica, non sono un esperto ma dubito che lo stesso\
  \ vaccino possa avere alcun effetto su una malattia virale. \nMa.... non voglio\
  \ fare il vostro lavoro, che vedo sapete fare egregiamente.\nSaluti\nAldo\n\n\n\n\
  \nIn tutta la Lombardia, interpellata, gli Ospedali Civili di Bergamo, di Brescia,\
  \ Cremona, Chiari, e..in quasi 2.000 ricoverati in terapia intensiva.. sorpresa!\
  \ non risulta nessun extracomunitario \nche abbia il Covid 19.\nPossibile che siano\
  \  tutti sani?\nAllora faccio un esempio, a Borgo San Giacomo, solo gli italiani\
  \ hanno preso il Covid19. Come mai? Sono 5.000 abitanti di cui 3.500 indiani e 1.500\
  \ italiani, giovani e vecchi. Gli indiani giovani e vecchi: 50 e 60 enni sono in\
  \ un numero importante. Cosa dicono gli indiani: noi non lo prendiamo  Il corona..\
  \ boh... forse per noi è una normale influenza, a noi non viene la polmonite perche'\
  \ siamo vaccinati contro la Tubercolosi. Quando ci ammaliamo dopo uno, due giorni\
  \ passa. Solo voi italiani che non siete piu' vaccinati (il vaccino dura 20 anni\
  \ e se non c'è nessun richiamo vaccinale forse siete di nuovo esposti a polmonite)\
  \ dalla tubercolosi e vi ammalate, prima di influenza ma poi di polmonite. Soprattutto\
  \ gli anziani, che ormai è da 40 anni che non fanno richiami. Cosi i bambini italiani\
  \ non si ammalano (non di Corona...che attiva la Tubercolosi) di polmonite perche'\
  \ sono vaccinati contro la TBC. Vaccino che dura fino a 19/20 anni. Ovviamente anche\
  \ i vostri ventenni cominciano ad ammalarsi di Cov e Tubercolosi. Perche' da Voi\
  \ non c'e' piu l'obbligo di fare il richiamo. \nMa Pensa!! La Lombardia ha la piu'\
  \ alta concentrazione di Extracomunitari: Senegalesi, Bengalesi, Egiziani, Marocchini,\
  \ Rumeni, Albanesi, Tunisini, Algerini...e non c'è ne manco uno con la polmonite?!?\
  \ Perche' sono giovani?? Noo...perche' sono tutti coperti da vaccino Tubercolosi,\
  \ che e' un protocollo di copertura previsto (DALLE ASL) per gli extracomunitari!!\n\
  Fate una verifica e vedrete che in tutti gli ospedali, non c'è un extracomunitario\
  \ di qualsiasi eta' positivo o ricoverato per COV19!!\nCome e' possibile!?!\nSolo\
  \ gli italiani....allora..."
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Per ora ho messo non accettato. La #1079 è stata chiusa ma penso dovremo fare un post su questo.
