### ISSUE TITLE
Trovata su fb

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1111]
<pre><yamldata>
Cosa: Trovata su fb
Descrizione: "E QUESTA QUALCUNO ME LA DEVE SPIEGARE!!!! \n\nSe reale bisogna fare\
  \ una rivoluzione!!!\n\nQuindi la considerazione è questa ipotesi sul Coronavirus.\n\
  Leggere con calma. \nIn tutta la Lombardia, dove abito, ho interpellato gli Ospedali\
  \ di Bergamo, Civili di Brescia, Cremona, Chiari, e...in quasi 2000 ricoverati in\
  \ terapia intensiva... sorpresa!\nnon risulta nessun extracomunitario \nhe abbia\
  \ il Coronavirus. Possibile che siano  tutti sani?\nAllora faccio un esempio, a\
  \ Borgo San Giacomo, solo gli italiani hanno preso il Covid19.Come mai? Sono 5000\
  \ abitanti di cui 3500 indiani e 1500 italiani, giovani e vecchi. Gli indiani giovani\
  \ e vecchi: 50 e 60 enni sono in un numero importante. Cosa mi dicono gli indiani:\
  \ noi non lo prendiamo  Il corona... boh... forse per noi è una normale influenza,\
  \ a noi non viene la polmonite perche' siamo vaccinati contro la Tubercolosi. Quando\
  \ ci ammaliamo dopo uno, due giorni passa. Solo voi italiani che non siete piu'\
  \ vaccinati (il vaccino dura 20 anni e se non c'è nessun richiamo vaccinale forse\
  \ siete di nuovo esposti a polmonite) dalla tubercolosi e vi ammalate, prima di\
  \ influenza ma poi di polmonite. Soprattutto gli anziani, che ormai è da 40 anni\
  \ che non fanno richiami. Cosi i bambini italiani non si ammalano (non di Corona...che\
  \ attiva la Tubercolosi) di polmonite perche' sono vaccinati contro la TBC. Vaccino\
  \ che dura fino a 19/20 anni. Ovviamente anche i vostri ventenni cominciano ad ammalarsi\
  \ di Cov e Tubercolosi. Perche' da Voi non c'e' piu l'obbligo di fare il richiamo.\
  \ Ma Pensa!!!! La Lombardia ha la piu' alta concentrazione di Extracomunitari, Senegalesi,\
  \ Bengalesi, Egiziani, Marocchini, Rumeni, Albanesi, Tunisini, Algerini...e non\
  \ c'è ne manco uno con la polmonite?!?!?! Perche' sono giovani????  Noooooooo....perche'\
  \ sono tutti coperti da vaccino Tubercolosi, che e' un protocollo di copertura previsto\
  \ (DALLE ASL) per gli extracomunitari!!!!\nFate una verifica e vedrete che in tutti\
  \ gli ospedali, non c'è un extracomunitario di qualsiasi eta' positivo o ricoverato\
  \ per COV19!!!!!!!!!!\nCome e' possibile!?!?!? Solo gli italiani....allora... MEDITARE\
  \ GENTE \U0001F628\U0001F628"
</yamldata></pre>

**Comment by margheritapuca** [comment]
#1103
