### ISSUE TITLE
Non è vero che c'è stato un controesodo sullo Stretto di Messina

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1112]
<pre><yamldata>
Cosa: Non è vero che c'è stato un controesodo sullo Stretto di Messina
Descrizione: 'Un report dei passaggi sui vettori privati, mostra come il numero dei
  mezzi da Villa San Giovanni a Messina, sia addirittura sceso rispetto al giorno
  precedente.

  Tratta           Partenza         Auto  Passeggeri

  MES – VSG Ven 13/03/2020 409  1697

  MES – VSG Sab 14/03/2020 240  1255

  MES – VSG Dom 15/03/2020 211  763

  MES – VSG Lun 16/03/2020 351  1146

  MES – VSG Mar 17/03/2020 271   990

  MES – VSG Mer 18/03/2020 271   936

  MES – VSG Gio 19/03/2020 161    691

  MES – VSG Ven 20/03/2020 236   707

  MES – VSG Sab 21/03/2020 134  382

  MES – VSG Dom 22/03/2020 123 310'
Indirizzo: 38.19395841 15.55572383
Link: http://www.messinaora.it/notizia/2020/03/23/coronavirus-nessun-controesodo-sullo-stretto-lo-dicono-i-numeri/127799?fbclid=IwAR3VIpYQScLjUhYlRohVfpE9STfiY2P1dhdbirfO2M2mJyPf6ZTjuJoSY3k
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 38.19395841 15.55572383 (Messina) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=38.19395841+15.55572383&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by cristigalas** [comment]
Il titolo è fuorviante, in realtà la notizia dice solo che i numeri dei passaggi non erano così alti se confrontati con i giorni precedenti...
