### ISSUE TITLE
Raccolta fondi per sanificare casa di riposo Lazzarelli, #SanSeverino #Marche

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1116]
<pre><yamldata>
Causale: Donazione per Casa di riposo Lazzarelli
Descrizione: 'CASA DI RIPOSO LAZZARELLI

  Vogliamo dare un contributo per un servizio di sanificazione importantissimo per
  tutelare la salute dei nonnini e di chi ci lavora e le rispettive famiglie.

  Per chi volesse aiutarci il nostro IBAN è:

  IT16H0331769200000210302119

  Vi ricordiamo che siamo un’associazione ODV iscritta nel registro regionale, le
  donazioni danno benefici a livello fiscale'
IBAN: IT16H0331769200000210302119
Intestazione: Associazione Help SOS Salute e Famiglia Onlus
Link: https://www.facebook.com/associazionehelp/posts/2848850968529711
Nome: Associazione HELP per la Casa di riposo Lazzarelli di San Severino Marche
Posizione: 43.232173 13.180134 0 0
</yamldata></pre>

**Comment by FrancescaZambi89** [comment]
Gli obiettivi di questa Raccolta Fondi non sono chiari e, oltre al link Facebook, non ho trovato altre info sul loro sito http://associazionehelp.org/cosa-puoi-fare-tu/ 
La valuto come uno spot promozionale.
Come da Policy, ho messo label "non accettato"

**Comment by cristigalas** [comment]
@FrancescaZambi89 a me l’obiettivo mi pare chiaro: sanificare la casa di riposo, così come mi pare chiaro chi sia il soggetto che ha lanciato la raccolta fondi (vedi info pagina Facebook). Non mi pare uno spot... accetterei.

**Comment by chiccap** [comment]
Raccolta fondi chiusa, casa di riposo sanificata!
