### ISSUE TITLE
SERVIZIO GRATUITO DI SUPPORTO PSICOLOGICO TELEFONICO

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1120]
<pre><yamldata>
Cosa: SERVIZIO GRATUITO DI SUPPORTO PSICOLOGICO TELEFONICO
Descrizione: "Servizio di supporto psicologico telefonico gratuito \n\npromosso dal\
  \ Centro per la Psicoterapia e la Ricerca “Open” dell’Istituto di Psicoterapia Psicoanalitica\
  \ di Torino.\n\nGli accadimenti come quello che la nostra società sta vivendo, rendono\
  \ necessari interventi tempestivi a favore della popolazione. \nNoi psicoterapeuti\
  \ di “Open” abbiamo sentito il dovere e la necessità di mettere al servizio della\
  \ popolazione la nostra professionalità secondo un principio etico e curativo che\
  \ sentiamo fondamentale e fondante la nostra attività clinica.\n\nCome funziona:\n\
  Attivo dalle ore 10 alle ore 22\n-telefonare al numero:\n+39 3348951276\n\n- Scrivere\
  \ sms al numero:\n+39 3348951276\nper essere ricontattati\n\n- Scrivere a:\ncentro.psicoterapia@ippweb.it\n\
  \nL’iniziativa è promossa da un’ équipe di professionisti specializzati composta\
  \ da psicologi e medici psicoterapeuti,  che offre gratuitamente la propria competenza\
  \ in termini di disagio psicologico, dato il momento di particolare criticità sociale.\
  \ L’intervento proposto mira principalmente ad accogliere eventuali richieste di\
  \ supporto, fornendo un contributo specialistico nell’affrontare le conseguenze\
  \ psicologiche ed emotive connesse alla pandemia da Coronavirus e orientare il singolo\
  \ seguendo le direttive nazionali, attraverso colloqui di supporto psicologico telefonico.\n\
  \nCome professionisti psicologi e psicoterapeuti, siamo a vostra disposizione per\
  \ svolgere il nostro compito insieme: ora più che mai è importante prendersi cura\
  \ della propria salute fisica, psicologica ed emotiva.\nForza e coraggio!"
Destinatari: '• Coloro che sentono il bisogno di un sostegno emotivo in questo periodo
  di emergenza Covid-19.

  • Personale sanitario medico e infermieristico impegnato in prima linea nell’affrontare
  l’emergenza Covid-19.'
Email: centro.psicoterapia@ippweb.it
Immagine: corona-17_38_42.jpg
Link: http://www.ippweb.it/istituto/centro-psicoterapia-e-ricerca.html
Telefono: '3348951276'
</yamldata></pre>

**Comment by FrancescaZambi89** [comment]
già inserita nella #issue1118
