### ISSUE TITLE
Coronavirus, l’ultima bufala sui social? Migranti immuni al contagio

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1121]
<pre><yamldata>
Cosa: Coronavirus, l’ultima bufala sui social? Migranti immuni al contagio
Descrizione: "“Fate una verifica e vedrete che in tutti gli ospedali, non c'è un extracomunitario\
  \ di qualsiasi età positivo o ricoverato per Cov19!!!!!!!!! Come è possibile!?!?!?\
  \ Solo gli italiani....allora...meditare gente”. E’ questo solo uno dei post che,\
  \ negli ultimi giorni, gira sui social e che affronta la questione del contagio\
  \ da coronavirus, relativa alla popolazione straniera presente nel nostro paese.\
  \ C’è chi parla di migranti vaccinati contro la tubercolosi, fattispecie che li\
  \ renderebbe immuni al contagio. Chi, con tono complottista, di un virus che attacca\
  \ solo gli italiani, perché nelle statistiche non risulterebbero deceduti di nazionalità\
  \ straniera. \nIn realtà, la questione è molto semplice. Nelle tabelle rese note\
  \ giornalmente dalla Protezione Civile, che riportano il numero dei contagi, dei\
  \ decessi e dei guariti, non vengono indicate le nazionalità dei pazienti. Motivo\
  \ per cui alcune persone sono portate erroneamente a pensare che si tratti esclusivamente\
  \ di italiani. Ad oggi, quindi, non sappiamo quanti siano gli stranieri che hanno\
  \ contratto il virus e se si tratti di comunitari o extracomunitari.\nA smentire\
  \ la bufala oggi è intervenuto anche il virologo Roberto Burioni, che in tweet polemico\
  \ sottolinea: “L'ultima delle bufale è che il coronavirus non colpisce gli extracomunitari.\
  \ Chi è dotato di sprezzo del pericolo può venire dove mi trovo in questo preciso\
  \ momento, al San Raffaele di Milano, per controllare di persona che non è assolutamente\
  \ vero”."
Link: https://www.redattoresociale.it/article/notiziario/coronavirus_l_ultima_bufala_sui_social_migranti_immuni_al_contagio#
</yamldata></pre>

**Comment by cristigalas** [comment]
Doppia. Vedi #1103.
