### ISSUE TITLE
In queste ore nel nostro Paese salgono in modo allarmante i contagi da coronavirus: per questo l’UNI

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1138]
<pre><yamldata>
Descrizione: 'In queste ore nel nostro Paese salgono in modo allarmante i contagi
  da coronavirus: per questo l’UNICEF sta inviando in Italia una fornitura di materiali
  indispensabili per gli operatori sanitari, sostenendo l''azione del nostro governo
  nell''emergenza sanitaria globale più grave degli ultimi 100 anni.

  Sono in arrivo:

  • Mascherine

  • Guanti

  • Tute protettive e visiere per gli occhi

  • Soluzioni disinfettante per le mani

  • Termometri

  Continua il nostro lavoro in tutto il mondo. Dall’inizio della pandemia abbiamo
  inviato 6 tonnellate di materiale sanitario e abbiamo tutelato i bambini e le loro
  famiglie nel far fronte all’emergenza.'
Link: https://www.adnkronos.com/fatti/cronaca/2020/03/23/coronavirus-unicef-aiuti-per-italia-via-campagna-raccolta-fondi_rtFhZIi431dId1CqSQ4okJ.html
Nome: Unicef
</yamldata></pre>

**Comment by marcocovid83** [comment]
mi sembra una notizia generica senza destinatari o servizi.
