### ISSUE TITLE
Come costruire um Termometro infrarossi con Arduino

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1142]
<pre><yamldata>
Cosa: Termometro infrarossi con Arduino
Descrizione: Istruzioni per assemblare e programmare un termometro IR basato su scheda
  Arduino.
Fonte: Circuidigest
Link: https://circuitdigest.com/microcontroller-projects/ir-thermometer-using-arduino-and-ir-temperature-sensor
</yamldata></pre>

**Comment by marcocovid83** [comment]
@chiccap  @Saraveg @luciaroma mi sembra una cosa molto tecnica e molto complessa, per ora non ho accettato ma vedete voi
