### ISSUE TITLE
SIARE Engineering azienda #Bologna che produce ventilatori polmonari cerca sviluppatore C++ 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1144]
<pre><yamldata>
Cosa: Ricerca sviluppatore C++ per azienda emiliana che produce ventilatori polmonari
Descrizione: Linko post su Twitter dove azienda Siare di Bologna cerca un programmatore che possa aiutare nello sviluppo dei ventilatori polmonari.
Link: https://twitter.com/italiancpp/status/1240228096336441344?s=19
Posizione: 44.5075 11.3514
</yamldata></pre>

**Comment by cristigalas** [comment]
@marcocovid83 occhio alle label. È una richiesta di aiuto.

**Comment by cristigalas** [comment]
Sviluppatore trovato, come comunicato qui https://bit.ly/3btBQXX
Chiudo.
