### ISSUE TITLE
“Questa battaglia si vince da casa.Un nuovo artwork al giorno per sostenere l’emergenza.” Asta benefica di opere d'arte su instagram.

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1147]
<pre><yamldata>
CC_Postale: '20136'
Descrizione: '“Questa battaglia si vince da casa.

  Un nuovo artwork al giorno per sostenere l’emergenza Covid-19.”

  Per dare il nostro contributo e aiutare attivamente la regione Lombardia, quella
  che ci ospita e che attualmente ha registrato il maggior numero di casi, abbiamo
  deciso di dare vita a un progetto di beneficenza che coinvolge sia gli artisti che
  i nostri lettori.

  Dal 20 marzo fino al 30 aprile con “Art is Resistance” racconteremo sul nostro profilo
  Instagram @Collater.al il lavoro di alcuni dei più interessanti artisti contemporanei.

  Attraverso dei takeover che avverranno in diretta sulle Instagram Stories del nostro
  canale, ogni artista mostrerà il making-of di un’opera originale realizzata per
  questa particolare occasione che verrà poi messa all’asta qui.   Il ricavato di tutte le aste verrà donato alla regione Lombardia per sostenere l’emergenza
  Covid-19 e utilizzato per l’acquisto straordinario i materiali di consumo, quali
  mascherine, tute protettive, disinfettanti e strumentazioni necessari alle strutture
  sanitarie, ai medici, agli infermieri e al personale per curare al meglio i malati
  e limitare le occasioni di contagio.

  Il nostro obiettivo, e quello di tutti gli artisti coinvolti, è quello di combattere
  questa battaglia da casa aiutando chi invece lavora in prima linea. 
  Vi aspettiamo ogni giorno sul nostro profilo Instagram dove verranno comunicate
  date e orari di tutte le live session degli artisti e poi qui, dove potrete contribuire
  alla causa acquistando un pezzo unico ideato solo ed esclusivamente per questa occasione.'
Email: miriam@collater.al
Link: https://www.32auctions.com/artisresistance
Nome: Collater.al
Posizione: 45.4513778 9.1884711 0 0
</yamldata></pre>

**Comment by chiccap** [comment]
si è conclusa l'8 maggio
