### ISSUE TITLE
Materiali informativi multilingua

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1150]
<pre><yamldata>
Da_chi_offerta: Associazione Il Grande Colibrì | Associazione Les Cultures
Descrizione: Materiali informativi semplificati e multilingua per cittadini stranieri
Destinatari: Cittadini stranieri
Link: https://www.ilgrandecolibri.com/coronavirus-spiegato-migranti-asilanti/
Natura: solidale
Tipo_di_soggetto: privato
Titolo: Materiali informativi multilingua
</yamldata></pre>

**Comment by FrancescaZambi89** [comment]
segnalazione già in piattaforma e inserita con la #issue339
"non accettata" e chiusa
