### ISSUE TITLE
Notizia da testata dubbia, sospetto allarmismo gratuito

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1151]
<pre><yamldata>
Cosa: Notizia da testata dubbia, sospetto allarmismo gratuito
Descrizione: "La testata in oggetto è nota (siti antibufale hanno discreto dossier,\
  \ es. Butac.it) per le fake news.\n\nPone a fianco fatti correlati temporalmente\
  \ senza citare studi a corredo. \nCordiali saluti, \nAndrea Mora\nParma"
Link: https://www.affaritaliani.it/cronache/covid-due-interrogativi-letali-660769.html
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Chiudo per non dare visibilità a questo tipo di notizie e affaritaliani è considerata testata non credibile.
