### ISSUE TITLE
Messaggio whatsapp

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1159]
<pre><yamldata>
Cosa: Messaggio whatsapp
Descrizione: 'Buongiorno, nel gruppo di amici è arrivato un messaggio audio di una
  donna che racconta di essere andata a fare la spesa e di essere stata fermata dai
  carabinieri. Essendo in regola, le hanno suggerito di conservare lo scontrino, perché
  le auto di pattuglia sono provviste di telecamere e se, successivamente, a seguito
  di un controllo, richiedessero le motivazioni della presenza dell''auto in un dato
  posto, lo scontrino può attestare la giustificata presenza. I carabinieri arrestano
  che sia presente all''interno del decreto. È vero?

  Grazie. Rainone Paola'
Posizione: 43.926648 11.038696 0 0
</yamldata></pre>

**Comment by chiccap** [comment]
@cristigalas come gestiamo questa? non ha lasciato contatti.

**Comment by cristigalas** [comment]
@chiccap già... ho provato a cercare se c’è qualche segnalazione a riguardo e sembra che qualche polizia locale abbia chiesto di conservare lo scontrino per provare il motivo dell'uscita. Ad es. [vedi qui ](https://www.confinelive.it/controlli-covid-19-gli-scontrini-diventano-prova-per-gli-spostamenti-indifferibili/), [qui](https://www.ladige.it/territori/trento/2020/03/11/autocertificazioni-scontrini-prova-polizia-locale-spiega-chi-pu-muoversi) e [qui](https://www.ilcentro.it/l-aquila/gli-automobilisti-che-si-spostano-devono-mostrare-gli-scontrini-1.2389348). Ma sono notizie scarse e frammentate e comunque non abbiamo contatto signora e non abbiamo abbastanza materiale per fare una segnalazione ad hoc. Credo non ci resti che chiudere issue.
