### ISSUE TITLE
Supporto psicologico gratuito online

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#116]
<pre><yamldata>

chi: B-Yourself
comune: Cento
contatti: vincenzocaporaso@b-yourself.it 
descrizione: "Colloqui online gratuiti con supporto psicologico del Dott. Vincenzo Caporaso. Tre ore a settimana sarà disponibile, in orari concordati, ad un colloquio gratuito utilizzando la tecnologia a disposizione: videochiamata con WhatsApp, FaceTime, Skype, ZoomMeeting. "
destinatari: Tutte e tutti
fonte: https://www.facebook.com/events/220634185998977/?event_time_id=220635752665487
provincia: Ferrara
regione: Emilia-Romagna
tag: Supporto psicologico

</yamldata></pre>

**Comment by margheritapuca** [comment]
Posizione: 44.72744 11.29030

**Comment by cristigalas** [comment]
Psicologi privato, non accettiamo.
