### ISSUE TITLE
"Polmonite da dispiacere"

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1166]
<pre><yamldata>
Cosa: '"Polmonite da dispiacere"'
Descrizione: "Il Dott. Oliviero sostiene che la polmonite interstiziale da coronavirus\
  \ sia legata all'instaurarsi di meccanismi emozionali legati a conflitti biologici\
  \ che ognuno si porta dietro dal passato (in modo particolare al \"conflitto di\
  \ morte\"). \nPazienti che giungono in ospedale con una sintomatologia respiratoria\
  \ lieve, dopo aver ricevuto notizia della positività del proprio tampone al covid\
  \ 19, peggiorerebbero in maniera catastrofica proprio per lo sviluppo di una reazione\
  \ autoimmune contro il tessuto connettivo dei polmoni che esita nel quadro di polmonite\
  \ interstiziale.\nNel video seguono poi altri 15 minuti di bufale."
Link: https://www.youtube.com/watch?v=DavWFA0ymgQ&feature=emb_title
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Non accetterei questo tipo di segnalazione per non dare visibilità a queste info
