### ISSUE TITLE
#Hackweagainstvirus: un hackaton per sviluppare idee - 28/29 marzo '20

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1168]
<pre><yamldata>
Da_chi_offerta: https://hackthealps.it/
Descrizione: "HACKATHON \n\nLa nostra vita quotidiana è stata stravolta in modo negativo\
  \ dal Covid-19.\nCollaboriamo a trovare soluzioni insieme!\nl’hackathon inizia Sabato,\
  \ 28 marzo 2020, alle ore 09.00 CET"
Destinatari: sviluppatori software
Link: https://hackthealps.it/weagainstvirus/
Natura: solidale
Tipo_di_soggetto: privato
Titolo: weagainstvirus
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Iniziativa già svolta
