### ISSUE TITLE
Prelievo forzoso

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1172]
<pre><yamldata>
Cosa: Prelievo forzoso
Descrizione: La notizia parla di un presunto prelievo forzoso del 2% che lo stato
  farà sui conti dei cittadini, date le conseguenze finanziarie del covid-19
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Non ci sono link o contatti utili
