### ISSUE TITLE
Raccolta fondi Croce Verde #Vigevano acquisto di ventilatori polmonari 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1206]
<pre><yamldata>
Causale: Croce verde Vigevano per un ventilatore polmonare
Descrizione: Raccolta fondi per l'acquisto di ventilatori polmonari da donare al reparto
  di rianimazione dell'Ospedale Civile di Vigevano.
IBAN: IT18D0521623000000000086450
Link: https://www.informatorevigevanese.it/attualita/2020/03/24/news/croce-verde-una-raccolta-fondi-per-la-rianimazione-dell-ospedale-di-vigevano-545932/
Nome: Croce Verde Vigevano
Posizione: 45.31886101 8.841402 0 0
</yamldata></pre>

**Comment by chiccap** [comment]
Conclusa
