### ISSUE TITLE
video, testi e traduzioni per migranti

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1208]
<pre><yamldata>
Cosa: video, testi e traduzioni per migranti
Descrizione: Materiale informativo prodotto dall’associazione di volontariato Il Grande
  Colibrì (anche in collaborazione con Les Cultures, Naga e Certi Diritti) sul nuovo
  coronavirus SARS-CoV-2 e sull’epidemia di COVID-19 in Italia in diverse lingue.
  Questa pagina è aggiornata di ora in ora.
Fonte: https://www.ilgrandecolibri.com/coronavirus-spiegato-migranti-asilanti/
Link: https://www.ilgrandecolibri.com/coronavirus-spiegato-migranti-asilanti/
Posizione: 42.55308029 13.359375 0 0
</yamldata></pre>

**Comment by chiccap** [comment]
già presente #339
