### ISSUE TITLE
Solo per persone con difficoltà e/o di oltre 65 anni, in collaborazione con la Protezione Civile

È 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1209]
<pre><yamldata>
Descrizione: "Solo per persone con difficoltà e/o di oltre 65 anni, in collaborazione\
  \ con la Protezione Civile\n\nÈ possibile comunque prenotare e andare a ritirare\
  \ la spesa senza fare fila contattando i seguenti numeri: \n\n3755352058\n3208406188\n\
  3206307729\n3494516117"
Link: https://www.facebook.com/ComunediCori/photos/pb.436528463192694.-2207520000../1495271560651707/?type=3&theater
Nome_dell_esercizio_commercial: Conad di Cori per persone in difficoltà
Telefono: '3355342197'
</yamldata></pre>

**Comment by gloriaschiavi** [comment]
da chiudere, è venuto un pasticcio. Ho rifatto la segnalazione, è la #1215
