### ISSUE TITLE
Portierato di quartiere #Ancona

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#121]
<pre><yamldata>chi: Casa delle Culture
comune: Ancona
contatti: '3737660799'
descrizione: Portierato di quartiere
destinatari: residenti quartiere Vallemiano
fonte: https://www.facebook.com/casacultureancona/photos/a.106921962675490/3051249511576039/?type=3&theater
provincia: Ancona
regione: Marche
tag: Consegne e commissioni
</yamldata></pre>

**Comment by chiccap** [comment]
Chiudo perchè #226 più completa
