### ISSUE TITLE
Nessun CORONAVIRUS ma istallazione 5G

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1216]
<pre><yamldata>
Cosa: Nessun CORONAVIRUS ma istallazione 5G
Descrizione: 'Questa signorina ANNUNCIA che ha trovato lo scopo di queste disposizioni
  internazionali di distanziamento sociale: la libera istallazione di 5G !! Vi prego
  diffondete che è un fake.

  Guardate anche altri video del suo canale.'
Link: https://www.youtube.com/watch?v=b-h-FAU0miQ&t=3s
Posizione: 43.245203 -346.35498 0 0
</yamldata></pre>

**Comment by cristigalas** [comment]
Vedi #1245
