### ISSUE TITLE
Informazioni su Covid19 per stranieri/e

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#122]
<pre><yamldata>chi: "Il grande colibrì"
comune: Nazionale
contatti: ''
descrizione: informazioni su Covid19 in lingua e con video, per stranieri
destinatari: stranieri
fonte: https://www.ilgrandecolibri.com/coronavirus-spiegato-migranti-asilanti/
provincia: ''
regione: ''
tag: Informazioni utili
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Già presente in #339
