### ISSUE TITLE
VIdeo TgrLeonardo puntata del 16/11/2020

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1220]
<pre><yamldata>
Cosa: VIdeo TgrLeonardo puntata del 16/11/2020
Link: http://www.rai.it/dl/RaiTV/programmi/media/ContentItem-5e3275ba-475c-4cf4-b402-1e27dc47565b.html
</yamldata></pre>

**Comment by cristigalas** [comment]
Vedi #1239
