### ISSUE TITLE
Cura Italia, immigrazione e cittadinanza: sospesi i termini dei procedimenti amministrativi

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1223]
<pre><yamldata>
Cosa: 'Cura Italia, immigrazione e cittadinanza: sospesi i termini dei procedimenti
  amministrativi'
Descrizione: 'Si tratta della sospensione dei termini prevista dal decreto legge 17
  marzo 2020, n.18 (cosiddetto “Cura Italia”), richiamata nella circolare del dipartimento
  per le libertà civili e l''immigrazione.

  In base a tali disposizioni, peraltro, viene conservata la validità fino al 15 giugno
  di certificati, attestati, permessi, concessioni, autorizzazioni e atti abilitativi
  comunque denominati, in scadenza tra il 31 gennaio e il 15 aprile 2020.'
Fonte: Ministero degli Interni
Link: https://www.interno.gov.it/sites/default/files/allegati/circolare_sospensione_termini_procedimenti_amministrativi_prot.3511.pdf
Posizione: 47.279229 14.414063 0 0
</yamldata></pre>

**Comment by cristigalas** [comment]
Vedi #1242
