### ISSUE TITLE
Adottauneroe | Aiuto dal tuo vicinato per l'acquisto di alimentari e farmaci durante l'emergenza cor

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1224]
<pre><yamldata>
Cosa: Adottauneroe | Aiuto dal tuo vicinato per l'acquisto di alimentari e farmaci
  durante l'emergenza corona virus
Descrizione: 'Ciao a tutti.

  Durante lo scorso weekend abbiamo creato una piccola piattaforma per mettere in
  contatto telefonico persone bisognose di aiuto per fare spesa alimentare e farmaceutica
  con enti e giovani volontari nei loro paraggi pronti ad aiutare.

  Se pensi di poter dare una mano alle persone in difficoltà, a coloro che lottano
  in prima linea oppure tu stesso hai bisogno di aiuto, iscriviti e condividi questo
  link.

  https://adottauneroe.com/

  È un''iniziativa senza scopo di lucro per il bene comune ed è nata proprio per risolvere
  questa esigenza che abbiamo visto che sta aumentando.

  #adottauneroe #iorestoacasa #lontanimavicini

  Grazie'
Destinatari: Enti e persone che hanno bisogno di aiuto
Email: alessandro@loud.com
Immagine: logo_presti-19_14_20.png
Link: https://adottauneroe.com/
Telefono: '3466276297'
</yamldata></pre>

**Comment by chiccap** [comment]
presente #1221
