### ISSUE TITLE
Avresti sempre voluto stare fuori dalla grande distribuzione e non vi va di rinunciare a mangiare sa

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1233]
<pre><yamldata>
Descrizione: 'Avresti sempre voluto stare fuori dalla grande distribuzione e non vi
  va di rinunciare a mangiare sano, proprio ora che la salute è tanto importante ma
  non puoi uscire di casa? Sfoglia l’elenco dei produttori del GASP e una staffetta
  pedalerà a consegnarti la spesa! Supporta i piccoli produttori locali contro la
  grande distribuzione che sfrutta e inquina!
  Non hai mai avuto così tanto tempo per leggere un libro? Consulta il catalogo della
  Don Durito. Una staffetta in bicicletta te lo porterà alla porta di casa. Supporta
  l’editoria indipendente, metti in circolo la cultura.'
Email: gasp.sms@gmail.com
Link: www.cantiere.org
Metodi_di_pagamento_accettati: contanti
Nome_dell_esercizio_commercial: Gruppo Acquisto Solidale Popolare spazio mutuo soccorso
Posizione: 45.482418 9.143379 0 0
</yamldata></pre>

**Comment by cristigalas** [comment]
Doppia.
