### ISSUE TITLE
Fake news

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1236]
<pre><yamldata>
Cosa: Fake news
Descrizione: Volevo informazione in merito al video di Leonardo tg3, sono un antifakews
  in vari gruppi whatapps e mi piacerebbe collaborare con voi
Email: danielepennuto@gmail.com
Nome: Daniele Pennuto
Telefono: '3342078156'
</yamldata></pre>

**Comment by cristigalas** [comment]
Risposto via email segnalando #1239 e invitandolo a collaborare inviando segnalazioni di bufale via web form.
