### ISSUE TITLE
Catena WhatsApp: riduzione utilizzo rete

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1248]
<pre><yamldata>
Cosa: 'Catena WhatsApp: riduzione utilizzo rete'
Descrizione: 'Fonte MISE _ Comunicazione.

  *I gestori di rete dati chiedono di non diffondere video se non strettamente necessari;
  ogni invio e ogni download attraverso i social, compreso WhatsApp, impegnano la
  rete impedendo il regolare funzionamento. Le reti stanno collassando: protezione
  civile, ospedali, scuole e aziende non riescono più a scambiare dati*.  Fermiamoci.  _
  fai girare anche tu /

  Il sito del MISE non dice niente a riguardo. I giornali non ne parlano, i gestori
  di rete nemmeno.'
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
