### ISSUE TITLE
Raccolta fondi per sostenere gli Ospedali Bollini Rosa in tutta #Italia

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1249]
<pre><yamldata>
Descrizione: 'E'' possibile fare una donazione per sostenere gli Ospedali Bollini
  Rosa durante l''emergenza Coronavirus.

  Consulta l'' elenco per identificare l’ospedale o gli ospedali di interesse e le
  relative indicazioni per dare il tuo contributo.'
Link: https://www.bollinirosa.it/emergenza-coronavirus-aiuta-anche-tu-gli-ospedali-con-i-bollini-rosa
Nome: Gli Ospedali aderenti alla rete  Bollini Rosa
Posizione: 45.4749399 9.1899873 0 0
</yamldata></pre>

**Comment by chiccap** [comment]
conclusa
