### ISSUE TITLE
Comune di #Torino attiva linea telefonica con psicologi dell'emergenza

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1252]
<pre><yamldata>
Email: coronaviruspsi@gmail.com
Indirizzo: 45.0730018 7.683173 0 0
Link: https://www.facebook.com/749431391738924/photos/a.749471985068198/3521845037830865/?type=3&theater&ifg=1
Nome: CoronavirusPSI
Scopo: 'La Città di Torino con con Psicologi per i Popoli di Torino mette a disposizione
  una linea telefonica diretta con Psicologi di emergenza

  Dal lunedì alla domenica dalle 10.00 alle 12.00 e dalle 17.00 alle 19.00.'
Telefono: 01101137782
</yamldata></pre>

**Comment by FrancescaZambi89** [comment]
Gia inserita in #issue516
