### ISSUE TITLE
CRI, al via un servizio di teleassistenza psicologica per operatori sanitari

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1272]
<pre><yamldata>
Cosa: CRI, al via un servizio di teleassistenza psicologica per operatori sanitari
Descrizione: Per non lasciare solo chi si prende di cura della salute delle persone,
  la Croce Rossa Italiana ha attivato uno speciale servizio di teleassistenza psicologica
  dedicato proprio agli operatori sanitari impegnati nell’emergenza Covid-19, che
  risponde al numero 06.5510 (opzione 5), dal lunedì al sabato, dalle ore 8 alle 20.
Link: http://www.salute.gov.it/portale/news/p3_2_1_1_1.jsp?lingua=italiano&menu=notizie&p=dalministero&id=4325
</yamldata></pre>

**Comment by FrancescaZambi89** [comment]
già inserita nella issue #1265 
non accettata e chiusa
