### ISSUE TITLE
Lettura giornaliera di tutto il Decamerone

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#128]
<pre><yamldata>chi: lavoratori della cultura
comune: Italia
contatti: https://www.facebook.com/decamerone2020/
descrizione: Lettura giornaliera di tutto il Decamerone, dal 29 febbraio al 9 marzo.
destinatari: tutti
fonte: https://www.facebook.com/decamerone2020/
provincia: Italia
regione: Italia
tag: "Attivit\xE0 culturali e ricreative"
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Iniziativa già finita
