### ISSUE TITLE
URGENTE: Cercasi volontari che parlino #spagnolo Ospedale #Crema

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1287]
<pre><yamldata>
Cosa: 'Cercasi volontari che parlino spagnolo Ospedale #Crema'
Descrizione: "All'ospedale di Crema cercano volontari che parlino spagnolo,  disposti\
  \ ad assistere i medici cubani per le traduzioni. Il servizio dovrà essere svolto\
  \ anche all'interno dell'ospedale da campo. Se conosci qualcuno, digli di contattare\
  \ l'ospedale di Crema, dott.ssa de martinis. \nBisogna mandare una mail dichiarante\
  \ la propria disponibilità a : direzione.sanitaria@asst-crema.it"
Destinatari: Volontari/e che parlino lo spagnolo
Email: direzione.sanitaria@asst-crema.it
Indirizzo: 45.364569 9.681578 0 0
Nome: Dott.ssa De Martinis
</yamldata></pre>

**Comment by luciaroma** [comment]
mandiamo loro mail per sapere se hanno trovato? e se sì, se hanno altre esigenze da segnalarci?

**Comment by chiccap** [comment]
mail inviata

**Comment by chiccap** [comment]
Non hanno più risposto chiudo, ormai i medici cubani sono tornati a Cuba!
