### ISSUE TITLE
L’ idea di asini e basilico nasce dal nostro terreno sulle colline di Murta, consapevoli della soddi

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1291]
<pre><yamldata>
Descrizione: 'L’ idea di asini e basilico nasce dal nostro terreno sulle colline di
  Murta, consapevoli della soddisfazione delle persone nel nutrirsi di prodotti appena
  colti e coltivati in modo naturale, e constatando d’altro canto quanto sia difficile,
  soprattutto in una regione come la nostra, vivere di agricoltura e permettere alla
  crescente richiesta di prodotti genuini da parte del consumatore di incontarsi con
  l’offerta dei produttori in modo agevole e a un prezzo equo.

  Asini e basilico vuole proporsi come tramite tra questi due mondi arricchendo la
  sua offerta con una proposta gastronomica per non rinunciare ai prodotti genuini,
  spesso sacrificati per questioni di tempo o opportunità, gustandoli, freschi o cucinati,
  comodamente a casa propria o in ufficio.'
Indirizzo: 45.8099912 9.08515955
Link: http://www.asiniebasilico.it/
Metodi_di_pagamento_accettati: bonifico_banca contanti
Nome_dell_esercizio_commercial: Asini&basilico
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 45.8099912 9.08515955 (Como) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=45.8099912+9.08515955&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by claudiamazzantiact** [comment]
Già presente in segnalazione #1289
