### ISSUE TITLE
Erboristeria con rimedi firoterapici, olii essenziali, the, infusi e spezie.
Prodotti eco-bio per la

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1296]
<pre><yamldata>
Descrizione: 'Erboristeria con rimedi firoterapici, olii essenziali, the, infusi e
  spezie.

  Prodotti eco-bio per la cura della persona anche per pelli sensibili e allergiche.

  Selezione di articoli per bambini.

  Giochi e libri per i più piccoli!

  Make-up certificato bio è testato per il nichel.

  Ampia selezione di articoli profumati.'
Email: delferraromichela@libero.it
Metodi_di_pagamento_accettati: bonifico_banca contanti
Nome_dell_esercizio_commercial: Erboristeria i giardini di marzo
Posizione: 41.642644 -347.085571 0 0
Telefono: '3381958516'
</yamldata></pre>

**Comment by luciaroma** [comment]
Non viene specificato in nessun luogo che fanno consegne a domicilio; sulla loro pagina facebook non viene specificata nessuna offerta di servizio di servizio commissioni e non è evidente la connessione con l'emergenza
