### ISSUE TITLE
URGENTE - Protezione civile cerca 500 infermieri per Unità infermieristica COVID19

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1301]
<pre><yamldata>
Cosa: 'Protezione civile costituisce Unità infermieristica per COVID-19: cercasi 500
  infermieri per le zone più colpite'
Descrizione: "Ordinanza della Protezione civile  n. 656 del 26 marzo 2020: si costituisce\
  \ una Unità  infermieristica a supporto delle strutture sanitarie regionali più\
  \ colpite da COVID-19.\nIn sintesi, 500 infermieri volontari (selezionati in base\
  \ alle esperienze professionali “ritenute necessarie” tra le domande che arriveranno\
  \ entro le 20 del 28 marzo) faranno parte di una task force destinata dalla protezione\
  \ civile alle Regioni più colpite da COVID-19. A questi infermieri, siano essi dipendenti\
  \ del Ssn, di strutture anche non accreditate con questo o liberi professionisti,\
  \ verranno corrisposti 200 euro al giorno oltre allo stipendio o al guadagno già\
  \ percepito e se non assicurati in modo specifico a questo ci penserà la Protezione\
  \ civile che gli rimborserà anche le spese di viaggio.\nPer far parte della task\
  \ force non serve l’autorizzazione del servizio sanitario di appartenenza, ma per\
  \ i dipendenti l’assenso della struttura da cui dipendono. \nPer aderire: infermieripercovid@protezionecivile.it\
  \ o compilare il format breve sul sito della Protezione Civile."
Link: https://www.fnopi.it/2020/03/26/covid-19-unita-infermieristica-500-infermieri-compenso-200-euro-giorno/
Posizione: 41.8933203 12.4829321 0 0
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Secondo me possiamo chiudere questa issue perchè l'annuncio è cessato e la task force è già stata costituita
