### ISSUE TITLE
"I migliori Pensieri". 100 artisti per Emergency contro il COVID-19

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1310]
<pre><yamldata>
Cosa: '"I migliori Pensieri". 100 artisti per Emergency contro il COVID-19'
Descrizione: 'I Migliori Pensieri è il brano introduttivo dell’omonimo progetto discografico
  corale che coinvolge più di 100 artisti tra musicisti, cantanti, attori rappers
  e writers, uniti con lo scopo di sostenere Emergency attraverso una raccolta fondi
  a favore di chi sta operando contro il COVID-19.
  “Ci servono i migliori pensieri” è la frase che Gruff e le sue voci ripetono come
  un mantra, nel tentativo di regalare 7 minuti di ottimismo agli ascoltatori.
  In questa prima traccia, il rap di Clementino si alterna a quello di Oyoshe e di
  Militant A (Assalti Frontali), la cantante Petra Magoni invita ad apprezzare il
  tempo lento di quest’oggi, mentre il trombonista Gianluca Petrella ne impreziosisce
  la melodia, cadenzata dalle percussioni del salentino Roberto Chiga (Notte della
  Taranta). Le voci di Asia Argento, Frankie Hi-Energy, Corrado Fortuna, Dj Ralf e
  altri fuoriclasse del cinema e della musica, che hanno contribuito alla generazione
  del brano, vengono scratchate dalle mani esperte di Gruff, anche ideatore dell’intera
  base accompagnatrice.
  Ascolta il brano: https://djgruff.com/i-migliori-pensieri-emergency/
  La Genesi del progetto:
  L’idea nasce da una telefonata intercorsa tra Sandro Orrù e Dario Fichera, perfusionista
  cardiovascolare dell’azienda ospedaliera dell’Università di Padova, in trincea da
  giorni, sin dalla primissima diffusione del virus COVID-19.
  Fichera invita Gruff a supportare il corpo dei medici e degli infermieri con la
  sua musica, così come già fece nel 2015, quando l’operatore sanitario e l’artista
  organizzarono il tour italiano del “Camps Breakerz Crew”, progetto a sostegno della
  danza, dell’arte e dell’istruzione, che tramite una raccolta fondi mirata aveva
  l’obiettivo di garantire studi a molti ragazzi profughi di Gaza, che poi ha avuto
  un seguito nel 2019 con il progetto “Gaza is Alive” promosso dall’Associazione Ya
  Basta! Êdî Bese!
  Le parole di Fichera commuovono Gruff, che si muove immediatamente, diffondendo
  un appello a musicisti, cantanti, attori, rappers e writers.
  «Via le barriere, via i conflitti, in questo momento difficile per l’Italia, uniamoci
  nella musica e insieme, da lontano, ognuno porti il suo messaggio.» Dj Gruff.
  In pochi minuti arrivano le registrazioni: chi da cellulare, chi dallo studio, e
  poi le musiche che sono tante, troppe per un solo brano. Così il progetto si amplia
  e nasce l’idea di un album, che si comporrà di brani ciascuno in uscita cadenzata,
  rispondendo alla (non) logica di questo tempo incerto e sospeso.
  Come detto in precedenza, dalla notte tra il 24 ed il 25 marzo 2020, I Migliori
  Pensieri è disponibile online, mentre già ci prepariamo per l’uscita della seconda
  traccia, Viene e Va 2020, il terzo (attesissimo) lato del progetto uscito nel 2008,
  che aveva già visto la straordinaria partecipazione di diversi musicisti, dj e tantissimi
  rappers, che tornano finalmente in campo uniti, dopo tutti questi anni, per una
  nuova lotta: quella contro il Corona Virus.

  Per questo secondo brano ci aspettano i contributi di oltre 50 artisti tra i quali
  Cenzou, Inoki, Ekspo, Esa, Ramtzu, 5l e Fakser (alien army), Willy Valanga, DJ Stile,
  Reka Uomodisu, Zorlak e molti altri.

  Tutti i brani che comporranno I Migliori Pensieri saranno rigorosamente no profit.

  Ogni ascoltatore troverà le istruzioni per la libera donazione, che verrà devoluta
  alla ONG Emergency onlus.'
Link: https://www.sherwood.it/articolo/7486/i-migliori-pensieri-il-rap-per-emergency-contro-il-covid-19
</yamldata></pre>

**Comment by cristigalas** [comment]
Scaduta.
