### ISSUE TITLE
Corse gratuite in taxi per medici e infermieri, raccolta fondi di Cuore Digitale e Pronto Taxi #Roma

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1325]
<pre><yamldata>
Descrizione: Campagna su Gofundme.it promossa da Cuore Digitale, in collaborazione
  con Printo Taxi, per dare la possibilità a medici ed operatori sanitari di usufruire
  di corse taxi gratuite. La raccolta fondi sarà utilizzata per consegnare dei voucher
  prepagati a tutte le strutture ospedaliere covid-19 di Roma. L'obiettivo è raggiungere
  la somma di 7.500 euro che corrisponde a 500 corse (il costo solidale  concordato,
  per tale emergenza, tra  l'associazione "Cuore Digitale" e la cooperativa "Pronto
  Taxi 6645" per una corsa, a km illimitato, su Roma dentro GRA è di 15 euro). Per
  garantire almeno una corsa solidale chiediamo una donazione di almeno 15 euro.
Link: https://www.gofundme.com/f/dona-una-corsa-taxi-a-medici-ed-operatori-sanitari/
Nome: Dona una corsa taxi solidale contro il coronavirus! Raccolta fondi di Cuore
  Digitale e Pronto Taxi Roma
Posizione: 41.858015 12.56889 0 0
</yamldata></pre>

**Comment by chiccap** [comment]
conclusa
