### ISSUE TITLE
Il sito alvearechedicesi.it è una piattaforma che permette agli utenti di gestire la loro attività i

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1338]
<pre><yamldata>
Descrizione: Il sito alvearechedicesi.it è una piattaforma che permette agli utenti
  di gestire la loro attività in maniera autonoma. Ogni singolo Alveare ha il suo
  sito, curato dal Gestore dell’Alveare. Ogni produttore ha il suo spazio di vendita
  dedicato, dove può gestire il suo catalogo, i prezzi, le vendite, le distribuzioni.
  E ogni membro può iscriversi a diversi Alveari e condividere la vita della comunità.
  Tutti gli attori sono connessi tra loro e contribuiscono a un sistema alimentare
  più giusto, più umano e più collaborativo. È possibile comprare frutta e verdura,
  ma anche carne, pesce e formaggi etc.
Email: assistenza@alvearechedicesi.it
Link: https://alvearechedicesi.it/it
Nome_dell_esercizio_commercial: L'alveare che dice sì
</yamldata></pre>

**Comment by chiccap** [comment]
già presente #1095
