### ISSUE TITLE
Consegne e commissioni a domicilio #Cosenza

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#134]
<pre><yamldata>chi: Ass. La Terra di Piero
comune: Cosenza
contatti: info@laterradipiero.it
descrizione: Servizi a domicilio
destinatari: Tutti
fonte: https://www.facebook.com/880454068642880/posts/2988423671179232/
provincia: Cosenza
regione: Calabria
tag: Servizi e iniziative solidali private
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Segnalazione uguale a issue #115
