### ISSUE TITLE
Raccolta fondi Policlinico di #Milano #Lombardia

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1360]
<pre><yamldata>
Chi: 'Policlinico di #Milano #Lombardia'
Citta: Milano
Fonte: Sito dell'Ospedale
Indirizzo: Via Francesco Sforza, 35, 20122 Milano
Link: https://www.policlinico.mi.it
Posizione: 45.462833 9.1984326
Regione: Lombardia
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 45.462833 9.1984326 (Via Francesco Sforza, 35, 20122 Milano) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=45.462833+9.1984326&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by chiccap** [comment]
già presente #139
