### ISSUE TITLE
Raccolta fondi Ospedale Sacco (Fatebenefratelli Sacco) #Milano #lombardia

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1361]
<pre><yamldata>
BIC SWIFT: BLOPIT22
Causale: sostegno economico per emergenza "Covid-19"
Chi: 'Ospedale Sacco (Fatebenefratelli Sacco) #Milano #lombardia'
Citta: Milano
Fonte: Sito dell'Ospedale
IBAN: IT57W0311101603000000009130
Indirizzo: Via Giovanni Battista Grassi, 74, 20157 Milano
Link: https://www.asst-fbf-sacco.it
Posizione: 45.5185445 9.1188341
Regione: Lomabardia
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 45.5185445 9.1188341 (Via Giovanni Battista Grassi, 74, 20157 Milano) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=45.5185445+9.1188341&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by chiccap** [comment]
già presente #350
