### ISSUE TITLE
Raccolta fondi Ospedale Papa Giovanni XXIII #Bergamo #Lombardia

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1363]
<pre><yamldata>
BIC SWIFT: 'POSOIT22 '
Causale: ' indicare possibilmente nome, cognome e codice fiscale del benefattore  '
Chi: 'Ospedale Papa Giovanni XXIII #Bergamo #Lombardia'
Citta: Bergamo
Fonte: Sito dell'Ospedale
IBAN: 'IT52Z0569611100000012000X95   (se richiesto) '
Indirizzo: Piazza OMS, 1, 24127 Bergamo BG
Intestazione: Azienda Socio Sanitaria Territoriale Giovanni XXIII
Link: http://www.asst-pg23.it
Posizione: 45.6872029 9.638849222162662
Regione: Lombardia
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 45.6872029 9.638849222162662 (Piazza OMS, 1, 24127 Bergamo BG) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=45.6872029+9.638849222162662&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by chiccap** [comment]
Già presente #345
