### ISSUE TITLE
Raccolta fondi ASST Sette Laghi

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1370]
<pre><yamldata>
BIC SWIFT: 'BAPPIT21N67  '
Causale: 'Donazione Covid-19    '
Chi: ASST Sette Laghi
Citta: Varese
Descrizione: 'ATTENZIONE: nel codice IBAN, dopo IT75 c''è una O di Otranto, seguita
  da uno zero'
Fonte: Sito dell'ASST
IBAN: IT75O0306910810100000046111
Indirizzo: Viale Luigi Borri, 57, 21100 Varese VA
Link: https://www.asst-settelaghi.it/
Posizione: 45.809666 8.8359075
Regione: Lombardia
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 45.809666 8.8359075 (Viale Luigi Borri, 57, 21100 Varese VA) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=45.809666+8.8359075&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by chiccap** [comment]
presente #820
