### ISSUE TITLE
Raccolta fondi Ospedale Cotugno (ospedale dei colli)

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1374]
<pre><yamldata>
Chi: Ospedale Cotugno (ospedale dei colli)
Citta: Napoli
Descrizione: 'Raccolta Fondi non ufficiale dell''Ospedale, citata da più fonti nazionali.
  Autorizzata dall''ospedale stesso. La piattaforma trattiene il 2,9% +€0,25 per donazione  '
Fonte: Io Donna
Indirizzo: Viale Orazio Flacco, 65, 70124 Bari BA
Link: https://www.iodonna.it/attualita/eventi-e-mostre/2020/03/11/coronavirus-donazioni-gofundme-come-contribuire/
Posizione: 41.1119087 16.8628237
Regione: Campania
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 41.1119087 16.8628237 (Viale Orazio Flacco, 65, 70124 Bari BA) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=41.1119087+16.8628237&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by chiccap** [comment]
già presente #537
