### ISSUE TITLE
Raccolta fondi Fondazione Ospedale Sant'Orsola

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1378]
<pre><yamldata>
Chi: Fondazione Ospedale Sant'Orsola
Citta: bologna
Fonte: Sito dell'Ospedale
Indirizzo: Via Giuseppe Massarenti, 9, 40138 Bologna BO
Link: https://www.aosp.bo.it
Posizione: 44.4929103 11.3604116
Regione: Emilia Romagna
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 44.4929103 11.3604116 (Via Giuseppe Massarenti, 9, 40138 Bologna BO) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=44.4929103+11.3604116&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by FrancescaZambi89** [comment]
già inserita in issue #145
