### ISSUE TITLE
Raccolta fondi Azienda ospedaliero-universitaria di Modena

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1379]
<pre><yamldata>
Causale: 'aiutocovid19  '
Chi: Azienda ospedaliero-universitaria di Modena
Citta: Modena
Fonte: Sito Ospedale
IBAN: 'IT57X0306902477100000046051  '
Indirizzo: Largo del Pozzo, 71, 41125 Modena MO
Intestazione: Azienda Ospedaliero - Universitaria di Modena
Link: http://www.aou.mo.it/home.html
Posizione: 44.6364897 10.9423442
Regione: Emilia Romagna
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 44.6364897 10.9423442 (Largo del Pozzo, 71, 41125 Modena MO) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=44.6364897+10.9423442&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by FrancescaZambi89** [comment]
già inserita in issue #817
