### ISSUE TITLE
Raccolta fondi Protezione civile/ Regione Emilia Romagna

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1380]
<pre><yamldata>
Causale: '"Insieme si può: l''Emilia-Romagna contro il Coronavirus"'
Chi: Protezione civile/ Regione Emilia Romagna
Fonte: Sito regione Emilia Romagna
IBAN: IT69G020080243500010442896
Indirizzo: Viale Aldo Moro 52, 40127 Bologna
Link: https://www.regione.emilia-romagna.it/notizie/attualita/coronavirus-in-emilia-romagna-1739-casi-positivi-718-in-cura-a-casa-38-i-guariti
Posizione: 44.5086078 11.3633696
Regione: Emilia Romagna
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 44.5086078 11.3633696 (Viale Aldo Moro 52, 40127 Bologna) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=44.5086078+11.3633696&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by FrancescaZambi89** [comment]
già inserita in issue #595
