### ISSUE TITLE
Raccolta fondi Ospedale di Piacenza

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1381]
<pre><yamldata>
Chi: Ospedale di Piacenza
Citta: Piacenza
Fonte: GoFundme
Indirizzo: Via Taverna Giuseppe, 49, 29121 Piacenza PC
Regione: Emilia Romagna
</yamldata></pre>

**Comment by FrancescaZambi89** [comment]
Su gofundme le raccolte fondi a favore dell'ospedale di Piacenza sono diverse.
Nella segnalazione non c'è un link a cui risalire
