### ISSUE TITLE
Raccolta fondi ULLS 2 Treviso

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1383]
<pre><yamldata>
Causale: '"Emergenza Coronavirus"'
Chi: ULLS 2 Treviso
Citta: Treviso
Fonte: corriere.it
IBAN: IT47V030690960610000060572
Indirizzo: Borgo Cavalli, 42, 31100 Treviso TV
Link: https://www.google.com/amp/s/www.corriere.it/cronache/20_marzo_10/coronavirus-generosita-privati-aiuto-sanita-pubblica-come-donare-50bdce30-62cc-11ea-a693-c7191bf8b498_amp.html
Posizione: 45.6685067 12.252772
Regione: Veneto
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 45.6685067 12.252772 (Borgo Cavalli, 42, 31100 Treviso TV) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=45.6685067+12.252772&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by FrancescaZambi89** [comment]
già inserita in issue #827
