### ISSUE TITLE
Raccolta fondi Ospedale San Bortolo di #Vicenza

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1384]
<pre><yamldata>
Chi: Ospedale San Bortolo
Citta: Vicenza
Fonte: Sito dell'Ospedale Sito AULSS 8 Berica
IBAN: IT90X0306911894100000002765
Indirizzo: Viale Ferdinando Rodolfi, 37, 36100 Vicenza VI
Link: https://www.aulss8.veneto.it/nodo.php/2072
Posizione: 45.5561213 11.5481124 0 0
Regione: Veneto
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 45.5561213 11.5481124 (Viale Ferdinando Rodolfi, 37, 36100 Vicenza VI) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=45.5561213+11.5481124&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by FrancescaZambi89** [comment]
già inserita in issue #687
