### ISSUE TITLE
Raccolta fondi Azienda Ospedaliero Universitaria Pisana

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1390]
<pre><yamldata>
Chi: Azienda Ospedaliero Universitaria Pisana
Citta: Pisa
Fonte: GoFundme
Indirizzo: Via Paradisa, 2, 56124 Pisa PI
Posizione: 43.708507 10.439106675127729
Regione: Toscana
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 43.708507 10.439106675127729 (Via Paradisa, 2, 56124 Pisa PI) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=43.708507+10.439106675127729&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by FrancescaZambi89** [comment]
già inserita in issue #668
