### ISSUE TITLE
Raccolta fondi Ospedale San Jacopo di Pistoia

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1391]
<pre><yamldata>
Chi: Ospedale San Jacopo di Pistoia
Citta: Pistoia
Fonte: GoFundme
Indirizzo: Via Ciliegiole, 97, 51100 Pistoia PT
Posizione: 43.9212479 10.9058657
Regione: Toscana
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 43.9212479 10.9058657 (Via Ciliegiole, 97, 51100 Pistoia PT) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=43.9212479+10.9058657&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by FrancescaZambi89** [comment]
già inserita in issue #861
