### ISSUE TITLE
Raccolta fondi Azienda Ospedaliero Universitaria Careggi

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1393]
<pre><yamldata>
? ''
: https://www.aou-careggi.toscana.it/
CC postale: '22755508'
Causale: ' "donazione emergenza coronarovirus"  Inviare ad AOUC la Comunicazione di
  avvenuta donazione, email: donazionicoronavirus@aou-careggi.toscana.it  '
Chi: Azienda Ospedaliero Universitaria Careggi
Citta: Firenze
Fonte: Sito dell'Ospedale
IBAN: IT06V0306902887100000046016
Indirizzo: Largo G. Alessandro Brambilla, 3, 50134 Firenze FI
Intestazione: Azienda Ospedaliero - Universitaria Careggi - Firenze
Regione: Toscana
</yamldata></pre>

**Comment by FrancescaZambi89** [comment]
già inserita in issue #839 
chiusa e non accettata
