### ISSUE TITLE
Raccolta fondi Azienda USL Toscana Nord Ovest

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1394]
<pre><yamldata>
Causale: emergenza coronavirus. E' possibile indicare la destinazione preferita.  Si
  prega di inviare la ricevuta del bonifico alla e-mail patrimonio.bm@uslnordovest.toscana.it
Chi: Azienda USL Toscana Nord Ovest
Fonte: Sito dell'Ospedale
IBAN: IT63N0503414011000000010002
Indirizzo: Piazza Aldo Moro, 34, 55012 Capannori LU
Intestazione: 'Azienda USL Toscana nord ovest '
Link: https://www.uslnordovest.toscana.it/
Posizione: 43.848749 10.5757536
Regione: Toscana
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 43.848749 10.5757536 (Piazza Aldo Moro, 34, 55012 Capannori LU) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=43.848749+10.5757536&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by FrancescaZambi89** [comment]
Raccolta fondi già inserita tramite issue #843 
chiusa e non accettata
