### ISSUE TITLE
Raccolta fondi Ospedale Sant'Andrea

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1395]
<pre><yamldata>
Chi: Ospedale Sant'Andrea
Citta: La Spezia
Fonte: GoFundme
Indirizzo: Corso Mario Abbiate, 21, 13100 Vercelli VC
Posizione: 45.3173453 8.4131621
Regione: Liguria
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 45.3173453 8.4131621 (Corso Mario Abbiate, 21, 13100 Vercelli VC) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=45.3173453+8.4131621&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by FrancescaZambi89** [comment]
non è specificato il link alla donazione. Su gofundme ci sono attive 4 raccolte fondi per lo stesso ospedale di La Spezia.

**Comment by cristigalas** [comment]
Non accettiamo.
