### ISSUE TITLE
Raccolta fondi per la Terapia Intensiva dell'ospedale di #Pordenone in #Friuli 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1399]
<pre><yamldata>
Causale: REPARTO DI TERAPIA INTENSIVA - OSPEDALE DI PORDENONE
Chi: AS FO Azienda Sanitaria Friuli Occidentale
Citta: Pordenone
Fonte: Sito dell'Ospedale
IBAN: 'IT31G0200812510000104095551 '
Indirizzo: Via Montereale, c/o Ospedale, 24, 33170 Pordenone PN
Link: https://asfo.sanita.fvg.it
Posizione: 45.96892 12.65331 0 0
Regione: FVG
</yamldata></pre>

**Comment by amerlo94** [comment]
Location: 45.96892 12.65331

**Comment by FrancescaZambi89** [comment]
Il link inserito nella segnalazione rimanda al sito dell'azienda sanitaria locale dove è inserita la raccolta fondi della Protezione civile con un altro iban. Cercando online abbiamo trovato un'altra raccolta fondi per lo stesso ospedale su gofundme.

**Comment by chiccap** [comment]
La raccolta fondi segnalata sul sito dell'ospedale è la #1398

**Comment by FrancescaZambi89** [comment]
La raccolta fondi segnalata su gofundme è la #1405
