### ISSUE TITLE
Raccolta fondi Santa Maria Della Misericordia

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1400]
<pre><yamldata>
Chi: Santa Maria Della Misericordia
Citta: Udine
Fonte: Testata locale (Messaggero Veneto) https://messaggeroveneto.gelocal.it/udine/cronaca/2020/03/11/news/in-24-ore-70-mila-euro-per-l-ospedale-i-friulani-solidali-come-nel-1976-1.38581004
Indirizzo: Piazzale Santa Maria della Misericordia, 15, 33100 Udine UD
Link: 'https://www.gofundme.com/f/1x9byk2d5c?utm_medium=copy_link&utm_source=customer&utm_campaign=p_lico+share-sheet'
Regione: FVG
</yamldata></pre>

**Comment by amerlo94** [comment]
Location: 46.07636 13.22920

Questa la raccolta fondi (https://www.gofundme.com/f/1x9byk2d5c), che però al momento sembra essersi conclusa.

**Comment by FrancescaZambi89** [comment]
Confermo, raccolta fondi al momento è disattivata
