### ISSUE TITLE
Raccolta fondi Ex OPG occupato Jè so Pazzo per pacchi spese e DPI #Napoli

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1402]
<pre><yamldata>
Descrizione: 'Il Coronavirus può contagiare chiunque, limitare il contagio è fondamentale.
  C’è però chi può attrezzarsi meglio a resistere in questi tempi difficili e chi
  invece sta vivendo in questi giorni una situazione drammatica.

  Sono tantissimi infatti i lavoratori che sono stati licenziati in queste settimane,
  sono tantissime le altre fasce sociali che sono attualmente rimaste senza sostegno
  adeguato per la sopravvivenza quotidiana, come i migranti nei centri d’accoglienza
  e nei campi, i senzatetto, le famiglie disoccupate che si rivolgevano ai servizi
  di supporto alla spesa alimentare. Per questo abbiamo deciso, ancora una volta,
  di attivarci, insieme, dal basso.

  Di fronte all''insufficienza delle misure istituzionali, abbiamo bisogno di sostegno
  e solidarietà popolare.

  Attiviamo questa raccolta fondi per permettere ai volontari di poter organizzare
  l’ acquisto dei pacchi spesa, l’acquisto e la distribuzione di dispositivi di protezione
  minima consigliati, il supporto alle fasce sociali più a rischio - come gli anziani
  - per limitare le uscite e i contatti.

  Ogni contributo in questo momento è fondamentale, l’epidemia dovuta al virus si
  contrasta rispettando la quarantena e grazie al sacrificio incredibile del personale
  sanitario che va supportato in ogni modo, ma va scongiurata allo stesso modo l’epidemia
  sociale che si rafforza in questo stato d’emergenza: la miseria.

  Lavoreremo in tal senso nella massima sicurezza per i volontari e gli assistiti,
  rispettando la tutela sanitaria e le disposizioni sulle distanze e i contatti per
  evitare il contagio.

  Restiamo uniti anche nella distanza, durante l’emergenza attiviamo la solidarietà!

  #resistiamoinsieme #diamociunamano'
Link: https://www.produzionidalbasso.com/project/durante-l-emergenza-attiviamo-la-solidarieta/
Nome: Ex OPG "Je so' Pazzo"
Posizione: 40.8543652 14.2417587 0 0
</yamldata></pre>

**Comment by chiccap** [comment]
campagna terminata
