### ISSUE TITLE
Codice d'Onore Medico Chirurgo Omeopata Unicista

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1404]
<pre><yamldata>
Cosa: Codice d'Onore Medico Chirurgo Omeopata Unicista
Descrizione: 'Sfogo in 23 punti di un medico chirurgo su come si diffonde il virus
  Covid19 anche grazie alla presenza delle reti 5G, della debolezza immunitaria causata
  dai vaccini (SIC!) e del test ipersensibile che darebbe l''80% dei risultati positivi...

  Circola su whatsapp ma è presente sulla pagina personale del medico interessato'
Link: https://salvatoreraino.com/codice-donore/
</yamldata></pre>

**Comment by cristigalas** [comment]
Fake news su rete 5g già presente, vedi https://covid19italia.help/issues/1245
