### ISSUE TITLE
Raccolta fondi per la terapia intensiva dell'Ospedale di #Pordenone

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1405]
<pre><yamldata>
Descrizione: 'RAFFORZIAMO LA TERAPIA INTENSIVA

  Siamo Marco e Valentino Zuzzi del Molino di Pordenone. Abbiamo deciso di organizzare
  questa raccolta fondi a favore dell'' Ospedale di Pordenone ASFO - AZIENDA SANITARIA
  FRIULI OCCIDENTALE per rafforzarne la terapia intensiva. Nel nostro piccolo e nelle
  nostre possibilità possiamo fare la differenza. Donate e condividete. In questi
  momenti bisogna rimanere uniti. Anche un piccolo contributo può fare la differenza.

  Grazie a tutti.

  NB:Da ogni donazione il sistema propone di trattenere una percentuale preimpostata
  pari al 15% per offrire un contributo NON OBBLIGATORIO per la gestione della piattaforma
  . Questo contributo può essere ridotto fino a 0€ (se lo si ritiene giusto) permettendo
  cosi di donare il 100% all''Ospedale .

  Basta inserire l''importo che si vuole donare nell''apposito spazio e successivamente
  cliccare sul riquadro in basso dove vi è la percentuale 15% e cliccando su ALTRO
  si potrà immettere qualsiasi importo si voglia far recapitare alla piattaforma per
  la gestione del sito.

  Credo sia corretto mettere in evidenza questa informazione in alto alla descrizione,
  visto che per esperienza personale è facile sbagliare e che presi dai nostri mille
  pensieri si dona senza stare lì a leggere e pensare, perché in questo duro momento,
  credo sia importante, DONARE NEL MODO GIUSTO , per far arrivare il massimo contributo
  alle associazioni che stiamo cercando di aiutare'
Indirizzo: 45.969011050000006 12.653883625587156 0 0
Link: https://www.gofundme.com/f/covid19-ospedale-di-pordenone-terapia-intensiva/@@reset-optout
Nome: Ospedale Pordenone Terapia Intensiva
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 45.95443546 12.66002911 (Pordenone) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=45.95443546+12.66002911&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by michelerestuccia** [comment]
La raccolta fondi è conclusa
