### ISSUE TITLE
Raccolta fondi Ospedale Papa Giovanni XXIII #Bergamo

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#141]
<pre><yamldata>chi: Ospedale Papa Giovanni XXIII
comune: Bergamo
contatti: ''
descrizione: Raccolta fondi per Ospedale Papa Giovanni XXIII di Bergamo
destinatari: Tutti
fonte: http://www.asst-pg23.it/2020/03/_emergenza_coronavirus_come_aiutarci/
provincia: Bergamo
regione: Lombardia
tag: Raccolta fondi
</yamldata></pre>

**Comment by chiccap** [comment]
Chiusa perchè #345 più completa @luciaroma

**Comment by luciaroma** [comment]
sì scusate, non ho messo non ho accettato (ho inserito questa, quella del Sacco e quella della comunità bresciana). Li sto reinserendo più completi, via form.

La visualizzazione della segnalazione in github mi sembra un pochino sballata, in termini di ordine con cui compaiono le informazioni
