### ISSUE TITLE
Informazioni

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1415]
<pre><yamldata>
Cosa: Informazioni
Descrizione: "Buongiorno,\nDa due settimane sono raffreddato,ma da tre giorni oltre\
  \ al mal di gola si è aggiunto anche il bruciore alla stessa,il raffreddore e aumentato,non\
  \ ho mai avuto febbre fino ad oggi ma mi sento debole da giorni,sono affetto da\
  \ sclerosi multipla,e come consigliato dal mio medico ho assunto tachipirina da\
  \ 1000.\nLavoro nella GDO,quindi a stretto contatto con molte persone,quindi chiedo\
  \ è il caso di ulteriori controlli o del tampone?\nIn attesa di vostro riscontro\
  \ \nCordiali saluti"
Email: Eziomessina@live.it
Indirizzo: 45.491019 12.096708 4.013213634490967 165
Nome: Ignazio messina
Telefono: '3285467852'
</yamldata></pre>

**Comment by cristigalas** [comment]
Richiesta di aiuto di tipo medico a cui non possiamo rispondere.
