### ISSUE TITLE
Raccolta Fondi associazione Il Gioco del Sorriso per Asp #Caltanisetta

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1443]
<pre><yamldata>
Descrizione: "Spiver & Il gioco del Sorriso ancora insieme, ma stavolta per lanciare\
  \ una straordinaria Raccolta Fondi denominata #TuttiInsieme ! \n\nUna raccolta fondi\
  \ destinata alle strutture sanitarie nissene, necessarie per fronteggiare l’emergenza\
  \ Corona Virus. Invitiamo tutte le aziende, i nostri politici, i singoli privati,\
  \ i nostri cari followers e tutti coloro che volessero farlo ad “aprire il cuore”\
  \ e a donare quanto più è possibile, per combattere questa grande emergenza che\
  \ stiamo fronteggiando e ci accingeremo a farlo in modo più importante nei prossimi\
  \ giorni. \n\nLa donazione può essere effettuata in due diverse modalità: \n\n1)\
  \ Tramite piattaforma GoFoundMe \n\n2) O direttamente attraverso l'IBAN IT18 X089\
  \ 5283 4200 0000 0020 677 Intestato a: Associazione il Gioco del Sorriso \n\nCon\
  \ la causale: Raccolta Fondi Tutti Insieme - Covid 19 \n\nLe nostre strutture sanitarie,\
  \ i nostri medici ed infermieri, la nostra gente hanno bisogno di noi. Dai dispositivi\
  \ di protezione individuali, alle attrezzature mediche necessarie per fronteggiare\
  \ l’emergenza. Noi abbiamo già aderito. \n\nUNISCITI A NOI Insieme, possiamo vincere\
  \ questa battaglia! #TuttiInsieme #CeLaFaremo"
Link: https://www.gofundme.com/f/1xl6vtyn5c
Nome: 'Raccolta Fondi #TUTTINSIEME - Asp #Caltanissetta'
Posizione: 37.490285 14.030914 0 0
</yamldata></pre>

**Comment by michelerestuccia** [comment]
La raccolta fondi si è conclusa.
