### ISSUE TITLE
Raccolta fondi, in collaborazione con la Fondazione AGire Insieme, per l'Azienda sanitaria di #Agrigento

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1450]
<pre><yamldata>
Descrizione: "Ognuno di noi può fare la sua parte nella battaglia contro il Covid-19.\
  \ Solo rimanendo in casa possiamo veramente fermarlo. Ma in provincia di Agrigento\
  \ non ci sono posti a sufficienza in terapia intensiva. E questa è già un'emergenza!\
  \ L'Azienda sanitaria provinciale sta facendo una corsa contro il tempo per aumentare\
  \ i posti letto. \n\nCon il denaro raccolto - seguendo le indicazioni che verranno\
  \ fornite dall'Azienda sanitaria - si acquisteranno attrezzature mediche, dispositivi\
  \ di protezione individuale, disinfettanti e tutto ciò di cui gli ospedali di Agrigento,\
  \ Licata, Canicattì, Sciacca e Ribera avranno bisogno per affrontare l'emergenza\
  \ del Coronavirus. \n\nCon un semplice click puoi dare il tuo importante contributo\
  \ in questa battaglia. Restiamo a casa. E doniamo.\n\n(Raccolta fondi in collaborazione\
  \ con la Fondazione AGire insieme per l'Azienda sanitaria provinciale di Agrigento\
  \ ideata e promossa da Piero Barone, Lello Analfino, Silvio Schembri, Sergio Friscia,\
  \ Gianfranco Jannuzzo, Pino Cuttaia e Daniele Magro)."
Link: https://www.gofundme.com/f/sostegno-ospedali-della-provincia-di-agrigento
Nome: 'Coronavirus - Raccolta fondi Sostegno ospedali della provincia di #Agrigento'
Posizione: 37.289449 13.531895 0 0
</yamldata></pre>

**Comment by chiccap** [comment]
La campagna si è conclusa.
