### ISSUE TITLE
Raccolta fondi su Facebook dell’associazione Mastropietro #Cuorgnè #Torino

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1451]
<pre><yamldata>
Descrizione: 'Ti chiediamo Aiuto per affrontare questa Immane Emergenza Umanitaria
  e non solo Sanitaria.
  Abbiamo Bisogno di Fondi per DPI, Mascherine e Guanti oltre che per le spese di
  Gestione del Servizio di Consegna Borse Alimentari.'
Link: https://www.facebook.com/donate/231507177971809/3143395629006310/
Nome: Associazione Mastropietro & C. Onlus
Posizione: 45.390404 7.649767 0 0
</yamldata></pre>

**Comment by michelerestuccia** [comment]
La raccolta fondi è terminata
