### ISSUE TITLE
Raccolta fondi per ospedale San Giovanni di Dio di #Agrigento

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1452]
<pre><yamldata>
Descrizione: "Tutti noi sappiamo il tragico momento che sta attraversando il mondo\
  \ e soprattutto il nostro paese.\nSono Salvatore Moribondo e vengo da agrigento\
  \ . Io e altri ragazzi, membri del “fantasan”, abbiamo deciso di annullare la competizione\
  \ fantacalcistica e devolvere il montepremi creando una raccolta fondi dedicata\
  \ al nostro ospedale San Giovanni di Dio di Agrigento.\n\nSiamo in contatto con\
  \ il sindaco e con l’Asp di Agrigento ,cercando di arrivare quanto prima all’obbiettivo\
  \ prefissato e magari superarlo, per contribuire all’acquisto di respiratori, mascherine,\
  \ microchip per la terapia sub-intensiva, attrezzature e tutto quello che possa\
  \ servire per un’adeguata cura.\n\nCi appelliamo al buonsenso delle persone, crediamo\
  \ in noi e nel nostro paese , UNITI SI PUÒ. Al termine della campagna preleveremo\
  \ i fondi raccolti e partirà un bonifico direttamente all’ospedale San Giovanni\
  \ di Dio. \nOvviamente il tutto sarà documentato e reso pubblico.\n\n#Aggiornamenti\n\
  24 MARZO 2020\ndi Salvatore Moribondo, Organizer\n\nBuonasera, volevamo aggiornarvi\
  \ sugli sviluppi della campagna di raccolta fondi.\nVisto che l'Asp di Agrigento\
  \ non può ricevere soldi nel bilancio che non provengano dalla regione Sicilia e\
  \ data l'impossibilità di prelevare personalmente quanto raccolto, abbiamo raggiunto\
  \ un accordo con la Fondazione \"#AGireinsieme\" di Agrigento, nel rispetto di tutte\
  \ le politiche della piattaforma gofundme, che si prodigherà di prelevare direttamente\
  \ i fondi ed inviarli immediatamente all'azienda \"#Siare\", con la quale siamo\
  \ in contatto già da giorni per l'acquisto delle strumentazioni sanitarie richieste\
  \ dal reparto di \"terapia intensiva e rianimazione\" dell'ospedale San Giovanni\
  \ di Dio di Agrigento."
Link: https://www.gofundme.com/f/aiutiamoci-covid19-agrigento
Nome: '#AIUTIAMOCI COVID-19 #AGRIGENTO - ospedale San Giovanni di Dio di Agrigento.'
Posizione: 37.351874 13.60764 0 0
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.

**Comment by michelerestuccia** [comment]
La raccolta fondi è conclusa
