### ISSUE TITLE
Raccolta fondi per Ospedale di #Leonforte #Enna

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1454]
<pre><yamldata>
Descrizione: "L'emergenza sanitaria innescata da un nemico invisibile, il COVID 19,\
  \ rende necessarie misure straordinarie di solidarietà. Questa raccolta fondi iniziata\
  \ da un giovane medico del nostro territorio Francesco Leonforte, sempre attivo\
  \ in ambito umanitario, è stata condivisa dal Sindaco di Leonforte Carmelo Barbera,\
  \ il vice Sindaco, le Forze dell'ordine, la protezione civile e i medici ( dott\
  \ Campione in primis) sono in prima linea, purtroppo, senza armi con cui combattere.\n\
  \nFacciamo appello a tutti i fratelli italiani per una donazione a favore dell'Ospedale\
  \ di Leonforte, br />La struttura dell'Ospedale di Leonforte farebbe invidia ad\
  \ una clinica svizzera ma per insane e scellerate scelte passate, riconducibili\
  \ ad ogni parte politica, è stato nel tempo depotenziato di attrezzature e personale\
  \ medico ed è attualmente presidiato soltato da pochi eroi medici e infermieri che\
  \ hanno dato se stessi e stanno dando tutto ciò che hanno, a rischio dell'incolumità\
  \ personale.\n\nC'è urgente bisogno di soldi per comprare attrezzature di primo\
  \ soccorso, dispositivi di protezione, ventilatori polmonari, in attesa che il Governo\
  \ Regionale e Nazionale si decidano ad allestire posti letto anche per altre patologie,\
  \ le quali, ricordo, non sono di certo scomparse e che per forza di cose sono state\
  \ messe da parte.\nIl Coronavirus ha fatto e farà morti diretti e indiretti per\
  \ il ritardo e il differimento delle cure a coloro che soffrono altre patologie.\
  \ Non possiamo fare altro che stringerci a corte e manifestare solidarietà, quale\
  \ unico popolo d'Italia.\n\nFacciamo appello alle vostre sensibilità e vi invito\
  \ a donare, perché la situazione è veramente drammatica e dobbiamo agire subito.\
  \ Siamo certi che non farete mancare il vostro appoggio in questo momento di estrema\
  \ difficoltà per una comunità dell'entroterra bistrattata. Peraltro, il presidio\
  \ sanitario di Leonforte serve le comunità di Assoro, Agira, Nissoria, Regalbuto,\
  \ quindi un'area estesa di circa 25.000 abitanti.\n\nNell'impotenza di fare diminuire\
  \ i contagi, affidando a Dio le sorti del suo popolo, possiamo solo agire affinché\
  \ i contagiati possano ricevere un minimo di assistenza e possano avere un'opportunità\
  \ di guarigione.\nGrazie per ciò che farete.\n\n\nAggiornamenti \n26 MARZO 2020\n\
  di Nino Ginardi, Team Member."
Link: https://www.gofundme.com/f/coronavirus-riformiamo-terapia-intensiva-sicilia
Nome: 'Emergenza Coronavirus -Sosteniamo Ospedale di #Leonforte'
Posizione: 37.65267 14.411187 0 0
</yamldata></pre>

**Comment by michelerestuccia** [comment]
La raccolta fondi è conclusa
