### ISSUE TITLE
#StayON live music

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1456]
<pre><yamldata>
Da_chi_offerta: KeepOn
Descrizione: '#StayON è l''iniziativa nata insieme a Live Club e Festival, ideata
  per dare una continuità di programmazione agli spazi dove torneremo ad ascoltare
  musica e non solo!

  Ogni Live sarà collegato ad una raccolta fondi in favore di Ospedali, Enti, Protezione
  Civile, impegnati ad affrontare l’attuale emergenza sanitaria.'
Destinatari: tutti
Link: https://www.keeponlive.com/blog/stayon?fbclid=IwAR0Pzg_BVTy0Ll3lkmvGhmwt6ZwGCGeevCZMyJ_2ZrplQ8WEmZ8fjCCpBb8
Natura: culturale-ricr
Titolo: '#StayON live music'
</yamldata></pre>

**Comment by michelerestuccia** [comment]
La raccolta fondi è conclusa
