### ISSUE TITLE
Educatrici scuole dell'infanzia proseguono le cure educative a distanza #Palermo

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1458]
<pre><yamldata>
Da_chi_offerta: 'comune di #palermo -scuola'
Descrizione: 'UNO SPAZIO VIRTUALE PER STARE INSIEME

  Con Lab Web Coccole e Abbracci asili nido e scuole per l’infanzia di Palermo reagiscono
  alla sospensione dell’attività imposta dalla diffusione del Coronavirus continuando
  la cura educativa a distanza.

  In questo spazio virtuale ludico e creativo i genitori dei piccoli da zero a tre
  anni possono trovare ogni giorno i suggerimenti video delle educatrici sui giochi
  da fare con i propri figli a casa, mentre le bambine e i bambini dai tre ai sei
  anni possono seguire video-fiabe, tutorial e laboratori degli insegnanti. Inoltre,
  gli allievi delle scuole per l’infanzia possono partecipare ad un collegamento web
  periodico pensato per mantenere saldo il dialogo affettivo e il contatto visivo
  al quale sono abituati. Infine, il sito ospita anche i consigli ai genitori di una
  pedagogista esperta.

  Inventiva e tecnologia insieme alla forza affettiva per una modalità nuova di sperimentare
  cure educative che riescano a farci stare vicini anche se lontani, ad abbracciarci
  anche se solo virtualmente, fino a quando questi giorni di separazione passeggeri
  finiranno e torneremo alla normalità'
Destinatari: asili nido e scuole per l’infanzia
Link: https://portalescuola.comune.palermo.it/coccoleeabbracci/
Natura: didattica
Posizione: 38.115432 13.362229 0 0
Titolo: 'Lab Web Coccole e Abbracci comune di #Palermo'
</yamldata></pre>

**Comment by PaolaLiliana** [comment]
@FrancescaZambi89  secondo me questa iniziativa è la stessa della issue successiva, 1459. Sono incerta quale delle due pubblicare, forse la successiva mi sembra la più completa delle due.

**Comment by PaolaLiliana** [comment]
@FrancescaZambi89  dove devo inserire la frase: Già inserita in #issue1044 ?

**Comment by chiccap** [comment]
Già inserita in #1044

@PaolaLiliana
