### ISSUE TITLE
Le scuole per l'infanzia comunali offrono sostegno educativo a distanza #Palermo,

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1459]
<pre><yamldata>
Da_chi_offerta: 'comune di #Palermo'
Descrizione: 'L’emergenza Coronavirus ha causato l’improvvisa chiusura dei servizi
  per l’infanzia comunali. Per questo, tutti insieme, siamo chiamati a sperimentare
  strategie di sostegno educativo a distanza attraverso il Portale della Scuola di
  Palermo.

  Per i più piccoli, da zero a tre anni, proponiamo suggerimenti e consigli rivolti
  ai genitori. Invece, per la fascia di età da tre a sei anni, saranno le maestre,
  con le video-favole, i libri narrati, i giochi e i disegni a dialogare direttamente
  con i bimbi a casa. La pagina web offre anche gli approfondimenti di una pedagogista
  esperta e altri documenti utili ad interagire con bambine e bambini rimasti a casa.

  L’obiettivo per tutti è di mantenere una continuità a garanzia del benessere dei
  più piccoli anche al di fuori delle aule rinsaldando lo spirito dell’intera comunità
  educante in un momento in cui sembra prevalere la paura e la preoccupazione.

  Un modo innovativo per affrontare la crisi causata dal virus Covid-19 con energia
  positiva e capacità di condivisione nella cura educativa. Andrà tutto bene.'
Destinatari: asili nido e scuole per l’infanzia al fianco dei genitori per il sostegno
  educativo a distanza dei bambini
Link: https://portalescuola.comune.palermo.it/emergenzacoronavirus/
Natura: didattica
Posizione: 38.115402 13.361827 0 0
Titolo: 'Portale #Scuola Emergenza Coronavirus Comune di #Palermo,'
</yamldata></pre>

**Comment by PaolaLiliana** [comment]
@FrancescaZambi89 secondo me questa iniziativa è la stessa della issue precedente, 1458

**Comment by chiccap** [comment]
Già inserita in #1044
