### ISSUE TITLE
Accesso gratuito catalogo film in streaming di Cineteca di #Milano

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#146]
<pre><yamldata>
Cosa: Catalogo di film in streaming gratuiti
Descrizione: "La Fondazione Cineteca di Milano ha reso gratuito il catalogo in streaming\
  \ dei film. \xC8 sufficiente registrarsi."
Link: https://www.cinetecamilano.it/biblioteca
regione_manuale: tutte
</yamldata></pre>

**Comment by tailot** [comment]
@cristigalas volevo effettuare una verifica ma non sono riuscito a registrarmi al sito. Sei riuscita a verificare ?

**Comment by cristigalas** [comment]
No. Io per ora sistemo solo issue. Ma verifiche sono necessarie. Puoi contattare tu Cineteca e segnale problema di registrazione?

**Comment by gloriaschiavi** [comment]
chiudo perchè doppia #343
