### ISSUE TITLE
L'Ordine degli Architetti lancia una raccolta fondi a supporto del personale sanitario #Trapani

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1473]
<pre><yamldata>
Descrizione: 'SOS Coronavirus. L’Ordine degli Architetti della Provincia lancia una
  raccolta fondi.

  27 Marzo 2020

  Riceviamo e pubblichiamo per la condivisione il comunicato dell’Ordine degli Architetti
  della Provincia di #Trapani

  COMUNICATO STAMPA

  L’Ordine degli Architetti PPC della Provincia di Trapani lancia la raccolta fondi
  “SOS CORONAVIRUS TRAPANI”

  L’inedita e drammatica situazione venutasi a creare per l’emergenza Coronavirus
  ci spinge oggi ad abbracciare con convinzione scelte solidali in aiuto dei nostri
  medici ed infermieri che lavorano in emergenza e in carenza di dispositivi di protezione
  individuale.

  È per questa ragione che l’Ordine degli Architetti PPC della Provincia di Trapani,
  riunito in streaming nella seduta straordinaria del 26/03/2020, ha deciso di avviare
  una campagna di raccolta fondi, che abbiamo chiamato “SOS CORONAVIRUS TRAPANI”,
  destinando 1.000,00 euro del proprio Bilancio all’emergenza sanitaria.

  Lo farà unitamente al contributo libero dei componenti del Consiglio dell’Ordine
  e con il supporto della Fondazione degli Architetti nel Mediterraneo “Francesco
  La Grassa”.

  Ma non basta. Abbiamo bisogno anche dell’aiuto vostro, dei vostri cari, dei vostri
  amici.

  Per contribuire alla raccolta fondi sarà possibile devolvere fino al 3 aprile 2020
  una donazione in denaro, di importo libero, tramite bonifico sul conto della Fondazione
  Architetti nel Mediterraneo di Trapani “Francesco La Grassa “:

  IBAN: IT37 U030 3216 4010 1000 0004 167 – c/o CREDEM Trapani AG. 2

  CAUSALE: “SOS CORONAVIRUS TRAPANI”, indicando cognome e nome del donatore.

  I fondi raccolti saranno devoluti all’Azienda Sanitaria Provinciale di Trapani affinchè,
  in relazione all’importo raccolto, vengano impiegati per l’acquisto di beni strumentali
  per i pronto soccorso e gli ospedali della Provincia di Trapani in cui sono stati
  attivati i reparti Covid e/o per l’acquisto di dispositivi di protezione individuale
  per medici e paramedici.

  Oggi siamo chiamati a dare il nostro contributo, manifestando responsabilità, sensibilità
  e solidarietà verso chi è in corsia in prima linea. È per questo motivo che vogliamo,
  tutti insieme, aiutare chi ogni giorno si impegna ad aiutarci.

  Un sentito ringraziamento per ciò che vorrai fare. Tutti insieme riusciremo a superare
  questo difficile momento.

  F.to

  Il Segretario – arch. Giuseppina PIZZO

  Il Presidente –  arch. Vito MANCUSO'
Email: info@architettitrapani.it
Link: https://www.architettitrapani.it/dettagli_news.php?id=763&tipo=news
Nome: 'Provincia di #Trapani -SOS Coronavirus. L’Ordine degli Architetti della Provincia
  lancia una raccolta fondi'
Posizione: 38.018632 12.51817 0 0
</yamldata></pre>

**Comment by michelerestuccia** [comment]
La raccolta è conclusa come annunciato in https://www.architettitrapani.it/dettagli_news.php?id=771&tipo=news
