### ISSUE TITLE
Aiuto Bufale su Whatsapp

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1479]
<pre><yamldata>
Cosa: Bufale
Descrizione: Mi è arrivato un link su whatsapp, ho cliccato e ho compilato il breve
  sondaggio senza inserire però dati personali, poi ho scoperto che fosse una truffa,
  che cosa posso fare per proteggere i miei dati?
Email: rosorpicari@gmail.com
Link: https://promozioniltaliane.com/supermercato/
Nome: Picari Rozalda
</yamldata></pre>

**Comment by cristigalas** [comment]
@chiccap non possiamo accettare, c’è link alla bufala. Rispondiamo via email di contattare polizia postale.

**Comment by cristigalas** [comment]
> @chiccap non possiamo accettare, c’è link al sito truffa e abbiamo già pubblicato smentita. Rispondiamo via email di contattare polizia postale.
