### ISSUE TITLE
Rsa

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1481]
<pre><yamldata>
Cosa: Rsa
Descrizione: 'In RSA via Olgettina 63 Milano Istituto Ambrosiano vi sono decine di
  decessi che non vengono certificati ossia non si fanno i tamponi quindi non si riescono
  ad isolare le persone positive dai sani. Gli unici casi accertati sono di anziani
  che sono stati condotti in pronto soccorso per rottura di femore e sono stati dall''ospedale
  fatti rientrare in RSA i pazienti continuano a fare vita comunitaria mangiando ad
  esempio insieme senza sapere se sono positivi o meno regione Lombardia continua
  a insistere a non fare i tamponi nelle comunità in RSA non tengono gli anziani nelle
  loro camere perché non hanno sufficienti assistenti per gestire gli anziani presso
  le proprie camere gli assistenti hanno un unico camicie che utilizzano quando entrano
  nella stanza dei positivi accertati e poi entrano nelle camere degli altri ospiti
  anche per il cambio del indumenti o l''igiene personale dei pazienti.

  Non è stata fatta una comunicazione ufficiale da parte della RSA ai parenti

  Aiutateci'
</yamldata></pre>

**Comment by favoeva** [comment]
manderei mail a https://peranziani.it/contattaci/segnalazioni chiedendo un feedback

**Comment by Albertopi78** [comment]
Un'altra alternativa è rivolgerci a qualche giornale che possa fare il lavoro. 
Così com'è è una segnalazione non accettabile, secondo me.

**Comment by cristigalas** [comment]
È anonima, secondo me non ci possiamo fare nulla...

**Comment by cristigalas** [comment]
> manderei mail a https://peranziani.it/contattaci/segnalazioni chiedendo un feedback

Anche qui c’è una form che chiede i dati di chi fa la segnalazione, mi sembra complicato segnalare questa segnalazione (scusa gioco di parole :)
