### ISSUE TITLE
Promozioni 200 euro supermercato

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1487]
<pre><yamldata>
Cosa: Promozioni 200 euro supermercato
Descrizione: L’Italia è il paese più colpito in Europa al giorno d’oggi. I cittadini
  sono bloccati nelle loro case, con un accesso molto restrittivo agli acquisti. Quindi,
  tutti i rivenditori di generi alimentari in Italia, abbiamo deciso di creare un’avventura
  comune e aiutare tutta la nostra gente. Offriamo buoni gratuiti a tutti i cittadini
  in Italia (almeno 18 anni). Tutto quello che devi fare è completare il muggito del
  quiz”.
</yamldata></pre>

**Comment by cristigalas** [comment]
Vedi qui https://covid19italia.help/issues/968
