### ISSUE TITLE
Disinfezione e sanificazione

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1501]
<pre><yamldata>
Cosa: Disinfezione e sanificazione
Descrizione: Disinfezione e sanificazione nelle aree esterne dei Progetti Case dalle
  ore 7.30 del 29/03/2020.
Link: https://www.comune.laquila.it/index.php?id_oggetto=3&id_cat=0&id_doc=7044&id_sez_ori=0&template_ori=1&&gtp=1
Posizione: 42.369927 13.320022 0 0
</yamldata></pre>

**Comment by cristigalas** [comment]
Scaduta.
