### ISSUE TITLE
Ass. Energie Sociali Jesurum&Coop Lombardia - Raccolta fondi per servizio consegne a domicilio cibo per animali domestici a over 65

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1507]
<pre><yamldata>
Descrizione: "Si tratta di un servizio per over 65 che provvede a consegne gratuite\
  \ di generi di prima necessità e prodotti per la cura degli animali e (dalla settimana\
  \ prossima) un servizio gratuito di dog sitting. \n\nGrazie alla collaborazione\
  \ con Coop Lombardia e Energie Sociali Jesurum, l'iniziativa porterà nelle case\
  \ di anziane e anziani un massimo di 25 prodotti alimentari ma non solo, anche prodotti\
  \ per gli animali da compagnia, dalla sabbia alla pappa, per aiutare cittadine e\
  \ cittadini a prendersi cura non solo di sé, ma anche dei propri amici animali."
Link: https://www.retedeldono.it/it/progetti/associazione-energie-sociali-jesurum/mai-solo-se-resta-a-casa
Nome_dell_esercizio_commercial: Mai solo, se resti a casa
Posizione: 45.3570822 9.3226748 0 0
</yamldata></pre>

**Comment by cristigalas** [comment]
@luciaroma occhio al titolo, non lo hai modificato o salvato

**Comment by luciaroma** [comment]
non salvato!

**Comment by cristigalas** [comment]
Corretto.

**Comment by chiccap** [comment]
già presente #1422
