### ISSUE TITLE
Unicef, Médecins du Monde, Asinitas: numero per parlare con un medico in #francese #inglese #italiano

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1553]
<pre><yamldata>
Descrizione:  Per tutti coloro che non hanno un medico di base e che vorrebbero un consulto telefonico sul nuovo coronavirus, Médecins du Monde - Missione Italia ha messo a disposizione un numero di #telefono per parlare con un medico, in #francese, #inglese, e #italiano.
 Ecco il numero da chiamare: +39 3510221390
Link: https://www.facebook.com/MdMmissioneItalia
Telefono: '35110221390'
Titolo: Emergenza Covid-19 – Unicef, Médecins du Monde, Asinitas
tel2: '800905570'
</yamldata></pre>

**Comment by cristigalas** [comment]
C’è già https://www.covid19italia.help/issues/1425/
