### ISSUE TITLE
Raccolta fondi per ASL #Cosenza

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#156]
<pre><yamldata>
Descrizione: "Il ricavato verr\xE0 devoluto all\u2019Azienda Ospedaliera di Cosenza\
  \ e sar\xE0 vincolato all\u2019acquisto di materiale medico e/o sanitario necessario\
  \ a fronteggiare l\u2019emergenza COVID-19,\nquali attrezzature per l\u2019UTI,\
  \ cpap, dispositivi di protezione (tute, mascherine e occhiali protettivi) e quant\u2019\
  altro verr\xE0 ritenuto dall\u2019Azienda Ospedaliera stessa secondo le proprie\
  \ esigenze, da valutare anche alla luce della cifra finale che verr\xE0 raggiunta."
Destinatari: Azienda Ospedaliera di Cosenza
Link: https://www.gofundme.com/f/cosenza-anticovid?utm_source=customer&utm_medium=copy_link-tip&utm_campaign=p_cp+share-sheet
Natura_dell_iniziativa: solidale
Tipo_di_soggetto: privato
Titolo: Cosenza Anti-Covid
</yamldata></pre>

**Comment by margheritapuca** [comment]
Comune: Cosenza
Provincia: Cosenza
Regione: Calabria
Posizione: 39.30999 16.25019

**Comment by luciaroma** [comment]
dal link: L'organizzatore ha momentaneamente disattivato le donazioni per questa campagna.
