### ISSUE TITLE
TNVirus.it

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1587]
<pre><yamldata>
Da_chi_offerta: Gruppo di cittadini della provincia di Trento
Descrizione: 'TNVIRUS.IT, nato senza scopo di lucro da un''idea di un gruppo di persone
  di Rovigo, attivo già in altre 14 Province italiane, e da poco anche per le persone
  che si trovano in questo momento in provincia di Trento.

  La formula è semplice: aiutare cittadini ed imprese nel rispondere a domande irrisolte.

  Si spazia dall''apertura dei negozi, alle forme di solidarietà e volontariato delle
  associazioni, fino al bonus 600€ per le partite IVA e all''ausilio cassa integrazione
  per le imprese.

  È una piattaforma aperta a qualsiasi domanda: i gestori del sito girano le questioni
  a esperti di settore, i quali si impegnano a rispondere nella maniera più precisa
  possibile.'
Destinatari: Persone in provincia di trento in questo momento
Link: https://www.tnvirus.it/il-progetto/
Natura: solidale
Posizione: 46.065906 11.126318 0 0
Tipo_di_soggetto: privato
Titolo: TNVirus.it
</yamldata></pre>

**Comment by cristigalas** [comment]
Io non accetterei, non si capisce chi sono e cosa ci fanno con le info che raccolgono..l
