### ISSUE TITLE
Spesa e consegna solidale

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1596]
<pre><yamldata>
Da_chi_offerta: Potere al Popolo Torino
Descrizione: "Chiamaci al 3386103909\n\nPer la spesa solidale siamo stati contattati\
  \ da oltre 30 volontari distribuiti su tutta la città, che ogni giorno consegnano\
  \ spesa e farmaci a casa di anziani, persone in isolamento o chiunque altro non\
  \ possa allontanarsi da casa. Un'esperienza che ci sta insegnando quanto sia importante\
  \ l'esistenza di una comunità che è in grado di aiutarsi reciprocamente, un insegnamento\
  \ che dovremo tenere a mente anche quando (speriamo presto) l'emergenza virus sarà\
  \ passata, ma resteranno, forse ancora più violente, tutte le altre emergenze: lavoro,\
  \ casa, salute, socialità.\n\n https://www.facebook.com/Poterealpopolotorino/photos/a.1938579479508634/3478123825554184/?type=3&theater"
Destinatari: anziani, malati, persone bloccate in casa
Link: https://www.facebook.com/Poterealpopolotorino/photos/a.1938579479508634/3478123825554184/?type=3&theater
Natura: solidale
Tipo_di_soggetto: pubblico
Titolo: Spesa e consegna solidale
</yamldata></pre>

**Comment by cristigalas** [comment]
Doppia.
