### ISSUE TITLE
Raccolta fondi per ospedale di #Crotone

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#160]
<pre><yamldata>
Da_chi_offerta: Matteo Arminio
Descrizione: "Mi chiamo Matteo Arminio, sono un tecnico sanitario di radiologia medica,\
  \ sono preoccupato e ho deciso di agire istintivamente. \nHo cercato su google vari\
  \ siti per poter organizzare questa raccolta, ho trovato questa piattaforma affidabile\
  \ per altre raccolte organizzate e cos\xEC ho deciso di utilizzarla.\n\nHo scelto\
  \ quest'ospedale perch\xE8 \xE8 il punto di riferimento per tutta la provincia,\
  \ \xE8 il punto di riferimento per tutti noi cittadini e perch\xE8 credo fortemente\
  \ che abbia bisogno di supporto materiale.\n\nOggi ci troviamo a fronteggiare un\
  \ emergenza che non conosce eguali, oggi pi\xF9 che mai con un piccolo contributo,\
  \ possiamo aiutare l'Ospedale San Giovanni di Dio di Crotone all'acquisto di ventilatori\
  \ o di altro materiale che supporti tutte le persone che cercano di combattere questo\
  \ virus.\n\nHo 25 anni e da professionista sanitario,  non posso permettermi di\
  \ non fare niente in questa situazione pur non vivendo pi\xF9 nella mia citt\xE0\
  , lo devo ai miei genitori, ai miei parenti, ai miei amici, ai miei conoscenti ed\
  \ alla MIA citt\xE0.\n\nNon siamo in Veneto, in Lombardia,  nel nord Italia, siamo\
  \ in Calabria,dobbiamo fare in modo di sostenerci, perch\xE9 non abbiamo, n\xE9\
  \ i materiali e n\xE8 attrezzature a sufficienza per contrastare quest'epidemia.\n\
  \n\nFacciamo qualcosa e rendiamoci utili."
Destinatari: Ospedale di Crotone
Link: https://www.gofundme.com/f/crotonecovid19?utm_source=customer&utm_medium=copy_link-tip&utm_campaign=p_cp+share-sheet
Natura_dell_iniziativa: solidale
Tipo_di_soggetto: privato
Titolo: CROTONE-Emergenza Covid19
</yamldata></pre>

**Comment by luciaroma** [comment]
L'organizzatore ha momentaneamente disattivato le donazioni per questa campagna.
