### ISSUE TITLE
Ciao Cristina, Il tuo ordine e stato confermato!  Programma la consegna qui vuedc.info/h5g3mf

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1603]
<pre><yamldata>
Cosa: Ciao Cristina, Il tuo ordine e stato confermato!  Programma la consegna qui
  vuedc.info/h5g3mf
</yamldata></pre>

**Comment by cristigalas** [comment]
È spam! Ne sono arrivate altre sotto label fake news. Che facciamo? @avivace @iltempe

**Comment by iltempe** [comment]
Non le accettiamo.

**Comment by cristigalas** [comment]
> Non le accettiamo.

Sì, certo ma c’è un modo per fermare la cosa? Ne sono arrivate altre...
