### ISSUE TITLE
Ehi, a causa di questa crisi i supermercati offrono buoni da 200 €. Prendi uno qui: https://promozio

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1604]
<pre><yamldata>
Cosa: 'Ehi, a causa di questa crisi i supermercati offrono buoni da 200 €. Prendi
  uno qui: https://promozioniltaliane.com/supermercato/ finché dura.'
</yamldata></pre>

**Comment by cristigalas** [comment]
Spam.
