### ISSUE TITLE
supporto psicologico

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1607]
<pre><yamldata>
Da_chi_offerta: Coop ARS onlus
Descrizione: 'In questi giorni difficili siamo chiuse/i in casa con le nostre paure
  che spesso non possiamo comunicare a chi ci è accanto. Per questo A.R.S. ha attivato
  una linea di ascolto per quante/i abbiano voglia di non sentirsi sole/i. E'' importante
  condividere sensazioni e preoccupazioni con esperti psicologi, psicoterapeuti, psichiatri.
  "Non c''è salute senza salute mentale" Puoi chiamare gratuitamente a questo numero.
  Solo sostenedoci possiamo uscirne. Condividi questo post

  #controilvirusmaisoli #unitisivince #andràtuttobene #iorestoacasa

  http://www.arscooperativa.it/'
Destinatari: tutte le donne e gli uomini da qualsiasi Regione, tutte le età
Link: http://www.arscooperativa.it/
Natura: solidale
Tipo_di_soggetto: privato
Titolo: supporto psicologico
</yamldata></pre>

**Comment by Polva13** [comment]
GIà segnalato qui https://github.com/emergenzeHack/covid19italia_segnalazioni/issues/1282
