### ISSUE TITLE
Comunicazione marketing

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1608]
<pre><yamldata>
Cosa: Comunicazione marketing
Descrizione: 'Consulenza gratuita in marketing etico e comunicazione consapevole a
  CHIUNQUE ha un’attività in proprio e in questo momento non sa come muoversi per
  pro-muoversi.

  COME ACCEDERE?

  1. Iscriviti su www.youelements.com/teacher_training

  2. Ricevi via email il link di un gruppo privato su cui si terrà il webinar

  3. Rispondi alla mail con le domande che volete pormi

  4. Vi risponderò pubblicamente durante il webinar di venerdì h11

  Puoi partecipare da tutta Italia ed estero (anche in inglese e francese).

  #solodarietàdigitale'
Destinatari: 'Tutti quelli che hanno attività in proprio. Priorità settori etici:
  come yoga, salute e benessere, sport, olistica, sostenibilità'
Email: Info@youelements.com
Immagine: FD7558D1-99F1-4443-873B-26B2EA53A09E-21_24_47.png
Link: www.youelements.com
Telefono: '3494997789'
</yamldata></pre>

**Comment by chiccap** [comment]
già presente #547
