### ISSUE TITLE
A #Bari il centro antiviolenza rimane attivo

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#163]
<pre><yamldata>
Comune: Bari
Cosa: centro antiviolenza Bari
Descrizione: "I Centri Antiviolenza di BAri non si fermano. Di seguito i contatti:\n\
  \nCentro Antiviolenza del Comune di Bari:\nStrada S. Giorgio n. 21, Bari\nNumero\
  \ Verde: 800202330 (attivo h24) \nNumero di pubblica utilit\xE0: 1522 (attivo h24)\
  \ \nE' aperto dal luned\xEC al venerd\xEC dalle 9.30 alle 12.30 e dalle 15.30 alle\
  \ 18.30.\nhttps://www.centroantiviolenzabari.it/\n\nCAV Paola Labriola: \nVia Napoli\
  \ 308, Bari\nSede ass. G.I.R.AF.F.AH"
Posizione: 41.0965024 16.9564435 0 0
Provincia: Bari
Regione: Puglia
</yamldata></pre>

**Comment by chiccap** [comment]
@avivace cosa dobbiamo sistemare in questa?

**Comment by cristigalas** [comment]
È doppia. Chiudo.
