### ISSUE TITLE
Casa Ronald cerca amuchina, guanti, mascherine #Roma

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#182]
<pre><yamldata>
Cosa: AMUCHINA GUANTI e MASCHERINE
Descrizione: "Fondazione Ronald McDonald\n\n\nLe case Ronald di  Roma che ospitano\
  \ i bambini e famiglia  degli ospedali pediatrici di riferimento sono piene . le\
  \ loro patologie e cure sono INDIFFERIBILI e i pazienti NON DIMISSIBILI. Nelle case\
  \ in cui i nostri operatori sono a contatto con bambini e famiglie ci mancano AMUCHINA\
  \ GUANTI e MASCHERINE . stiamo cercando aiuto dalle aziende amiche . Per poter dare\
  \ continuit\xE0 al servizio abbiamo bisogno del vostro aiuto subito . se avete un\
  \ amico farmacista di quartiere o un supermercato vicini vi chiediamo di fare una\
  \ scorta e di inviarcelo a uno dei seguenti indirizzi . Arrivano subito a chi ne\
  \ ha bisogno senza passare per magazzini.\n\nGrazie.\n\nCasa Ronald Roma Bellosguardo,\n\
  Parco Bellosguardo,\nVia degli Aldobrandeschi 3,\n00163 (Roma)"
Destinatari: Casa Ronald Roma Bellosguardo, Parco Bellosguardo, Via degli Aldobrandeschi
  3, 00163 (Roma)
Indirizzo: 41.882614 12.404634 0 0
Link: https://www.linkedin.com/posts/elenazanella_fondazione-no-profit-ronald-mcdonalditalia-activity-6643058880739897345-4fWx/
</yamldata></pre>

**Comment by cristigalas** [comment]
Doppia.
