### ISSUE TITLE
Decreto reddito di emergenza

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1946]
<pre><yamldata>
Cosa: Decreto reddito di emergenza
Descrizione: 'Buongiorno,

  per poter usufruire il decreto di emergenza dove mi devo rivolgere?

  Il 19/12/2019 la azienda per cui lavoravo è fallita,al momento sono in attesa di
  informazioni dal curatore fallimentare,ps. sono 6 mesi che non ho entrate finanziare.'
Email: zjmarcello@libero.it
Nome: Claudio Vettorato
Telefono: '3479464166'
</yamldata></pre>

**Comment by luciaroma** [comment]
@chiccap @cristigalas come gestiamo questa?

**Comment by cristigalas** [comment]
@luciaroma potremmo chiedere al consulente che ha intervistato Barbara se ci scrive una risposta da inviare via email. Che dici? Eh @chiccap?

**Comment by luciaroma** [comment]
sì mi sembra un'ottima idea e poi gliela giriamo. @chiccap chi ha sua mail?

**Comment by cristigalas** [comment]
> sì mi sembra un'ottima idea e poi gliela giriamo. @chiccap chi ha sua mail?

Barbara D’Amico.

**Comment by luciaroma** [comment]
@BarbaraDAmico abbiamo qui una richiesta di chiarimento su come poter accedere ai sussidi previsti dalla decretazione di emergenza. Possiamo chiedere al consulente di scriverci due righe per email così le giriamo a questa persona?
Puoi occupartene tu di chiederglielo?
Grazie

**Comment by cristigalas** [comment]
@luciaroma semmai scriviamole anche su chat.

**Comment by BarbaraDAmico** [comment]
@luciaroma puoi mettere qui la richiesta? Così capisco meglio grazie

**Comment by BarbaraDAmico** [comment]
Ah sorry, non avevo visto tutta la issue: si si ma è una richiesta a cui possiamo rispondere senza scomodare Furfaro, ti preparo due righe qui di seguito:

**Comment by BarbaraDAmico** [comment]
Per accedere alle misure economiche previste dal decreto Cura Italia occorre monitorare il sito dell'Inps - che è l'ente centrale responsabile della maggior parte delle erogazioni dei sussidi/indennità per l'emergenza covid-19, qui l'indirizzo https://www.inps.it/nuovoportaleinps/default.aspx

In particolare:

- **Le circolari con le istruzioni per la modulistica e i criteri di accesso generali si trovano qui**: https://www.inps.it/nuovoportaleinps/default.aspx?itemdir=53542

- **Congedi parentali e per assistenza persone non autosufficienti**, qui
https://www.inps.it/nuovoportaleinps/default.aspx?itemdir=53541

- **Bonus Baby Sitting**, qui
https://www.inps.it/nuovoportaleinps/default.aspx?itemdir=53540

- **Indennità autonomi 600 euro**, qui (se si è liberi professionisti iscritti a un albo occorre rivolgersi invece al proprio ordine)
https://www.inps.it/nuovoportaleinps/default.aspx?itemdir=53539

L'Inps ha fatto anche sapere che per le richieste online occorrerà **dotarsi di un PIN digitale** che sarà l'ente stesso a rilasciare con una procedura semplificata (monitorando questa pagina https://www.inps.it/nuovoportaleinps/default.aspx?itemdir=53534)

Come indicato dal consulente del lavoro Luca Furfaro è possibile poi rivolgersi:
- alla propria azienda, se si è dipendenti
- al proprio ordine professionale, se si è iscritti a un albo

**Comment by luciaroma** [comment]
nel suo caso, visto che l'azienda è fallita, deve chiedere al curatore fallimentare, giusto?

**Comment by BarbaraDAmico** [comment]
Eh si , anche perché in realtà in questo caso è in una brutta situazione: con il fallimento non si può accedere a molte delle misure del Cura Italia. Ma non dirglielo: deve chiedere direttamente a chi sta seguendo la procedura

**Comment by luciaroma** [comment]
Cosa: Decreto reddito di emergenza
Descrizione: 'Buongiorno,

  per poter usufruire il decreto di emergenza dove mi devo rivolgere?
 Il 19/12/2019 la azienda per cui lavoravo è fallita,al momento sono in attesa di
  informazioni dal curatore fallimentare,ps. sono 6 mesi che non ho entrate finanziare.'

**Comment by BarbaraDAmico** [comment]
Solo un consulente del lavoro può dirglielo, se non ne ha uno deve rivolgersi a un caaf (è una richiesta troppo specifica). Nel Cura Italia sono stati previsti aggiustamenti anche per chi riceve la disoccupazione o naspi, ma appunto non sappiamo questa persona perché non abbia avuto accesso a tali forme di sostegno. Quindi l'unica è che si rivolga ai sindacati e/o al curatore fallimentare

**Comment by BarbaraDAmico** [comment]
@luciaroma per caso abbiamo sulla piattaforma servizi di aiuto/consulenza sulle misure economiche o per i lavoratori? Perché in quel caso potremmo rimandarla a uno di quei servizi

**Comment by luciaroma** [comment]
Qualcosa c'è ma non so se è adatto, cerco.

**Comment by chiccap** [comment]
#1509 o #540

**Comment by BarbaraDAmico** [comment]
Ottimo! Allora io la rimanderei a queste opzioni anche perché la sua situazione è proprio oggetto di dibattito, guardate qui https://www.ilfattoquotidiano.it/2020/03/26/cura-italia-il-rebus-del-curatore-fallimentare-che-non-puo-avviare-licenziamenti-lavoratori-senza-stipendio-ne-disoccupazione/5750243/

**Comment by BarbaraDAmico** [comment]
Scusate, last but not least: @luciaroma copiamo e incolliamo il corpo testo dei servizi segnalati direttamente nell'email di risposta, perché il sito è temporaneamente giù (vedo che ci stanno lavorando). grazie a tutte!

**Comment by luciaroma** [comment]
benissimo, lascio a @chiccap (non appena avrà accesso mail) o @cristigalas 
grazie mille

**Comment by chiccap** [comment]
email inviata!

**Comment by cristigalas** [comment]
> email inviata!

Chiudo.

**Comment by claudiamazzantiact** [comment]
@cristigalas e @chiccap  questa issue non va riaperta?

**Comment by cristigalas** [comment]
@claudiamazzantiact perché riaprirla? Abbiamo inviato email con la risposta...

**Comment by claudiamazzantiact** [comment]
Scusa, pensavo fosse utile avere un feedback prima di chiudere ma come non detto...
