### ISSUE TITLE
Non è vero che puoi richiedere il tuo buono del supermercato

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1947]
<pre><yamldata>
Cosa: Richiedi il tuo buono del supermercato
Descrizione: Ehi a causa di questa crisi i supermercati offrono buoni da 200€. Prendi
  uno qui:https://promozioniitaliane.com/supermercato. finchè dura
</yamldata></pre>

**Comment by cristigalas** [comment]
@luciaroma attenzione questo è spam!
