### ISSUE TITLE
Fondazione Fratelli San Francesco d’Assisi #Milano cerca volontari per consegna farmaci

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1951]
<pre><yamldata>
Cosa: Cercasi volontari - Fondazione Fratelli San Francesco d’Assisi ONLUS a Milano
Descrizione: 'Si cercano volontari per smistamento dei farmaci provenienti dal Banco
  Farmaceutico e di preparare i pacchi per le diverse case di accoglienza.

  Necessario possedere conoscenze di farmaceutica.'
Link: https://www.csvlombardia.it/milano/post/cercarsi-volontari-per-servizio-farmacia-e-smistamento-farmaci/
Posizione: 45.4759642 9.1934105 0 0 
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 45.46679408 9.1903474 (Milano) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=45.46679408+9.1903474&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by chiccap** [comment]
link non più attivo, chiudo!
