### ISSUE TITLE
Richiesta di Tablet per pazienti in isolamento Covid19 - Ospedale #Pavia

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1953]
<pre><yamldata>
Cosa: Tablet
Descrizione: 'Siamo un ospedale di Pavia:
  www.mondino.it
  La nostra attività è di norma dedicata all’ambito neurologico e di psichiatrica
  infantile, ma data l’emergenza sanitaria in corso dedicheremo un intero reparto
  a pazienti codiv 19. In questo ambito avremmo la necessità di dispositivi elettronici
  per consentire ai pazienti ed ai loro famigliari di rimanere in collegamento onde
  mitigare gli impatti psicologici correlati alla gestione del paziente in isolamento.
  Grazie Francesca Acerbi - Dirigente Responsabile IT Fondazione Mondino'
Destinatari: Pazienti con Covid 19 ricoverati
Email: francesca.acerbi@mondino.it
Nome: Francesca Acerbi
Telefono: 0382380363
Posizione:  45.2010395 9.1741206 0 0
</yamldata></pre>

**Comment by cristigalas** [comment]
Fatto tweet bombing a varie aziende e inoltrato richiesta a https://www.donauntablet.it/

**Comment by chiccap** [comment]
Inviata richiesta a info@polotecnologicopavia.it

**Comment by cristigalas** [comment]
Fatto nuovo tweet bombing ad altre aziende tech, tra cui Polo Tecnologico Pavia, e contattato via email e telefono Banco Informatico che ci farà sapere....

**Comment by cristigalas** [comment]
Informatica Ak su Twitter ci ha chiesto di contattarli via email e quindi ho inviato una mail.

**Comment by chiccap** [comment]
Consegnato un tot di 20 dispositivi! L'ospedale ci ringrazia e ci chiede di chiudere!

**Comment by chiccap** [comment]
@cristigalas in questo caso lasciamo label accettato?

**Comment by cristigalas** [comment]
Sì, sì certo... se funziona come per Tci... forse merita fare una verifica sul sito per vedere come si visualizza una volta chiusa.
