### ISSUE TITLE
Iniziativa Spesa "sospesa" in regalo ai più bisognosi - Proponila al tuo supermercato

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1954]
<pre><yamldata>
Cosa: Spesa sospesa - Proponila al tuo supermercato
Descrizione: A causa dell'emergenza Covid19 molte famiglie non avranno la possibilità
  di fare la spesa, proponi la spesa sospesa al tuo supermercato di fiducia, un atto
  di generosità verso chi è in difficoltà.
Link: https://www.ohga.it/la-spesa-sospesa-per-aiutare-chi-e-in-difficolta-a-causa-del-covid-19-chiedi-al-tuo-supermercato-di-aderire/
</yamldata></pre>

**Comment by luciaroma** [comment]
La notizia di fatto è questa:
Dopo aver donato una "spesa sospesa" si invitano i cittadini a contattare la Municipalità via telefono per comunicare la donazione, ma si ricorda che è strettamente vietato recarsi negli uffici municipali per questo servizio. "E' un'iniziativa in soccorso di coloro che, a causa dell'emergenza sanitaria, si trovano in difficoltà economica. Ci basiamo su due principi indissolubili: restare a casa e donare agli altri", sottolinea il presidente della municipalita' Francesco Chirico. Diffuso anche un elenco di attività che effettuano le consegne a domicilio nei quartieri di Materdei, Forcella, Quartieri Spagnoli, Mercato, piazza del Gesù, piazza Mazzini, Pignasecca.

Riguarda Napoli. Non credo sia possibile proporlo al supermercato, ma va concordato tra amministrazione, supermercati/negozi ... 

Sono indecisa se accettare così o se specificare. Ad oggi cmq è attiva solo su Napoli

**Comment by cristigalas** [comment]
No, non accettiamo, non è chiara...
