### ISSUE TITLE
Regala lenti a contatto giornaliere

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#1967]
<pre><yamldata>
Da_chi_offerta: Spaccio occhiali Vision Ghedi BS
Descrizione: 'DA VERIFICARE ESSENDO STATO SEGNALATO DA DIPENDENTE NEGOZIO. https://www.spacciocchialivision.it

  Di Ghedi (BS)

  il nostro punto vendita regala lenti a contatto giornaliere a tutto il personale
  sanitario    e agli esponenti delle forze dell’ordine qualora fossero in grado di
  dimostrare (attraverso per esempio badge identificativo) di lavorare per il SSN
  o per lo stato'
Destinatari: a tutto il personale sanitario    e agli esponenti delle forze dell’ordine
  qualora fossero in grado di dimostrare (attraverso per esempio badge identificativo)
  di lavorare per il SSN o per lo stato
Natura: solidale
Tipo_di_soggetto: pubblico
Titolo: Regala lenti a contatto giornaliere
</yamldata></pre>

**Comment by Polva13** [comment]
Notizia non presente nè sul sito nè sulla pagina facebook dell'esercizio commerciale.
