### ISSUE TITLE
Asta benefica di raccolta fondi per aiutare gli ospedali di #Torino (5-6 aprile)

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2018]
<pre><yamldata>
Descrizione: "Asta benefica di raccolta fondi per aiutare gli ospedali torinesi. \n\
  L’asta inizierà domenica 5 aprile alle 11 e si concluderà alle 21 di lunedì 6 aprile.\n\
  Per partecipare all’asta benefica sarà sufficiente fare la propria offerta nei commenti\
  \ ai post degli artisti che partecipano, su instagram, taggando la persona che ha\
  \ fatto l’ultima offerta più alta.\nPer sapere quali artisti partecipano segui l’hashtag\
  \ #urbanartistpertorino\nLa base d’asta sarà di 50€ (con rilanci minimi di 20€).\n\
  L’offerta più alta tra i commenti vincerà l’asta e si aggiudicherà l’opera.\nIl\
  \ vincitore dell’asta effettuerà il pagamento direttamente all’ospedale mediante\
  \ bonifico bancario (causale “covid-19 asta urban artist per torino”). Troverete\
  \ le coordinate sul post di instagram, a pagamento effettuato sarà sufficiente inviare\
  \ copia del bonifico all'artista per accordarsi sulla consegna."
Link: https://www.facebook.com/ilcerchioelegocce/posts/2979052595473981
Nome: Associazione Il Cerchio e le Gocce, Torino
Posizione: 45.071429 7.682469 0 0
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Iniziativa conclusa

**Comment by cristigalas** [comment]
Scaduta. Chiudo.
