### ISSUE TITLE
Gli Empori Solidali di Case Zanardi a #Bologna cercano beni di prima necessità per le loro attività

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2033]
<pre><yamldata>
Descrizione: 'Dal 2014 gli Empori Solidali di Case Zanardi hanno aiutato 718 famiglie
  bolognesi in difficoltà corrispondenti a 2589 persone di cui 1163 minori.

  Dal 2015 le Cucine Popolari preparano circa 60.000 pasti all’anno per sostenere
  persone in condizione di fragilità economica ma anche sociale e relazionale.

  In questo momento di grave emergenza sanitaria, sociale ed economica sia gli Empori
  Solidali che le Cucine Popolari hanno grandi difficoltà a rifornirsi degli approvvigionamenti
  utili a garantire alle famiglie più fragili l’aiuto necessario.

  Per questo motivo saremo tutti noi cittadini ad essere solidali ed a sostenere gli
  Empori e le Cucine Popolari per aiutarli ad affrontare e superare questa grave emergenza.

  Vi chiediamo quindi un aiuto concreto per permettere ai volontari degli Empori Solidali
  e delle Cucine Popolari di continuare a svolgere il loro prezioso lavoro ed a fornire
  beni di prima necessità e pasti a centinaia di bolognesi ogni settimana.'
Link: https://www.ideaginger.it/progetti/solidali-a-bologna-con-gli-empori-e-le-cucine-popolari.html
Nome: Empori Solidali del Comune di Bologna e le Cucine Popolari
Posizione: 44.493743 11.341985 0 0
</yamldata></pre>

**Comment by cristigalas** [comment]
Doppia.
