### ISSUE TITLE
Emergenza COVID - Spesa solidale

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2034]
<pre><yamldata>
Da_chi_offerta: Seconda Mamma
Descrizione: "Seconda Mamma #restaAcasa ma non si ferma! \nNon possiamo restare inermi\
  \ a guardare le tante famiglie che sono in difficoltà a causa di tutto quello che\
  \ stiamo vivendo.\nAbbiamo dunque aperto una raccolta fondi per sostenere i tanti\
  \ nuclei familiari che ci stanno chiedendo aiuto e che non appartengono già alla\
  \ rete di sostegno di Seconda Mamma.\nCome sempre, tutto con la trasparenza e la\
  \ meticolosità che ci contraddistingue: pubblicheremo periodicamente i dati relativi\
  \ alla raccolta fondi, agli aiuti erogati e a quanti nuclei famigliari in più sono\
  \ stati sostenuti sulla home page del nostro sito internet.\n\nSe hai bisogno di\
  \ sostegno temporaneo per la spesa alimentare, puoi contattare i volontari di Seconda\
  \ Mamma tramite i seguenti canali:\n- Modulo di contatto nella home page del sito\
  \ http://www.secondamamma.org/\n- mail a info@secondamamma.org\n- via telefono al\
  \ numero +39 379 198 7376\n- tramite messaggio privato sulla nostra pagina facebook\
  \ http://fb.me/SecondaMammaVolontariato"
Destinatari: Famiglie con minori in temporaneo stato di indigenza
Link: http://www.secondamamma.org/
Natura: solidale
Tipo_di_soggetto: privato
Titolo: Emergenza COVID - Spesa solidale
Posizione: 41.0880031 16.83698 0 0
</yamldata></pre>

**Comment by FrancescaZambi89** [comment]
già inserita in issue #2029
