### ISSUE TITLE
Zumbimbi

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2036]
<pre><yamldata>
Da_chi_offerta: La Cordata
Descrizione: 'È nato il progetto Zumbimbi!

  Durante questo periodo di emergenza La Cordata ha deciso, insieme al Comune di Milano,
  alla Cooperativa Comin, a Emergency e alla Diaconia Valdese, di fare la loro parte
  e di aiutare chi è maggiormente fragile.

  Per questo ospitano presso la struttura di via Zumbini 6 minori tra i 6 e i 14 anni,
  i cui genitori sono in ospedale perché positivi al Coronavirus e che non hanno altri
  adulti di riferimento che possano prendersi cura di loro. In ottemperanza al protocollo
  sanitario, garantiremo la quarantena in isolamento.'
Destinatari: minori tra i 6 e i 14 anni
Link: https://www.lacordata.it/zumbimbi/
Natura: solidale
Tipo_di_soggetto: privato
Titolo: Zumbimbi
</yamldata></pre>

**Comment by FrancescaZambi89** [comment]
già inserita nella issue #1255 che ho arricchito con il link riportato in questa segnalazione. 
chiudo e non accetto
