### ISSUE TITLE
Italia IN Social Network del Made in Italy

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2050]
<pre><yamldata>
Da_chi_offerta: CBF E-Social S.R.L. startup innovativa e CAD Sociale Pavia
Descrizione: 'Stiamo costruendo la prima piattaforma Italiana di Import/Export Made
  in Italy, il "Facebook" Italiano, per unire e far comunicare tra loro tutti i commercianti
  e i cittadini Italiani.

  Dopo questa emergenza sanitaria, avremo un altro problema da affrontare, tutti insieme...la
  crisi finanziaria più grande della storia Italiana.

  Quello che sta succedendo con l''Europa deve farci riflettere e deve farci tornare
  un attimo indietro sui nostri passi.

  Dobbiamo tornare ad acquistare Italiano, dalle nostre micro e piccole imprese, da
  Nord a Sud, che stanno cominciando a chiudere per il bene del paese.

  Tutti uniti, siamo l''Italia il paese più bello del Mondo, uniamoci Italiani, uniamo
  l''Italia!🇮🇹🇮🇹

  Visita il sito ufficiale 👇

  https://www.cbfblockchain.com/italiain-social/

  Entra nel gruppo anche tu👇

  https://www.facebook.com/groups/3124054430952250/'
Destinatari: Aziende, partite iva, cittadini, turisti
Link: https://www.cbfblockchain.com/italiain-social/
Natura: sostegno-lavor
Titolo: Italia IN Social Network del Made in Italy
</yamldata></pre>

**Comment by cristigalas** [comment]
Sembra più uno spot che altro, non accetterei. Che dici @chiccap?
