### ISSUE TITLE
SalvaLì - Compra una gift card al tuo locale preferito

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2059]
<pre><yamldata>
Da_chi_offerta: SalvaLì
Descrizione: SalvaLì è una piattaforma solidale online che permette ai ristoranti
  di offrire ai propri clienti abituali, e chiunque lo desideri, la possibilità di
  comprare delle Gift Card da spendere nel loro ristorante preferito appena riaprirà
  (quanto prima!!)
Destinatari: ristoranti e altri servizi
Link: http://www.salvali.it/
Natura: sostegno-lavor
Posizione: 45.464059 9.188433 0 0
Titolo: SalvaLì - Compra una gift card al tuo locale preferito
</yamldata></pre>

**Comment by PaolaLiliana** [comment]
@chiccap secondo me questa issue non va accattata, mi sembra una promozione pubblicitaria

**Comment by cristigalas** [comment]
Concordo.
