### ISSUE TITLE
Servono letti, materassi, frigo, cucina e lavatrice per famiglia senza reddito a #Milano quartiere #Giambellino.

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2082]
<pre><yamldata>
Cosa: Servono letti, materassi, frigo, cucina e lavatrice per famiglia senza reddito.
Descrizione: 'Alla Milano che si muove.
  Servono letti, materassi, frigo, cucina e lavatrice per famiglia senza reddito.
  6 figli, tutti minorenni. Ricevono il pacco alimentare ma non possono cucinare quello
  che contiene. Dormono per terra.
  Scrivete a giambellinolorenteggio@gmail.com'
Destinatari: famiglia senza reddito
Email: giambellinolorenteggio@gmail.com
Indirizzo:  45.44696905 9.137870756854172 0 0
Link: https://www.facebook.com/LaboratoriodiQuartiereGiambellinoLorenteggio/
Nome: Laboratorio di Quartiere Giambellino-Lorenteggio
</yamldata></pre>

**Comment by chiccap** [comment]
L’associazione non ha piú risposto alla nostra email del 14/4 in cui chiedevamo se la richiesta fosse stata risolto. Probabilmente hanno risposto al bisogno.

**Comment by chiccap** [comment]
@cristigalas in questa mettiamo label risolta?

**Comment by cristigalas** [comment]
Non so, non ne abbiamo certezza... riproviamo a sollecitare una risposta? Semmai su Facebook?

**Comment by chiccap** [comment]
Ho scritto attendiamo risposta!

**Comment by chiccap** [comment]
Su fb hanno risposto che hanno risolto chiudo.
