### ISSUE TITLE
Per attività di mediazione e supporto psicologico-sociale la cooperativa Crinali ricerca 10 tablet e 3 smartphone #Milano

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2108]
<pre><yamldata>
Cosa: 10 TABLET e 2 TELEFONI CELLULARI - per attività di mediazione
Descrizione: "La cooperativa Crinali, che da anni si occupa di supporto, accoglienza\
  \ e orientamento dei migranti (in particolare donne e bambini) presso i servizi\
  \ socio-sanitari del territorio (ospedali, consultori familiari, strutture di accoglienza\
  \ o sostegno psico sociale) ha dovuto adattare le proprie attività e servizi (mediazione\
  \ linguistico culturale, sostegno psicologico, sostegno alle donne e loro bambini)\
  \ alle esigenze del momento attuale. In particolare dal 9 marzo la cooperativa sta\
  \ svolgendo parte delle sue attività con un sistema a distanza, non potendo recarsi\
  \ presso le strutture e venire in contatto con i beneficiari.\n\nI progetti nei\
  \ consultori familiari di Milano, negli ospedali dell'ASST Santi Paolo e Carlo presso\
  \ i servizi sociali per minori in carcere richiedono attualmente un supporto organizzativo\
  \ e tecnologico che sostenga le attività di mediazione e supporto psico-sociale\
  \ a distanza. \n\nPer questo sarebbero necessari 10 tablet , comprensivi di SIM,\
  \ e 3 smartphone attivi, comprensivi di SIM."
Posizione: 45.49424 9.20317 0 0
Email: k.scorzelli@coopcrinali.it
Link: www.crinali.org
Nome: Karina Scorzelli - Presidente Cooperativa CRINALI
</yamldata></pre>

**Comment by chiccap** [comment]
Inviata richiesta a wind tramite modulo: https://www.samsung.com/it/support/email/

**Comment by chiccap** [comment]
Aggiornamento: https://www.donauntablet.it/ donano solo a Ospedali quindi l'associazione non ha potuto usufruirne. rilanciamo? @luciaroma @cristigalas

**Comment by luciaroma** [comment]
direi proprio di sì .... tra l'altro essendo anche per attività di mediazione, segnalerei anche ad Arci/Unhcr così rilanciano anche loro, che ne dite?

**Comment by chiccap** [comment]
sì chi va? io oggi sono imballata.

**Comment by cristigalas** [comment]
> Aggiornamento: https://www.donauntablet.it/ donano solo a Ospedali quindi l'associazione non ha potuto usufruirne. rilanciamo? @luciaroma @cristigalas

Ok! Su Twitter rilancio io.

**Comment by chiccap** [comment]
![Crinali](https://user-images.githubusercontent.com/21237278/79559256-ad14c480-80a5-11ea-9f8e-845866ed7f9b.png)

**Comment by chiccap** [comment]
Ricevuti 5 tablet da Amazon e il resto del materiale da privati!

**Comment by cristigalas** [comment]
@chiccap aveva dimenticato la label Risolta :)

**Comment by chiccap** [comment]
> @chiccap hai dimenticato la label Risolta :)

Hai ragione! Che bella label :)
