### ISSUE TITLE
Raccolta fondi per acquisto di caschi per la ventilazione non invasiva destinati agli Ospedali in #Campania - Fondazione Le Quattro Stelle Onlus

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2117]
<pre><yamldata>
Descrizione: "In questo drammatico momento di emergenza sanitaria è necessario il sostegno di TUTTI, piuttosto che a progetti, agli enti sanitari che lottano per salvare vite. In tale contesto, la Fondazione Le Quattro Stelle, previo confronto tra i membri del Comitato scientifico ed alcuni ricercatori campani, ha scelto di dare un aiuto concreto nella battaglia che l’Italia, nello specifico la Campania, sta portando avanti  promuovendo una campagna di fundraising per l’acquisto di dispositivi medici, in particolare caschi per la ventilazione non invasiva, da donare ai seguenti ospedali: Ospedale Cotugno di Napoli, Ospedale SS. Anna e Sebastiano di Caserta e Ospedale Maddaloni (individuato quale presidio ospedaliero in caso di emergenza #Covid
  a Caserta). Il tutto con il supporto di www.oksalute.it anche per il reperimento dei dispositivi medici. Qualsiasi donazione sarà detraibile per le persone fisiche nonché deducibile dalle
  imprese, così come statuito dall’ art. 66 del decreto cd. “Cura Italia”, con la
  presentazione al proprio commercialista della ricevuta rilasciata da Facebook."
Destinatari: "Ospedale Cotugno di Napoli, Ospedale SS.Anna e Sebastiano di Caserta, Ospedale Maddaloni (CE)."
Email: info@lequattrostelle.it
IBAN: IT27D0335901600100000108 633
Intestazione: FONDAZIONE LE QUATTRO STELLE ETS
Link: "https://www.facebook.com/donate/202627401009849/?fundraiser_source=external_url
https://www.lequattrostelle.it/chi-siamo.html"
Posizione: 41.08031 14.33758
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 40.83956554 14.25085002 (Napoli) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=40.83956554+14.25085002&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by michelerestuccia** [comment]
La raccolta fondi è terminata
