### ISSUE TITLE
COVID-19 Trend Logaritmico Italia

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2122]
<pre><yamldata>
Cosa: COVID-19 Trend Logaritmico Italia
Descrizione: Dashboard interattiva che mostra diverse variabili tra cui contagi, decessi
  e tamponi. Il grafico incrocia l'aumento con il numero totale per mostrare se le
  misure restrittive stanno sortendo gli effetti desiderati.
Fonte: Mattia Zago
Link: https://www.zagomattia.it/covid/
</yamldata></pre>

**Comment by cristigalas** [comment]
Concordo.
