### ISSUE TITLE
Richiesta aiuto su indicazioni per collaboratrice domestica #Milano

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2123]
<pre><yamldata>
Descrizione: "Desidero ricevere indicazioni su come comportarmi con la collaboratrice
  domestica che segue i miei genitori per le pulizie, a fronte dell’emergenza attuale
  in cui ci troviamo. La persona è assunta regolarmente, e fino ad ora le abbiamo chiesto di astenersi
  dal lavoro tramite ferie 2020 retribuite, considerando pericoloso che si recasse presso l’abitazione di una persona anziana (e quindi a rischio di contagiarla). Col protrarsi dell’emergenza non sappiamo però come sia corretto procedere, per lei e per noi. Quali strumenti e quali soluzioni sono disponibili in questo momento? Il nuovo decreto introduce qualche forma d sostegno per queste figure, e soprattutto come attivarle? A chi rivolgersi?"
Email: instafanu@gmail.com
Posizione: 45.464352 9.190627 0 0
</yamldata></pre>

**Comment by sessen-daniel** [comment]
@cristigalas le richieste di aiuto personali si accettano e si mettono in bollettino? Come verificarle?

**Comment by cristigalas** [comment]
@sessen-daniel no, non si pubblicano ma si cerca di dare loro risposta/aiuto via email. Quindi adesso sentiamo le altre ma credo che potremmo passare questa richiesta al nostro contatto Arci.

**Comment by cristigalas** [comment]
@chiccap @Saraveg @claudiamazzantiact @luciaroma chiediamo aiuto a Arci? Oppure al consulente del lavoro che ha fatto la diretta? O entrambi ;)

**Comment by chiccap** [comment]
> @chiccap @Saraveg @claudiamazzantiact @luciaroma @favoeva chiediamo aiuto a Arci? Oppure al consulente del lavoro che ha fatto la diretta? O entrambi ;)

Sí sentiamo il consulente del lavoro! Mi sembra di aver letto dalle info grafiche di lucha y siesta che questa categoria di lavoratrici è esclusa dal decreto ma non vorrei sbagliarmi. Chi ha i contatti?

**Comment by cristigalas** [comment]
> > @chiccap @Saraveg @claudiamazzantiact @luciaroma @favoeva chiediamo aiuto a Arci? Oppure al consulente del lavoro che ha fatto la diretta? O entrambi ;)
> 
> Sí sentiamo il consulente del lavoro! Mi sembra di aver letto dalle info grafiche di lucha y siesta che questa categoria di lavoratrici è esclusa dal decreto ma non vorrei sbagliarmi. Chi ha i contatti?

Il contatto lo ha @bdamico.

**Comment by BarbaraDAmico** [comment]
Eccoci, non inoltrerei richieste simili al consulente che ho intervistato perché non lo fa gratis (purtroppo non sono domande generali, sono esigenze specifiche e come minimo il consulente per fare una risposta deve vedere il contratto, capire che è succ... eccc..). Furfaro in sostanza lo fa a pagamento.  Ma se per caso abbiamo il contatto di un consulente del lavoro o legale che in questo momento sta facendo supporto/consueling iniziale pro bono, possiamo reindirizzarli lì. Detto ciò le risponderei così:

Buongiorno,

Certo, esistono servizi di consulenza specifici proprio per il lavoro domestico e per il vostro caso particolare. Le consigliamo di contattare Assoincolf che ha predisposto una pagina specifica: 
https://www.assindatcolf.it/speciale-coronavirus/

Anche l'associazione Domina può esservi di aiuto. Hanno previsposto un vademecum https://associazionedomina.it/wp-content/uploads/2020/03/vademecum-DOMINA-lavoro-domestico.pdf e sono raggiungibili qui  https://associazionedomina.it/tesseramento-gratuito/

Spesso queste organizzazioni hanno i loro consulenti legali o del lavoro quindi è più semplice porre le domande.

Se invece avesse bisogno di consulenti legali o del lavoro può sentire anche lo Studio Furfaro - CodivHelp ha intervistato Luca Furfaro sui temi del decreto Cura Italia - reperibile tramite questo sito https://www.consulentedellavorotorino.com/ - la consulenza in genere, lo precisiamo, non è gratuita.

Speriamo di esserle stati d'aiuto

Covidhelp

**Comment by chiccap** [comment]
email di risposta inviata! attendiamo un riscontro ma nel frattempo chiuderei!
