### ISSUE TITLE
Avviso pubblico per erogazione buoni spesa - Comune #Lucoli #LAquila

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2128]
<pre><yamldata>
Da chi è offerto: Comune di Lucoli
Descrizione: " Con ordinanza sindacale n. 12 del 31/03/2020 sono stati adottati i criteri per la concessione dei buoni spesa previsti dall’Ordinanza del Capo Dipartimento della Protezione Civile n. 658 del 29/03/2020. Possono fare domanda i nuclei familiari in gravi difficoltà economiche:
  - senza alcun reddito disponibile e alcuna forma di sostentamento reperibile attraverso
  accumuli bancari o postali;
  - privi di forme di sostegno pubblico oppure beneficiari di forme di sostegno pubblico
  fino ad un massimo di € 500,00 mensili, fermo restando che i nuclei familiari privi
  di qualsivoglia forma di sostegno avranno la priorità nell’assegnazione del buono. 
Gli esercizi commerciali dove sarà possibile spendere il buono assegnato e il modello di domanda sono riportati sul sito. Gli interessati dovranno presentare domanda preferibilmente a mezzo posta elettronica all’indirizzo servizidemografici@comune.lucoli.aq.it oppure a mezzo posta elettronica
certificata all’indirizzo servizioamministrativo.lucoli.aq@legalmail.it. Solo in caso di
indisponibilità dei suddetti strumenti, la domanda può essere presentata al protocollo
dell’ente nei seguenti orari di apertura: dal lunedì al venerdì ore 9.00-12.00, martedì e
giovedì ore 15.00-16.30. Le domande dovranno pervenire agli indirizzi di posta elettronica indicati a partire dalla pubblicazione del presente avviso e fino al 06.04.2020. Le domande pervenute oltre il predetto termine saranno evase solamente nel caso di disponibilità di risorse e secondo l’ordine cronologico di arrivo."
Telefono: 3451426217 (dal lunedì al venerdì esclusivamente dalle ore 9.00 alle ore 12.00)
Destinatari: Persone e/o famiglie in condizioni di disagio, comune di Lucoli.
Link: http://www.comune.lucoli.aq.it/
Natura: solidale
Tipo_di_soggetto: pubblico
Titolo: "Avviso pubblico per erogazione buoni spesa - Comune #Lucoli"
Comune: Lucoli
Provincia: L'Aquila
Regione: Abruzzo
Posizione: 42.25155 13.37688
</yamldata></pre>

**Comment by cristigalas** [comment]
Scaduta. Chiudo.
