### ISSUE TITLE
Avviso pubblico per erogazione buoni spesa - Comune #Tornimparte #LAquila

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2132]
<pre><yamldata>
Da chi è offerta: Comune di Tornimparte
Descrizione: "I Cittadini che si trovano in difficoltà economica causata dalle misure
legate all’emergenza Coronavirus, potranno fare richiesta dei buoni spesa compilando il modulo di
autocertificazione che può essere scaricato dal sito del Comune. Il contributo viene erogato PRIORITARIAMENTE alle persone che NON sono già assegnatarie di sostegno erogato da Enti Pubblici (es.: reddito o pensione di cittadinanza, reddito di inclusione, bonus 600 euro, etc.).  La misura si articola su un “pacco spesa” di prodotti di prima necessità che verrà consegnato dai volontari del COC coordinati dalla PIVEC e su un “buono spesa” da utilizzare in tutti gli esercizi commerciali aderenti che trovate a breve sul sito. Le domande dovranno essere presentate entro le ore 12:00 del 9 aprile 2020.
Al fine di non creare sovraffollamento all’interno del municipio, vi invitiamo a inoltrare la richiesta all’indirizzo e-mail protocollo@comune.tornimparte.aq.it
Tutti coloro i quali non sono in grado di utilizzare i mezzi informatici, possono lasciare la richiesta nella cassetta delle lettere del Municipio ."
Destinatari: Persone in difficoltà economica, comune di Tornimparte
Telefono:  "Comune di Tornimparte 0862 72372;
 Sindaco 3294243305; 
Polizia Locale 3488600784; 
Responsabile Protezione Civile Tornimparte Matteo Rossi 3348844865"
Link: http://www.comune.tornimparte.aq.it/index.php?id=19&oggetto=295&fbclid=IwAR120DSGjCt-Ji7AKrMYAqvJ3e7q5npLJPBq6M1wejcV0Qh1r5ZUZMnAGiU
Natura: solidale
Tipo_di_soggetto: pubblico
Titolo: "Avviso pubblico per erogazione buoni spesa- Comune #Tornimparte"
Comune: Tornimparte
Provincia: L'Aquila
Regione: Abruzzo
Posizione: 42.29054 13.26662
</yamldata></pre>

**Comment by cristigalas** [comment]
@sessen-daniel ricordati di aggiungere la provincia.

**Comment by cristigalas** [comment]
Scaduta. Chiudo.
