### ISSUE TITLE
URGENTE: Richiesta camici monouso per Ospedale #Matera

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2144]
<pre><yamldata>
Cosa: Richiesta camici monouso
Descrizione: Servono urgentemente camici monouso per l'ospedale di Matera
Destinatari: Personale dell'Ospedale di Matera
Email: 
Link: https://www.facebook.com/groups/673361526137687/1743219059151923/?comment_id=1743248065815689&notif_id=1585814961725275&notif_t=group_comment_mention
Nome: Ospedale di Matera
Posizione: 40.66852 16.60159
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Segnalazione inserita da form, il contatto è mio, manca quello locale

**Comment by favoeva** [comment]
ho trovato solo questo articolo che parla in generale di problemi rifornimento DPI ospedali Matera e Provincia https://www.sassilive.it/salute-e-sociale/notizie-mediche/coronavirus-fials-chiede-tamponi-per-tutti-gli-operatori-sanitari-e-pazienti-di-strutture-pubbliche-e-private-di-matera-e-provincia/

**Comment by cristigalas** [comment]
Anch’io non ho trovato nulla. Chiudiamo.
