### ISSUE TITLE
In questi giorni abbiamo messo in campo tante azioni per sostenere chi è maggiormente in difficoltà,

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2146]
<pre><yamldata>
Causale: '[Codice Fiscale del > Versante] + Donazione emergenza'
Descrizione: 'In questi giorni abbiamo messo in campo tante azioni per sostenere chi
  è maggiormente in difficoltà, con questo #Iban privati e aziende potranno fare donazioni
  per permettere l’acquisto di generi di prima necessità da donare alle persone più
  bisognose. Partecipare alla raccolta fondi produce un doppio beneficio: dare sollievo
  alle persone più deboli, in ossequio al principio costituzionale di solidarietà,
  e uno sconto fiscale per chi dona. #Covid19 #RaccoltaFondi'
Email: info.lifeonlus@gmail.com
IBAN: IT66E0623075010000057138001
Intestazione: ASSOCIAZIONE LIFE
Link: https://g.page/asslifeonlus
Nome: ASSOCIAZIONE LIFE
Posizione: 41.034578 14.341165 0 0
</yamldata></pre>

**Comment by favoeva** [comment]
il link rimanda a una posizione google . Non trovo sito.

**Comment by cristigalas** [comment]
Non accettiamo.
