### ISSUE TITLE
Associazione Cielo e terra Onlus ricerca 3 tablet da donare per didattica a distanza #Legnano #Milano

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2149]
<pre><yamldata>
Cosa: Tablet per didattica a distanza
Descrizione: Per attività scolastica di didattica a distanza si cercano 3 tablet da
  fornire a famiglie di richiedenti asilo politico o titolari di protezione internazionale
Email: PROFUGHI@CIELOETERRAONLUS.ORG
Indirizzo: 45.599176 8.909998 0 0
Link: http://www.cieloeterraonlus.org/
Posizione: 45.59470 8.91836
Nome: Associazione Cielo e terra Onlus
Telefono: '3488553097'
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
@chiccap e @cristigalas possiamo rilanciare questa?

**Comment by chiccap** [comment]
Inviata richiesta a wind tramite modulo: https://www.samsung.com/it/support/email/

**Comment by chiccap** [comment]
Ho contattato l'associazione 2 tablet sono stati reperiti tramite la scuola e 1 donato tramite la segnalazione! chiudo!
