### ISSUE TITLE
Emergenza Coronavirus: tutti gli aiuti al non profit e al Paese.

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2154]
<pre><yamldata>
Da_chi_offerta: https://italianonprofit.it/
Descrizione: invita a compilare schede per le necessità degli enti del terzo settore
  finalizzate a ricevere aiuti, raccordare iniziative e tc.
Destinatari: enti terzo settore e beneficiari
Natura: solidale
Posizione: 39.568436 8.296875 0 0
Tipo_di_soggetto: privato
Titolo: 'Emergenza Coronavirus: tutti gli aiuti al non profit e al Paese.'
</yamldata></pre>

**Comment by cristigalas** [comment]
Non c’è un link utile se non un generico rimando alla home del sito e sul sito non c’è nulla a riguardo. Non accetterei.
