### ISSUE TITLE
MISURE URGENTI DI SOLIDARIETÀ ALIMENTARE  AVVISO PUBBLICO PER MANIFESTAZIONE DI INTERESSE Comune di 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2168]
<pre><yamldata>
Cosa: 'MISURE URGENTI DI SOLIDARIETÀ ALIMENTARE  AVVISO PUBBLICO PER MANIFESTAZIONE
  DI INTERESSE Comune di Loreto #Ancona'
Descrizione: i titolari degli esercizi commerciali per la vendita di generi alimentari
  che hanno sede nel territorio comunale di Loreto  e che intendano essere inclusi
  nel predetto elenco, possono manifestare il loro interesse utilizzando l’allegato
  modulo da far pervenire al Comune con la massima urgenza.
Link: http://www.comune.loreto.an.it/comunicazioni/index.php?id=read&idnews=3901
Posizione: 43.438136 13.619434 0 0
</yamldata></pre>

**Comment by favoeva** [comment]
non accetterei questo tipo di segnalazioni. Sono avvisi già pubblicati sui siti sezione trasparenza dei Comuni e si rivolgono ad aziende che volgiono essere inserite nell'elenco di quelle accreditate per l'utilizzo dei buoni spesa da parte dei cittadini .

**Comment by cristigalas** [comment]
@favoeva ok. Segnalo anche a @chiccap @claudiamazzantiact @sessen-daniel @luciaroma @PaolaLiliana @Polva13
