### ISSUE TITLE
Raccolta fondi Mastini Varese Hockey per acquisto materiale sanitario Ospedale #Varese

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2179]
<pre><yamldata>
Descrizione: La società di hockey su ghiaccio di Varese ha avviato una raccolta fondi
  per acquistare mascherine e materiale protettivo da donare all’ospedale di Varese
Link: https://www.gofundme.com/f/5keq9s-sd
Nome: Mastini Varese Hockey
Posizione: 45.463212 9.234302 106.42764282226562 65
</yamldata></pre>

**Comment by chiccap** [comment]
@deborah-aa @MartaMant bravissime, il titolo meglio così

**Comment by michelerestuccia** [comment]
La raccolta è conclusa
