### ISSUE TITLE
Raccolta fondi per donare sapone alla sezione femminile della Casa Circondariale “Lorusso e Cutugno” #Torino

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2188]
<pre><yamldata>
Descrizione: 'Si salva chi può. E chi non può? In questo momento di emergenza sanitaria
  abbiamo deciso di pre-occuparci di una delle fasce più dimenticate della popolazione,
  quella carceraria. Vogliamo rispondere alla richiesta delle detenute del carcere
  di Torino, spaventate come tutti dalla pandemia in atto, regalando loro saponi liquidi
  per rispettare anche lì dentro le più elementari norme igienico sanitarie.

  Verdessenza Soc. Coop, in sostegno all''ufficio della Garante delle persone private
  della libertà personale della Città di Torino, lancia questa iniziativa di raccolta
  fondi perché riconosciamo il diritto di tutti e tutte alla salute, con l''obiettivo
  di donare alla sezione femminile della Casa Circondariale “Lorusso e Cutugno” di
  Torino flaconi di sapone liquido per le mani.

  Con €1000 di donazioni potremo acquistare un numero di flaconi sufficiente per l''intera
  sezione.'
Link: https://www.produzionidalbasso.com/project/libere-di-proteggersi-acquistiamo-sapone-liquido-per-le-detenute-di-torino/?fbclid=IwAR0uT86H8L6Njl68oYSDIG-lU6B2fM2QSZanCzuwsf8qSNouobY3Lu9Z3KQ
Nome: Verdessenza Soc. Coop, Torino
Posizione: 45.07052 7.68573 0 0
</yamldata></pre>

**Comment by michelerestuccia** [comment]
La campagna è conclusa.
