### ISSUE TITLE
Le misure di sostegno al reddito e al mercato del lavoro

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2191]
<pre><yamldata>
Cosa: Le misure di sostegno al reddito e al mercato del lavoro
Descrizione: 'Per arginare gli effetti del tessuto economico ed occupazionale causati
  dall''epidemiogia da Covid-19, il Governo ha adottato, oltre a una serie di DPCM
  per il contenimento della pandemia, il DL n. 18/20 ''Cura Italia'' che stanzia misure
  per 25 miliardi di euro a sostegno dell''economia, di cui circa 10 destinati al
  lavoro. Tra l''altro, l''art. 22 dispone che Regioni e Province autonome possono
  riconoscere anche trattamenti di cassa integrazione salariale in deroga (CIGD).
  Il Decreto Ministeriale 24 marzo 2020 ripartisce, come da tabella riportata, le
  predette risorse alle Regione e alle Province Autonome, per il finanziamento dei
  trattamenti di CIGD, stanziando 1.293,2 milioni di euro quale prima quota per l''anno
  2020.

  https://public.tableau.com/profile/anpalservizi?fbclid=IwAR06SaSMeG7Qg7FyzEiyEmi9pUYYqH86G7CZbMhGZNAZdaLHiu8aQ2XxDzc#!/vizhome/MISUREREGIONALI-EMERGENZACORONAVIRUS/COVID19'
Fonte: Elaborazione Anpal Servizi
</yamldata></pre>

**Comment by FrancescaZambi89** [comment]
il link non funziona

**Comment by claudiamazzantiact** [comment]
Non ho trovato neanche altri link all'articolo da sostituire a questo
