### ISSUE TITLE
Croce Rossa di #Terni promuove per sabato 4 aprile raccolta alimentare presso centro commerciale Cospea

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2202]
<pre><yamldata>
Da_chi_offerta: Croce Rossa Italiana - Comitato di Terni
Descrizione: Sabato 4 aprile, dalle ore 9.00 alle 19.00, presso il centro commerciale
  Cospea di Terni, si effettuerà una raccolta alimentare promossa dal comitato di
  Terni della Croce Rossa Italiana. Chi può può comprare alcuni alimenti che le famiglie
  più bisognose non riescono a recuperare, come pasta, riso, caffè, cibo in scatola,
  e per i più piccoli omogeneizzati e pastine. Ci penseranno poi i volontari della
  Croce Rossa a recapitare questi prodotti alle famiglie.
Destinatari: Famiglie più bisognose
Link: https://m.facebook.com/story.php?story_fbid=1167772550232567&id=404416159901547
Natura: solidale
Tipo_di_soggetto: privato
Titolo: Raccolta alimentare
</yamldata></pre>

**Comment by cristigalas** [comment]
Scaduto. Chiudo.
