### ISSUE TITLE
Siamo gli infermieri della RSA Villa Giulia di Roma. Abbiamo organizzato una raccolta fondi per aiut

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2215]
<pre><yamldata>
Descrizione: Siamo gli infermieri della RSA Villa Giulia di Roma. Abbiamo organizzato
  una raccolta fondi per aiutare noi ed altre cliniche nella nostra situazione per
  comprare dispositivi di protezione individuale, in quanto le istituzioni non ci
  aiutano nei rifornimenti di dispositivi. Avere un gran numero di dispositivi di
  protezione individuale significa tutelare il personale ed i pazienti, riuscendo
  ad azzerare i contagi e di conseguenza non occupare posti letto negli ospedali adibiti
  alla lotta al covid-19.
Email: luca.tessecini@gmail.com
Link: https://www.gofundme.com/f/aiutiamo-le-rsa?utm_source=customer&utm_medium=copy_link&utm_campaign=p_cf+share-flow-1
Nome: Aiutiamo le RSA
Posizione: 41.839354 12.422554 0 0
</yamldata></pre>

**Comment by PaolaLiliana** [comment]
La segnalazione è stata già inviata qui: #2213

**Comment by chiccap** [comment]
> La segnalazione è stata già inviata qui: #2213

Quando non accetti devi anche chiudere la segnalazione!
