### ISSUE TITLE
Sportello virtuale e supporto psicologico a distanza #Prato #Firenze

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2216]
<pre><yamldata>
Da_chi_offerta: Oxfam Italia
Descrizione: 'A Prato, il servizio di ascolto e informazione del community center
  Cieli Aperti rimane attivo attraverso uno sportello virtuale, anche per aiutare
  le persone più vulnerabili a orientarsi rispetto alle nuove regole imposte dall’emergenza
  coronavirus.

  I cittadini italiani e stranieri di Prato possono infatti contattare operatori dedicati
  via telefono e via email per richiedere informazioni e aiuto.

  Il Community Center offre anche un servizio di supporto psicologico tramite telefono.
  Per usufruirne, è possibile scrivere via email a info@cieliaperti.it richiedendo
  un colloquio con la psicologa del centro e lasciando il proprio numero di telefono.
  La psicologa provvederà a mettersi in contatto con gli utenti.

  Per informazioni telefono 3898475801

  Posizione: 43.88187 11.09765'
Destinatari: I cittadini italiani e stranieri di Prato
Link: https://www.facebook.com/associazionecieliapertionlus/
Natura: solidale
Tipo_di_soggetto: privato
Titolo: 'Sportello virtuale e supporto psicologico a distanza #Prato #Firenze'
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 43.76923077 11.25588885 (Firenze) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=43.76923077+11.25588885&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by gloriaschiavi** [comment]
doppione #873
