### ISSUE TITLE
il progetto “PortaMi la spesa” per la consegna di prodotti, dagli alimenti all’igiene personale e pe

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2217]
<pre><yamldata>
Descrizione: 'il progetto “PortaMi la spesa” per la consegna di prodotti, dagli alimenti
  all’igiene personale e per la casa, gratuitamente a fasce di popolazione che più
  di altre rischiano di rimanere isolate a causa del coronavirus: disabili, over 70
  con problematiche di salute o non autosufficienti, persone che hanno difficoltà
  a fare acquisti da sole o che per la scarsa confidenza con la tecnologia non sono
  in grado di fare la spesa online, senza contare gli ormai lunghissimi tempi di attesa.

  Basta chiamare il numero 02.4070.3350 da lunedì a venerdì dalle 8.30 alle 14.00
  per parlare con un operatore che appunterà la lista della spesa, per poi consegnarla
  gratuitamente entro i tre giorni successivi. L’ordine potrà essere effettuato una
  volta a settimana, si paga alla consegna solo la spesa.'
Email: info@portamilaspesa.org
Link: https://www.portamilaspesa.org/
Nome_dell_esercizio_commercial: Confcooperative Milano Lodi Monza e Brianza e Legacoop
  Lombardia
Telefono: '0240703350'
</yamldata></pre>

**Comment by chiccap** [comment]
presente #2197
