### ISSUE TITLE
Ordinanza regionale n.36 del 3/4/2020

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2229]
<pre><yamldata>
Cosa: Ordinanza regionale n.36 del 3/4/2020
Descrizione: 'La proroga dell’ordinanza sulle misure di contenimento al Coronavirus
  valide su tutto il Piemonte: avrà efficacia fino al 13 aprile, in linea con il decreto
  del Governo.

  ... vietata ogni attività sportiva all’aria aperta, salvo brevi uscite nei pressi
  della propria abitazione che sono consentite solo entro una distanza massima di
  200 metri...'
Fonte: Regione#Piemonte
Link: https://www.regione.piemonte.it/web/sites/default/files/media/documenti/2020-04/ordinanza_3-4.pdf
</yamldata></pre>

**Comment by deborah-aa** [comment]
già inserito link istituzionale in #issue211, non accettata e chiusa
