### ISSUE TITLE
Chiarimenti di Interesse Generale ordinanza n.36 del 3/4/2020

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2231]
<pre><yamldata>
Cosa: Chiarimenti di Interesse Generale ordinanza n.36 del 3/4/2020
Descrizione: Chiarimenti sull’ordinanza.
Fonte: Regione#Piemonte
Link: https://www.regione.piemonte.it/web/sites/default/files/media/documenti/2020-04/faq_3-4.pdf
Posizione: 45.06776 7.68249
</yamldata></pre>

**Comment by deborah-aa** [comment]
già inserito link istituzionale in #issue211, non accettata e chiusa
