### ISSUE TITLE
Associazione di Promozione Sociale ETNA-Progetto di Psicologia Analitica offre supporto psicologico telefonico gratuito per migranti durante l'emergenza Covid-19 #

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2238]
<pre><yamldata>
Da_chi_offerta: Associazione di Promozione Sociale ETNA-Progetto di Psicologia Analitica
Descrizione: 'ETNA mette in campo i suoi psicoterapeuti con una formazione specifica
  nell''ambito della Etnopsicologia  per promuovere l''iniziativa Corona-Help, nata
  per offrire un supporto psicologico telefonico gratuito, fino alla fine dell''emergenza
  Covid-19.

  Il servizio è rivolto alle persone migranti adulti e minori, ospiti nei centri di
  accoglienza e non, alle persone migranti di seconda generazione e agli operatori
  dei centri offrendo consulenze psicologiche nella gestione delle persone ospitate.'
Destinatari: 'alle persone migranti: uomini, donne,adolescenti, coppie e famiglie
  ospiti di centri di accoglienza e non, alle persone migranti di seconda generazione.
  Agli operatori delle strutture di accoglienza'
Link: www.etnopsicologianalitica.com
Natura: solidale
Posizione: 41.902708 12.49624 0 0
Tipo_di_soggetto: privato
Titolo: Corona-Help supporto psicologico telefonico per migranti
</yamldata></pre>

**Comment by cristigalas** [comment]
Attenzione @deborah-aa c’era già, vedi qui https://covid19italia.help/issues/1556 
Chiudo.
