### ISSUE TITLE
Regione Lombardia cerca imprese che producano mascherine e/o Dispositivi di Protezione Individuale (DPI) #Lombardia

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2241]
<pre><yamldata>
Cosa: Richiesta di disponibilità alle aziende e indicazioni tecniche per la produzione
  di mascherine e dispositivi di protezione individuale
Descrizione: "Cerchiamo aziende che siano in grado di produrre mascherine e/o DPI\
  \ (Dispositivi di Protezione Individuale) idonei anche alla luce di quanto disposto\
  \ dagli artt. 15 e 16 del D.L. 18/2020. \nVi preghiamo, inoltre, di segnalarci la\
  \ vostra eventuale disponibilità alla fornitura di questi ulteriori dispositivi,\
  \ anch’essi necessari per fronteggiare l’emergenza Covid19: \n·       visiere di\
  \ protezione; \n·       occhiali protettivi; \n·       occhiali protettivi a maschera;\
  \ \n·       soluzione idroalcolica in litri; \n·       respiratori; \n·       postazioni\
  \ di terapia intensiva. \nAl link tutte le info per rispondere alla chiamata e le\
  \ indicazioni sulle caratteristiche tecniche richieste."
Destinatari: Aziende
Email: DPIcoronavirus@regione.lombardia.it
Indirizzo: 45.499519 9.19178 0 0
Link: https://www.regione.lombardia.it/wps/portal/istituzionale/HP/DettaglioAvviso/istituzione/attivita-istituzionali/avv-mascherine-made-in-italy?fbclid=IwAR3TquRMgZCapmpHEM2IfgJjrxxHknYiEVYHVW5-DgVPAKwI-OZDqcjcCgA
Nome: Regione Lombardia
</yamldata></pre>

**Comment by SimonettaAA** [comment]
Mi sembra sia la stessa richiesta di aiuto di issue #996

**Comment by favoeva** [comment]
sì è al stessa . Chiudo.
