### ISSUE TITLE
La solidarietà è contagiosa!

IKENGA un'associazione e community center a Palermo.
Dall'inizio di qu

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2243]
<pre><yamldata>
BIC_SWIFT: CCRTIT2T84A
Causale: Solidarietà Contagiosa
Descrizione: 'La solidarietà è contagiosa!

  IKENGA un''associazione e community center a Palermo.

  Dall''inizio di questa emergenza abbiamo supportato tante persone in difficoltà,
  e il 24 marzo è partita la raccolta fondi "solidarietà contagiosa". In dieci giorni
  abbiamo raccolto oltre 1.600€ e diversi generi alimentari, grazie ai quali abbiamo
  distribuito 150 buoni da 10€ e 30 pacchi spesa.

  La nostra rete locale abbraccia prevalentemente persone con origini non italiane,
  per cui sono stati loro i principali beneficiari della nostra iniziativa.

  Abbiamo ancora bisogno di tutte e tutti in attesa che gli aiuti del Comune di Palermo
  vadano a ragime, e con particolare attenzione a coloro che non possono accedervi.'
Email: info@ikengasicily.it
IBAN: IT31E0501804600000016795809
Intestazione: IKENGA APS
Link: https://www.facebook.com/ikenga.palermo/posts/834980140356638
Nome: IKENGA
Posizione: 38.112625 13.36475 0 0
</yamldata></pre>

**Comment by favoeva** [comment]
segnalazione doppia
