### ISSUE TITLE
La scuola si fa in rete: materiale didattico e videolezioni di italiano per stranieri 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2258]
<pre><yamldata>
Da_chi_offerta: Associazione Che Guevara Onlus
Descrizione: Proseguimento delle lezioni di italiano per stranieri attraverso videolezioni
  (zoom) e materiale didattico inviato (whatsapp e Google classroom)
Destinatari: Migranti
Link: https://associazionecheguevara.wordpress.com/
Natura: didattica
Titolo: La scuola si fa in rete
</yamldata></pre>

**Comment by cristigalas** [comment]
Non c’è nessun riferimento sul servizio di videolezioni e didattica online nel loro sito e su pagina Facebook. Non accetto.
