### ISSUE TITLE
Il 5G è la causa delCoronavirus

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2276]
<pre><yamldata>
Cosa: Il 5G è la causa delCoronavirus
Descrizione: In Gran Bretagna sta dilagando il complottismo e la nuova causa del coronavirus
  dicono sia il 5G ovviamente non è vero
Link: https://www.repubblica.it/esteri/2020/04/04/news/_la_rete_5g_e_la_causa_del_coronavirus_il_complottismo_dilaga_online_in_gran_bretagna-253159600/
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente https://www.covid19italia.help/issues/1245/
