### ISSUE TITLE
Webinar 12/3/20 - Didattica a distanza e valutazione delle competenze

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#228]
<pre><yamldata>
Da_chi_offerta: CampusStore
Descrizione: "webinar 12 marzo alle ore 10.30  con  Alessandra Rucci   \n\n#smartlearning\
  \ #elearning #valutazione #MiurSocial"
Destinatari: Insegnanti
Link: https://bit.ly/2THdfbQ
Natura: didattica
Titolo: 'Didattica a distanza e valutazione delle competenze: la parola ai Dirigenti
  Scolastici'

</yamldata></pre>

**Comment by avivace** [comment]
@Jolsty questo Link non ha "http" ma è stato accettato comunque

**Comment by Jolsty** [comment]
@avivace 
Nel form "Segnala Iniziative e Servizi" non c'era la regexp che valida sul link, ho redeployato il form. Se vuoi fai pure una prova

**Comment by chiccap** [comment]
Funziona! Ricordiamoci di chiudere issue domani!

**Comment by cristigalas** [comment]
Scaduta. Chiudo.
