### ISSUE TITLE
Non è vero che la Coop offre una spesa omaggio di 250€ 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2289]
<pre><yamldata>
Cosa: 250€ di spesa omaggio ? :)
Descrizione: Spesa omaggio di 250€ per la Coop. Ovviamente na bufalona
Link: http://www.coop.it-drogheria.club/
</yamldataregione_manuale: quellochevuoi></pre>

**Comment by cristigalas** [comment]
@luciaroma attenzione, è spam! Il sito indicato è quello della truffa! Ne abbiamo ricevuto già altri, questo tipo di fake news non vanno mai accettate.

**Comment by luciaroma** [comment]
ci casco sempre, sorry. Ci farò più attenzione
