### ISSUE TITLE
Raccolta fondi per Ospedali San Paolo e San Carlo #Milano

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#229]
<pre><yamldata>
BIC_SWIFT: BLOPIT22565
Causale: EMERGENZA CORONAVIRUS OSPEDALI SAN PAOLO E SAN CARLO
Comune: Milano
Descrizione: "Al fine di rendere questi gesti di solidariet\xE0 spontanea e vicinanza\
  \ a tutti i nostri operatori ufficiali, sicuri e trasparenti l\u2019ASST Santi Paolo\
  \ e Carlo ha deciso di promuovere una Campagna di raccolta fondi istituzionale."
IBAN: IT92F0311101634000000000003
Intestazione: AZIENDA SOCIO SANITARIA TERRITORIALE SANTI PAOLO E CARLO
Link: https://www.asst-santipaolocarlo.it/web/guest/contenuto-web/-/asset_publisher/Q47FrkrNjNTu/content/campagna-andos-prime-visite-senologiche-gratuite
Nome: OSPEDALI SAN PAOLO E SAN CARLO
Posizione: 45.465549 9.187189 0 0
Provincia: Milano
Regione: Lombardia
</yamldata></pre>

**Comment by chiccap** [comment]
presente #609
