### ISSUE TITLE
Durante il periodo in cui lo sportello legale dell’associazione Todo Cambia dovrà restare chiuso, a 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2303]
<pre><yamldata>
Cosa: CONSULENZE TELEFONICHE SUI PERMESSI DI SOGGIORNO, CITTADINANZA, ECC
Descrizione: 'Durante il periodo in cui lo sportello legale dell’associazione Todo
  Cambia dovrà restare chiuso, a causa delle misure di sicurezza per evitare la diffusione
  del corona virus, sarà offerto un servizio di consulenza telefonica su rilascio
  e rinnovo permesso di soggiorno, ricongiungimento e coesione familiare, permesso
  CE per soggiornanti di lungo periodo, cittadinanza, ecc.

  Inoltre offriamo informazione sulle iniziative di aiuto alimentare e alloggio solo
  nella città di Milano.

  Potete chiamare i seguenti numeri, nei giorni e negli orari indicati:

  Lunedì dalle 18.00 alle 20.00 – Tel. 351 743 3635

  Martedì dalle 16.00 alle 18.30 – Tel. 351 111 8471

  Mercoledì dalle 18.00 alle 20.30 – Tel. 351 111 8471

  Giovedí dalle 9.30 alle 12.00 – Tel. 320 464 9155

  Venerdì dalle 16.00 alle 18.30 – Tel. 351 111 8471

  Appena sarà possibile riaprire la nostra sede lo sportello tornerà a svolgere il
  suo consueto orario: tutti i lunedì dalle ore 18.30 alle 20.30 in via Benaco 1 (presso
  arci Ohibo)'
Destinatari: persone immigrate
Email: tc@todocambia.net
Immagine: logo_Todo Cambia-11_35_38.tif
Link: https://todocambia.net/
Telefono: 351 111 8471
</yamldata></pre>

**Comment by Fatima-web** [comment]
@chiccap questo è un doppione del #1163, lo chiudo
