### ISSUE TITLE
Servizio di assistenza e ascolto telefonico per stranieri dello Sportello ARCI #Pescara

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2306]
<pre><yamldata>
Da_chi_offerta: ARCI Pescara
Descrizione: 'Durante il periodo di emergenza Covid-19 i servizi dello Sportello per
  la tutela dei diritti gestito da ARCI Pescara sono riconvertiti in chiave smart
  attraverso l''attivazione di un servizio telefonico di ascolto, supporto e orientamento
  per i cittadini stranieri e attraverso l''attività della Pagina Facebook dello Sportello.

  Gli operatori offrono assistenza e orientamento sugli interventi di pronto intervento
  sociale e assistenza attivati sul territorio a seguito dell''emergenza; supporto
  e assistenza per gli adempimenti amministrativi e burocratici per l''accesso alle
  risorse per il sostegno economico; diffusione di materiale informativo in lingua.

  Contatti

  telefono: 393 8819512 - lunedì, martedì, mercoledì, giovedì dalle 10.30 alle 17.00

  email: sportello@arcipescara.org'
Destinatari: cittadini stranieri
Link: https://www.facebook.com/pg/ARCI-Sportello-di-informazione-consulenza-e-tutela-dei-diritti-107225807393242/about/?ref=page_internal
Natura: solidale
Posizione: 42.46663 14.21393
Tipo_di_soggetto: privato
Titolo: Sportello telefonico di informazione, consulenza e tutela dei diritti
</yamldata></pre>

**Comment by Fatima-web** [comment]
@chiccap questo è un doppione del #2302 non ancora accettato. quale dei due andrebbe chiuso?
geolocalizzato con Pescara Via Venezia (sede di questa Arci)

**Comment by Fatima-web** [comment]
@chiccap cambiato titolo e aggiunta label Stranieri, è ok?

**Comment by cristigalas** [comment]
Sì, è un doppione. Non accettiamo e chiudiamo.
