### ISSUE TITLE
Il Centro Antiviolenza I-Dea si pone come punto di riferimento per donne che si trovano in situazion

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2311]
<pre><yamldata>
Da_chi_offerta: Be Free Cooperativa Sociale contro tratta, violenze e discriminazioni
Descrizione: "Il Centro Antiviolenza I-Dea si pone come punto di riferimento per donne\
  \ che si trovano in situazioni di violenza. È collegato alla linea telefonica nazionale\
  \ antiviolenza 1522 ed è reperibile telefonicamente 24 ore su 24. \nIl Centro effettua\
  \ colloqui telefonici e a distanza via Skype, colloqui face to face, dà informazioni\
  \  e un primo orientamento legale. I servizi sono volti alla costruzione di un progetto\
  \ di consulenza psico-sociale per la fuoriuscita dalla violenza e la progettazione\
  \ di obiettivi di autorealizzazione, a partire da un'attenta ricognizione delle\
  \ risorse individuali e contestuali disponibili e reperibili. Lavora per la costruzione\
  \ di reti territoriali di sostegno e per la messa in protezione, attraverso l'attivazione\
  \ di procedure per ospitalità in emergenza, l'interlocuzione con Forse dell'Ordine\
  \ e servizi istituzionali. Il colloquio con l’operatrice è un luogo di confronto\
  \ dove ogni donna ha la possibilità di svolgere un esame realistico delle possibilità\
  \ concrete di realizzazione dei propri obiettivi e di protezione dalla violenza.\
  \ Offre informazioni e sostegno a chi segnala situazioni di donne che subiscono\
  \ violenza e orientamento  relativamente ai bambini e le bambine che hanno subito\
  \ violenze e abusi, o che hanno assistito a violenze contro la propria madre.\n\n\
  Il Centro si trova a Maccarese e lavora in partenariato con il Comune di Fiumicino.\
  \ I servizi vengono erogati indipendentemente dal luogo di residenza delle donne\
  \ che ne fanno richiesta. \n\nContatti:\nCell. 3661245342 H24 \n06.652108402\n@:\
  \ cav.idea.fiumicino@gmail.com\n\nOrari: \nlunedì-mercoledì-venerdì 9:30-17:00\n\
  martedì-giovedi 9:00-17:00\n\nIndirizzo: \nVia del Buttero 3 \nCasa della Partecipazione\
  \ \nMaccarese"
Destinatari: Donne italiane e straniere in situazioni di violenze e abusi
Link: http://www.befreecooperativa.org/
Natura: solidale
Posizione: 41.877373 12.214944 0 0
Tipo_di_soggetto: privato
Titolo: Centro Antiviolenza I-Dea
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente (@eleninz3 motivare sempre perché non accettato e poi chiudere segnalazione).
