### ISSUE TITLE
Coronavirus - Farmaci a domicilio grazie ad accordo tra Croce Rossa Italiana e FederFarma
06 Aprile 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2314]
<pre><yamldata>
Da_chi_offerta: Croce Rossa Italiana e FederFarma
Descrizione: "Coronavirus - Farmaci a domicilio grazie ad accordo tra Croce Rossa\
  \ Italiana e FederFarma\n06 Aprile 2020.\n\nAl fine di rispettare le misure di contenimento\
  \ del contagio da COVID-19, adottate con i vari Decreti del Presidente del Consiglio\
  \ dei Ministri, la Croce Rossa Italiana e FederFarma hanno stipulato un accordo\
  \ per la consegna di farmaci a domicilio per tutte quelle persone alle quali è sconsigliato\
  \ spostarsi al di fuori del proprio domicilio o che sono impossibilitate a recarsi\
  \ presso una farmacia, e che\n\n – attraverso il #numeroverde 800.065510 – \n\n\
  potranno richiedere la consegna dei farmaci a casa per il mantenimento dei parametri\
  \ essenziali di continuità e aderenza alla terapia.\n\nPossono accedere al servizio\
  \ le persone con oltre 65 anni, i soggetti con sintomatologia da infezione respiratoria,\
  \ e febbre (>37,5°),persone non autosufficienti o sottoposti alla misura della quarantena\
  \ o, in ogni caso, risultati positivi al virus COVID-19.\n\nIl servizio può essere\
  \ richiesto esclusivamente al numero verde 800.065510 – attivo H24, 7 giorni su\
  \ 7 – per i soggetti sopra precisati, già in possesso di prescrizione medica.\n\n\
  All’ atto dell'istanza, il richiedente dovrà indicare l'indirizzo di ritiro della\
  \ ricetta e della consegna dei farmaci.\nIl personale della Croce Rossa - in uniforme\
  \ della C.R.I. – provvederà al ritiro della ricetta o del promemoria presso l'indirizzo\
  \ e si recherà presso la farmacia più vicina al domicilio dell'utente, salvo diversa\
  \ indicazione dell'utente stesso.\nOve trattasi di ricette o promemoria consegnati\
  \ da persone non autosufficienti o sottoposti a quarantena o positivi al virus COVID-19,\
  \ il personale CRI provvederà ad avvisare il personale della farmacia.\n\nUna volta\
  \ acquistati i farmaci (il cui prezzo, dove previsto, è anticipato al farmacista\
  \ da parte di CRI) gli stessi verranno consegnati in busta chiusa all'utente che\
  \ provvederà a rimborsare il personale CRI.\n\nCRI è responsabile del corretto trasporto\
  \ dei farmaci dalla farmacia all'utente che li ha richiesti e della protezione dei\
  \ suoi dati personali in ottemperanza alla legislazione vigente.\nNULLA E’ DOVUTO\
  \ DAGLI UTENTI per lo svolgimento del servizio oltre a quanto necessario per l'acquisto\
  \ dei farmaci. L'utente può richiedere al personale CRI l'emissione dello scontrino\
  \ fiscale “parlante” da utilizzare per le detrazioni fiscali, fornendo la tessera\
  \ sanitaria o il codice fiscale.\n\nL’accordo resterà valido fino a quando saranno\
  \ in vigore le disposizioni che limitano lo spostamento delle persone."
Destinatari: persone con oltre 65 anni, i soggetti con sintomatologia da infezione
  respiratoria, e febbre (>37,5°), persone non autosufficienti o sottoposti alla misura
  della quarantena o, in ogni caso, risultati positivi al virus COVID-19.
Link: https://protezionecivile.comune.palermo.it/protezione-civile-dettaglio.php?id=27106&s=2
Natura: solidale
Posizione: 38.1156 13.361413 0 0
Tipo_di_soggetto: pubblico
Titolo: 'Coronavirus-consegna #farmaci a domicilio a #Palermo- accordo Croce Rossa
  e Federfarma'
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente #1025.
