### ISSUE TITLE
Galbusera S.p.A. effettua donazioni di colombe pasquali

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2316]
<pre><yamldata>
Da_chi_offerta: GALBUSERA spa
Descrizione: "Galbusera S.p.A. ha manifestato disponibilità a  effettuare donazioni\
  \ di colombe pasquali. \nContattare la sig.ra Giulia Avicoli al seguente numero\
  \ di telefono: 351.7483365 o giulia.avicolli@galbusera.it. \n\nPer questioni organizzative\
  \  necessitano di ricevere le seguenti informazioni:\na)\tstima delle quantità \n\
  b)\tpunto di consegna di prodotti omaggio, ovvero disponibilità al ritiro. \n\n\n\
  Per contatti:\nGiulia Avicoli\nGALBUSERA SpA \nVia Marconi, 20  20864 Agrate Brianza\
  \ MB \ncel.351.7483365\ntel:  039/63741"
Destinatari: associazioni, onlus, ong
Natura: solidale
Posizione: 45.57572 -350.658703 0 0
Tipo_di_soggetto: privato
Titolo: donazione colombe pasquali
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Chiusa su richiesta della persona che ha fatto segnalazione tramite issue #2379
