### ISSUE TITLE
Diretta Facebook 12/03/20 - "La società civile nella società del rischio" 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#232]
<pre><yamldata>
Da_chi_offerta: Vita non profit
Descrizione: "Diretta Facebook oggi gioved\xEC 12 marzo dalle 14,30 alle 16 sulla\
  \ pagina di Vita. Vita inizia un percorso di riflessione su ci\xF2 che in questi\
  \ giorni sta emergendo con forza: la necessit\xE0 e il valore di una societ\xE0\
  \ civile sempre pi\xF9 organizzata e coesa."
Destinatari: Chiunque sia interessato
Link: https://www.facebook.com/events/238262550549880/
Natura: culturale-ricr
Titolo: "La societ\xE0 civile nella societ\xE0 del rischio"

</yamldata></pre>

**Comment by cristigalas** [comment]
Scaduta. Chiudo.
