### ISSUE TITLE
Struttura dell'Asp a #Palermo accoglie ragazzi con autismo 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2321]
<pre><yamldata>
Cosa: '#Autismo-Attivo il Centro diurno per i #bambini di #Palermo'
Descrizione: 'Sinergia tra Comune di Palermo, l''Asp e il Centro diurno per l''Autismo
  che ha portato a stipulare la convenzione: grazie a questa collaborazione viene
  data la possibilità a bambini e ragazzi con autismo di usufruire di una struttura,
  in via Don Orione 18/a, con adeguati servizi di riabilitazione e di cura.
  Il Centro Diurno per l’Autismo è quindi la prima struttura di assistenza convenzionata
  con il Servizio sanitario nazionale (la ASP 6) per l’assistenza a soggetti autistici.
  Una struttura che nasce e opera in un bene confiscato alla mafia, di proprietà del
  Comune di Palermo, e trasformato dall''A.G.S.A.S. Onlus (Associazione Genitori Soggetti
  Autistici Solidali) in una struttura per la riabilitazione delle persone con autismo.
  Sedici bambini con autismo di età compresa tra i 6 e i 16 anni, su una capacità
  ricettiva di venti soggetti, ricevono una prestazione riabilitativa presso il Centro
  Diurno in relazione con i contesti di vita: domicilio, territorio e scuola, secondo
  T.E.I.P.A. (trattamento educativo integrato per le Persone con Autismo) con ciclo
  terapeutico semestrale rinnovabile.
  Il tutto sovra coordinato dal dipartimento di Salute Mentale in sinergia con l’Unità
  Operativa di Neuropsichiatria per l''Infanzia e l''Adolescenza territoriale e dall’ambulatorio
  Autismo ASP 6 di Palermo.
  Il centro vanta un''organizzazione di professionisti specializzati ABA e tecniche
  riabilitative validate a livello mondiale nel trattamento educativo rivolto alle
  persone con autismo, configurandosi come "Polo di eccellenza" per il trattamento
  dell''autismo.
  Un''unione di intenti tra pubblico e privato con l’obiettivo di garantire un’alta
  qualità delle prestazioni erogate per la persona con Autismo e i suoi familiari
  e per fornire un servizio di assistenza il più completo possibile.
  Sede:
  Via Don Orione, 18, 90142 Palermo PA
  Telefono: +39 091.226331
  Email: info@autismoperche.it
  Sito Web: www.autismoperche.it'
Link: https://www.balarm.it/news/magazine/autismo-un-centro-diurno-per-i-bambini-di-palermo-17801
Posizione: 38.143269 13.362105 0 0
</yamldata></pre>

**Comment by cristigalas** [comment]
@marcocovid83 qui label giusta era Donazioni beni e offerte servizi. Ma a parte questo, io avrei aspettato ad accettare e inviare a Bollettino perché qui si dice che si accolgono ragazzi autistici in un centro diurno quando questi dovrebbero essere chiusi per le misure anticontagio. È necessario prendere informazioni, prima accettare. Intanto ho eliminato tweet e post Telegram e tolto label accettato. @chiccap tu che ne pensi?

**Comment by Polva13** [comment]
ops...mi dispiace, non avevo notato, cercherò di starci più attento.
