### ISSUE TITLE
Raccolta fondi per l'acquisto di 3 pulsossimetri pediatrici per strutture Usca #Osimo #Ancona

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2329]
<pre><yamldata>
Causale: DONAZIONE per l'acquisto di 3 pulsossimetri pediatrici
Descrizione: "OBIETTIVO: QUOTA 205 EURO!\n Raccolgo l'invito del mio ex pediatra dott.\
  \ Cicione di trovare i fondi necessari per l'acquisto di 3 pulsossimetri pediatrici\
  \ per 3 USCA (Unità Speciali di Continuità Assistenziali) attive per i comuni di\
  \ Osimo, Castelfidardo, Camerano, Loreto, Sirolo e Numana.\nSono strumenti indispensabili\
  \ per valutare la saturazione nei bambini e  in caso di infezione da Covid-19 per\
  \ il team di medici e pediatri impegnati nel territorio"
Email: silena.sernani@gmail.com
IBAN: IT37L0200837497000040470506
Intestazione: Silena Sernani
Link: https://www.gofundme.com/f/raccolta-di-3-pulsossimetri-pediatrici-usca
Nome: Silena Sernani
Posizione: 43.48521 13.48754
</yamldata></pre>

> @chiccap @cristigalas ho qualche dubbio, sto approndendo ma volevo verificare meglio inizaitiva, che ne pensate?

Possiamo inviare una email e chiedere ulteriori info, anche se abbiamo approvato già raccolte simili.

**Comment by marcocovid83** [comment]
@chiccap @cristigalas ho qualche dubbio, sto approndendo ma volevo verificare meglio inizaitiva, che ne pensate?

**Comment by Fatima-web** [comment]
conosco chi ha fatto la segnalazione, posso informarmi. quali sono i dubbi da sottoporre?

**Comment by Fatima-web** [comment]
Allora la segnalazione è da parte di una cittadina di Osimo, tal Silena Sernani, che ha avviato la raccolta fondi privatamente per conto della USCA territoriale (è una struttura che fa capo all'Asur) del comuni di Osimo, Castelfidardo e quelli citati nella segnalazione. Vanno quindi a sostegno del Pubblico quindi per me si può approvare. Se vi interessano maggiori info fatemi sapere.

**Comment by Fatima-web** [comment]
@chiccap accettato e messo in Bollettino

**Comment by cristigalas** [comment]
> Allora la segnalazione è da parte di una cittadina di Osimo, tal Silena Sernani, che ha avviato la raccolta fondi privatamente per conto della USCA territoriale (è una struttura che fa capo all'Asur) del comuni di Osimo, Castelfidardo e quelli citati nella segnalazione. Vanno quindi a sostegno del Pubblico quindi per me si può approvare. Se vi interessano maggiori info fatemi sapere.

Ma questa privata cittadina è in contatto con la struttura? Il problema di queste raccolte fondi è sapere se sono approvate dagli enti beneficiari...

**Comment by Fatima-web** [comment]
Si, mi é stato detto che lo sta facendo per conto di questa struttura

Il mar 7 apr 2020, 18:49 Cristina Galasso <notifications@github.com> ha
scritto:

**Comment by luciaroma** [comment]
ho visto che hanno raggiunto la quota richiesta e anzi l'hanno superata di poco :-), con un impennata di donazioni nella giornata di oggi. Sarà anche merito nostro?! Chissà. Comunque, possiamo chiuderla che dite?

**Comment by cristigalas** [comment]
@luciaroma @Fatima-web aspettiamo a chiudere, l’abbiamo pubblicata oggi e il link alla segnalazione potrebbe ancora girare... Semmai monitoriamola per un paio di giorni, può darsi che la estendano per acquistare altre attrezzature...

**Comment by Fatima-web** [comment]
@cristigalas @luciaroma Buonasera, mi sono informata ed hanno effettivamente esteso la raccolta per ulteriori materiale ed attrezzature da acquistare. Hanno integrato la loro descrizione sul sito e indicheranno a giorni le prossime destinazione dei fondi. Si può lasciare la segnalazione aperta o consiglio loro di farne una nuova?

**Comment by cristigalas** [comment]
@Fatima-web ottimo, grazie Fatima! Lascerei questa segnalazione e la integrerei con le nuove attrezzature che intendono comprare. Una volta integrato il testo della descrizione modifica anche il titolo.

**Comment by Fatima-web** [comment]
Ok, li sto infatti monitorando così da assicurare informazioni corrette ed
aggiornate :)

Il mer 8 apr 2020, 19:36 Cristina Galasso <notifications@github.com> ha
scritto:

**Comment by michelerestuccia** [comment]
La raccolta fondi si è conclusa.
