### ISSUE TITLE
Comune di #Jesi #Ancona cerca computer preferibilmente portatili per didattica online

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2332]
<pre><yamldata>
Cosa: raccolta computer portatili
Descrizione: 'Il Comune di Jesi ha attivato una raccolta di computer, preferibilmente portatili (massimo 7/8 anni di vita), funzionanti e con web-camera (con almeno windows 7, se possibile 64 bit) da mettere a disposizione degli alunni che ne sono sprovvisti per la teledidattica.
  Per segnalare disponibilità:
  3285897535
  mauro.mariani2018@gmail.com'
Destinatari: alunni che ne sono sprovvisti per la teledidattica
Email: mauro.mariani2018@gmail.com
Link: https://t.me/ComuneJesi/628
Indirizzo: 43.522505 13.243624 0 0
Nome: Comune di Jesi
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
@luciaroma @cristigalas @chiccap forse possiamo contattare questa persona per avere più informazioni su questa iniziativa

**Comment by cristigalas** [comment]
> @luciaroma @cristigalas @chiccap forse possiamo contattare questa persona per avere più informazioni su questa iniziativa

Eh sì, così non possiamo accettarla. Possiamo anche provare a fare una ricerca sul web perché nel ‘nome’ ha indicato Comune di Jesi... altrimenti inviamo email per chiarimenti e maggiori info.

**Comment by luciaroma** [comment]
l'ho inserita io direttamente ... è arrivata tramite canale telegram del comune ma in effetti non ho trovato poi on line (ne sul sito ne su fb) la notizia. Però il canale è attendibile, dico il telegram, ed era insieme ad altre comunicazioni covid del comune.
Magari a breve pubblicano qualcosa anche su sito e social, poi aggiorno.

**Comment by cristigalas** [comment]
> l'ho inserita io direttamente ... è arrivata tramite canale telegram del comune ma in effetti non ho trovato poi on line (ne sul sito ne su fb) la notizia. Però il canale è attendibile, dico il telegram, ed era insieme ad altre comunicazioni covid del comune.
> Magari a breve pubblicano qualcosa anche su sito e social, poi aggiorno.
> 
> Andrebbero comunque contattati per sapere di quanti dispositivi hanno bisogno

Ah sì, ho visto anch’io adesso la [comunicazione](https://t.me/ComuneJesi/628) sul loro canale Telegram, che è appunto canale ufficiale quindi possiamo senz’altro accettare aggiungendo il link al post Telegram. Poi direi di inviare comunque una email per avere maggiori info e stabilire comunque un contatto. @luciaroma ci pensi tu?

**Comment by luciaroma** [comment]
sì ci penso io

**Comment by luciaroma** [comment]
mandata mail, attendo aggiornamenti

**Comment by luciaroma** [comment]
il tipo mi ha chiamata la volo. Il fabbisogno è di circa 100 pc, preferibilmente con webcam (per le lezioni), anche usati vanno bene ma non più vecchi di 7/8anni.
Che dite, lanciamo una richiesta ampia?

**Comment by chiccap** [comment]
> il tipo mi ha chiamata al volo. Il fabbisogno è di circa 100 pc, preferibilmente con webcam (per le lezioni), anche usati vanno bene ma non più vecchi di 7/8anni.

Sì assolutamente. Farei subito una card per i social + tweet bombing che ne dite?

**Comment by chiccap** [comment]
![7](https://user-images.githubusercontent.com/21237278/78701714-c7ada780-7907-11ea-98fc-2873c7395b5f.png)
 Tipo così, se per voi ok condivido con media team e partiamo!

**Comment by luciaroma** [comment]
per me perfetto! possiamo partire

**Comment by luciaroma** [comment]
ps: io avevo inserito la posizione dal form, ma vedo che è arrivata con label "posizione mancante", credo capiti spesso.

**Comment by cristigalas** [comment]
@chiccap modificherei il testo per evitare ripetizione Aiutaci e aiutare. Tipo così: _Anche grazie al tuo aiuto il Comune di Jesi potrà garantire la didattica online alle alunne e agli alunni senza computer._

**Comment by luciaroma** [comment]
MIA PROPOSTA: Aiuta con noi il Comune di Jesi a garantire la didattica online agli alunni e alle alunne del Comune di Jesi: servono computer portatili

Poi lancerei oggi, per battere il ferro finchè è caldo e poter essere incisivi :-).
Una volta che la lanciamo, scrivo al Sindaco e glielo dico e inizio a fare push per far inserire il form sul sito e sui canali ufficiali! ;-) Daje

**Comment by cristigalas** [comment]
> MIA PROPOSTA: Aiuta con noi il Comune di Jesi a garantire la didattica online agli alunni e alle alunne della città: servono computer portatili
> 
> Poi lancerei oggi, per battere il ferro finchè è caldo e poter essere incisivi :-).
> Una volta che la lanciamo, scrivo al Sindaco e glielo dico e inizio a fare push per far inserire il form sul sito e sui canali ufficiali! ;-) Daje

Per me va bene! Ditemi quando è pronta la card che parto su Twitter.

**Comment by luciaroma** [comment]
oltre @chiccap ci sono altri/e che si possono occupare della card?

**Comment by cristigalas** [comment]
> oltre @chiccap ci sono altri/e che si possono occupare della card?

Se è con Canva posso fare io, vado a vedere...

**Comment by chiccap** [comment]
> > oltre @chiccap ci sono altri/e che si possono occupare della card?
> 
> Se è con Canva posso fare io, vado a vedere...

Tranquille ragazze vado io con la modifica proposta da Cristina e giro al gruppo media :)

**Comment by cristigalas** [comment]
> > > oltre @chiccap ci sono altri/e che si possono occupare della card?
> > 
> > 
> > Se è con Canva posso fare io, vado a vedere...
> 
> Tranquille ragazze vado io con la modifica proposta da Cristina e giro al gruppo media :)

Ok!

**Comment by luciaroma** [comment]
ActionAid ha mappato e indirizzato una serie di richieste di dispositivi mobili per la didattica a distanza ad Amazon, con cui si è raggiunto un accordo per la fornitura, a copertura dei fabbisogni. 
Jesi è rientrato nella fornitura Amazon.

**Comment by cristigalas** [comment]
@luciaroma @chiccap @favoeva questa è un’altra good news che dobbiamo scrivere sul sito! Intanto facciamo un post sui social?

**Comment by luciaroma** [comment]
sì decisamente good news, per i social aspettiamo un attimo. Se lo facciamo forse non possiamo citare Amazon o almeno non ora perché, avendo fatto una donazione importante per varie altre scuole di progetti ActionAid in Italia, usciremo anche coi social AA con una comunicazione unica sulla collaborazione. Possiamo però di certo e assolutamente coordinarci. 
@chiccap @Saraveg confermate?

**Comment by davidedistaso** [comment]
@luciaroma durante The Global Hack abbiamo creato www.ognistudenteonline.org per raccogliere tutte le richieste di dispositivi e le offerte. Il portale offre un sistema automatico per mettere in contatto donatori e riceventi, ma abbiamo bisogno di auto per spargere la voce e per verificare la legittimità delle richieste. Fatemi sapere se siete interessati a collaborare!
