### ISSUE TITLE
Un Vademecum per le persone senza fissa dimora per orientarsi tra decreti e multe, a cura di Avvocati di strada

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2343]
<pre><yamldata>
Da_chi_offerta: Avvocato di strada
Descrizione: In questo periodo di emergenza le persone senza dimora si trovano in
  ancor maggiore difficoltà dal momento che una casa in cui poter stare non ce l'hanno.
  Avvocato di strada sta continuando a lavorare per cercare di diffondere il più possibile
  (tramite canali web e social, ma soprattutto grazie alla collaborazione con i servizi
  del territorio) le informazioni circa le norme da rispettare, i comportamenti da
  tenere e riguardo ai servizi attivi in questo momento, cercando così di favorire
  l'inserimento di più persone possibili all'interno delle strutture preposte. Continuiamo
  inoltre a fornire assistenza ai nostri utenti via mail o telefono e ci stiamo preparando
  ad affrontare dal punto di vista giuridico le multe e sanzioni che purtroppo diverse
  persone senza dimora stanno ricevendo in varie città d'Italia per il solo fatto
  di trovarsi inevitabilmente per strada, violando così le norme attualmente in vigore.
Destinatari: Persone senza dimora
Link: https://www.avvocatodistrada.it/covid19-multe-e-denunce-un-vademecum-per-le-persone-senza-dimora/
Natura: solidale
Posizione: 44.497745 11.34377 0 0
Tipo_di_soggetto: privato
Titolo: Assistenza alle persone senza dimora
</yamldata></pre>

**Comment by marticorti** [comment]
@FrancescaZambi89 non è la stessa segnalazione #2268  ?

**Comment by cristigalas** [comment]
@FrancescaZambi89 c’è già!
