### ISSUE TITLE
I Brico di Milano offrono servizio di consegna a domicilio a 9,90 euro; alcuni dei negozi Brico offr

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2349]
<pre><yamldata>
Descrizione: I Brico di Milano offrono servizio di consegna a domicilio a 9,90 euro;
  alcuni dei negozi Brico offrono anche il servizio di prenotazione e ritiro in 4
  ore dall'ordine
Link: https://www.bricocenter.it/
Nome_dell_esercizio_commercial: Bricocenter
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 45.46679408 9.1903474 (Milano) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=45.46679408+9.1903474&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by marticorti** [comment]
@chiccap @cristigalas nella segnalazione si parla dei Brico di Milano, ma dal sito si legge che l'iniziativa è attiva in tutta Italia (ttps://www.bricocenter.it/yep-content/media/CHIAMA-E-CONSEGNIAMO_GENERICO-CON-ELENCO-NEGOZI_A4_(4).pdf). Che posizione inserire? Inoltre, accettiamo questo tipo di segnalazioni anche se il servizio offerto è a pagamento?

**Comment by cristigalas** [comment]
@marticorti @chiccap non accetterei.

**Comment by claudiamazzantiact** [comment]
Anche secondo me è un servizio da non pubblicizzare

**Comment by claudiamazzantiact** [comment]
@cristigalas chiudo?

**Comment by cristigalas** [comment]
> @cristigalas chiudo?

Sì, togli label Da sistemare e Posizione da verificare, metti Non accettato e chiudi issue.
