### ISSUE TITLE
servizio aggiuntivo gratuito per privati e professionisti che consente l’acquisto con una semplice t

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2350]
<pre><yamldata>
Descrizione: 'servizio aggiuntivo gratuito per privati e professionisti che consente
  l’acquisto con una semplice telefonata, in modo da poter continuare a effettuare
  l''ordine, proprio come nel solito negozio.

  CONSEGNA A DOMICILIO IN 72 ORE dal pagamento.

  dal lunedì al sabato dalle 8:00 alle 17:00'
Link: https://www.leroymerlin.it/vendita-telefonica-assistita
Nome_dell_esercizio_commercial: Leroy Merlin
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
idem come segnalazione #2349

**Comment by claudiamazzantiact** [comment]
Procedo con la chiusura della segnalazione perchè è identica a quella citata sopra appena chiusa.
