### ISSUE TITLE
Piattaforma online del municipio Roma VIII per ricevere sostengo per il reperimento dei beni di prim

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2355]
<pre><yamldata>
Cosa: Beni e servizi di prima necessità
Descrizione: Piattaforma online del municipio Roma VIII per ricevere sostengo per
  il reperimento dei beni di prima necessità come alimenti e farmaci. E' possibile
  inoltre trovare informazioni sui servizi di sostegno psicologico per tutte e tutti
  e orientamento per donne in situazioni di violenza e persone LGBTQ
Destinatari: Popolazione del Municipio VIII di Roma
Email: municipiosolidale@gmail.com
Immagine: municipio solidale-10_4_34.jpg
Link: https://www.municipio-solidale.it/
Telefono: '0640060606'
</yamldata></pre>

**Comment by FrancescaZambi89** [comment]
già inserita con #issue414
non accettata e chiusa
