### ISSUE TITLE
Associazione 180Amici #LAquila, attiva nella salute mentale, cerca smartphone e tablet per offrire servizi a distanza ai propri utenti

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2357]
<pre><yamldata>
Cosa: Si cercano smartphone o tablet
Descrizione: Siamo una associazione che opera in salute mentale e finché non sarà possibile riattivarle in tutta sicurezza, le nostre attività sono sospese. Lo sono da quasi un mese ormai e stiamo cercando delle nuove modalità (telematiche, ovviamente) per riprendere. Molte delle persone che intendiamo raggiungere però non dispongono al momento dei mezzi necessari per una videochiamata o videoconferenza. Stiamo cercando SMARTPHONE e TABLET, almeno 10, da consegnare alle persone che abbiano bisogno di mettersi in contatto con noi per permettere loro di partecipare a distanza alle varie iniziative che stiamo predisponendo. Abbiamo fatto appello alle grandi aziende, senza per il momento ricevere risposta. CI APPELLIAMO QUINDI ALLA SOLIDARIETÀ DEI PRIVATI. Se qualcuno avesse uno smartphone o tablet da donare, ci contatti telefonicamente al numero 3274181827 o sulla pagina Facebook dell'associazione. Se volesse, invece, sostenere le nostre attività con una donazione, IBAN IT67S0538703601000000165363, causale Donazione emergenza covid19. Sostegno a persone in difficoltà.
Destinatari: tutti
Link: https://www.facebook.com/photo?fbid=3900835359934054&set=a.1250253941658889
Nome: Associazione 180Amici - L'Aquila
Telefono: '3274181827'
Posizione: 42.352385 13.382618 0 0
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Ho messo label contatti perchè c'è anche segnalazione iban per donazione (label raccolta fondi ci eravamo detti solo da utilizzare per questo tipo di issue).

@cristigalas @chiccap  la rilanciamo con forza?

**Comment by claudiamazzantiact** [comment]
@Saraveg possiamo sapere se c'è un numero o una stima di quanti smartphone e tablet hanno bisogno?

**Comment by Saraveg** [comment]
Li chiamo subito

**Comment by cristigalas** [comment]
> Ho messo label contatti perchè c'è anche segnalazione iban per donazione (label raccolta fondi ci eravamo detti solo da utilizzare per questo tipo di issue).
> 
> @cristigalas @chiccap @Saraveg la rilanciamo con forza?

No, label Contatti non ci va messa. Semmai andrebbe fatta nuova segnalazione per la raccolta fondi e tolto da qui il testo che parla della raccolta fondi. Altrimenti modifichiamo il titolo aggiungendo anche la raccolta fondi e aggiungiamo label Raccolta Fondi.

**Comment by Saraveg** [comment]
@avivace che è successo?

**Comment by cristigalas** [comment]
> @avivace che è successo?

Ci sto lavorando, ci sono due punti e apostrofi che non li piacciono :(

**Comment by cristigalas** [comment]
@avivace aiuto! Le ho provate tutte e non funziona!

**Comment by mfortini** [comment]
@cristigalas te lo stava dicendo :) in fondo c'era "/yamldata>" e invece si aspettava "</yamldata>", l'ho sistemato

**Comment by cristigalas** [comment]
@mfortini grazieeee 😘

**Comment by chiccap** [comment]
![Copia di Post IG (6)](https://user-images.githubusercontent.com/21237278/79467800-7afc5780-7ffe-11ea-831d-d799219a07c9.png)

**Comment by chiccap** [comment]
Come si può vedere da qui: https://www.instagram.com/p/CAnAOFUKrAc/?igshid=xc92vplkowjc
L'associazione Il coraggio di un sorriso ha donato i tablet a 180amici.
