### ISSUE TITLE
#Bergamo Aiuta: nasce la piattaforma dove trovare numeri e informazioni utili relativi all'emergenza Covid-19 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2361]
<pre><yamldata>
Da_chi_offerta: Comune di Bergamo
Descrizione: 'Il Comune di Bergamo in questi giorni difficili si impegna a non lasciare
  soli i suoi cittadini.

  Tu resta a casa, noi ti garantiamo i servizi necessari: su questa piattaforma troverai
  tutti i numeri e le informazioni utili che ti servono'
Destinatari: cittadini/e di Bergamo 
Link: http://bergamoaiuta.it/
Titolo: Bergamo Aiuta - Emergenza Coronavirus, informazioni e servizi
comune_manuale: Bergamo
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 45.69441368 9.66842453 (Bergamo) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=45.69441368+9.66842453&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by cristigalas** [comment]
@marticorti c’era già https://www.covid19italia.help/issues/1973/
Controllare sempre per questo tipo di segnalazioni.
