### ISSUE TITLE
Raccolta fondi per supportare bambini e ragazzi dei Villaggi SOS in Italia durante l'emergenza #Trento #Vicenza #Saronno #Ostuni #Mantova #Roma #Torino #Calabria

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2378]
<pre><yamldata>
Da_chi_offerta: SOS Villaggi dei Bambini Italia
Descrizione: "Milano, 9 aprile 2020 - L'emergenza Coronavirus si è abbattuta come\
  \ un fulmine a ciel sereno sui circa 500 bambini e ragazzi ospiti nei Villaggi SOS\
  \ a Trento, Vicenza, Saronno, Ostuni, Mantova, Roma e nei due Programmi SOS a Torino\
  \ e in Calabria, così come sui 230 operatori che si prendono cura di loro ogni giorno.\
  \ Con l'attenzione dovuta in modo specifico ai bambini e ai ragazzi, si continua\
  \ a tutelare l'atmosfera familiare che circonda gli ospiti dei Villaggi e Programmi\
  \ SOS. Gli educatori e gli operatori sono impegnati costantemente nel sensibilizzarli\
  \ e istruirli sulle regole da mettere in pratica a tutela della salute propria e\
  \ degli altri membri della comunità. Una particolare attenzione è riservata agli\
  \ aspetti psicologici dell'emergenza: i bambini e i ragazzi sono resi consapevoli\
  \ e informati nelle modalità adatte alla loro età, sempre comunque confortati e\
  \ rassicurati; stanno peraltro proseguendo via Skype e telefono i colloqui individuali\
  \ con lo psicoterapeuta.\n\nI provvedimenti stabiliti dai Dpcm che si sono succeduti\
  \ in queste settimane (l'ultimo è quello del 1° aprile), hanno comportato, dentro\
  \ ai Villaggi SOS, il ricorso a misure di sicurezza particolari. E così gli incontri\
  \ tra i minorenni e i famigliari, su indicazione delle Istituzioni e su autorizzazione\
  \ dei Servizi Sociali, sono stati sospesi e vengono gestiti via Skype o telefono,\
  \ con una attenzione da parte degli educatori a interfacciarsi e aggiornare sia\
  \ i servizi sociali che i familiari; sono state sospese le attività esterne di carattere\
  \ sportivo, laboratoriale, ludico-ricreative e aggregative; ciascun ambiente è stato\
  \ dotato di soluzione igienizzante; lo studio quotidiano è gestito a distanza con\
  \ il supporto degli operatori presenti nelle case, accanto ai ragazzi.\n\nSi tratta\
  \ di misure necessarie e drastiche, che hanno messo l'Organizzazione dinanzi a nuovi\
  \ bisogni e costi aggiuntivi da sostenere. Basti pensare al presidio eccezionale\
  \ rispetto alla normale turnazione del personale coinvolto nella cura dei bambini\
  \ e dei ragazzi, e quindi al relativo costo delle ore di lavoro extra degli educatori\
  \ e degli operatori. Ma c'è bisogno anche di garantire il rifornimento di materiale\
  \ sanitario, come gel mani e prodotti per disinfettare. Così come servono PC e device\
  \ per garantire a tutti la possibilità di seguire le lezioni a distanza e materiale\
  \ utile per fare dei laboratori e realizzare le attività ludico-creative.\n\nAll'appello\
  \ di SOS Villaggi dei Bambini ha risposto, tra gli altri, Fondazione Snam, con una\
  \ donazione destinata a sostenere i costi del lavoro straordinario degli operatori\
  \ e le spese per l'acquisto di materiale igienico-sanitario, come gel disinfettante\
  \ e mascherine - sia di tipo ffp2 che monouso - per tutti i Villaggi SOS e per il\
  \ Programma SOS di Torino. Una donazione che fa la differenza, in un momento così\
  \ delicato per la salute sia fisica che psicologica dei più piccoli. \"La situazione\
  \ è complessa per tutti. L'emergenza ci costringe a richiuderci nelle singole case\
  \ e a evitare ogni possibile contatto con gli altri residenti della nostra comunità.\
  \ - spiega Marta Trecco, Direttrice del Villaggio SOS di Vicenza - È stato difficilissimo\
  \ per me spiegarlo ai bambini. Ho dedicato alcune ore in ogni casa per spiegare\
  \ la situazione ai più piccoli e ai più grandi. Ho trovato una comprensione commovente,\
  \ sono stati bravissimi.”  \n\nLa donazione di Fondazione Snam arriverà presto a\
  \ questi bambini, così come agli ospiti degli altri Villaggi e Programmi SOS in\
  \ tutta Italia. Un gesto di grande valore, che dà a SOS Villaggi dei Bambini la\
  \ speranza per dire: andrà tutto bene."
Destinatari: SOS Villaggi dei Bambini
Link: https://www.facebook.com/donate/2526008721048054/
Natura: solidale
Tipo_di_soggetto: privato
Titolo: Fondazione Snam aiuta a proteggere i 500 bambini dei Villaggi Sos
</yamldata></pre>

**Comment by chiccap** [comment]
La raccolta fondi è conclusa.
