### ISSUE TITLE
Ciao, non ho trovato altro modo di comunicare con voi se non cosi che cosi.
Ho fatto io la segnalazi

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2379]
<pre><yamldata>
Da_chi_offerta: GALBUSERA
Descrizione: "Ciao, non ho trovato altro modo di comunicare con voi se non cosi che\
  \ cosi.\nHo fatto io la segnalazione delle colombe gratuite Galbusera. \nOra Galbusera\
  \ mi scrive che ha ricevuto una montagna di richieste, quindi bene; e hanno esaurito\
  \ le colombe. Saranno  consegnate anche  nelle prossime settimane ma non possono\
  \ prendere altre richieste.  Pertanto Galbusera  chiede che la segnalazione su questo\
  \ sito venga eliminata. Grazie.\nAndrea Carnovali AA ITA"
Destinatari: TUTTI
Natura: solidale
Tipo_di_soggetto: privato
Titolo: COLOMBE
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Segnalazione #2316 chiusa e chiudo anche questa
