### ISSUE TITLE
Bando European Youth Foundation (EYF) per finanziare organizzazioni giovanili locali e nazionali che sviluppano progetti di solidarietà in risposta all'emergenza Covid19 (in inglese)

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2380]
<pre><yamldata>
Da_chi_offerta: European Youth Foundation (EYF)
Descrizione: 'The European Youth Foundation (EYF) is launching a special call for
  local or national youth organisations that are looking for funding for activities
  which respond to local needs arising from the COVID-19 crisis.
  You can apply for the EYF pilot activity grants. Priority will be given to pilot
  activities that aim at demonstrating solidarity and support to all persons affected
  by the COVID-19 crisis, such as:
  - Reaching out to and supporting particularly vulnerable groups of people, including
  homeless, refugees and asylum-seekers, people with disabilities, people living in
  isolation or in remote communities;
  - Support to health, social and educational services;
  - Education and awareness-raising of the importance of human rights in responses
  to COVID-19 crisis.'
Destinatari: Local or national youth organisations that are looking for funding for
  activities which respond to local needs arising from the COVID-19 crisis
Link: https://www.coe.int/en/web/european-youth-foundation/home/-/asset_publisher/1HFcQgqhfuet/content/special-call-for-grant-applications-for-pilot-activities-responding-to-local-needs-arising-from-the-covid-19-c
Natura: sostegno-lavor
Titolo: Special call for grant applications for pilot activities responding to local
  needs arising from the COVID-19
regione_manuale: tutte
</yamldata></pre>

**Comment by cristigalas** [comment]
Scaduto.
