### ISSUE TITLE
in un gruppo molto serio di lavoratori del web è stato segnalato questo, non ho trovato riscontri e 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2383]
<pre><yamldata>
Cosa: virus whatsapp
Descrizione: 'in un gruppo molto serio di lavoratori del web è stato segnalato questo,
  non ho trovato riscontri e ho chiesto gli screenshot, ma se nel frattempo potete
  controllare voi sarebbe grande:

  ***ATTENZIONE***

  virus su whatsapp...

  ho preso un virus sul cell :(

  visto che ho il n. di molte di voi faccio prima ad avvisare così...

  il virus si manifesta prima con un semplice ciao, se voi rispondete vi dirà che
  x errore vi è stato mandato un codice che serve con urgenza alla persona con cui
  state parlando. se glielo mandate, con questo codice entrerà nel vs whatsapp e ciaone,
  farà ciò che vorrà del vs account wa.

  P.s. poi si specifica che il messaggio originale "ciao" arriva da numeri in rubrica'
Link: https://www.facebook.com/groups/socialgnock/permalink/1994412654036018/
</yamldata></pre>

**Comment by cristigalas** [comment]
Questa segnalazione non mi pare si riferisca al coronavirus ma sono le solite cose che circolano su whatsapp. E poi il link rimanda ad un gruppo chiuso e non ad un post. Infine, noi pubblichiamo le smentite e non le semplici segnalazioni di bufale.
