### ISSUE TITLE
Raccolta fondi di Open Arms Italia per l'acquisto di strumenti informatici per sostenere le scuole nella didattica a distanza

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2396]
<pre><yamldata>
Descrizione: Raccolta fondi di Open Arms Italia per l'acquisto di strumenti informatici per sostenere
  le scuole nella didattica a distanza.
Link: https://www.produzionidalbasso.com/project/open-arms-italia-per-la-scuola/
Nome: Open Arms Italia
regione_manuale: tutte
</yamldata></pre>

**Comment by cristigalas** [comment]
@deborah-aa qui va sola label raccolta fondi. Aggiungi anche posizione con indirizzo sede a Open Arms. E togli regione_manuale: tutte. Nelle raccolte fondi non importa.

**Comment by chiccap** [comment]
già presente #2443
