### ISSUE TITLE
Sei un Medico?
Attiva il servizio di Video Visita su Paginemediche per continuare a prenderti cura d

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2398]
<pre><yamldata>
Da_chi_offerta: PagineMediche.it
Descrizione: 'Sei un Medico?

  Attiva il servizio di Video Visita su Paginemediche per continuare a prenderti cura
  dei tuoi pazienti, a distanza e in tutta sicurezza.

  Il servizio, GDPR compliant, è disponibile gratuitamente e risulta compatibile con
  la definizione di Televisita del Ministero della Salute. Sei un Paziente?

  Attiva il monitoraggio Covid-19 e invita il tuo medico al servizio di Video Visita
  offerto gratuitamente da Paginemediche. Sarà il tuo medico a ricontattarti per accedere
  alla Video Visita.

  Ricorda che se presenti sintomi sospetti da COVID-19 puoi utilizzare la chat informativa
  per sapere come comportarti, secondo le linee guida del Ministero della Salute e
  registrandoti al servizio Visitami puoi attivare il monitoraggio'
Destinatari: Tutti Medici, Pazienti e Cittadini
Link: https://tivideovisito.it/
Natura: solidale
Tipo_di_soggetto: privato
Titolo: VideoVisita e telemonitoraggio
</yamldata></pre>

**Comment by cristigalas** [comment]
Non so se accettare... @chiccap @favoeva @luciaroma

**Comment by chiccap** [comment]
> Non so se accettare... @chiccap @favoeva @luciaroma

Qual è il tuo dubbio? Che sia un servizio a pagamento?

**Comment by cristigalas** [comment]
> > Non so se accettare... @chiccap @favoeva @luciaroma
> 
> Qual è il tuo dubbio? Che sia un servizio a pagamento?

Sì anche e poi chi sono questi medici? Il servizio è approvato da Ministero/Regione? Che significa ‘monitoraggio’, è o no un servizio di sorveglianza?

**Comment by favoeva** [comment]
E’ arrivato diverse volte sul gruppo Fb , fino ad ora non lo abbiamo accettato . Sembra un prodotto per medici

**Comment by favoeva** [comment]
![9BFFA35A-DE4F-498A-967E-5B5B20B56553](https://user-images.githubusercontent.com/9965333/79076698-83058000-7cfc-11ea-92b9-ef2ca2cc8318.png)

Serve per ‘vendere’ visite private dei medici del loro network

**Comment by cristigalas** [comment]
Ok grazie @favoeva. Non accettiamo e chiudo.
