### ISSUE TITLE
#Streetartistperfirenze Asta d’arte su Instagram per sostenere la coop. sociale Cat 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2403]
<pre><yamldata>
Causale: donazione liberale campagna uniti si svolta
Descrizione: 'Con la prima asta #streetartistperfirenze hanno raccimolato un bel gruzzolo:
  16.500 euro tondi, destinati all’ospedale di Careggi. Così gli urban artist fiorentini,
  tra cui NINJAZ e EXIT artisti seguitissimi sui social, raddoppiano mettendo in piedi
  su Instagram una seconda asta di opere ma stavolta per sostenere gli ultimi, quelli
  più esposti a questa emergenza sanitaria quanto economica. I ricavati, infatti,
  andranno a CAT, che dall’85 si occupa di marginalità (migranti, accoglienza, prostituzione,
  senzatetto, inclusione sociale).

  Le opere saranno raccolte su INSTAGRAM dall’hashtag “#unitisisvolta“, mentre per
  l’asta vera e propria saranno a disposizione 26 ore: da lunedì 13 prossimo alle
  10 fino a mezzogiorno di martedì 14. Il tutto grazie ad una procedura snella: per
  partecipare basterà cliccare sulla foto dell’opera scelta e cominciare a ‘gareggiare’
  direttamente sul post (si parte da una base d’asta di 40 euro, con un rilancio minimo
  di 20 euro).

  Finito il tempo, il vincitore farà un bonifico a CAT (IBAN IT59 G030 6909 6061 0000
  0146 860, con la causale “donazione liberale campagna uniti si svolta”). Una volta
  girata la ricevuta all’artista, avrà il suo ‘pezzo’ da collezione a fine emergenza“per
  non sovraccaricare i corrieri che continuano comunque a lavorare mentre noi restiamo
  a casa”.

  Il senso dell’asta è sintetizzato nelle parole:  “Sosteniamo chi, di fronte a questa
  crisi sanitaria, è più vulnerabile. Sostenere queste persone significa sostenere
  la salute della comunità intera. Chi non può #restareacasa, perché una casa non
  ce l’ha, chi vive in alloggi precari in condizioni sanitarie inadeguate all’emergenza,
  chi ha perso le proprie fonti di reddito e non ha reti di sostegno, chi ha una casa,
  ma è il luogo in cui subisce violenze, chi è vittima di tratta e grave sfruttamento
  lavorativo, chi è stato escluso dalle accoglienze e dai percorsi di protezione internazionale,
  chi vive una condizione di esclusione digitale che amplifica l’esclusione sociale,
  chi ha difficoltà ad accedere ai servizi sociali, chi non ha accesso alle informazioni
  nella propria lingua”.'
Email: presidenza@coopcat.it
IBAN: IBAN IT59 G030 6909 6061 0000 0146 860
Intestazione: CAT COOPERATIVA SOCIALE
Link: https://www.coopcat.it/2020/04/09/unitisisvolta-raccolta-fondi-per-sostenere-gli-ultimi/
Nome: CAT COOPERATIVA SOCIALE
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 43.76923077 11.25588885 (Firenze) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=43.76923077+11.25588885&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by cristigalas** [comment]
Scaduta. Chiudo.
