### ISSUE TITLE
il cortisone ... lo avevo pensato anche io chissà

Ricevo ed inoltro da collega cardiologo di Pavia:

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2404]
<pre><yamldata>
Cosa: notizia medica
Descrizione: 'il cortisone ... lo avevo pensato anche io chissà

  Ricevo ed inoltro da collega cardiologo di Pavia:

  "Non vorrei sembrarvi eccessivo ma credo di aver dimostrato la causa della letalità
  del coronavirus.

  Solo al Beato Matteo ci sono 2 cardiologi che girano su 150 letti a fare ecocardio
  con enorme fatica e uno sono io. Fatica terribile!

  Però, di quello che alcuni supponevano, ma non ne riuscivano a essere sicuri, ora
  abbiamo i primi dati.

  La gente va in rianimazione per tromboembolia venosa generalizzata, soprattutto
  polmonare.

  Se così fosse, non servono a niente le rianimazioni e le intubazioni perché innanzitutto
  devi sciogliere, anzi prevenire queste tromboembolie. Se ventili un polmone dove
  il sangue non arriva, non serve! Infatti muoiono 9 su 10. Perché il problema è cardiovascolare,
  non respiratorio! Sono le microtrombosi venose, non la polmonite a determinare la
  fatalità!

  E perché si formano trombi? Perché l''infiammazione come da testo scolastico, induce
  trombosi attraverso un meccanismo fisiopatologico complesso ma ben noto.

  Allora? Quello che la letteratura scientifica, soprattutto cinese, diceva fino a
  metà marzo era che non bisognava usare antinfiammatori. Ora in Italia si usano antinfiammatori
  e antibiotici (come nelle influenze) e il numero dei ricoverati crolla.

  Molti morti, anche di 40 anni, avevano una storia di febbre alta per 10-15 giorni
  non curata adeguatamente. Qui l''infiammazione ha distrutto tutto e preparato il
  terreno alla formazione dei trombi. Perché il problema principale non è il virus,
  ma la reazione immunitaria che distrugge le cellule dove il virus entra. Infatti
  nei nostri reparti COVID non sono mai entrati malati di artrite reumatoide! Perché
  sono in terapia cortisonica.

  Questo è il motivo principale per cui in Italia le ospedalizzazioni si riducono
  e sta diventando una malattia curabile a casa.

  Curandola bene a casa eviti non solo l''ospedalizzazione, ma anche il rischio trombotico.

  Non era facile capirlo perché i segni della microembolia sono sfumati, anche all''ecocardio.

  Ma questo we ho confrontato i dati dei primi 50 pazienti tra chi respira male e
  chi no e la situazione è apparsa molto chiara.

  Per me si potrebbe tornare a vita normale e riaprire le attività commerciali. Via
  quarantena.

  Non subito. Ma il tempo di pubblicare questi dati. Il vaccino può arrivare con calma.

  In America e altri stati che seguono la letteratura scientifica che invita a NON
  usare antinfiammatori è un disastro! Peggio che in Italia.

  E parliamo di farmaci vecchi e che costano pochi euro."

  La testimonianza del collega parrebbe confermata dai protocolli di alcuni altri
  ospedali:

  al Sacco danno Clexane a tutti, con D-dimero predittivo: più è alto meno risponderà
  il pz.

  al San Gerardo di Monza Clexane e cortisone

  al Sant''Orsola di Bologna Clexane a tutti + protocollo condiviso con i medici di
  famiglia che prescrivono Plaquenil a pioggia su tutti i pz. monosintomatici a domicilio

  Integro con una precisazione sugli antinfiammatori:

  La produzione di COX 2 è aumentata nei tessuti bersaglio virali da pazienti con
  infezione virale attiva e si è visto che la delezione della cox2 riduce la mortalità
  , mentre la delezione della cox1 è associata al peggioramento dell’infezione

  Quindi i farmaci antinfiammatori tipo Brufen, naproxene, aspirina che inibiscono
  la cox1 oltre che la Cox 2 non andrebbero usati,

  Mentre celecoxib un inibitore selettivo della Cox 2 sembra dare buoni risultati,
  bisogna comunque aspettare esito di studi, invece questa analisi porta in evidenza
  la necessità di usare negli stadi più avanzati della malattia una eparina a basso
  peso molecolare ad alte dosi... (Clexane 8.000 UI/die)

  Evito (per non appesantire troppo l''esposizione, e perché il testo è troppo tecnico)
  di riportare un''interessante testimonianza di un anatomo-patologo: vi basti pensare
  che il "Papa Giovanni XXIII" di Bergamo ha eseguito 50 autopsie ed il "Sacco" di
  Milano 20 (quella italiana è la casistica più alta del mondo, i cinesi ne hanno
  fatte solo 3 e "minimally invasive"). Tutto quanto ne esce sembra confermare in
  pieno le informazioni sopra riportate.

  In poche parole, pare che l''exitus sia determinato da una DIC (per i non medici,
  Coagulazione Intravascolare Disseminata) innescata dal virus. Quindi la polmonite
  interstiziale non c''entrerebbe nulla, sarebbe stato soltanto un abbaglio diagnostico:
  abbiamo raddoppiato i posti in rianimazione, con costi esorbitanti, probabilmente
  inutilmente.

  Col senno di poi, mi viene da ripensare a tutti quegli Rx Torace che commentavamo
  circa un mese fa: quelle immagini che venivano interpretate come polmonite interstiziale
  in realtà potrebbero essere del tutto coerenti con una DIC.

  Sarà interessante adesso (una volta che tutte queste nuove informazioni venissero
  confermate) verificare se ci sarà la "volontà politica" di recepirle da parte delle
  Istituzioni.

  Potrebbe significare uscire da questo casino in quattro e quattr''otto, togliendoci
  un sacco di rotture di coglioni (mascherine, app di tracciamento, code ai negozi,
  ecc. ecc.).

  Purtroppo ho qualche dubbio al riguardo ...'
Link: Https://facebook.com
</yamldata></pre>

**Comment by cristigalas** [comment]
Non accettiamo notizie medico-scientifiche.
