### ISSUE TITLE
Onestamente mi sembra grossa. Potete verificare? grazie
https://buongiornonews.it/coronavirus-una-sp

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2410]
<pre><yamldata>
Cosa: Segnalazione possibile bufala
Descrizione: 'Onestamente mi sembra grossa. Potete verificare? grazie

  https://buongiornonews.it/coronavirus-una-speranza-dalla-scoperta-del-prof-giannini/'
Link: https://buongiornonews.it/coronavirus-una-speranza-dalla-scoperta-del-prof-giannini/
</yamldata></pre>

**Comment by cristigalas** [comment]
Sì, è una bufala vedi qui https://www.medicalfacts.it/2020/04/11/coronavirus-la-lettera-del-cardiologo-di-pavia-che-gira-su-whatsapp/
Faccio segnalazione.
