### ISSUE TITLE
“ceste sospese”: a #Milano l’iniziativa di solidarietà alimentare diffusa 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2415]
<pre><yamldata>
Cosa: '“Ceste sospese” a #Milano'
Descrizione: "Si sono ispirate al Panaro Solidale napoletano un gruppo di donne dei\
  \ quartieri Dergano e Bovisa che hanno appeso fuori dalle loro abitazioni le prime\
  \ sedici ceste con prodotti alimentari e per l’igiene personale. L’obiettivo: dare\
  \ un aiuto materiale a chi ha bisogno. \nL’idea è semplice: una cesta in cui inserire\
  \ prodotti alimentare confezionati, ma anche libri e pannolini per bambini; renderla\
  \ accessibile dalla strada. Con un’avvertenza: chi ha bisogno può liberamente prendere\
  \ e altrettanto liberamente chi può contribuire è invitato a farlo. Ispirandosi\
  \ all’iniziativa partita da poco a Napoli del “Panaro solidale”."
Destinatari: Chi ha bisogno
Immagine: 9A3B048F-1313-46E2-AB80-B18B5E9ABA5F-8_5_44.png
Link: http://www.vita.it/it/article/2020/04/03/le-cestesospese-alla-conquista-di-milano/154851/
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 45.46679408 9.1903474 (Milano) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=45.46679408+9.1903474&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by cristigalas** [comment]
Già presente.
