### ISSUE TITLE
Q uesto signore che parla e un giornalista con le contropalle di nome MASSIMO MAZZUCCO! VOLEVATE SAP

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2419]
<pre><yamldata>
Cosa: Video da messanger Massimo Mazzucco
Descrizione: Q uesto signore che parla e un giornalista con le contropalle di nome
  MASSIMO MAZZUCCO! VOLEVATE SAPERE COSA CI ASPETTA? ECCOLO....E NOI CONTINUAMO A
  DORMIRE!!
Link: https://contro.tv/
</yamldata></pre>

**Comment by Polva13** [comment]
@cristigalas questa la rifiutiamo vero? Oltretutto il link non rimanda alla notizia, che comunque mi pare fuori luogo. Chiedo a te per sicurezza

**Comment by cristigalas** [comment]
@Polva13 si sì, non accettare e chiudi issue.
