### ISSUE TITLE
A seguito di 5 decessi causati da Coronavirus e 26 tamponi positivi in data 08.04.20 la redidenza pe

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2424]
<pre><yamldata>
Cosa: Abbiamo bisogno di 5 medici, 12 infermieri, 7000 mascherine FFP2, 3000 camici
  protettivi
Descrizione: A seguito di 5 decessi causati da Coronavirus e 26 tamponi positivi in
  data 08.04.20 la redidenza per anziani Menotti Bassani di LavenoMombello (VA) cerca
  urgentemente 5 medici, 12 infermieri, 7000 mascherine FFP2, 3000 camici protettivi
Email: info@menottibassani.it
Indirizzo: 45.910642 8.618766 0 0
Link: https://www.menottibassani.it/lettera-diffusione-covid-19/
Nome: Fondazione Centro Residenziale per Anziani Menotti Bassani
Telefono: 0332 668339
</yamldata></pre>

**Comment by Polva13** [comment]
già segnalata qui https://github.com/emergenzeHack/covid19italia_segnalazioni/issues/2401
