### ISSUE TITLE
Il sostegno pedagogico a distanza è offerto dalla Cooperativa Andirivieni nell’ambito dei servizi de

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2425]
<pre><yamldata>
Da_chi_offerta: Centro Famiglie C.I.S.S.38 e Cooperativa Andirivieni
Descrizione: "Il sostegno pedagogico a distanza è offerto dalla Cooperativa Andirivieni\
  \ nell’ambito dei servizi del Centro Famiglie CISS38, per orientare e supportare\
  \ i genitori nella gestione dei figli in questi giorni di grande cambiamento.\n\
  Contatta la dottoressa Ilaria Pollono (Coop. Andirivieni) al: 3480183680 \nL’iniziativa\
  \ è realizzata grazie al Progetto Movimenti, finanziato dalla Fondazione Con I Bambini."
Destinatari: Genitori e famiglie
Link: http://www.ciss38.it/it/avvisi?Id=1708#briciole
Natura: solidale
Posizione: 45.33097 7.729483 0 0
Tipo_di_soggetto: pubblico
Titolo: Centro Famiglie CISS38 - Sportello di sostegno pedagogico a distanza
</yamldata></pre>

**Comment by eleninz3** [comment]
@chiccap la stessa cooperativa ha un'altra segnalazione in cui però era considerata come servizi e iniziative solidali private.
Qui cosa lasciamo?

**Comment by cristigalas** [comment]
@eleninz3 ho aggiornato questa segnalazione già esistente #2110 aggiungendo anche il numero di telefono presente in quest’ultima segnalazione. Tutte le altre info sono uguali. Chiudo.
