### ISSUE TITLE
Rete di associazioni e altre organizzazioni che raccoglie beni di prima necessità (alimentari e non)

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2428]
<pre><yamldata>
Da_chi_offerta: Rete Don't Panic
Descrizione: Rete di associazioni e altre organizzazioni che raccoglie beni di prima
  necessità (alimentari e non) per le famiglie che accedono agli empori solidali della
  città, nuclei in uscita da condizione di povertà con il supporto dei Servizi Sociali
  Territoriali.
Destinatari: Famiglie e altri soggetti in difficoltà
Link: https://dontpanicbo.it
Natura: solidale
Posizione: 44.493659 11.343196 0 0
Tipo_di_soggetto: privato
Titolo: 'Spesa solidale e servizi di supporto #Bologna'
</yamldata></pre>

**Comment by marticorti** [comment]
Già pubblicata #1104

**Comment by chiccap** [comment]
> Già pubblicata #1104

Quando non si accetta la segnalazione poi bisogna chiuderla! Pulsante CLOSE.
