### ISSUE TITLE
emersione e sostegno vittime di tratta

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2433]
<pre><yamldata>
Da_chi_offerta: Differenza Donna
Destinatari: donne vittime di tratta a scopi sessuali e/o commerciali
Link: https://www.differenzadonna.org/
Natura: solidale
Posizione: 41.853196 12.502441 0 0
Tipo_di_soggetto: privato
Titolo: emersione e sostegno vittime di tratta
</yamldata></pre>

**Comment by cristigalas** [comment]
Nessun riferimento a servizi per l’emergenza, neanche sul loro sito. Non accettiamo.
