### ISSUE TITLE
Lancio della campagna "Covid19-Nessuna da sola-Sostieni le sexworker" il 7 aprile 2020
COVID 19 - SO

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2444]
<pre><yamldata>
Da_chi_offerta: Comitato per i Diritti Civili delle Prostitute onlus
Descrizione: 'Lancio della campagna "Covid19-Nessuna da sola-Sostieni le sexworker"
  il 7 aprile 2020

  COVID 19 - SOLIDARIETÀ IMMEDIATA PER LE SEX WORKER PIÙ COLPITE DALL''EMERGENZA

  📢 La pandemia #COVID19 sta influendo drammaticamente sulle vite di chi fa lavoro
  sessuale. La maggior parte delle e dei #sexworker non è in grado di accedere alle
  prestazioni sociali istituite come misure di emergenza dal Governo. È un momento
  di disperazione e di paura: molte delle giovani sex worker donne e persone trans
  sono migranti, sole e senza una rete familiare a cui far riferimento; molte altre
  sono madri e con il loro lavoro sostengono tutta la famiglia.📢 In queste settimane
  e sempre di più nelle prossime, l’#emergenza che stiamo vivendo sta spingendo sull’orlo
  del baratro molte/i di loro, dando origine a situazioni di disagio e povertà sempre
  più gravi . E sarà sempre peggio. Vi sono persone dedite ad attività di prostituzione
  in forma libera, concordata o costretta, già in condizioni di vulnerabilità umana
  e sociale, e oggi rischiano di precipitare in condizioni di #povertà estrema. Condizioni
  di necessità che potrebbero costringerle a lavorare, violando le regole, esponendosi
  alle relative conseguenze penali e ai rischi per la propria salute e quella collettiva.

  🔥 Le-gli operatrici/ori del sistema nazionale antitratta, in collaborazione con
  altre reti e soggetti del civismo attivo e dell’auto-organizzazione delle sex worker,
  promuovono una campagna di #crowdfunding mirata a sostenere economicamente e con
  aiuti materiali tutte queste persone che stanno vivendo in una condizione di indigenza,
  determinata dall''emergenza Covid-19 e che non potranno richiedere gli ammortizzatori
  sociali .

  🔥 Vogliamo spezzare questo silenzio e stare al fianco di tutte le lavoratrici e
  lavoratori sessuali che sono maggiormente vulnerabili in questa situazione emergenziale
  . Per questo lanciamo una rete di #solidarietà che possa aiutare nel concreto e
  raggiungere quante più persone possibili, attraverso la Piattaforma nazionale anti-tratta,

  le associazioni e i collettivi che da anni lavorano come supporto alla complessa
  realtà del sex work.

  TUTTI I SOLDI DONATI VERRANNO UTILIZZATI PER ASSISTERE ECONOMICAMENTE E MATERIALMENTE
  LAVORATRICI E LAVORATORI SESSUALI IN SITUAZIONI DI ESTREMO BISOGNO:

  Per contribuire va bene qualsiasi cifra vogliate donare, sottoscrivete in maniera
  libera e generosa.

  https://www.produzionidalbasso.com/project/covid19-nessuna-da-sola-solidarieta-immediata-alle-lavoratrici-sessuali-piu-colpite-dall-emergenza/'
Destinatari: Sostegno ai/alle sex e i/le ptenziali vittime di tratta e di grave sfruttamento
Link: https://www.facebook.com/nessunadasola/
Natura: solidale
Tipo_di_soggetto: privato
Titolo: Sostegno alle sex workers e/o potenziali vittime di tratta e di grave sfruttamento
</yamldata></pre>

**Comment by PaolaLiliana** [comment]
@chiccap sto trasformando questa segnalazione in una segnalazione di raccolta fondi. Quindi inserisco l'etichetta "non accettata"
