### ISSUE TITLE
Raccolta fondi del Comitato per i diritti civili delle prostitute a sostegno di chi svolge lavoro sessuale

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2446]
<pre><yamldata>
Descrizione: 'La pandemia COVID-19 sta influendo drammaticamente sulle vite di chi
  fa lavoro sessuale.

  La maggior parte di loro non è in grado di accedere alle prestazioni sociali istituite
  come misure di emergenza dal Governo, sono migranti e senza una rete familiare a
  cui far riferimento.

  Ecco perché diverse organizzazioni hanno deciso di avviare una raccolta fondi per
  aiutare chi in questo momento di isolamento si trova in situazione di bisogno estremo.

  L''obiettivo iniziale è di raccogliere 30.000 euro per andare a coprire le richieste
  di aiuto in tutta Italia.

  La donazione verrà addebitata sul conto corrente dedicato e gestito dal Comitato
  per i Diritti Civili delle Prostitute. Il Comitato distribuirà le donazioni attraverso
  la rete composta da associazioni e unità di strada che da anni sono al fianco di
  chi fa lavoro sessuale, che raccoglie localmente i bisogni e le varie richieste
  di aiuto, valutandone l’urgenza e le necessità.

  COME VERRANNO SPESI I SOLDI RACCOLTI

  - Distribuzione pacchi alimentari e generi di prima necessità

  - Farmaci e presidi sanitari

  - Sostegno nel pagare le utenze

  - Sostegno nel pagare l’affitto'
Email: solidarieta.sw@gmail.com
Link: https://www.produzionidalbasso.com/project/covid19-nessuna-da-sola-solidarieta-immediata-alle-lavoratrici-sessuali-piu-colpite-dall-emergenza/
Nome: Comitato per i diritti civili delle prostitute Onlus
Posizione: 45.65003 13.77066
</yamldata></pre>

**Comment by PaolaLiliana** [comment]
@chiccap non riesco a trovare l'indirizzo di Comitato per i diritti civili delle prostitute Onlus.

**Comment by claudiamazzantiact** [comment]
Ciao! @PaolaLiliana dalla pagina fb dovrebbe essere Trieste

**Comment by chiccap** [comment]
Campagna terminata
