### ISSUE TITLE
Ferramenta e attrezzi

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2456]
<pre><yamldata>
Descrizione: Ferramenta e attrezzi
Nome_dell_esercizio_commercial: Agrimec
Telefono: ' 0923 912881 '
Link: https://www.facebook.com/agrimecpantelleria
Posizione: 36.831234 11.947452 0 0
</yamldata></pre>

**Comment by cristigalas** [comment]
Incompleta nelle info e non si capisce se eventuale servizio a domicilio sia gratuito.
