### ISSUE TITLE
M.V.I. da assistenza medica e farmacologica alle persone accolte nel centro di accoglienza attivato 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2472]
<pre><yamldata>
Cosa: Progetto assistenza dimessi post polmonite dagli ospedali
Descrizione: 'M.V.I. da assistenza medica e farmacologica alle persone accolte nel
  centro di accoglienza attivato all''H. Michelangelo, che, ancora in convalescenza
  non possono rientrare a domicilio o sono homeless. Scopo del progetto: liberare
  posti letto per acuti negli ospedali per soggetti con polmonite virale.'
Posizione: 45.485154 9.206243 0 0
</yamldata></pre>

**Comment by marcocovid83** [comment]
è una ripetizione della segnalazione precedente. abbiamo già segnalato iniziativa di accoglienza all'hotel michelangelo di milano
