### ISSUE TITLE
I lprogetto ha come scopo la realizzazione di progetti di assistenza e protezione sociale rivolti a 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2484]
<pre><yamldata>
Da_chi_offerta: Volontarius - La Strada der Weg - Consis
Descrizione: Il progetto ha come scopo la realizzazione di progetti di assistenza
  e protezione sociale rivolti a persone straniere vittime di tratta e sfruttamento,
  o che si trovano in condizioni di vulnerabilità personale, con l’obiettivo di favorire
  il loro inserimento socio-lavorativo
Destinatari: persone immigrate vittime di tratta e grave sfruttamento
Link: http://www.albaprojectbz.it/index.php/news/
Natura: solidale
Posizione: 46.490003 11.341474 0 0
Tipo_di_soggetto: privato
Titolo: Progetto Alba
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Sono in dubbio se accettare questa segnalazione perchè il progetto mi pare non sia collegato all'emergenza Covid-19

**Comment by cristigalas** [comment]
Sì, ho guardato il loro sito e non c’è nulla...
