### ISSUE TITLE
Attività di sostegno psico-sociale realizzate da un'equipe multidisciplinare (etnopsichiatra, psicol

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2490]
<pre><yamldata>
Da_chi_offerta: Asl 4 Chiavarese (GE)
Descrizione: 'Attività di sostegno psico-sociale realizzate da un''equipe multidisciplinare
  (etnopsichiatra, psicologi, medico antropologo, mediatori culturali).

  Contatto telefonico 0185 329784'
Destinatari: Richiedenti asilo/ Rifugiati
Natura: solidale
Tipo_di_soggetto: pubblico
Titolo: Progetto FAMI
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Già presente in #2488
