### ISSUE TITLE
Il quartiere Aurora è un quartiere di Torino particolarmente fragile con una percentuale di stranier

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2500]
<pre><yamldata>
Cosa: Nel quartiere Aurora di Torino si cercano soluzioni per raccogliere articoli
  di cancelleria da far arrivare alle famiglie con bambini e adolescenti in difficoltà
Descrizione: "Il quartiere Aurora è un quartiere di Torino particolarmente fragile\
  \ con una percentuale di stranieri tra le più alte della città e una quota importante\
  \ di popolazione alle prese con un disagio economico pesante. \nIn questo contesto,\
  \ a molte famiglie mancano articoli di cancelleria (matite, biro, pennarelli, quaderni\
  \ e carta) necessari a seguire le attività didattiche erogate dalle scuole in modalità\
  \ telematica.\nCerchiamo soluzioni per raccogliere e far arrivare articoli di cancelleria\
  \ alle famiglie più in difficoltà."
Destinatari: Persone e famiglie in difficoltà
Email: arteria.associazione@gmail.com
Nome: Ivano Casalegno, Associazione Arteria, capofila del “Coordinamento Aurora per
  l’emergenza Covid-19”, che raggruppa una quarantina di organizzazioni operanti sul
  territorio con l’obiettivo di raccogliere i bisogni, condividere informazioni, individuare
  soluzioni.
Telefono: '3482205594'
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 45.0732745 7.68068748 (Torino) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=45.0732745+7.68068748&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by claudiamazzantiact** [comment]
Già presente in #2499
