### ISSUE TITLE
“Quarantena: prendiamola per il verso giusto”, poesie a sostegno della raccolta fondi di Cuamm Marche

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2501]
<pre><yamldata>
Descrizione: "In una fase d’emergenza, quasi surreale, siamo rimasti  per un attimo\
  \ a guardare, per avere una visione completa e poi scegliere come agire.\n\nConsapevoli\
  \ che ciascuno, a suo modo, può fare la sua parte in questa emergenza, vi presentiamo\
  \ un progetto in perfetto stile KIND of, che da un bisogno comune cerca di trovare\
  \ risposte, attraverso l’arte e la creatività.\n\nUn progetto “for heArt”, dove\
  \ la poesia (in questo caso) può rappresentare un mezzo per avvicinare le persone,\
  \ farle sentire meno sole e proporre loro una possibilità di azione concreta, per\
  \ raggiungere e aiutare chi ha più bisogno (pur “restando a casa”).\n\n“QUARANTENA:\
  \ Prendiamola per il verso giusto” è una mini raccolta poetica, in formato digitale,\
  \ estrapolata da un progetto editoriale più ampio, dal nome “IO VERSO A CASA”. Poesie\
  \ ispirate dall’emergenza, ma anche dalla quotidianità, nate sui social per allietare\
  \ le giornate delle persone e diventate poi un prodotto digitale a scopo benefico.\
  \ \n\nIn questo evento vi daremo indicazioni su come poter richiedere una copia\
  \ di “QUARANTENA: Prendiamola per il verso giusto”, sostenendo (attraverso un’offerta\
  \ libera) la campagna legata all’Emergenza coronavirus, lanciata dalla ONG Medici\
  \ con l'Africa Cuamm, per contribuire all'acquisto di 4 respiratori e degli equipaggiamenti\
  \ necessari nei principali reparti di terapia intensiva degli ospedali più colpiti.\n\
  \n\U0001D5E6\U0001D5F6 \U0001D5FD\U0001D602\U0001D5FC̀ \U0001D5F2\U0001D5F3\U0001D5F3\
  \U0001D5F2\U0001D601\U0001D601\U0001D602\U0001D5EE\U0001D5FF\U0001D5F2 \U0001D602\
  \U0001D5FB\U0001D5EE \U0001D5F1\U0001D5FC\U0001D5FB\U0001D5EE\U0001D607\U0001D5F6\
  \U0001D5FC\U0001D5FB\U0001D5F2 \U0001D5F1\U0001D5F6\U0001D5FF\U0001D5F2\U0001D601\
  \U0001D601\U0001D5EE\U0001D5FA\U0001D5F2\U0001D5FB\U0001D601\U0001D5F2 \U0001D5F1\
  \U0001D5EE\U0001D5F9\U0001D5F9\U0001D5F2 \U0001D5FD\U0001D5EE\U0001D5F4\U0001D5F6\
  \U0001D5FB\U0001D5F2 \U0001D5FA\U0001D5F2\U0001D600\U0001D600\U0001D5F2 \U0001D5EE\
  \ \U0001D5F1\U0001D5F6\U0001D600\U0001D5FD\U0001D5FC\U0001D600\U0001D5F6\U0001D607\
  \U0001D5F6\U0001D5FC\U0001D5FB\U0001D5F2 \U0001D5F1\U0001D5EE\U0001D5F9 \U0001D5D6\
  \U0001D5E8\U0001D5D4\U0001D5E0\U0001D5E0:\n\nhttps://www.facebook.com/donate/139151517520176/\n\
  \nhttps://www.mediciconlafrica.org/emergenzacoronavirus\n\n\U0001D5F2 \U0001D5FD\
  \U0001D5FC\U0001D5F6 \U0001D5F6\U0001D5FB\U0001D603\U0001D5F6\U0001D5EE\U0001D5FF\
  \U0001D5F2 \U0001D602\U0001D5FB\U0001D5EE \U0001D5FF\U0001D5F6\U0001D5F0\U0001D5F2\
  \U0001D603\U0001D602\U0001D601\U0001D5EE \U0001D5F1\U0001D5F2\U0001D5F9\U0001D5F9\
  \U0001D5EE \U0001D5F1\U0001D5FC\U0001D5FB\U0001D5EE\U0001D607\U0001D5F6\U0001D5FC\
  \U0001D5FB\U0001D5F2 \U0001D5EE “\U0001D5DE\U0001D5DC\U0001D5E1\U0001D5D7 \U0001D5FC\
  \U0001D5F3” \n\nkindofstorytelling@gmail.com \n\nIn alternativa, potete allegare\
  \ la ricevuta direttamente nel FORM apposito, che trovate cliccando sul pulsante\
  \ \"biglietti\" dell'evento. \n\n\U0001D5E6\U0001D5F2 \U0001D5FD\U0001D5FF\U0001D5F2\
  \U0001D5F3\U0001D5F2\U0001D5FF\U0001D5F6\U0001D601\U0001D5F2, \U0001D5FD\U0001D5FC\
  \U0001D601\U0001D5F2\U0001D601\U0001D5F2 \U0001D5F2\U0001D5F3\U0001D5F3\U0001D5F2\
  \U0001D601\U0001D601\U0001D602\U0001D5EE\U0001D5FF\U0001D5F2 \U0001D5F9\U0001D5EE\
  \ \U0001D5F1\U0001D5FC\U0001D5FB\U0001D5EE\U0001D607\U0001D5F6\U0001D5FC\U0001D5FB\
  \U0001D5F2 \U0001D601\U0001D5FF\U0001D5EE\U0001D5FA\U0001D5F6\U0001D601\U0001D5F2\
  \ \U0001D5DC\U0001D5FB\U0001D600\U0001D601\U0001D5EE\U0001D5F4\U0001D5FF\U0001D5EE\
  \U0001D5FA @\U0001D5F8\U0001D5F6\U0001D5FB\U0001D5F1\U0001D5FC\U0001D5F3\U0001D600\
  \U0001D601\U0001D5FC\U0001D5FF\U0001D606\U0001D601\U0001D5F2\U0001D5F9\U0001D5F9\
  \U0001D5F6\U0001D5FB\U0001D5F4 (nella storia in evidenza):\n\nhttps://www.instagram.com/s/aGlnaGxpZ2h0OjE3OTQ3MDk1MDQ2MzMzMTA2?igshid=1ie7kkt3ox3v7\n\
  \nRiceverete \"QUARANTENA: Prendiamola per il verso giusto\", senza il bisogno di\
  \ inviarci alcuna ricevuta."
Email: kindofstorytelling@gmail.com
Link: https://www.facebook.com/events/642195543243921/
Nome: CUAMM
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 44.89912921 8.20414255 (Asti) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=44.89912921+8.20414255&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by chiccap** [comment]
campagna conclusa
