### ISSUE TITLE
Il servizio emersione si è riorganizzato cercando di mantenere inalterate le attività che svolgeva p

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2502]
<pre><yamldata>
Da_chi_offerta: On The Road Società Cooperativa Sociale
Descrizione: 'Il servizio emersione si è riorganizzato cercando di mantenere inalterate
  le attività che svolgeva precedentemente all''emergenza covid19: counseling e supporto
  psico sociale, informative legali e sanitarie (che oggi vengono svolte tramite videochiamate),
  mediazione tra i servizi pubblici del territorio ed il target, supporto agli enti
  del privato sociale impegnati nella distribuzione di cibo e beni di prima necessità
  alla popolazione immigrata indigente'
Destinatari: Vittime di tratta e sfruttamento, immigrati indigenti
Natura: solidale
Tipo_di_soggetto: privato
Titolo: Servizio emersione On The Road Società cooperativa sociale
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Gia inserita #2494
