### ISSUE TITLE
Le realtà di Novate, CRP – Comunità di Relazioni Positive, ANFFAS ONLUS Bollate Novate, La Tenda ODV

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2529]
<pre><yamldata>
Da_chi_offerta: ANFFAS Bollate Novate, CRP - Comunità di Relazioni Positive, La Tenda
  ODV
Descrizione: "Le realtà di Novate, CRP – Comunità di Relazioni Positive, ANFFAS ONLUS\
  \ Bollate Novate, La Tenda ODV, insieme ad un gruppo di volontari, hanno dato vita\
  \ all'iniziativa “Gruppo di Prossimità” per sostenere le persone maggiormente in\
  \ difficoltà a seguito delle restrizioni legate all’emergenza Coronavirus. \n\n\
  Il Gruppo di Prossimità si rende disponibile, con il personale dipendente e volontario\
  \ delle proprie realtà, a contattare telefonicamente le persone sole, le persone\
  \ anziane, i ragazzi con una disabilità che non stanno frequentando i loro centri\
  \ o qualsiasi altra persona ne avesse la necessità.\n\nCi proponiamo con questo\
  \ di far sentire le persone meno sole e isolate, dare loro conforto, scambiare due\
  \ parole, raccontare una storia o proporre una attività che possa essere fatta in\
  \ casa, ascoltare le riflessioni e le preoccupazioni che possono insorgere in queste\
  \ giornate di difficoltà e isolamento, raccogliere richieste di aiuto, indirizzare,\
  \ qualora ce ne sia il bisogno, a servizi specifici e numeri utili attivi.\n\nMettiamo\
  \ a disposizione un numero per essere contattati e per ricevere segnalazioni di\
  \ persone che sono sole o che potrebbero beneficiare di questo servizio: ☎️ 370/3752763\
  \ (numero dello Sportello di ANFFAS). Il numero è attivo tutti i giorni sabato e\
  \ domenica inclusi, dalle 10.00 alle 21.00.\n\nInvitiamo chiunque a segnalarci situazioni\
  \ di persone che passano tante ore da sole in casa o che sono particolarmente fragili\
  \ in questo momento. E' un segno di attenzione verso l'altro e di interessamento.\n\
  \nPossiamo essere contattati anche per ricevere manifestazioni di nuove disponibilità\
  \ ad aiutare.\nRiteniamo che solo insieme, occupandoci gli uni degli altri, senza\
  \ lasciare nessuno escluso, si possa superare positivamente questo difficile momento."
Destinatari: bambini, persone con disabilità, fruitori dei servizi di CSE, persone
  sole, anziani
Link: https://www.facebook.com/CRPassociazione/
Natura: solidale
Posizione: 45.528524 9.148779 0 0
Tipo_di_soggetto: privato
Titolo: Gruppo di Prossimità
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
