### ISSUE TITLE
Contro il Covid-19- DONA all’Ospedale di Cetraro - #Certaro (CS)

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#253]
<pre><yamldata>
Comune: Cetraro
Descrizione: "Contro il Covid-19- DONA all\u2019Ospedale di Cetraro"
Link: https://www.gofundme.com/f/contro-il-covid19-dona-allospedale-di-cetraro?utm_source=facebook&utm_medium=social&utm_campaign=p_cp+share-sheet&fbclid=IwAR2muSHbMThKAcpZ8Xnm_aN1ZZShhNORR1YoeK1liVN8jVeuUGE99TgCSu8
Nome: Miriam Grosso Ciponte
Posizione: 39.530592 15.91854 0 0
Provincia: Cosenza
Regione: Calabria
</yamldata></pre>

**Comment by luciaroma** [comment]
Vi ringraziarvi tutti per le donazioni ricevute, vi informo che la cifra raccolta confluirà nell'iniziativa organizzata da Bergamo Guido sempre qui su GoFoundme (gf.me/u/xqasyg questo è il link alla donazione) e che ha già raggiunto la quota di 23.900 euro, è stata infatti identificata da Lui la società MedicAir che fornirà la disponibilità di ventilatori polmonari, i macchinari sono stati approvati dai dottori dell'Ospedale di Cetraro e presto verranno consegnati.
