### ISSUE TITLE
Notizie ufficiali dell'Ambasciata d'Italia in Spagna, informazioni utili sui voli speciali durante l

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2536]
<pre><yamldata>
Cosa: Notizie per italiani in Spagna
Descrizione: Notizie ufficiali dell'Ambasciata d'Italia in Spagna, informazioni utili
  sui voli speciali durante l'emergenza coronavirus, eventi, iniziative per italiani
  che si trovano in Spagna.
Link: https://www.itagnol.com/spagna-news-ultime-notizie/italiani-spagna-estero/
Posizione: 40.418864 -3.705161 0 0
</yamldata></pre>

**Comment by cristigalas** [comment]
Sito già segnalato.
