### ISSUE TITLE
Entro una comunità vasta, interconnessa a livello nazionale e internazionale, e fortemente motivata 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2539]
<pre><yamldata>
Cosa: Scuola Universitaria Superiore Sant'Anna. Quali cooperazioni tra umani e robots
  per contrastare la diffusione del contagio Covid-19?
Descrizione: Entro una comunità vasta, interconnessa a livello nazionale e internazionale,
  e fortemente motivata a intervenire, anche la Scuola Superiore Sant'Anna sta impegnando
  tutte le sue risorse per garantire il proprio contributo. Ricercare risposte concrete
  per contrastare l’emergenza sanitaria e sociale che deriva da eventi pandemici attraverso
  la cooperazione tra persona umana e robot.
Link: https://www.mastermepa.santannapisa.it/it/news/il-ruolo-della-robotica-ai-tempi-del-covid-19-idee-proposte-e-soluzioni-combattere-la
Posizione: 43.720601 10.402647 0 0
</yamldata></pre>

**Comment by cristigalas** [comment]
Io non accetterei. Tra l’altro abbiamo già segnalato che sono online un pacchetto di lezioni della Scuola Sant’Anna.
@chiccap che dici?

**Comment by chiccap** [comment]
> Io non accetterei. Tra l’altro abbiamo già segnalato che sono online un pacchetto di lezioni della Scuola Sant’Anna.
> @chiccap che dici?

Sì ho visto la segnalazione e sono d’accordo non accetterei.
