### ISSUE TITLE
Testimonianze dalla Scuola Universitaria Superiore Sant'Anna: informazioni e documenti per superare 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2540]
<pre><yamldata>
Cosa: Preparare la fase 2. Come adottare i comportamenti più opportuni per muovere
  verso una nuova normalità?
Descrizione: 'Testimonianze dalla Scuola Universitaria Superiore Sant''Anna: informazioni
  e documenti per superare la fase dell’emergenza sanitaria e agevolare il ritorno
  a una “nuova” normalità nel rispetto di tutte le misure che sono indispensabili
  a tutelare la salute e la sicurezza delle persone'
Link: https://www.mastermepa.santannapisa.it/it/news/covid-19-la-scuola-santanna-e-la-fase-2-limpegno-didattica-ricerca-terza-missione-informazioni
Posizione: 43.720608 10.402669 0 0
</yamldata></pre>

**Comment by cristigalas** [comment]
Non accetterei, per lo stesso motivo di #2539.
