### ISSUE TITLE
Il 12 aprile su Facebook è stata pubblicata un’immagine che mostra un bonifico di 478,22 euro erogat

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2551]
<pre><yamldata>
Cosa: on è vero che il bonus di 600 euro erogato dall'Inps è in realtà pari a circa
  480 euro
Descrizione: 'Il 12 aprile su Facebook è stata pubblicata un’immagine che mostra un
  bonifico di 478,22 euro erogato dall’Inps il 9 aprile 2020. La foto è accompagnata
  da un commento in cui si sostiene che si tratterebbe del bonus di 600 euro per le
  partite Iva previsto dal governo Conte II per far fronte alle difficoltà economiche
  di alcuni lavoratori durante la pandemia da Covid-19.

  La cifra, stando a quanto denunciato da questa immagine, sarebbe in realtà lorda
  e quindi tassata: non si tratterebbe dunque di 600 euro ma di circa 480 euro.

  Questa notizia è falsa, smentita dallo stesso Istituto nazionale della previdenza
  sociale. Andiamo con ordine.

  Il bonus di 600 euro in questione è previsto, per diverse tipologie di lavoratori,
  nel cosiddetto decreto “Cura Italia” pubblicato in Gazzetta ufficiale il 17 marzo
  scorso. Queste indennità, per legge, devono essere erogate dall’Inps dopo la compilazione
  di un modulo online.

  Si tratta di un’indennità netta di 600 euro non soggetta a imposizione fiscale,
  spiega l’Inps. Non è quindi corretto sostenere che il bonus venga tassato.

  Infine, l’Istituto nazionale della previdenza sociale ha chiarito sul proprio profilo
  Twitter che l’immagine messa in circolazione sui social network è un falso: riporta
  come data di accredito il 9 aprile mentre i pagamenti da parte dell’ente cominceranno
  in realtà da mercoledì 15 aprile.'
Link: https://facta.news/2020/04/14/non-e-vero-che-il-bonus-di-600-euro-erogato-dallinps-e-in-realta-pari-a-circa-480-euro/
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
