### ISSUE TITLE
Il progetto CivicoZero Torino, gestito da Save  the Children in collaborazione con l'Ufficio Minori 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2553]
<pre><yamldata>
Da_chi_offerta: Save The Children e Comune di Torino
Descrizione: 'Il progetto CivicoZero Torino, gestito da Save  the Children in collaborazione
  con l''Ufficio Minori Stranieri del Comune di Torino,  è volto a fornire supporto,
  orientamento e protezione a minori e neomaggiorenni stranieri,  in condizioni di
  marginalità sociale e a rischio di devianza, sfruttamento e abuso, con particolare
  attenzione per i minori stranieri non accompagnati.

  In seguito alla chiusura del centro in cui si svolgevano le attività del progetto,
  Civicozero è raggiungibile tramite il numero di servizio: 3429500858.'
Destinatari: minori e giovani migranti
Link: https://www.facebook.com/CivicozeroTorino/
Natura: solidale
Tipo_di_soggetto: privato
Titolo: Civicozero Torino
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 45.0732745 7.68068748 (Torino) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=45.0732745+7.68068748&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by cristigalas** [comment]
Già presente
