### ISSUE TITLE
Un Servizio telefonico multilingue (italiano, arabo, inglese, francese, tigrino, somalo, hindi, urdu

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2554]
<pre><yamldata>
Da_chi_offerta: Save The Children
Descrizione: 'Un Servizio telefonico multilingue (italiano, arabo, inglese, francese,
  tigrino, somalo, hindi, urdu, marathi, pangiabi, curdo, persiano curdo e dialetti
  francofoni quali wolof, mandinga, bambara, djoula, more, bissà, kassena) che garantisce,
  gratuitamente, supporto, consulenza ed orientamento ai minori migranti e a tutti
  gli adulti coinvolti nella gestione e nell''accoglienza dei minori migranti, al
  fine di informarli sui diritti dei minori stranieri non accompagnati, fornire assistenza
  legale, psicologica e mediazione linguistica, nonché attivare contatti locali con
  i servizi e le associazioni.

  Il servizio è attivo per 5 giorni alla settimana, dal Lunedì al Venerdì, dalle ore
  10:00 alle ore 17:00, ed è raggiungibile attraverso il Numero Verde gratuito 800
  14 10 16 (per Lycamobile: 351 2 20 20 16).'
Destinatari: Minori stranieri e adulti
Link: https://www.savethechildren.it/cosa-facciamo/progetti/helpline-minori-migranti
Titolo: Helpline Minori Migranti
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
