### ISSUE TITLE
Chiusura esercizi commerciali il 25 aprile e il 1° maggio in #Piemonte

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2564]
<pre><yamldata>
Cosa: 'Regione#Piemonte: negozi chiusi il 25/4 e il 1/5'
Descrizione: Esercizi commerciali chiusi il 25 aprile e il 1° maggio. Il presidente
  Alberto Cirio ha firmato un’ordinanza che prevede la chiusura di tutti gli esercizi
  commerciali il 25 aprile e il 1° maggio, ad eccezione di farmacie, parafarmacie
  e degli esercizi dedicati alla vendita esclusiva di prodotti sanitari.
Fonte: Regione#Piemonte
Link: https://www.regione.piemonte.it/web/sites/default/files/media/documenti/2020-04/decreto_presidente_della_giunta_regionale_n._47_-_20_aprile_2020.pdf
Posizione: 45.06776 7.68249 0 0
</yamldata></pre>

**Comment by cristigalas** [comment]
Scaduto.
