### ISSUE TITLE
Comitato Abitanti San Siro, Associazione Naga

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#258]
<pre><yamldata>
Cosa: Comitato Abitanti San Siro, Associazione Naga
Descrizione: Traduzione in 7 lingue decalogo del Ministero della Salute
Link: http://www.milanotoday.it/attualita/coronavirus/coronavirus-consigli-ministero-tradotti.html

</yamldata></pre>

**Comment by cristigalas** [comment]
Doppia. Chiudo.
