### ISSUE TITLE
DigiPass #Umbria, 26 aprile alle 18 webinar “Scuola digitale e software libero per la didattica a distanza”

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2581]
<pre><yamldata>
Da_chi_offerta: DigiPass Umbria
Descrizione: 'Domenica 26 aprile alle 18 evento online “Scuola digitale e software
  libero per la didattica a distanza” organizzato dai DigiPass della Regione Umbria
  (Assisi, Città di Castello, Foligno, Gubbio, Media Valle del Tevere, Narni, Orvieto,
  Perugia e Spoleto).
  Il webinar, in diretta streaming sul canale YouTube DigiPass Umbria (https://bit.ly/3eo0dZ7) e sulle pagine facebook dei DigiPass regionali, è un’occasione per raccontare
  esperienze e buone pratiche di OpenDidattica e spiegare come attivare e organizzare
  videolezioni a distanza tra docenti e studenti con Jitsi, piattaforma online e open
  source, gratuita, sicura e funzionale, che non richiede nessuna iscrizione o creazione
  di account senza bisogno di registrarsi e quindi lasciare i propri dati.
  Intervengono Sonia Montegiove del Digital Transformation Institute, Leopolda Mondi,
  docente e animatore digitale del Primo Circolo di Marsciano, e Giorgio Pezzanera,
  facilitatore del Digipass Media Valle del Tevere.'
Destinatari: docenti e studenti
Link: https://digipass.regione.umbria.it/scuola-digitale-26-aprile-diretta-online-su-didattica-a-distanza-e-software-libero/
Natura: didattica
Posizione: 43.11179 12.389343 0 0
Titolo: 'Scuola digitale: lezioni online con Jitsi'
</yamldata></pre>

**Comment by chiccap** [comment]
Scaduta.
