### ISSUE TITLE
Rilascio STP/ENI - #Sanimapp #Roma

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#2582]
<pre><yamldata>Fonte: "GRIS - Gruppi immigrazione e Salute della Societ\xE0 Italiana di Medicina"
Indirizzo: Roma, Lungotevere della Vittoria, 3
Orari: "dal luned\xEC al gioved\xEC 8.30-17.00 venerd\xEC 8.30-13.00 sabato 7.45-12.00"
Posizione: 41.9213903306825 12.4656946650698 0 0
Telefono: 06-68353113 / 3127
</yamldata></pre>

**Comment by cristigalas** [comment]
Segnalo a chi non sta seguendo questo lavoro che si tratta di una segnalazione di prova...

**Comment by mfortini** [comment]
Chiuso issue di prova
