### ISSUE TITLE
GEA è una cooperativa sociale senza scopo di lucro, fondata a Padova nel 2004. La cooperativa ha ha 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2585]
<pre><yamldata>
Da_chi_offerta: Gea Cooperativa Sociale
Descrizione: 'GEA è una cooperativa sociale senza scopo di lucro, fondata a Padova
  nel 2004. La cooperativa ha ha sviluppato una solida esperienza nei servizi per
  l''inclusione e la cittadinanza attiva di gruppi vulnerabili nello specifico di
  comunità, famiglie, persone migranti, lavorando in particolare con donne, giovani
  e bambini. GEA ha sviluppato diverse esperienze e competenze nel campo dell''integrazione
  e dell''educazione interculturale, offrendo

  diversi servizi come la Mediazione Culturale e Linguistica, la consulenza interculturale,
  i progetti sviluppo e gestione, supporto e consulenza di associazioni e gruppi di
  migranti in i loro rapporti con le istituzioni, i servizi territoriali pubblici
  e privati.'
Destinatari: Persone, Famiglie e Comunità vulnerabili e migranti.
Link: http://www.geacoop.org/it/home/
Natura: solidale
Posizione: 45.420851 11.885793 0 0
Tipo_di_soggetto: privato
Titolo: Cooperativa
</yamldata></pre>

**Comment by cristigalas** [comment]
Segnalazione generica. Non si menziona nessun servizio o rimodulazione attività per l’emergenza. Nessuna notizia nemmeno sul sito. Non accettiamo.
