### ISSUE TITLE
Regione #Lombardia: dal 4 al 12 maggio bando per contributi e-learning e mutuo prima casa a sostegno delle famiglie in difficoltà

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2587]
<pre><yamldata>
Cosa: 'Regione Lombardia: dal 4 maggio bando e-learning studenti e mutui'
Descrizione: 'Contributi straordinari regionali a sostegno delle famiglie in temporanea
  difficoltà a causa delle molteplici situazioni di disagio sociale generate dall’epidemia
  di Coronavirus.
   È stato pubblicato martedì 21 aprile sul Burl (Bollettino Ufficiale Regione Lombardia)
  l’Avviso del bando per accedervi. A partire dal 4 maggio le famiglie lombarde potranno,
  tramite l’applicativo bandi on line (www.bandi.servizirl.it), essere assegnatarie
  degli interventi straordinari stabiliti dalla delibera della Giunta regionale che
  prevede la concessione di due tipologie di contributi, non cumulabili tra loro:
  un contributo per il mutuo prima casa e un contributo per l’e-learning di sostegno
  allo studio (a esempio acquisto computer e tablet).
Le domande potranno essere presentate dalle ore 12 del 4 maggio alle ore 12 dell’11
  maggio attraverso SPID, CNS o registrazione con nome utente e password.
Contributo mutuo prima casa. Nel primo caso si tratta di un contributo straordinario una tantum pari a 500 euro
  per ogni nucleo familiare con almeno un figlio di età minore o uguale a 16 anni.
  L’agevolazione è concessa a fondo perduto e prevede la trasmissione, insieme alla
  domanda di contributo, della quietanza di pagamento di una rata del mutuo relativa
  all’anno 2020.
  Contributo e-learning studenti. Nel secondo caso l’agevolazione concessa fino a 500 euro a fondo perduto per ogni
  nucleo familiare con un figlio compreso tra i 6 e i 16 anni e prevede la trasmissione,
  insieme alla domanda di contributo, della fattura o ricevuta fiscale da cui si evinca
  la tipologia di bene acquistato, avvenuto in data successiva all’ordinanza del 23
  febbraio 2020 del Ministro della Salute d’intesa con il presidente della Regione
  Attilio Fontana che dispone in Lombardia la chiusura dei nidi, dei servizi educativi
  all’infanzia e delle scuole di ogni ordine e grado.
  I destinatari della misura sono i nuclei familiari nei quali almeno uno dei componenti
  sia residente in Lombardia e, a seguito dell’emergenza Covid-19, si trovi in una
  delle seguenti condizioni: lavoratore dipendente (con rapporto di lavoro subordinato,
  parasubordinato, di rappresentanza commerciale o di agenzia), con riduzione della
  retribuzione lorda mensile pari o superiore al 20%; libero professionista o autonomo
  con riduzione del proprio fatturato (in un trimestre successivo al 21 febbraio 2020)
  superiore al 33% del fatturato dell’ultimo trimestre 2019, in conseguenza della
  chiusura o della restrizione della propria attività a seguito delle disposizioni
  per il contenimento del Covid-19; morte di un componente del nucleo familiare.
Devono inoltre essere rispettati i seguenti requisiti: almeno un figlio di età inferiore
  o uguale a 16 anni di eta’, per il contributo mutui prima casa; e almeno un figlio
  di eta’ compresa tra i 6 e i 16 anni di eta’ all’atto di presentazione della domanda
  per il contributo e-learning; un Isee minore o uguale a 30.000 euro.'
Link: https://www.lombardianotizie.online/aiuti-e-learning-studenti-e-mutui/?fbclid=IwAR23VHb4nUkqE0MU_dQXv106s7CJ2R7XUe_MdGfBcR8IqWwDCd4YvJzs0V0
Posizione: 45.486613 9.196157 0 0
</yamldata></pre>

**Comment by cristigalas** [comment]
Scaduto.
