### ISSUE TITLE
Distribuzione beni di prima necessità, informativa COVID, informativa su misure di sostegno relative

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2597]
<pre><yamldata>
Da_chi_offerta: Solidal Help
Descrizione: Distribuzione beni di prima necessità, informativa COVID, informativa
  su misure di sostegno relative all'emergenza COVID, Accompagnamenti sanitari.
Destinatari: lavoratori e lavoratrici presenti in aree ad alto rischio di sfruttamento
Natura: solidale
Tipo_di_soggetto: privato
Titolo: Solidal Help
</yamldata></pre>

**Comment by PaolaLiliana** [comment]
Informativa lacunosa. Ho provato anche a cercare in rete il soggetto proponente ma non ho trovato alcun riscontro.
