### ISSUE TITLE
Fondo Emergenza promosso a #LAquila da 3e32 e United L'Aquila

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2604]
<pre><yamldata>
Descrizione: 'In queste settimane di emergenza alcune persone hanno una forte difficoltà
  ad affrontare le spese ordinarie che prima dell’emergenza avrebbero sostenuto.
  Per questo vi chiediamo un aiuto concreto che potrà aiutare a pagare bollette,
  affitti o altri bisogni necessari. Il mutuo aiuto è un valore che non dobbiamo mai
  perdere, soprattutto in questo momento. Aiutiamo chi è in difficoltà per aiutarci
  tutti vicendevolmente, attraverso la solidarietà.
  Potete donare tramite PayPal all’Associazione di Promozione Sociale 3e32 paypal.me/3e32
  o tramite bonifico all’Associazione Sportiva Dilettantistica United L’Aquila IBAN:
  IT40Q0832703601000000005000 Causale: donazione per emergenza Covid-19'
Link: http://www.3e32.org/?page_id=9660&fbclid=IwAR3bP_3UB3hgvqDOSn7EVswt0hrcIJKTjE3v5v8phIWY5ApLH8dahYrsOeY
Nome: Associazione di Promozione Sociale 3e32 L'Aquila
Posizione: 42.353394 13.401441 0 0
</yamldata></pre>

**Comment by michelerestuccia** [comment]
La stessa raccolta fondi è presente nella issue #1427, rimuoverei questa perchè è  più recente e quindi potrebbe essere girata di meno su bollettino. 
@cristigalas @chiccap

**Comment by cristigalas** [comment]
@michelerestuccia basta chiuderla, senza rimuovere label Accettata. Così comunque rimane visibile.
