### ISSUE TITLE
Bambini ... anche adesso che siamo a casa, facciamo bella la terra!

I nonni han curato per noi l'in

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2612]
<pre><yamldata>
Da_chi_offerta: Istituto Comprensivo "Federico Sacco"
Descrizione: "Bambini ... anche adesso che siamo a casa, facciamo bella la terra!\n\
  \nI nonni han curato per noi l'insalata e le fragole dell'orto. I fiori che abbiamo\
  \ piantato ed annaffiato sono in fiore! Dai cartelloni pensati dai bambini  grandi,\
  \ tutti abbiamo imparato a fare azioni per aiutare la terra. \n\nSono azioni  importantissime.\
  \ Se riusciamo a farle anche ora che siamo a casa, il nostro pianeta sarà più bello!\n\
  \nIl filmato fa parte di una più ampia raccolta di proposte per la didattica a distanza\
  \  - nella Scuola dell'Infanzia, Scuola Elementare e Media - - dell' Istituto Comprensivo\n\
  \nhttp://www.icsacco.it/didattica-a-distanza.html"
Destinatari: Scuola dell'Infanzia
Link: https://drive.google.com/drive/folders/1MU4gPa99AYIv1J2XnYclo20QWb50fKpd
Natura: didattica
Posizione: 44.553393 7.725749 0 0
Titolo: A casa insieme nella Giornata per la Terra
</yamldata></pre>

**Comment by FrancescaZambi89** [comment]
segnalazione già inserita tramite #issue #2611 
chiuso e non accetto
