### ISSUE TITLE
Webinar per genitori e insegnanti 'Didattica a distanza, videoconferenze e privacy' sabato 25 aprile ore 10:00

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2613]
<pre><yamldata>
Da_chi_offerta: Continuity srl
Descrizione: "Questo sabato 25 aprile 2020 ore 10:00 webinar on-line per comprendere meglio la gestione della privacy nelle
  piattaforme web proposte alle scuole, analizzando esempi concreti nel territorio
  nazionale.
  La presentazione è rivolta a genitori, insegnanti e dirigenti scolastici e a tutti coloro che
  si sono messi in gioco per portare un po’ di chiarezza sul tema della didattica
  a distanza.
  Per partecipare come pubblico e poter intervenire e fare domande è necessario iscriversi,
  gratuitamente."
Destinatari: genitori, insegnanti e dirigenti scolastici
Link: https://scuolalibera.continuity.space/event/didattica-a-distanza-videoconferenze-e-privacy-2020-04-25-2/page/introduction-didattica-a-distanza-videoconferenze-e-privacy
regione_manuale: tutte
Natura: didattica
Titolo: Didattica a distanza, videoconferenze e privacy
</yamldata></pre>

**Comment by cristigalas** [comment]
Mancavano le virgolette ad inizio e fine descrizione, le ho aggiunte. Però questa segnalazione era un lavoro di prova di @michelerestuccia. Lasciamola finire a lui.

**Comment by favoeva** [comment]
segnalazione scaduta . il webinar si è tenuto ieri. Chiudo.
