### ISSUE TITLE
#panoramidilibertà, una testimonianza di libertà dal balcone di casa per il 25 aprile 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2624]
<pre><yamldata>
Da_chi_offerta: Cinevan, Radio Popolare, La scheggia associazione culturale, Alma
  Rosé, Arci Milano, Shareradio, Il Cinemino, Perimetro, Cooperativa Dar Casa, Il
  festival delle periferie a Milano, Dike Sociale - Segnali dal territorio e Campsirago
  Residenza
Descrizione: 'Il 25 aprile 2020 la porta delle nostre case resterà chiusa.
  Una data così importante dovrà essere celebrata all’insegna dell’isolamento sociale.
  Se possiedi un videoproiettore o un vecchio proiettore per diapositive, spolveralo
  e appoggialo sul davanzale della tua finestra.
  Scegli una foto, scene di un film, visioni di paesaggi o immagini capaci di raccontare
  cosa è per te oggi la Liberazione e proiettale sul muro dei tuoi vicini.'
Destinatari: tutte e tutti
Link: https://www.facebook.com/events/2837968476317134/
Natura: culturale-ricr
Posizione: 45.464949 9.186557 0 0
Titolo: Panorami di Libertà
</yamldata></pre>

**Comment by chiccap** [comment]
scaduta.
