### ISSUE TITLE
Donazione di igienizzante mani

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#265]
<pre><yamldata>
Da_chi_offerta: Asb Azienda Speciale Buccinasco
Descrizione: In omaggio ai clienti una confezione da 50 ml di igienizzante mani preparato
  in farmacia.
Destinatari: Clienti dell'azienda
Link: https://giornaledeinavigli.it/cronaca/nellemergenza-coronavirus-storie-di-generosita-e-solidarieta/
Natura: solidale
Tipo_di_soggetto: privato
Titolo: Donazione di igienizzante mani

</yamldata></pre>

**Comment by cristigalas** [comment]
Doppia.
