### ISSUE TITLE
Informazioni tradotte per persone migranti

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#268]
<pre><yamldata>
Cosa: Informazioni tradotte per persone migranti
Descrizione: Testi e video con le informazioni basilari sul coronavirus e le nuove
  disposizioni in 23 lingue
Fonte: "Associazione di volontariato Il Grande Colibr\xEC"
Link: https://www.ilgrandecolibri.com/coronavirus-spiegato-migranti-asilanti/#por

</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Segnalazioen già presente #122
