### ISSUE TITLE
Arriviamo energie positive! Webinar gratuiti dedicati all'innovazione sociale

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#275]
<pre><yamldata>
Da_chi_offerta: Produzioni Dal Basso
Descrizione: "Con il coinvolgimento di alcuni tra i migliori professionisti del mondo\
  \ del digitale, della consulenza, del fundraising, dell\u2019innovazione sociale,\
  \ un ciclo di webinar completamente gratuiti, aperti a tutti ma pensati soprattutto\
  \ per chi opera nel non profit. Un\u2019opportunit\xE0 di crescita e di condivisione,\
  \ per non arrendersi al clima di emergenza, per generare un\u2019occasione di confronto,\
  \ conoscere nuovi strumenti, progettare nuove strategie."
Destinatari: tutti
Link: https://www.attiviamoenergiepositive.it/
Natura: didattica
Titolo: Arriviamo energie positive! Weimar gratuito dedicati all'innovazione sociale

</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Già inserita in #824
