### ISSUE TITLE
Una serra ipertecnologica ed ecosostenibile, frutto di un brevetto “made in Umbria”, in grado di acc

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2807]
<pre><yamldata>
Da_chi_offerta: DigiPass Umbria
Descrizione: 'Una serra ipertecnologica ed ecosostenibile, frutto di un brevetto “made
  in Umbria”, in grado di accelerare fino a 3 o 4 volte la crescita di piante, ortaggi
  e verdure.

  È il cuore dell’innovativo progetto “Serranova”, già in funzione all’Istituto Agrario
  di Todi, che giovedi 30 aprile alle ore 18 sarà al centro dell’evento online organizzato
  dal DigiPass Marsciano in collaborazione con i DigiPass dell''Umbria, la rete regionale
  che comprende Assisi, Città di Castello, Foligno, Gubbio, Media Valle del Tevere,
  Narni, Orvieto, Perugia e Spoleto.

  Il webinar, fruibile in diretta streaming sul canale YouTube DigiPass Umbria ( https://bit.ly/3eo0dZ7
  ) e sulle pagine facebook dei DigiPass regionali, è un’occasione per raccontare
  caratteristiche e funzionalità della serra “magica”, il cui prototipo è stato recentemente
  premiato come miglior startup del settore green in Italia alla 70esima edizione
  del salone internazionale del florovivaismo di Padova, e per approfondire aspetti
  legati all’utilizzo di risorse e strumenti digitali per l’agricoltura.

  Il progetto, rispetto al quale il “Ciuffelli” è apripista a livello nazionale, sarà
  illustrato durante il confronto live da Stefano Chiocchini, architetto e designer,
  inventore di “Serranova”, Gilberto Santucci, giornalista e coordinatore dell’azienda
  dell’Istituto Agrario di Todi, e da Giorgio Pezzanera, facilitatore del DigiPass
  Media Valle del Tevere.'
Destinatari: ricercatori architetti designer imprese agricole startup
Link: https://digipass.regione.umbria.it/
Natura: didattica
Titolo: 'Serranova: 30 aprile webinar sulla serra tecnologica ed ecosostenibile'
</yamldata></pre>

**Comment by favoeva** [comment]
Non è una segnalazione attinente all’obiettivo del progetto covid19italia.help
