### ISSUE TITLE
Associazione Maria Bianchi offre supporto per i bambini  in lutto a causa del covid19

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2810]
<pre><yamldata>
Da_chi_offerta: Associazione Maria Bianchi
Descrizione: 'La nostra riflessione, a cura di Marcella Oliva (operatrice dell’Unità
  Di Crisi Scolastica) per sostenere i bambini che in questo periodo hanno perso un
  famigliare, un parente o un amico per il Coronavirus: una serie di indicazioni,
  suggerimenti e azioni concrete.

  Il testo in allegato è disponibile anche nella pagina Facebook dell’Associazione
  e nella home-page del nostro sito (www.mariabianchi.it).

  ---

  Nicola Ferrari

  supporto alle persone in lutto, formatore, autore

  348 - 3623379

  mariabianchi.it'
Destinatari: famiglie/tutori
Link: https://www.facebook.com/notes/associazione-maria-bianchi/i-bambini-in-lutto-al-tempo-del-coronavirus-cosa-fare/3155083891171498/
Natura: solidale
Posizione: 45.190839 10.936418 0 0
Tipo_di_soggetto: privato
Titolo: I bambini in lutto al tempo del coronavirus
regione_manuale: tutte
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente, vedi https://covid19italia.help/issues/2605
