### ISSUE TITLE
Progetto #OpenSpace: a #Bari, #Palermo, #ReggioCalabria e #Milano attività online per ragazzi/e 14-17 anni contro la dispersione scolastica

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2824]
<pre><yamldata>
Cosa: Attività on line per ragazze e ragazzi 14-17 anni contro la dispersione scolastica
Descrizione: "Il progetto OpenSpace non si ferma e prosegue anche on line durante\
  \ l’emergenza Covid 19 con l’attività Tifa per te!\nIl percorso è destinato a ragazze\
  \ e ragazzi dai 14 a 17 anni per prevenire e contrastare l’abbandono scolastico\
  \ e la dispersione e per costruire assieme a loro la propria strada. L’attività\
  \ si articolerà in:\n•\tpercorsi di case management per la costruzione di un progetto\
  \ personalizzato che parta dalla scoperta dei talenti del singolo, attraverso esperienze\
  \ innovative quali l’ideazione di un programma web-radio;\n•\tincontri di orientamento\
  \ per conoscere il mondo del lavoro e della formazione e gli strumenti relativi\
  \ alla ricerca attiva del lavoro;\n•\telaborazione finale del proprio progetto formativo-professionale\n\
  L’ attività è preliminarmente destinata a residenti nelle città del progetto OpenSpace\
  \ (Milano, Bari, Palermo e Reggio Calabria) e successivamente aperta ad altre richieste\
  \ fino ad esaurimento posti disponibili.\nPer info: cell. 3283982106; mail: francesca.altomonte@actionaid.org"
Destinatari: Ragazze e ragazzi da 14 a 17 anni principalmente residenti a Milano,
  Bari, Palermo e Reggio Calabria e poi di altre città, fino ad esaurimento disponibilità.
Email: eleonora.scrivo@actionaid.org
Immagine: Tifa per Te...da casa!-9_46_52.docx
Posizione: 38.10354 15.63976 0 0
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 44.89912921 8.20414255 (Asti) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=44.89912921+8.20414255&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by SimonettaAA** [comment]
Non accetto perchè ce ne è una più completa la #2827
