### ISSUE TITLE
Fondazione #AIRC: è possibile ordinare online l'Azalea della Ricerca per finanziare la lotta contro il cancro

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2825]
<pre><yamldata>
Cosa: L'Azalea della Ricerca di Fondazione AIRC
Descrizione: Per la prima volta in trentasei anni il simbolo della lotta contro il
  cancro non sarà distribuita in piazza dai volontari ma si potrà ordinare su Amazon.it
  a fronte di una donazione di 15 euro per riceverla direttamente a casa grazie al
  contributo di Banco BPM.
Link: http://www.airc.it/
regione_manuale: tutte
</yamldata></pre>

**Comment by cristigalas** [comment]
Questa non è una notizia utile... e comunque non so se l’avrei accettata. Non ha a che fare con l’emergenza... @chiccap che dici? Comunque ormai è andata nel bollettino...

**Comment by chiccap** [comment]
Sì sono d’accordo possiamo chiuderla?

**Comment by cristigalas** [comment]
> Sì sono d’accordo possiamo chiuderla?

Aspetterei a chiudere, è andata in Bollettino. Ho messo Milestone al 2 maggio, così ci ricordiamo di chiuderla.
