### ISSUE TITLE
Cura Italia è un sito web che ha lo scopo di seguire l’andamento del Coronavirus in Italia, mostrand

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2830]
<pre><yamldata>
Da_chi_offerta: Riccardo Borchi
Descrizione: 'Cura Italia è un sito web che ha lo scopo di seguire l’andamento del
  Coronavirus in Italia, mostrando la situazione in tempo reale (con dati provenienti
  da fonti ufficiali e sempre aggiornati, regione per regione, provincia per provincia)
  e raccogliendo informazioni, notizie, consigli e materiali utili, tutto attraverso
  un’unica piattaforma online, pratica e accessibile da tutti. Il sito web è consultabile
  su desktop, tablet o smartphone all’indirizzo www.curaitalia.it.

  Chiunque voglia collaborare al progetto o abbia semplicemente idee e suggerimenti
  da proporre, può scrivere all''indirizzo email info@curaitalia.it o tramite il modulo
  di contatto presente all’interno del sito web.

  www.curaitalia.it'
Destinatari: Tutti
Link: https://www.curaitalia.it/
Natura: solidale
Tipo_di_soggetto: privato
Titolo: Progetto CURA ITALIA
</yamldata></pre>

**Comment by RBWebDesign** [comment]
Grazie per la pubblicazione!

www.curaitalia.it
