### ISSUE TITLE
Il documento, realizzato da Inail in collaborazione con l’Istituto superiore di sanità e approvato d

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2831]
<pre><yamldata>
Cosa: Documento tecnico sull'ipotesi di rimodulazione delle misure contenitive in
  relazione al trasporto pubblico collettivo terrestre, nell’ottica della ripresa
  del pendolarismo, nel contesto dell’emergenza da SARS-CoV-2
Descrizione: 'Il documento, realizzato da Inail in collaborazione con l’Istituto superiore
  di sanità e approvato dal Comitato tecnico scientifico (Cts) istituito presso la
  Protezione Civile, contribuisce a fornire elementi tecnici di valutazione al decisore
  politico circa l’adozione di misure di sistema, organizzative e di prevenzione,
  nonché semplici regole per l’utenza per il contenimento della diffusione del contagio
  sui mezzi di trasporto pubblico collettivo terrestre.

  La pubblicazione contiene anche un’analisi di benchmark delle principali misure
  contenitive adottate per il settore dei trasporti terrestre a livello internazionale

  Prodotto: Volume

  Edizioni: Inail - 2020

  Disponibilità: Consultabile solo in rete'
Fonte: INAIL
Link: https://www.inail.it/cs/internet/comunicazione/pubblicazioni/catalogo-generale/pubbl-documento-tecnico-trasporto-pubblico-covid-2.html
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente
