### ISSUE TITLE
La guida, realizzata dall’Istituto superiore di sanità (ISS) in collaborazione con Inail e Centro di

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2832]
<pre><yamldata>
Cosa: Coronavirus - Guida pratica per chi si prende cura degli anziani
Descrizione: 'La guida, realizzata dall’Istituto superiore di sanità (ISS) in collaborazione
  con Inail e Centro di promozione e sviluppo dell''assistenza Geriatri (Cepsag),
  offre informazioni, con un linguaggio semplice e immediato, sulle modalità di trasmissione
  e sui sintomi del nuovo coronavirus, e fornisce indicazioni sui comportamenti da
  seguire, in casa e fuori, per proteggere la salute degli anziani e di chi li assiste.

  Il documento contiene anche le risposte alle domande più ricorrenti per dare supporto
  a chi assiste quotidianamente le persone più fragili. Sono riportati, inoltre, alcuni
  approfondimenti sull''utilizzo della mascherina, su come lavare correttamente le
  mani, su come usare i guanti monouso e consigli sull''igiene domestica. In chiusura,
  un elenco di numeri utili e siti web che è possibile chiamare e consultare per informazioni
  e in caso di emergenza.

  Già disponibile in italiano, inglese, spagnolo e francese e, a breve, anche in rumeno,
  polacco, russo, portoghese e tamil.

  Prodotto: Opuscolo

  Gruppo di lavoro congiunto Iss, Inail, Cepsag

  Disponibilità: Consultabile solo in rete'
Fonte: INAIL
Link: https://www.inail.it/cs/internet/docs/alg-guida-cura-anziani-covid-19.pdf
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
