### ISSUE TITLE
La pubblicazione, approvata dal Comitato Tecnico Scientifico istituito presso la Protezione Civile, 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2836]
<pre><yamldata>
Cosa: 'Coronavirus, fase 2: online il documento tecnico Inail con le misure di contenimento
  e prevenzione nei luoghi di lavoro'
Descrizione: "La pubblicazione, approvata dal Comitato Tecnico Scientifico istituito\
  \ presso la Protezione Civile, è disponibile sul portale dell’Istituto. Contiene\
  \ indicazioni mirate ad affrontare la graduale ripresa in sicurezza delle attività\
  \ produttive e a garantire adeguati livelli di tutela della salute per tutta la\
  \ popolazione\n\nEsposizione, prossimità, aggregazione: le variabili per classificare\
  \ il rischio. Tra queste iniziative, le misure di contenimento indicate nella pubblicazione.\
  \ Nella prima parte del documento è illustrata una metodologia innovativa di valutazione\
  \ integrata del rischio che tiene in considerazione il rischio di venire a contatto\
  \ con fonti di contagio in occasione di lavoro, di prossimità connessa ai processi\
  \ lavorativi, oltre all’impatto connesso al rischio di aggregazione sociale anche\
  \ verso “terzi”.\n \nMisure di protezione e lotta all’insorgenza di focolai epidemici.\
  \ La seconda parte contiene un focus sull’adozione di misure organizzative, di prevenzione\
  \ e protezione e di lotta all’insorgenza di focolai epidemici, anche in considerazione\
  \ di quanto già contenuto nel “Protocollo condiviso di regolamentazione delle misure\
  \ per il contrasto e il contenimento della diffusione del virus Covid-19 negli ambienti\
  \ di lavoro” stipulato tra Governo e Parti sociali il 14 marzo 2020."
Fonte: INAIL
Link: https://www.inail.it/cs/internet/docs/alg-documento-tecnico-coronavirus-fase-2.pdf
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
