### ISSUE TITLE
“Cronache dal futuro”, iniziativa online di Lucha y Siesta per dar voce ai giovani tra i 14 e i 19 anni. Partecipa entro il 25 maggio

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2838]
<pre><yamldata>
Da_chi_offerta: Lucha y Siesta
Descrizione: "Hai tra i 14 e i 19 anni? Vogliamo darti voce\n\nInvia entro mezzogiorno\
  \ del 25 maggio un video, una foto, un audio, un testo. Puoi creare una poesia,\
  \ un racconto, un disegno, una performance, una canzone o usare qualsiasi altro\
  \ mezzo espressivo tu voglia. \n\nLe  categorie sono due e puoi partecipare a una\
  \ o entrambe:\n\n***CRONACHE***\n\nCi interessa sapere di te. Raccontaci come stai\
  \ vivendo la quarantena, i tuoi spazi, ciò che ti fa arrabbiare, che ti mette paura\
  \ e ciò che ti fa sentire meglio. Hai un’isola felice? Quali sono i pensieri che\
  \ ti frullano nella testa? Noi li vogliamo sapere.\n\n***VISIONI***\n\nIl tuo mondo\
  \ dopo la pandemia. Ci sono cose che vorresti non tornassero come prima? Puoi immaginare\
  \ un mondo intero senza limiti di fantasia, come è fatto, chi lo abita, come si\
  \ regge, o concentrarti solo su un pezzettino, quello che ti appartiene. Tutto può\
  \ essere, tutto può accadere. Crediamo che ciò che può essere immaginato, può essere\
  \ realizzato."
Destinatari: giovani 14-19 anni
Link: https://luchaysiesta.wordpress.com/cronache-del-futuro/
Natura: culturale-ricr
Posizione: 41.903312 12.495483 0 0
Titolo: Cronache del Futuro
</yamldata></pre>

**Comment by gloriaschiavi** [comment]
milestone passata, chiusa issue
