### ISSUE TITLE
Sezione Gazzetta Ufficiale con ordinanze coronavirus

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#285]
<pre><yamldata>
Cosa: Sezione Gazzetta Ufficiale con ordinanze coronavirus
Descrizione: 'Tutte le ordinanze aggiornate suddivise per: Governo, Dipartimento Protezione
  Civile, Ministero della Salute, Ministero delle Finanze.'
Fonte: Gazzetta Ufficiale
Link: https://www.gazzettaufficiale.it/dettaglioArea/12
meta/deprecatedID: uuid:cab55eaf-c536-41f6-a3c9-27c225ccb278

</yamldata></pre>

**Comment by cristigalas** [comment]
Doppia. Chiudo.
