### ISSUE TITLE
DIG The Lockdown Tapes, online documentari e inchieste dei DIG Awards fino al 3 maggio

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2851]
<pre><yamldata>
Da_chi_offerta: DIG documentari, inchieste, giornalismi
Descrizione: 'DIG The Lockdown Tapes è la rassegna online di documentari giornalistici
  che riunisce i migliori lavori premiati da DIG Awards negli ultimi anni: 12 inchieste
  video che hanno esposto le distorsioni causate da violenza e corruzione, raccontando
  le disuguaglianze e denunciando abusi di potere in tutto il mondo.

  DIG: The Lockdown Tapes è un modo per continuare la nostra missione in favore del
  giornalismo di inchiesta. I documentari resteranno a disposizione gratuitamente
  fino al prossimo 3 maggio incluso. In tempi bui come quelli che stiamo vivendo,
  siamo convinti che il coraggio del giornalismo investigativo sia più necessario
  che mai per continuare a fare luce sui punti oscuri che si celano dietro ogni storia.
  Per ricordarci di non dimenticare.'
Destinatari: tutti
Link: https://dig-awards.org/the-lockdown-tapes/
Natura: culturale-ricr
Titolo: 'DIG : The Lockdown Tapes, online i documentari dei DIG Awards'
Posizione: 43.99827 12.64744
regione_manuale: tutte
</yamldata></pre>

**Comment by gloriaschiavi** [comment]
Segnalazione scaduta il 3 maggio
