### ISSUE TITLE
Arera proroga al 17 maggio blocco ai distacchi elettricità, gas e acqua

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2861]
<pre><yamldata>
Cosa: '#Arera: per i clienti domestici prorogato fino al 17 maggio il blocco ai distacchi
  elettricità, gas e acqua'
Descrizione: ARERA proroga al 17 maggio - per i soli clienti domestici - i provvedimenti
  con i quali aveva già stabilito il blocco delle procedure di sospensione delle forniture
  di energia elettrica, gas e acqua.
Fonte: Autorità Energia
Link: https://www.arera.it/it/com_stampa/20/200430.htm
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
