### ISSUE TITLE
Quattro partners da quattro paesi - Estonia, Bulgaria, Italia, Portogallo - per un progetto ERASMUS+

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2880]
<pre><yamldata>
Da_chi_offerta: Associazione Promozione Sociale “Futuro Digitale”
Descrizione: "Quattro partners da quattro paesi - Estonia, Bulgaria, Italia, Portogallo\
  \ - per un progetto ERASMUS+ \n\nIl progetto nasce da una domanda che se ne porta\
  \ appresso una seconda. \n\nCome usare metodiche digitali per diffondere modalità\
  \ innovative ed inclusive per insegnare ed imparare? per migliorare l'occupabilità\
  \ di persone già adulte?\n\nTra i risultati del progetto una guida in lingua Italiana:\
  \ https://epale.ec.europa.eu/sites/default/files/ds4a_digital_guide_italian.pdf\n\
  \nda qui entri invece nel Sito del Progetto: https://ds4a.eu/"
Destinatari: educatori degli adulti
Link: https://epale.ec.europa.eu/sites/default/files/ds4a_digital_guide_italian.pdf
Natura: sostegno-lavor
Posizione: 39.655682 16.342378 0 0
Titolo: DS4A [Digital Skills 4 All]- La Guida Digitale in lingua Italiana
</yamldata></pre>

**Comment by cristigalas** [comment]
Non accetterei, non mi pare abbia che fare con emergenza covid19. @chiccap @favoeva che ne pensate?

**Comment by favoeva** [comment]
> Non accetterei, non mi pare abbia che fare con emergenza covid19. @chiccap @favoeva che ne pensate?

Sì, Sono d’accordo,si tratta di sostegno contro dispersione scolastica
