### ISSUE TITLE
Da un progetto ERASMUS+ - Italia, Francia, Belgio, Austria, Spagna - ormai completo, 

ecco una racc

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2881]
<pre><yamldata>
Da_chi_offerta: REPLAY Network associazione di promozione sociale
Descrizione: "Da un progetto ERASMUS+ - Italia, Francia, Belgio, Austria, Spagna -\
  \ ormai completo, \n\necco una raccolta di strumenti specializzati, sviluppati per\
  \ una pluralità di scopi e finalizzati a prevenire e a lottare contro l'abbandono\
  \ scolastico. La raccolta fornisce orientamento e guida per realizzare azioni, sia\
  \ all'interno che all'esterno dell'ambiente scolastico, e per progettare nuove soluzioni\
  \ rivolte sia a giovani che abbiano abbandonato precocemente la scuola a quanti\
  \ rischiano di abbandonarla.\n\nLa raccolta di strumenti in lingua italiana: http://www.replaynet.eu/it/mystorymap\n\
  \nSito del progetto My Story Map: https://www.mystorymap.eu/"
Destinatari: Dirigenti scolastici, Insegnanti, Educatori
Link: http://www.replaynet.eu/it/mystorymap
Posizione: 41.829819 12.520659 0 0
Titolo: My Story Map - Come attrezzarci per allontanare i rischi di abbandono scolastico
</yamldata></pre>

**Comment by cristigalas** [comment]
Non pertinente.
