### ISSUE TITLE
Informatici Senza Frontiere offre supporto alla didattica online per l'utilizzo delle principali piattaforme

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2890]
<pre><yamldata>
Da_chi_offerta: Informatici Senza Frontiere
Descrizione: 'Offriamo un servizio di supporto alla didattica online rivolto a docenti,
  famiglie e ragazzi, con l’obiettivo di guidare all’utilizzo delle piattaforme più
  in uso.

  Grazie alla disponibilità di alcuni soci volontari, abbiamo attivato uno sportello
  a cui ci si può rivolgere per avere supporto per l''uso delle più comuni piattaforme,
  come, ad es., Zoom, Google Suite, GoToMeeting ed altre.

  Per avere supporto su queste piattaforme, puoi scrivere direttamente le tue domande
  e i tuoi dubbi a: didattica.helpme@informaticisenzafrontiere.org

  Con il progetto diamo supporto anche su alcune piattaforme open source. Se stai
  usando Meet di Jitsi e vuoi rivolgerti al nostro sportello di supporto, scrivici
  a: jitsi.helpme@informaticisenzafrontiere.org

  Per la piattaforma Moodle, anch’essa open source, puoi chiederci supporto scrivendo
  a: moodle.helpme@informaticisenzafrontiere.org

  Il servizio è gratuito e aperto a tutti.'
Destinatari: Docenti, famiglie e studenti
Link: https://www.informaticisenzafrontiere.org/progetti/supporto-alla-didattica-online/
Natura: didattica
Titolo: Supporto alla didattica online
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente https://covid19italia.help/issues/2412
