### ISSUE TITLE
Informatici Senza Frontiere: 10 videolezioni gratuite di Scratch disponibili sul canale YouTube

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2894]
<pre><yamldata>
Da_chi_offerta: Informatici Senza Frontiere
Descrizione: 'Sul canale YouTube di Informatici Senza Frontiere, sono disponibili
  per tutti 10 videolezioni gratuite di Scratch: in ciascuna lezione, spieghiamo come
  prendere confidenza con il linguaggo Scratch, sviluppato dal MIT di Boston, come
  creare scene e animazioni.

  Il coding attraverso Scratch è uno strumento oggi fondamentale per imparare competenze
  che possono tornare utili in tutte le materie che si studiano.'
Destinatari: Bambini, ragazzi e docenti
Link: https://www.informaticisenzafrontiere.org/progetti/videolezioni-di-scratch/
Natura: didattica
Titolo: Videolezioni di coding con Scratch
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente https://covid19italia.help/issues/2413
