### ISSUE TITLE
Una raccolta di strumenti specializzati, sviluppati per una pluralità di scopi e finalizzati a preve

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2898]
<pre><yamldata>
Da_chi_offerta: REPLAY Network associazione di promozione sociale
Descrizione: 'Una raccolta di strumenti specializzati, sviluppati per una pluralità
  di scopi e finalizzati a prevenire e a lottare contro l''abbandono scolastico. La
  raccolta fornisce orientamento e guida per realizzare azioni, sia all''interno che
  all''esterno dell''ambiente scolastico, e per progettare nuove soluzioni rivolte
  sia a giovani che abbiano abbandonato precocemente la scuola a quanti rischiano
  di abbandonarla.

  Da un progetto ERASMUS+ - Italia, Francia, Belgio, Austria, Spagna - ormai completo.

  La raccolta di strumenti in lingua italiana: http://www.replaynet.eu/it/mystorymap

  Sito del progetto My Story Map: https://www.mystorymap.eu/'
Destinatari: Dirigenti scolastici, Insegnanti, Educatori
Link: http://www.replaynet.eu/it/mystorymap
Natura: didattica
Posizione: 41.829889 12.520691 0 0
Titolo: My Story Map - Per ripartire. Tempo di attrezzarci per allontanare il rischio
  di abbandono scolastico
</yamldata></pre>

**Comment by cristigalas** [comment]
Non pertinente.
