### ISSUE TITLE
ARCI con il supporto di UNHCR lancia piattaforma con informazioni su Covid-19 tradotte in diverse lingue

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2919]
<pre><yamldata>
Da_chi_offerta: ARCI con UNHCR
Descrizione: 'ARCI con il supporto dell’UNHCR ha lanciato sul portale Jumamap una
  piattaforma interattiva sul coronavirus dove vengono pubblicate notizie tradotte
  in diverse lingue.
Le traduzioni sono state eseguite da volontarie e volontari della Associazione Naga
  – Milano, Arci Milano e dalla rete dei mediatori del Numero Verde per richiedenti
  asilo e rifugiati ARCI'
Destinatari: Migranti, rifugiati
Link: https://coronavirus.jumamap.com/it_it/
Titolo: La piattaforma offre informazioni e notizie sul coronavirus tradotte in diverse
  lingue.
regione_manuale: tutte
</yamldata></pre>

**Comment by cristigalas** [comment]
@michelerestuccia questa segnalazione c’era già in due diversi format :( comunque semmai tra qualche giorno aggiorniamo le altre due segnalazioni se ci sono info mancanti e chiudiamo questa... non lo facciamo ora perché è andata al bollettino. Sei d’accordo @chiccap?

**Comment by chiccap** [comment]
Sì aspettiamo se qualcuno dovesse cliccare sul link in questi giorni poi decidiamo quale chiudere!

**Comment by cristigalas** [comment]
Doppio.
