### ISSUE TITLE
Raccolta fondi della Fondazione Domus de Luna di #Cagliari a sostegno di mamme e ragazzi in difficoltà

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2921]
<pre><yamldata>
BIC_SWIFT: BPMOIT22
CC_Postale: 000070473835
Causale: EMERGENZA COVID 19
Descrizione: "RACCOLTA FONDI PER I BAMBINI, I RAGAZZI E LE MAMME DI DOMUS DE LUNA\n\
  \nPerché si possa presto sorridere di nuovo insieme, vogliamo sostenere:\n\nI Buoni\
  \ e Cattivi, per salvaguardare il lavoro di quasi 50 tra ragazzi e mamme in situazione\
  \ di svantaggio attraverso l’avvio di attività nuove, garantendo il proseguo del\
  \ loro impegno  all'interno della Locanda e del Circolo, dove hanno trovato formazione\
  \ e riscatto.\n\nIl Centro Exmè che si sta dedicando alle famiglie delle periferie\
  \ di Cagliari in condizioni di povertà. In particolare con il sostegno alla spesa,\
  \ garantendo al momento 1200 persone con una dotazione  minima settimanale di alimenti,\
  \ distribuiti al Centro o direttamente a casa. \n\nLe 4 Comunità per mamme, bambini\
  \ in condizione di estrema  fragilità,  per  settimane costretti in casa, che stanno\
  \ riorganizzando il supporto educativo e pedagogico di questi mesi difficili.\n\n\
  La Fondazione Domus de Luna opera in Sardegna, in modo rilevante nella zona della\
  \ Città Metropolitana di Cagliari.\nCon Casa delle Stelle gestisce 4 comunità di\
  \ accoglienza per bambini, ragazzi, mamme con i loro figli. Tutti affidati ai nostri\
  \ educatori professionali dal Tribunale per incuria, maltrattamento, situazioni\
  \ di grave difficoltà famigliare. Con Exmè & Affini gestisce un ex mercato civico\
  \ nella periferia di Cagliari, baricentro della gran parte degli interventi di prevenzione,\
  \ in raccordo con le scuole: l’Exmè. Con  la Cooperativa dei Buoni e Cattivi, formazione\
  \ e lavoro per ragazzi che hanno vissuto fuori famiglia, donne vittime di violenza,\
  \ giovani rifugiati e con disabilità o misure penali a carico. 2 ristoranti, bar,\
  \ pizzeria, camere e appartamenti, con oltre l’80% del personale impiegato che proviene\
  \ da situazioni di grande fragilità."
Email: amministrazione@domusdeluna.it
IBAN: IT35U0101504801000070473835
Intestazione: Fondazione Domus de Luna via Francesco Coco 2 Cagliari 09127
Link: https://www.domusdeluna.it/index.php
Nome: Fondazione Domus de Luna
Posizione: 39.252312 9.125572 0 0
</yamldata></pre>

**Comment by michelerestuccia** [comment]
La raccolta fondi è terminata come si legge in https://www.facebook.com/donate/2672729496332300/
