### ISSUE TITLE
Il Centro Psychè adotta un approccio integrale alla persona che unisce la dimensione specificamente 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2928]
<pre><yamldata>
Da_chi_offerta: Medu - Medici per i diritti umani
Descrizione: 'Il Centro Psychè adotta un approccio integrale alla persona che unisce
  la dimensione specificamente clinica (attraverso la terapia medica, la psicoterapia
  cognitivo-comportamentale culturalmente adattata e tecniche specifiche sulla rielaborazione
  delle memorie traumatiche basate essenzialmente sulla narrazione e la testimonianza)
  con quella psico-sociale (sia con attività di informazione-orientamento sia con
  laboratori di musica e teatro) volta alla piena integrazione del paziente nella
  società che lo accoglie.

  Gli interventi nel centro Medu Psyché prevedono la presenza di un team multidisciplinare
  composto da:

  • medici,

  • psicoterapeuti,

  • psicologi,

  • mediatori culturali

  • e operatori psico-sociali'
Destinatari: gli uomini e le donne, indipendentemente dallo status giuridico e da
  qualsivoglia distinzione, che hanno subito tortura o trattamenti inumani e degradanti
  (CIDT)
Link: https://mediciperidirittiumani.org/medu-psyche-centro-di-cura-e-documentazione-contro-la-tortura-a-roma/
Natura: solidale
Tipo_di_soggetto: privato
Titolo: Medu Psychè - Safespace
</yamldata></pre>

**Comment by cristigalas** [comment]
Non è chiaro cosa offrano rispetto all’emergenza e in che modo. Anche sul sito c’è una scheda sul progetto in cui si parla di ambulatori ma senza nessun riferimento alle modalità di accesso alla luce delle misure anti-contagio. Sì tratta comunque un progetto attivo dal 2016. Non accetto.
