### ISSUE TITLE
Regione #Piemonte, bando per la ricerca di collaboratori professionali sanitari e tecnico-sanitari di laboratorio biomedico

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2929]
<pre><yamldata>
Cosa: Regione Piemonte, bando per la ricerca di collaboratori professionali sanitari
  e tecnico-sanitari di laboratorio biomedico
Descrizione: L’Unità di Crisi della Regione Piemonte ha aperto un bando valido fino
  al 9 maggio per ricercare collaboratori professionali sanitari e tecnico-sanitari
  di laboratorio biomedico. Il contratto di lavoro dura un anno. Scadenza per presentare le domande prorogata dal 9 al 13 maggio. Tutte le info al
  link.
Link: https://t.co/RYu07vgRaG
Posizione: 45.082703 7.681804 0 0
</yamldata></pre>

**Comment by cristigalas** [comment]
Scaduto. Chiudo.
