### ISSUE TITLE
Sportello di segretariato sociale e di orientamento lavorativo e formativo

Supporto telefonico nei 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2964]
<pre><yamldata>
Da_chi_offerta: Consulta delle Chiese Evangeliche
Descrizione: 'Sportello di segretariato sociale e di orientamento lavorativo e formativo

  Supporto telefonico nei seguenti giorni

  martedi

  mercoledi

  giovedi

  dalle 9:30 alle 17:00

  numeri di riferimento

  3892330920 (Sara)

  3883971162 (Anna)'
Destinatari: migranti e italiani
Natura: solidale
Tipo_di_soggetto: pubblico
Titolo: Sportello di ascolto e orientamento sociale e lavorativo
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente, vedi https://covid19italia.help/issues/2815/
