### ISSUE TITLE
Donazioni Emergenza Corona Virus "Grazie di Cuore" - Città della Salute e della Scienza di Torino. 


### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#2973]
<pre><yamldata>
BIC_SWIFT: BCITITMM
Causale: '"Donazione Covid-19" seguito da Cognome, Nome, Codice Fiscale del benefattore'
Descrizione: "Donazioni Emergenza Corona Virus \"Grazie di Cuore\" - Città della Salute\
  \ e della Scienza di Torino. \nIn questi giorni difficili, dove tutti insieme stiamo\
  \ lottando per contenere e debellare il Corona virus, con grande senso di responsabilità\
  \ e soprattutto con \"grande CUORE\", stiamo recependo da molti di voi cittadini\
  \ e associazioni l'intenzione di contribuire attraverso donazioni liberali per aiutarci\
  \ a superare le imponenti difficoltà a cui siamo chiamati in questa situazione di\
  \ emergenza sanitaria."
IBAN: IT35F0306909219100000046290
Intestazione: Azienda Ospedaliero-Universitaria Città della Salute e della Scienza
  di Torino
Link: https://www.cittadellasalute.to.it/
Nome: Città della Salute e della Scienza di Torino
Posizione: 45.074456 7.682204 0 0
</yamldata></pre>

**Comment by chiccap** [comment]
già presente #2966
