### ISSUE TITLE
Direttiva Lavoro Agile

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#298]
<pre><yamldata>
Cosa: Direttiva Lavoro Agile
Fonte: Presidenza Consiglio dei Ministri/Ministro per la Pubblica Amministrazione
Link: http://www.funzionepubblica.gov.it/articolo/ministro/12-03-2020/pa-ecco-la-nuova-direttiva-di-funzione-pubblica-sull%E2%80%99emergenza-covid-19
meta/deprecatedID: uuid:46c4b4c2-7953-4abd-8809-b9d2efc7fbcd

</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Link segnalazione non funziona

**Comment by claudiamazzantiact** [comment]
Link non funzionante
