### ISSUE TITLE
CSV  Milano in collaborazione con Studio Milano Notai ha organizzato  quattro incontri online per di

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3003]
<pre><yamldata>
Da_chi_offerta: CSV Milano
Descrizione: "CSV  Milano in collaborazione con Studio Milano Notai ha organizzato\
  \  quattro incontri online per discutere e analizzare l’impatto del Coronavirus\
  \ sulla gestione degli enti del Terzo settore.\n\nIncontri:\n• La riforma in emergenza\
  \ – 12 maggio, dalle 18 alle 19 \n• Il fundraising ai tempi del Covid – 15 maggio,\
  \ dalle 18 alle 19\n• Il modello 231 negli ETS: le forme, la sostanza – 19 maggio,\
  \ dalle 18 alle 19\n• Nuovi modelli di bilancio per gli ETS – 22 maggio, dalle 18\
  \ alle 19\n\nPer info e iscrizioni: https://www.csvlombardia.it/milano/post/tra-emergenza-e-riforma-webinar-gratuiti-per-il-non-profit/"
Destinatari: Enti Terzo settore
Link: https://www.csvlombardia.it/milano/post/tra-emergenza-e-riforma-webinar-gratuiti-per-il-non-profit/
Natura: didattica
Titolo: 'Tra emergenza e riforma: webinar gratuiti per il non profit'
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente #3002.
