### ISSUE TITLE
CSV #Milano offre un servizio agli enti non profit per la ricerca di volontari 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3005]
<pre><yamldata>
Cosa: Aiuto nella diffusione della ricerca volontari
Descrizione: "Cerchi volontari per il tuo ente non profit? \nNoi di CSV Milano ti\
  \ aiutiamo gratuitamente a diffondere la ricerca volontari per la tua attività.\n\
  Scopri di più sul nostro sito."
Destinatari: Enti Terzo settore in cerca di volontari
Link: www.csvlombardia.it/milano/post/hai-bisogno-di-volontari-ti-aiutiamo-noi
Posizione: 45.465454 9.186516
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente https://www.covid19italia.help/issues/2907/
