### ISSUE TITLE
Ho disponibilità di abbigliamento usato (ma in ottime condizioni) per ragazze orientativamente 8/14 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3020]
<pre><yamldata>
Cosa: Abbigliamento
Descrizione: Ho disponibilità di abbigliamento usato (ma in ottime condizioni) per
  ragazze orientativamente 8/14 anni. Tutto è raccolto in sacchi da prima dell'emergenza
  epidemia e non sono mai stati aperti. Sarebbe l'ideale per case famiglie.
Destinatari: Ragazze 8/14 anni
Email: dipierro@istat.it
Telefono: '3473778664'
</yamldata></pre>

**Comment by michelerestuccia** [comment]
Qualcuno può contattare via email la persona da indirizzo inserito e metterli in contatto con realtà che operano sul suo territorio. @chiccap @cristigalas

**Comment by cristigalas** [comment]
@michelerestuccia @chiccap a parte il fatto che non è una segnalazione pertinente, possiamo comunque dirle di rivolgersi alla Caritas locale anche se dubito che in questo momento raccolgano abiti...

**Comment by cristigalas** [comment]
Ho inviato una mail dicendo di rivolgersi alla Caritas più vicina.
