### ISSUE TITLE
Progetti maker innovativi per combattere il coronavirus: aperta la call per la prima Virtual Maker Faire

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3029]
<pre><yamldata>
Cosa: 'Progetti maker innovativi per combattere il coronavirus: aperta la call per
  la prima Virtual Maker Faire'
Descrizione: 'La risposta globale al Covid19 è l''innovazione! E'' aperta la Call
  per la Prima Virtual Maker Faire. Sei un Maker? Un innovatore? Hai realizzato un
  progetto per risolvere un problema legato alla pandemia? In attesa di #MFR20 partecipa
  alla prima Virtual Maker Faire in programma il 23 Maggio! 24 ore dedicate ai progetti
  maker più innovativi ideati per combattere il coronavirus.
Leggi le istruzioni e compila l’application form al link.'
Link: https://makerfaire.com/virtually-maker-faire-call-2020-for-makers/
regione_manuale: tutte
</yamldata></pre>

**Comment by gloriaschiavi** [comment]
milestone passata, issue chiusa
