### ISSUE TITLE
In questi giorni si parla di ripartenza, ma siamo sicuri che lo sia per tutti/e? Molte persone risch

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3038]
<pre><yamldata>
Cosa: ANNUNCIO RICERCA VOLONTARI/E MILANO
Descrizione: 'In questi giorni si parla di ripartenza, ma siamo sicuri che lo sia
  per tutti/e? Molte persone rischiano di essere lasciate indietro da un sistema economico
  che nella foga di "ripartire" si dimentica della dignità umana, come ha sempre fatto.
  Molti/e che sono in difficoltà ora, lo erano anche prima della crisi.

  Per questo, non ci fermiamo. Stiamo cercando nuove volontarie e volontari che abbiano
  voglia di unirsi a noi, ogni nuova aggiunta significa molte più persone aiutate.

  Cerchiamo persone che vogliano occuparsi di dare una mano con le consegne dei pacchi
  alimentari e la logistica delle nostre attività! L''ideale sarebbe avere un mezzo
  come l''auto, ma l''unica caratteristica necessaria è la voglia di aiutare.

  Se vuoi offrirti puoi scriverci una e-mail a brigatalia@gmail.com specificando:
  nome, cognome, età, numero di telefono, indirizzo di domicilio, disponibilità orarie
  e eventuale mezzo di trasporto.

  Ringraziamo già di cuore chi ci scriverà: insieme possiamo ricostruire a Milano
  quel tessuto di solidarietà e comunità che decenni di neoliberismo hanno devastato.

  NB: Possiamo accettare solo individui maggiorenni.'
Destinatari: Maggiorenni città diMilano
Email: brigatalia@gmail.com
Indirizzo: 45.46789 9.189813 0 0
Nome: Brigata Lia
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente, vedi #2870. Però visto questa nuova segnalazione e dunque il fatto che il bisogno di volontari persiste, suggerisco di fare tweet e post su Fb e Instagram. Che ne dite @chiccap @michelerestuccia? Io intanto vado di tweet.
