### ISSUE TITLE
Buonasera, sto facendo un'indagine sulle organizzazioni che forniscono servizi alla pandemia e vorre

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3046]
<pre><yamldata>
Cosa: information
Descrizione: Buonasera, sto facendo un'indagine sulle organizzazioni che forniscono
  servizi alla pandemia e vorrei saperne di più su di voi. Potrebbe dirmi chi ha creato
  la piattaforma? cosa ha motivato la creazione/come è nata l'idea? molto grato in
  questo momento.
Email: samantha_0906@hotmail.com
Telefono: '41996462166'
</yamldata></pre>

**Comment by michelerestuccia** [comment]
spam
