### ISSUE TITLE
Venerdì 29 maggio dalle  14:00 alle 15:00 Qubì Gratosoglio organizza incontro online gratuito con la pediatra Francesca Ferrante per famiglie con bambini 0-3 anni 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3047]
<pre><yamldata>
Da_chi_offerta: Qubì Gratosoglio
Descrizione: 'LA PEDIATRA RISPONDE servizion a cura della dott.ssa Francesca Ferrante

  VENERDì 29 MAGGIO dalle 14.00 alle 15.00

  un’opportunità gratuita dedicata alle famiglie con bambini 0-3 anni, per rispondere
  a tutti i tuoi dubbi e domande!

  Segui le istruzioni per il collegamento da pc, da tablet o da smartphone, tutte
  le info sul volantino al link!'
Destinatari: Famiglie con bambini Gratosoglio
Link: https://www.facebook.com/qubigratosoglio/posts/943977889372983
Natura: solidale
Posizione: 45.413022 9.172431 0 0
Tipo_di_soggetto: privato
Titolo: LA PEDIATRA RISPONDE
</yamldata></pre>

**Comment by gloriaschiavi** [comment]
milestone passata, chiusa issue
