### ISSUE TITLE
Raccolta Fondi per Ospedali di #Messina

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#305]
<pre><yamldata>
Comune: Messina
Descrizione: "Dona qualcosa per donare una posto in pi\xF9, un respiratore in pi\xF9\
  , un letto in pi\xF9 agli ospedali di Messina. Dona perch\xE9 quel letto potrebbe\
  \ essere tuo, di tuo padre, tua madre, tuo fratello. Anche se non vivi qui, anche\
  \ se mai ci sei stato e forse mai ci verrai, quel posto letto potrebbe fare la differenza\
  \ per qualcuno che sente le tue stesse paure, ora che mi stai leggendo."
Link: https://www.gofundme.com/f/covid19-un-posto-in-piu-negli-ospedali-di-messina
Nome: Piattaforma Go Fund Me
Posizione: 38.19376 15.55421 0 0
Provincia: Messina
Regione: Sicilia
</yamldata></pre>

**Comment by luciaroma** [comment]
fondi ricevuti e già trasferiti all'ospedale
