### ISSUE TITLE
Webinar #AssociazioneOrlando "Covid19: Uno Sguardo di Genere. Analisi collaborativa" - 27/05 h19 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3051]
<pre><yamldata>
Cosa: 'Covid19: Uno Sguardo di Genere. Analisi collaborativa - 27/05 h19'
Descrizione: 'Con il questionario “Covid19: Uno Sguardo di Genere”, pubblicato su
  www.women.it, l’associazione Orlando ha rilevato dati inerenti alle condizioni abitative,
  familiari, lavorative e al lavoro di cura, fondamentali per misurare e valutare
  i diversi impatti di questa crisi fra il 26 marzo e il 14 aprile 2020.
Il questionario ha coinvolto 4000 persone da tutta Italia, durante la Fase 1, per
  contribuire ad indagare quali siano le ricadute economiche e sociali dell''emergenza
  Covid19 per le donne e gli uomini in Italia.
Ci sono numerosi dati e elementi interessanti da condividere e discutere, e per
  questo motivo vi invitiamo a un incontro online di analisi collaborativa:
  - mercoledì 27 maggio alle ore 19.00
 - in diretta live sulla pagina facebook del Centro delle donne di Bologna'
Link: https://www.facebook.com/events/1189138318093382/
Posizione: 44.494187 11.34239 0 0
</yamldata></pre>

**Comment by gloriaschiavi** [comment]
milestone passata, chiusa issue
