### ISSUE TITLE
salve
in iran abbiamo avutl la notizia della cura del covid 19 tramite autopsia fatte da voi ke resp

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3058]
<pre><yamldata>
Cosa: la cura del covid 19
Descrizione: 'salve

  in iran abbiamo avutl la notizia della cura del covid 19 tramite autopsia fatte
  da voi ke responsabile e una batteria e lacura e iniettare 100 ml aspirina nel paziente.

  E vero questa notizia? o e una bufala?'
</yamldata></pre>

**Comment by michelerestuccia** [comment]
Spam.
