### ISSUE TITLE
Progetto  - Fondazione Cineteca Italiana Manifattura Tabacchi

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3085]
<pre><yamldata>
Descrizione: La Fondazione ha reso gratuito il catalogo in streaming dei film. Per
  accedere è sufficiente registrarsi sul sito.
Destinatari: tutti
Link: https://cinetecamilano.it/
Tipologia intervento: Cultura e didattica
Titolo: Progetto  - Fondazione Cineteca Italiana Manifattura Tabacchi
</yamldata></pre>

**Comment by cristigalas** [comment]
@chiccap questa è già presente, vedi qui #343. Chiudiamo questa e aggiungiamo label CsvLombardia a quella più vecchia?

**Comment by chiccap** [comment]
@cristigalas sí l’altra è anche piú completa!
