### ISSUE TITLE
Progetto Casa della cittadinanza - Il Torpedone - Civil Week

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3092]
<pre><yamldata>
Descrizione: 'Gli operatori e le operatrici della cooperativa hanno realizzato e stanno
  realizzando una serie di video, dando vita alla rubrica “Piccoli video contro la
  noia”.

  I filmati, pubblicati su Facebook, sono pensati per un pubblico vario che va da
  bambini, famiglie e adulti, proponendo di volta in volta fiabe animate, consigli
  di lettura, laboratori e molto altro.'
Destinatari: tutti
Link: https://www.facebook.com/casadellacittadinanzacinisello/?__tn__=K-R&eid=ARCagVojN9Xgm-eB2FXOK2jzfVxhyzVTa6Py4y0CZ8AMV9LYapjWnSaNBtk9_QPAas0xu0d1UU-5jDXv&fref=mentions
Tipologia intervento: Cultura e didattica
Titolo: Progetto Casa della cittadinanza - Il Torpedone - Civil Week
Posizione: 45.55606 9.21432
</yamldata></pre>

**Comment by cristigalas** [comment]
Semplice informazione. Non accettiamo.
