### ISSUE TITLE
Progetto  - Scuola Impresa Sociale - Civil Week

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3104]
<pre><yamldata>
Descrizione: '– Aiutiamo in sicurezza: serie di video – realizzati da Scuola di Impresa
  Sociale | Consorzio SiR in collaborazione con CSA Coesi Bergamo e Consolida Lecco
  – messi a disposizione gratuitamente di operatori professionali e volontari allo
  scopo di illustrare i corretti comportamenti da tenere per la tutela della propria
  salute e di coloro con cui si entra in contatto.

  – Risorse online: iniziativa di Mestieri Lombardia finalizzata a segnalare ai giovani
  come cercare di valorizzare il tempo chiusi in casa nella prospettiva di costruire
  il proprio percorso di inserimento progressivo nel mercato del lavoro. Le risorse
  saranno aggiornate settimanalmente.

  – Young Music Generation: progetto di Scuola di Impresa Sociale | Consorzio SiR
  con l’obiettivo di valorizzare idee di giovani, singoli o in gruppo, nell’ambito
  del mercato musicale. Viene proposto loro un percorso di formazione a Milano, uno
  stage all’estero ed un percorso di accompagnamento alla creazione di impresa (nelle
  più diverse forme) e di ospitalità negli spazi di BaseMilano e Music Innovation
  Hub per il primo periodo di vita.'
Destinatari: giovani e studenti
Link: http://www.mestierilombardia.it/risorseonline
Tipologia intervento: Cultura e didattica
Titolo: Progetto  - Scuola Impresa Sociale - Civil Week
</yamldata></pre>

**Comment by chiccap** [comment]
già presente #2814
