### ISSUE TITLE
Servizio gratuito di supporto psicologico via e-mail

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#312]
<pre><yamldata>
Da_chi_offerta: "Psicologhe Alessia Viola e Giulia Armani di Eir\xE9ne Psicologia"
Descrizione: "La crescente diffusione dell' epidemia da #coronavirus e le relative\
  \ ripercussioni nella vita quotidiana di ognuno di noi, stanno generando preoccupazioni\
  \ e disagi, che innalzano il livello di #stress individuale e della collettivit\xE0\
  . Come ci ripetono gli esperti, \xE8 fondamentale in questi momenti seguire le indicazioni\
  \ e prendere le giuste #precauzioni, senza cedere all'ansia e al panico.\nPer sostenere\
  \ i cittadini in questo delicato momento le psicologhe Giulia Armani e Alessia Viola\
  \ di eir\xE9ne mettono a disposizione un servizio gratuito di supporto psicologico\
  \ via e-mail.\nChiunque pu\xF2 scrivere per richiedere un aiuto e fare domande riguardo\
  \ problematiche di ansia e stress inerenti a questa situazione d'emergenza.\n\n\U0001F4E8\
  Scrivi a: eirenepsi@gmail.com"
Destinatari: Tutti
Link: http://www.eirenepsicologia.it/?fbclid=IwAR0p9hSO9fbsD8tpQImy6roaAs8dHdysp4M757IA3FguP-DcZbe_ZoarGRg
Natura: solidale
Tipo_di_soggetto: privato
Titolo: Servizio gratuito di supporto psicologico via e-mail

</yamldata></pre>

**Comment by luciaroma** [comment]
in base alle policy, questa non andrebbe accettata, perchè sono due psicologhe private.
posso cambiare in #nonaccettata? @cristigalas

**Comment by cristigalas** [comment]
@luciaroma parliamone nel gruppo Editor, è meglio...
