### ISSUE TITLE
CESV #Messina - programma completo dei seminari a distanza

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3128]
<pre><yamldata>
Da_chi_offerta: CESV Messina
Descrizione: "Il CESV Messina ha programmato, dal 4 aprile al 6 giugno, i propri servizi\
  \ di formazione con due cicli di seminari a distanza, alcuni più direttamente collegati\
  \ all’emergenza che stiamo vivendo ed altri comunque di interesse e sempre attuali.\
  \ \n\nEcco il programma completo\n\nLa normativa di emergenza: cosa cambia per gli\
  \ ETS\nIl volontario occasionale ai tempi del COVID-19\nPresentazione Bando per\
  \ contributi Banca d’Italia\nVolontariato e sicurezza ai tempi del COVID-19\nMessa\
  \ in trasparenza delle competenze dei volontari\nLa gestione contabile degli ETS\n\
  La normativa UE n. 2016/679 (GDPR) sulla protezione dei dati personali\nDifendersi\
  \ dalle Fake news. Comunicazione e disinformazione\nI programmi europei di mobilità\
  \ giovanile e per adulti\nLa normativa UE n. 2016/679 (GDPR) sulla protezione dei\
  \ dati personali e gli adempimenti per gli ETS\nGli strumenti finanziari per il\
  \ terzo settore\nI Programmi europei di mobilità giovanile e per adulti\nLo stato\
  \ di attuazione della riforma del terzo settore"
Destinatari: Organizzazioni di volontariato ed altri enti di terzo settore
Link: https://cesvmessina.org/notizie/cesv-news/dal-15-maggio-il-secondo-ciclo-di-webinar-del-cesv-messina/
Natura: didattica
Titolo: Formazione online - Webinar
Posizione: 38.19145 15.53252
</yamldata></pre>

**Comment by favoeva** [comment]
chiudo perché il programma è terminato.
