### ISSUE TITLE
Progetto Nessuno Escluso – Connettiamoci! - ANFFAS Novate - Civil Week

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3157]
<pre><yamldata>
Descrizione: Insieme ad altre realtà di Novate e grazie alla preziosa collaborazione
  di tanti volontari, l’associazione sostiene le persone più colpite dalle restrizioni
  dovute all’emergenza sanitaria.
Destinatari: persone maggiormente in difficoltà a seguito delle restrizioni
Tipologia intervento: Salute
Titolo: Progetto Nessuno Escluso – Connettiamoci! - ANFFAS Novate - Civil Week
</yamldata></pre>

**Comment by cristigalas** [comment]
Informazione generica. Anche sul sito non ci sono notizie di attività per l’emergenza. Non accetto.
