### ISSUE TITLE
COVID-19 contromisure

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#316]
<pre><yamldata>
Cosa: COVID-19 contromisure
Descrizione: 'Buonasera,

  Sempre Alessandro Rovetta che vi parla. Vi chiedo perdono: inerentemente al messaggio
  precedente (COVID-19 urgenza mutazioni evolutive etc.), lascio alcuni contatti.
  Grazie.

  Mail: rovetta.exiliumgames@gmail.com

  Telefono: 3927112808

  Buon lavoro.'
Posizione: 45.535453 10.21955 0 0

</yamldata></pre>

**Comment by favoeva** [comment]
aggiungo a segnalazione precedente e chiudo
