### ISSUE TITLE
Progetto  - Avo Milano - Civil Week

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3163]
<pre><yamldata>
Descrizione: AVO Milano si è organizzata per stare vicino agli anziani all’interno
  delle RSA al telefono e lavora per estendere questo servizio ad altre strutture
  e contesti, sia come Avo Milano che come federazione.
Destinatari: pazienti delle RSA
Tipologia intervento: Salute
Titolo: Progetto  - Avo Milano - Civil Week
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 45.46679408 9.1903474 (Milano) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=45.46679408+9.1903474&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by cristigalas** [comment]
Già presente, vedi #3171.
