### ISSUE TITLE
Progetto  - Fidas Peschiera Borromeo - Donatori di sangue

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3172]
<pre><yamldata>
Descrizione: L’associazione ha continuato le proprie attività di donazione di sangue
  grazie ai propri donatori.
Destinatari: tutti
Tipologia intervento: Salute
Titolo: Progetto  - Fidas Peschiera Borromeo - Donatori di sangue
</yamldata></pre>

**Comment by cristigalas** [comment]
Semplice comunicazione. Non accetto.
