### ISSUE TITLE
Progetto  - Fondazione Buzzi per l'Ospedale dei bambini

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3175]
<pre><yamldata>
Descrizione: In questa situazione di emergenza sanitaria, Fondazione Buzzi si è messa
  a disposizione delle autorità e del neo-nominato commissario straordinario per allestire
  nuovi posti letto di rianimazione, e acquistare il materiale di consumo come mascherine
  e camici, di cui oggi medici e infermieri hanno sempre più bisogno.
Destinatari: minori, malati e traumatizzati
Tipologia intervento: Salute
Titolo: Progetto  - Fondazione Buzzi per l'Ospedale dei bambini
</yamldata></pre>

**Comment by cristigalas** [comment]
@chiccap semplice notizia di ciò che hanno fatto non accetterei.
