### ISSUE TITLE
Progetto  - Fondazione Dr. Ambrosoli

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3176]
<pre><yamldata>
Descrizione: 'Con l’aiuto dei medici volontari, l’associazione sta supportando a distanza
  il personale dell’ospedale di Kalongo, impegnato nel piano emergenza dovuto alla
  pandemia.

  Inoltre, rimanendo in costante contatto con la struttura, Fondazione Dr. Ambrosoli
  la sostiene nell’approvvigionamento di dispositivi di protezione, di strumentazioni
  adeguate, di materiale sanitario e di farmaci.'
Destinatari: pazienti dell’ospedale di Kalongo, Uganda
Tipologia intervento: Salute
Titolo: Progetto  - Fondazione Dr. Ambrosoli
</yamldata></pre>

**Comment by cristigalas** [comment]
Semplice comunicazione di attività svolte (all’estero). Non accetto.
