### ISSUE TITLE
Progetto  - Fondazione Francesca Rava/NPH Italia Onlus - Civil Week

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3177]
<pre><yamldata>
Descrizione: '– Reperimento e donazione di attrezzature urgenti di terapia intensiva;

  – Invio di medici e personale sanitario volontario;

  – Distribuzione di gel igienizzante per le mani e mascherine alle case famiglia
  e alle comunità per minori sul territorio della Lombardia;

  – Attività di sensibilizzazione per i giovani volontari.'
Destinatari: tutti
Tipologia intervento: Salute
Titolo: Progetto  - Fondazione Francesca Rava/NPH Italia Onlus - Civil Week
</yamldata></pre>

**Comment by cristigalas** [comment]
Semplice comunicazione di attività svolte. Non accetto.
