### ISSUE TITLE
Progetto  - Fondazione Valter Longo - Civil Week

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3178]
<pre><yamldata>
Descrizione: Nonostante le difficoltà legate alla situazione sanitaria nazionale,
  Fondazione Valter Longo mette a disposizione servizi gratuiti per la comunità in
  tempi di Covid-19 per supportare i propri pazienti e la comunità in tutta Italia,
  per trasformare questo tempo di attesa e di solitudine in un tempo di qualità e
  ricreativo anche per le persone più fragili.
Destinatari: tutti
Link: https://www.fondazionevalterlongo.org/
Tipologia intervento: Salute
Titolo: Progetto  - Fondazione Valter Longo - Civil Week
</yamldata></pre>

**Comment by cristigalas** [comment]
Dal sito non si capisce che servizi siano e se siano ancora attivi. Non accetto.
