### ISSUE TITLE
Progetto  - Il Bullone - Civil Week

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3180]
<pre><yamldata>
Descrizione: Non potendo effettuare interventi di assistenza “fisica” in questo momento
  di emergenza, l’associazione è rimasta comunque al fianco degli utenti attraverso
  diversi strumenti online. Tra questi, particolarmente importante è il ruolo de “Il
  Bullone”, giornale con cui si da modo ai ragazzi di condividere le loro storie.
Destinatari: Giovani e ragazzi affetti da gravi patologie croniche
Link: https://www.ilbullone.org/il-giornale/
Tipologia intervento: Salute
Titolo: Progetto  - Il Bullone - Civil Week
</yamldata></pre>

**Comment by cristigalas** [comment]
Segnalazione poco chiara. Non accetto.
