### ISSUE TITLE
Progetto  - L'Abilità - Civil Week

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3181]
<pre><yamldata>
Descrizione: L’associazione, in seguito alle restrizioni dovute all’emergenza Coronavirus,
  ha comunque garantito sostegno a bambini e famiglie attraverso una serie di servizi
  di supporto a distanza.
Destinatari: bambini e ragazzi con disabilità
Tipologia intervento: Salute
Titolo: Progetto  - L'Abilità - Civil Week
</yamldata></pre>

**Comment by cristigalas** [comment]
Semplice comunicazione, senza riferimenti precisi. Non accetto.
