### ISSUE TITLE
Progetto Tecniche di rilassamento per ridurre l’ansia - Lab-Cos - Civil Week

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3182]
<pre><yamldata>
Descrizione: L’associazione ha pensato di dare il suo contributo in questo periodo
  di quarantena forzata offrendo gratuitamente un manuale di tecniche di rilassamento
  per ridurre l’ansia. Si tratta di uno strumento semplice e alla portata di tutti,
  utilizzabile quotidianamente per ritrovare una maggiore calma e serenità.
Destinatari: tutti
Tipologia intervento: Salute
Titolo: Progetto Tecniche di rilassamento per ridurre l’ansia - Lab-Cos - Civil Week
</yamldata></pre>

**Comment by cristigalas** [comment]
Semplice comunicazione, senza riferimenti precisi. Non accetto.
