### ISSUE TITLE
Progetto  - LILT Lega Italiana per la Lotta contro i Tumori - Civil Week

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3183]
<pre><yamldata>
Descrizione: L’associazione ha trasferito quanto più possibile online le attività
  di sensibilizzazione, promuovendo così video, webinar tematici e altri contenuti
  attraverso i propri canali di informazione.
Destinatari: tutti
Tipologia intervento: Salute
Titolo: Progetto  - LILT Lega Italiana per la Lotta contro i Tumori - Civil Week
</yamldata></pre>

**Comment by cristigalas** [comment]
Semplice comunicazione, senza riferimenti precisi. Non accetto.
