### ISSUE TITLE
Progetto  - Medici Senza Frontiere

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3184]
<pre><yamldata>
Descrizione: L’associazione ha messo a disposizione medici e altro personale sanitario
  a supporto del sistema sanitario italiano.
Destinatari: Malati e traumatizzati
Tipologia intervento: Salute
Titolo: Progetto  - Medici Senza Frontiere
</yamldata></pre>

**Comment by cristigalas** [comment]
Semplice comunicazione, senza riferimenti precisi. Non accetto.
