### ISSUE TITLE
Progetto #Prendersicura - NAGA

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3186]
<pre><yamldata>
Descrizione: L’unità mobile dell’associazione prosegue le uscite sul territorio per
  prendersi cura dei cittadini stranieri e monitorare i bisogni di chi vive nelle
  aree più nascoste della città.
Destinatari: Persone più in difficoltà in seguito all’emergenza sanitaria
Link: https://naga.it/2020/05/14/corona-virus-info-e-materiali-utili/
Tipologia intervento: Salute
Titolo: 'Progetto #Prendersicura - NAGA'
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente, vedi #2506.
