### ISSUE TITLE
Progetto A TU per TU...TOR - TU.TO.R Onlus

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3193]
<pre><yamldata>
Descrizione: L'associazione, con il progetto "A TU per TU... TOR" ha organizzato una
  serie di incontri online a favore dei propri beneficiari.
Destinatari: pazienti con tumori toracici rari
Link: https://www.tumoritoracicirari.it/2020/05/16/a-tu-per-tu-tor-4-video-chiacchiere-fra-di-noi-2/
Tipologia intervento: Salute
Titolo: Progetto A TU per TU...TOR - TU.TO.R Onlus
</yamldata></pre>

**Comment by cristigalas** [comment]
Segnalazione scaduta. L’ultimo incontro si è tenuto il 28 maggio. Non accetto.
