### ISSUE TITLE
Progetto  - Casa dell'agricoltura - Civil Week

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3208]
<pre><yamldata>
Descrizione: '– Consegne a domicilio;

  – Norme virus: si tratta di una rubrica diffusa sui canali social con cui l’associazione
  presenta tutte le disposizioni che nel corso del tempo sono state adottate per contrastare
  il virus.'
Destinatari: tutti
Link: https://www.facebook.com/casagricoltura/
Tipologia intervento: Sociale
Titolo: Progetto  - Casa dell'agricoltura - Civil Week
</yamldata></pre>

**Comment by cristigalas** [comment]
@chiccap notizia superata. Il link rimanda semplicemente alla pagina Fb. Non accetterei.
