### ISSUE TITLE
Progetto WeMI - Cascina Biblioteca

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3209]
<pre><yamldata>
Descrizione: 'L’associazione collabora con il Comune di Milano e la Protezione Civile
  per:

  – mappare i servizi dedicati agli anziani in queste settimane di emergenza;

  – supportare i più fragili attraverso consegne al domicilio di spesa, farmaci ed
  altri beni di prima necessità.'
Destinatari: anziani
Link: https://cascinabiblioteca.it/la-cooperativa-inclusione-sociale/coronavirus-cosa-stiamo-facendo/
Tipologia intervento: Sociale
Titolo: Progetto WeMI - Cascina Biblioteca
</yamldata></pre>

**Comment by cristigalas** [comment]
@chiccap notizia superata e il link rimanda in realtà ad una raccolta fondi. Non accetterei.
