### ISSUE TITLE
Progetto  - Cena dell'amicizia

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3210]
<pre><yamldata>
Descrizione: L’associazione ha mantenuto attivi i propri servizi che riguardano gli
  appartamenti protetti e i centri Clemente Papi e Casa di Alessia, tutti dedicati
  a persone senza tetto.
Destinatari: senza tetto e senza fissa dimora
Link: https://www.cenadellamicizia.it/il-centro-clemente-papi-e-la-casa-per-i-nostri-ospiti/
Tipologia intervento: Sociale
Titolo: Progetto  - Cena dell'amicizia
</yamldata></pre>

**Comment by cristigalas** [comment]
Non accetterei, è una notizia generica e superata.
