### ISSUE TITLE
Progetto  - Croce Rossa Italiana

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3211]
<pre><yamldata>
Descrizione: La CRI ha distribuito in questo periodo straordinario oltre oltre 600
  pasti, il doppio rispetto a quanto avveniva prima dell’emergenza sanitaria. Gli
  operatori, inoltre, affiancano altre realtà per informare le persone sul Coronavirus
  e le norme igieniche da seguire per prevenire il contagio.
Destinatari: persone in difficoltà economica e con fragilità abitative
Tipologia intervento: Sociale
Titolo: Progetto  - Croce Rossa Italiana
</yamldata></pre>

**Comment by cristigalas** [comment]
È una semplice notizia di cose fatte. Non accetto.
