### ISSUE TITLE
Progetto #acasacomeadynamo - Dynamo Camp

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3213]
<pre><yamldata>
Descrizione: 'Da metà marzo, con il progetto #acasacomeadynamo, l’associazione ha
  portato la Terapia Ricreativa Dynamo nelle case attraverso Facebook, proponendo
  di volta in volta attività di stimolo alla creatività e alle potenzialità di ognuno.'
Destinatari: minori con disabilità e famiglie
Link: https://www.facebook.com/dynamocamp/
Tipologia intervento: Sociale
Titolo: 'Progetto #acasacomeadynamo - Dynamo Camp'
</yamldata></pre>

**Comment by cristigalas** [comment]
@chiccap anche questa non l’accetterei, è superata.
