### ISSUE TITLE
Progetto  - Fondazione Casa della carità "Angelo Abriani"

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3216]
<pre><yamldata>
Descrizione: A causa dell’emergenza sanitaria, l’associazione ha sospeso le proprie
  attività diurne riorganizzando i turni degli operatori. Inoltre, ha creato uno spazio
  online di condivisione sul proprio sito.
Destinatari: over 65 e altre fasce della popolazione particolarmente colpite
Link: http://www.casadellacarita.org/flex/cm/pages/ServeBLOB.php/L/IT/IDPagina/1
Tipologia intervento: Sociale
Titolo: Progetto  - Fondazione Casa della carità "Angelo Abriani"
</yamldata></pre>

**Comment by cristigalas** [comment]
@chiccap Questa non l’accetterei perché è superata. L’associazione ha ripreso l’attività come risulta sul loro sito.
