### ISSUE TITLE
Progetto  - La casa di Emma

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3224]
<pre><yamldata>
Descrizione: L’associazione raccoglie e condivide tramite Facebook racconti, fotografie
  ed altre testimonianze per continuare a fare comunità nonostante le restrizioni
  dovute all’emergenza sanitaria.
Destinatari: bambini e famiglie
Link: https://www.facebook.com/casadiemma/photos/a.138969882938216/1514506032051254/?type=3&theater
Tipologia intervento: Sociale
Titolo: Progetto  - La casa di Emma
</yamldata></pre>

**Comment by cristigalas** [comment]
@chiccap anche questa non l’accetterei.
