### ISSUE TITLE
Progetto  - Worldrise

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3234]
<pre><yamldata>
Descrizione: L’associazione è riuscita a non fermare le proprie attività trovando
  nuovi modi di interagire con gli utenti. Con l’utilizzo di strumenti a distanza,
  ha promosso attività di cucina, fai da te, yoga e tanto altro.
Destinatari: tutti
Link: https://www.facebook.com/worldrise/photos/a.229505667209866/1477339535759800/?type=3&av=104488716266949&eav=AfZrhfVhCWhmY2bmprnxVo5iL67vmQ-ya9YOim1-6t76EBwjy5EcMwoBYUI3AwGkCgY&theater
Tipologia intervento: Sociale
Titolo: Progetto  - Worldrise
</yamldata></pre>

**Comment by cristigalas** [comment]
@chiccap questa non l’accetterei, è un notizia superata e tra l’altro il link non si apre.
