### ISSUE TITLE
Progetto  - Social Osa Basket Milano

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3241]
<pre><yamldata>
Descrizione: L'associazione ha coinvolto tutte le squadre in allenamenti in video
  chiamata con il preparatore Atletico organizzando sessioni tecniche, giochi e interviste. 
Destinatari: piccoli e grandi atleti di pallacanestro
Link: https://www.youtube.com/watch?v=3nRC_Mp9pmE&feature=youtu.be
Tipologia intervento: Sport
Titolo: Progetto  - Social Osa Basket Milano
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 45.46679408 9.1903474 (Milano) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=45.46679408+9.1903474&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by cristigalas** [comment]
@chiccap questa non l’accetterei anche se è una delle segnalazioni di Csv Milano.
