### ISSUE TITLE
Aggiornamento giornaliero dati statistici relativi all'emergenza covid

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3253]
<pre><yamldata>
Da_chi_offerta: A.G.D Nebrodi, Diabete Salute e Società ONLUS
Descrizione: Aggiornamento giornaliero dati statistici relativi all'emergenza covid
Destinatari: Le famiglie con bambini diabetici
Link: https://www.facebook.com/AGD-Nebrodi-Diabete-Salute-e-Societ%C3%A0-ONLUS-119126225127564/
Natura: solidale
Posizione: 38.06943 14.633875 0 0
Tipo_di_soggetto: privato
Titolo: Aggiornamento dati statistici sul covid
</yamldata></pre>

**Comment by cristigalas** [comment]
Poco chiaro di cosa si tratti, il link porta semplicemente alla pagina Fb dell’associazione.
