### ISSUE TITLE
La Misericordia di Spadafora, dal 12 marzo, ha effettuato il servizio “resta a casa e alla spesa ci 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3254]
<pre><yamldata>
Da_chi_offerta: Misericordia di Spadafora
Descrizione: 'La Misericordia di Spadafora, dal 12 marzo, ha effettuato il servizio
  “resta a casa e alla spesa ci pensiamo noi”. I volontari hanno consegnato generi
  alimentari di prima necessità e farmaci alle persone bisognose, indicate dall’ufficio
  dei servizi sociali del Comune, costrette a casa.

  Ogni volontario sarà provvisto di DPI.

  Il Call Center è attivo ai seguenti numeri: 3206696231, 0909928603, 0909574981'
Destinatari: Persone bisognose indicate dai servizi sociali del Comune
Link: https://cesvmessina.org/notizie/spadafora-servizio-resto-a-casa-e-alla-spesa-ci-pensiamo-noi-a-cura-della-misericordia/
Natura: solidale
Posizione: 38.223769 15.378499 0 0
Tipo_di_soggetto: privato
Titolo: Resta a casa e alla spesa ci pensiamo noi
</yamldata></pre>

**Comment by cristigalas** [comment]
@chiccap è un servizio ormai superato. Non lo accetterei così come non ho accettato altre segnalazioni superate che Cesv Messina ci ha inviato... forse bisognerebbe dire loro che ci devono inviare segnalazioni aggiornate e non usare la nostra piattaforma come archivio.

**Comment by chiccap** [comment]
sono d'accordo!
