### ISSUE TITLE
Il Gruppo Fratres di Letojanni ha organizzato una raccolta di sangue domenica 22 marzo dalle ore 8 a

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3256]
<pre><yamldata>
Da_chi_offerta: Gruppo Fratres di Letojanni
Descrizione: Il Gruppo Fratres di Letojanni ha organizzato una raccolta di sangue
  domenica 22 marzo dalle ore 8 alle ore 12 nella sede dell’Unità di raccolta di Letojanni,
  in Via Monte Bianco presso l’ex centro diurno ed un’ulteriore raccolta è stata fissata
  per venerdì 27 marzo. L’appuntamento del 27 marzo è “fuori programma”, ma è stato
  aggiunto – come spiega Carmelina Micalizzi, presidente del Gruppo Fratres di Letojanni
  – “per venire incontro alle richieste del Centro Trasfusionale di Taormina di fronte
  al crescente fabbisogno di sangue di questi giorni”.
Destinatari: Donatori e persone bisognose di sangue
Link: https://cesvmessina.org/notizie/sos-carenza-sangue-rafforzato-limpegno-delle-associazioni-per-donare-in-sicurezza/
Natura: solidale
Posizione: 37.883271 15.306873 0 0
Tipo_di_soggetto: privato
Titolo: Raccolta di sangue
</yamldata></pre>

**Comment by cristigalas** [comment]
Superato.
