### ISSUE TITLE
La raccolta è stata effettuata domenica 29 marzo, dalle ore 7:30 alle ore 11:00

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3257]
<pre><yamldata>
Da_chi_offerta: Avis di Santa Teresa di Riva
Descrizione: La raccolta è stata effettuata domenica 29 marzo, dalle ore 7:30 alle
  ore 11:00
Destinatari: Persone che hanno bisogno di trasfusioni
Link: https://cesvmessina.org/notizie/sos-carenza-sangue-rafforzato-limpegno-delle-associazioni-per-donare-in-sicurezza/
Natura: solidale
Posizione: 37.959882 15.36468 0 0
Tipo_di_soggetto: privato
Titolo: Raccolta di sangue
</yamldata></pre>

**Comment by cristigalas** [comment]
Superato.
