### ISSUE TITLE
Non è vero che il Ministero della salute ha vietato le autopsie sulle vittime di covid-19

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3261]
<pre><yamldata>
Cosa: Non è vero che il ministero della Salute ha vietato le autopsie sui morti di
  Covid-19
Descrizione: Non è vero che il Ministero della salute ha vietato le autopsie sui corpi
  di chi, purtroppo, ha perso la vita a causa di Covid-19 e per rendersene conto basta
  leggere il testo della circolare, la n.15280 del 2 maggio 2020.
Link: https://www.wired.it/scienza/medicina/2020/05/11/coronavirus-autopsie-bufala/
</yamldata></pre>

**Comment by favoeva** [comment]
Chiudo perché doppia
