### ISSUE TITLE
Ad alta Voce - audiolibri gratuiti

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#328]
<pre><yamldata>
Da_chi_offerta: Radio 3 RAI
Descrizione: Audiolibri gratuiti su Rai Radio 3
Destinatari: Tutti
Link: https://www.raiplayradio.it/articoli/2018/01/Radio3--Ad-alta-voce--tutti-i-romanzi-f91c61a8-0021-40ca-a62f-514b841b558b.html?fbclid=IwAR3t-hHhgR93rCaSHXPrchCduV07Dax4jFL1cZDAbdKWsyCKb356sckh2FI
Natura: culturale-ricr
Titolo: Ad alta Voce - audiolibri gratuiti

</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Segnalazione già presente issue #274

**Comment by cristigalas** [comment]
Non accettata, quindi va chiusa.
