### ISSUE TITLE
L’osservatorio “Mutamenti Sociali in Atto-COVID19” (MSA-COVID19) è un progetto del Consiglio Naziona

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3284]
<pre><yamldata>
Da_chi_offerta: CNR Consiglio Nazionale delle Ricerche
Descrizione: 'L’osservatorio “Mutamenti Sociali in Atto-COVID19” (MSA-COVID19) è un
  progetto del Consiglio Nazionale delle Ricerche (CNR-Irpps) realizzato in collaborazione
  con l’Istituto Nazionale di Geofisica e Vulcanologia (INGV) e la Fondazione Movimento
  Bambino ONLUS. L’Osservatorio indaga su atteggiamenti e comportamenti della popolazione
  nell’emergenza COVID19 in relazione al “distanziamento sociale”. A partire dall’emanazione
  del decreto #IoRestoaCasa da parte del Consiglio dei Ministri in materia di spostamento
  delle persone fisiche all’interno del territorio nazionale si è prodotto un cambiamento
  improvviso e radicale delle abitudini e degli stili di vita degli italiani con una
  drastica riduzione di ogni forma di socialità, mutamenti nell’interazione sociale
  e nella tenuta e organizzazione del lavoro.

  Il progetto, in una prospettiva diacronica, ha lo scopo di esplorare, analizzare,
  comprendere e proporre previsioni circa gli effetti psicosociali del distanziamento
  sociale e dei fenomeni connessi alla contrazione dell’interazione sociale e della
  prolungata convivenza abitativa, per poi definire interventi a sostegno del benessere
  della popolazione. Lo studio riguarda la dimensione interpersonale, individuale
  ed economica della crisi indotta dalla pandemia da COVID-19.

  Maggiori informazioni al link  https://www.irpps.cnr.it/musa/msa-covid19/'
Destinatari: tutti
Link: www.irpps.cnr.it/
Natura: culturale-ricr
Titolo: Osservatorio nazionale sul COVID-19
</yamldata></pre>

**Comment by michelerestuccia** [comment]
Già presente come #3285
