### ISSUE TITLE
GitHub dona un po di Cloud al progetto Folding@Home's

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#332]
<pre><yamldata>
Cosa: GitHub dona un po di Cloud al progetto Folding@Home's
Descrizione: Starting later today, GitHub is donating up to 60,000 core-hours per
  day of idle GitHub Actions compute capacity to Folding@Home's efforts to find drug
  treatments for 2019-nCOV. https://foldingathome.org/2020/02/27/foldinghome-takes-up-the-fight-against-covid-19-2019-ncov/
Link: https://twitter.com/natfriedman/status/1237466267998543872
Posizione: 37.782181 -122.391244 0 0

</yamldata></pre>

**Comment by cristigalas** [comment]
Testo in inglese. Per ora non accetterei, poi se qualcuno traduce l’accettiamo.
