### ISSUE TITLE
Consegna libri a #Torino

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#338]
<pre><yamldata>
Comune: Torino
Da_chi_offerta: Librerie del Golem
Descrizione: "Per chi non vuole o non pu\xF2 uscire di casa ho deciso di mettermi\
  \ a disposizione e portarvi i libri direttamente a casa.\n\nPotete farmi gli ordini\
  \ nei canali soliti della libreria e con la mia fida bicicletta gialla sar\xF2 da\
  \ voi."
Destinatari: Residenti a Torino
Link: https://www.facebook.com/lalibreriadelgolem/photos/a.1599887820243956/2718884935010900/?type=3&theater
Natura: solidale
Posizione: 45.06776 7.68249 0 0
Provincia: Torino
Regione: Piemonte
Tipo_di_soggetto: privato
Titolo: 'Consegna libri a #Torino'
</yamldata></pre>

**Comment by lucafanelli76** [comment]
secondo me non è totalmente solidale, in quanto è una libreria che consegna i libri venduti; non dico che non sia utile, ma bisogna in qualche modo che emerga, ad es. cambiando la natura "solidale"

**Comment by chiccap** [comment]
già esistente #109
