### ISSUE TITLE
Coronavirus in Italia: video, testi e traduzioni per migranti

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#339]
<pre><yamldata>
Da_chi_offerta: Il Grande Colibrì
Descrizione: Pubblicazione del materiale informativo prodotto dall’associazione di
  volontariato Il Grande Colibrì e da altre organizzazioni sul nuovo coronavirus SARS-CoV-2
  e sull’epidemia di COVID-19 in Italia in diverse lingue. Questa pagina è aggiornata
  di ora in ora, con l’aggiunta o l’aggiornamento dei materiali sia per le lingue
  già presenti sia per nuove lingue.
Destinatari: Migranti
Link: https://www.ilgrandecolibri.com/coronavirus-spiegato-migranti-asilanti/
Natura: solidale
Tipo_di_soggetto: privato
Titolo: 'Coronavirus in Italia: video, testi e traduzioni per migranti'
regione_manuale: tutte
</yamldata></pre>

**Comment by chiccap** [comment]
arrivata segnalazione aggiornata #2272
