### ISSUE TITLE
Raccolta Fondi per Croce Rossa Italiana

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#340]
<pre><yamldata>
Descrizione: ' I fondi raccolti verranno utilizzati dall’Ente Nazionale per acquistare ciò riterrà
  necessario per fronteggiare l’emergenza in tutta Italia.
  Siamo in costante contatto con i Responsabili della Croce Rossa Italiana - Comitato
  Regionale Piemonte e si precisa che i fondi raccolti saranno devoluti direttamente
  all’Ente Nazionale.'
Link: https://bit.ly/3cXr2mv
Nome: Croce Rossa Italiana

</yamldata></pre>

**Comment by gloriaschiavi** [comment]
L'organizzatore della raccolta fondi l'ha sospesa su gofundme
