### ISSUE TITLE
Brugherio aiuta Brugherio

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3403]
<pre><yamldata>Azione: donazioni (denaro,materiale,spazi)
Comune: Brugherio
Descrizione: 'Brugherio aiuta Brugherio '
Destinatari: "altro\u2026"
Ente: Comune
Fonte: CSV Lombardia
Link: http://www.comune.brugherio.mb.it/aree/comunicazione-e-stampa/novit/BRUGHERIO-AIUTA-BRUGHERIO-RACCOLTA-FONDI/
Posizione: 45.5582 9.2951 0 0
</yamldata></pre>

**Comment by michelerestuccia** [comment]
Ho scritto al comune per segnalare errore del link (msg 404), aspetto feedback.

**Comment by michelerestuccia** [comment]
Ho trovato un link aggiornato e l'ho sostituito al precedente.
