### ISSUE TITLE
Global Strike in digitale venerdì 13 marzo - Fridays For Future

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#342]
<pre><yamldata>
Cosa: https://www.facebook.com/FridaysItalia/
Descrizione: "un anno esatto dal primo 'Global Strike' purtroppo non sarà possibile\
  \ difendere il nostro futuro nelle piazze. Questo non significa smettere o arrendersi.\
  \ Anzi! Alla crisi sanitaria noi rispondiamo essendo ancora più attivi sui social\
  \ e gridando ancora più forte!\n\nCOME PARTECIPARE?⠀\n Posta sul tuo profilo una\
  \ foto mentre manifesti da casa con un cartellone sulla #CrisiClimatica!⠀\n⠀\nUsa\
  \ gli hashtag #ClimateStrikeOnline e #DigitalStrike... E non dimenticarti di taggarci!⠀\n\
  \nSabato pubblicheremo una foto collage con tutti i partecipanti che ci avranno\
  \ taggato!⠀\n\nLEGGI IL COMUNICATO STAMPA DI FRIDAYS FOR FUTURE: https://www.fridaysforfutureitalia.it/sciopero-online-clima…"
Link: https://www.facebook.com/FridaysItalia/

</yamldata></pre>

**Comment by cristigalas** [comment]
Scaduta. Chiudo.
