### ISSUE TITLE
Raccolta Fondi Croce Bianca #Biassono #Manza

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3481]
<pre><yamldata>Azione: donazioni (denaro,materiale,spazi)
Comune: Biassono
Descrizione: 'Raccolta Fondi Croce Bianca Biassono '
Destinatari: settore sanitario
Ente: Organizzazione
Fonte: CSV Lombardia
Link: https://www.gofundme.com/f/sos-covid-19-croce-bianca-biassono
</yamldata></pre>

**Comment by michelerestuccia** [comment]
Raccolta fondi conclusa
