### ISSUE TITLE
Brugherio: raccolta fondi per famiglie e persone in difficoltà

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3499]
<pre><yamldata>Azione: donazioni (denaro,materiale,spazi)
Comune: Brugherio
Descrizione: 'Brugherio aiuta Brugherio '
Destinatari: "altro\u2026"
Ente: Comune
Fonte: CSV Lombardia
Link: http://www.comune.brugherio.mb.it/news-e-iniziative/dettaglio/Brugherio-aiuta-Brugherio-raccolta-fondi/
Posizione: 45.5582 9.2951 0 0
</yamldata></pre>

**Comment by michelerestuccia** [comment]
Già presente in #3501
