### ISSUE TITLE
Raccolta fondi per l'Ospedale di #Vimercate 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#351]
<pre><yamldata>
Descrizione: Diamo nel nostro possibile un aiuto importante all’Ospedale di Vimercate,
  impegnata in questo momento delicato nel contenimento e nella cura di tutte le persone
  dell’area del Vimercatese che hanno contratto il COVID-19.
Informativa: OK
Link: https://www.gofundme.com/f/insieme-con-vimercate-contro-il-covid19
Nome: Ospedale di Vimercate

</yamldata></pre>

**Comment by luciaroma** [comment]
L'organizzatore ha momentaneamente disattivato le donazioni per questa campagna.
