### ISSUE TITLE
Calolziocorte: Servizio di sostegno e supporto alla cittadinanza

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3515]
<pre><yamldata>Azione: supporto psicologico
Comune: Calolziocorte
Descrizione: Servizio di sostegno e  supporto alla cittadinanza promosso da Distretto
  di Lecco, ASST e Fondazione don S. Caccia per i comuni della Valle San Martino
Destinatari: "comunit\xE0"
Ente: Comune
Fonte: CSV Lombardia
Link: http://www.comune.calolziocorte.lc.it/index.php/archivio-news/item/1536-servizio-di-sostegno-e-supporto-alla-cittadinanza
Posizione: 45.80180555555555 9.43361111111111 0 0
</yamldata></pre>

**Comment by michelerestuccia** [comment]
Link non funzionante (msg 404) e notizia non presente su archivi del sito del comune
