### ISSUE TITLE
Palazzo Arese Borromeo: #laculturanonsiferma

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3542]
<pre><yamldata>Azione: sollievo/intrattenimento
Comune: Cesano Maderno
Descrizione: 'Palazzo Arese Borromeo: #laculturanonsiferma '
Destinatari: famiglie
Ente: Comune
Fonte: CSV Lombardia
Link: https://www.comune.cesano-maderno.mb.it/servizi/Menu/dinamica.aspx?idSezione=616&idArea=21206&idCat=32419&ID=32463&TipoElemento=categoria
Posizione: 45.6313 9.1533 0 0
</yamldata></pre>

**Comment by michelerestuccia** [comment]
Il link non funziona (Messaggio: ATTENZIONE: Il documento richiesto e' obsoleto.) e sul sito del comune non è presente alcun riferimento alla notizia.
