### ISSUE TITLE
Gastronomia "Da Fabrizio"

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3545]
<pre><yamldata>Azione: consegne alimenti/farmaci
Comune: Chiavenna
Descrizione: Gastronomia "Da Fabrizio" offerta pranzo Pasqua a operatori sanitari
  ospedale Chiavenna
Destinatari: settore sanitario
Ente: Profit
Fonte: CSV Lombardia
Link: https://www.facebook.com/pages/category/Local-Business/Gastronomia-da-Fabrizio-Chiavenna-1826247654263649/
Posizione: 46.323888888888895 9.402083333333334 0 0
</yamldata></pre>

**Comment by michelerestuccia** [comment]
non pertinente
