### ISSUE TITLE
Ristorante "La Terrazza"

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3546]
<pre><yamldata>Azione: consegne alimenti/farmaci
Comune: Chiavenna
Descrizione: Ristorante "La Terrazza" offerta pranzo Pasqua a operatori sanitari ospedale
  Chiavenna
Destinatari: settore sanitario
Ente: Profit
Fonte: CSV Lombardia
Link: https://www.facebook.com/pages/category/Family-Style-Restaurant/Ristorante-La-Terrazza-374264059745200/https://www.ristorante-la-terrazza.it/
Posizione: 46.32758333333334 9.399972222222221 0 0
</yamldata></pre>

**Comment by michelerestuccia** [comment]
non pertinente
