### ISSUE TITLE
Gelateria "Il Gelato del Vecio"

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3547]
<pre><yamldata>Azione: consegne alimenti/farmaci
Comune: Chiavenna
Descrizione: Gelateria "Il Gelato del Vecio" offerta merende a operatori sanitari
  ospedale Chiavenna
Destinatari: settore sanitario
Ente: Profit
Fonte: CSV Lombardia
Link: https://www.facebook.com/ilgelatodelvecio/
Posizione: 46.321250000000006 9.403277777777777 0 0
</yamldata></pre>

**Comment by michelerestuccia** [comment]
non pertinente
