### ISSUE TITLE
Bar Pasticceria "Mastai"

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3548]
<pre><yamldata>Azione: consegne alimenti/farmaci
Comune: Chiavenna
Descrizione: Bar Pasticceria "Mastai" offerta merende a operatori sanitari ospedale
  Chiavenna
Destinatari: settore sanitario
Ente: Profit
Fonte: CSV Lombardia
Link: https://www.facebook.com/BarMastaihttp://www.mastai.it/
Posizione: 46.319583333333334 9.398722222222222 0 0
</yamldata></pre>

**Comment by michelerestuccia** [comment]
Non rilevante
