### ISSUE TITLE
C.A.I./C.A.I. Giovanile Chiavenna

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3551]
<pre><yamldata>Azione: "altro\u2026"
Comune: Chiavenna
Descrizione: 'C.A.I./C.A.I. Giovanile Chiavenna '
Destinatari: famiglie
Ente: Organizzazione
Fonte: CSV Lombardia
Link: https://www.facebook.com/111761572726593/photos/a.175790836323666/678781882691223/?type=3&theater
Posizione: 46.32077777777778 9.405722222222222 0 0
</yamldata></pre>

**Comment by michelerestuccia** [comment]
Già presente in #3550
