### ISSUE TITLE
Mtb Chiavennese

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3552]
<pre><yamldata>Azione: "altro\u2026"
Comune: Chiavenna
Descrizione: 'Mtb Chiavennese '
Destinatari: famiglie
Ente: Organizzazione
Fonte: CSV Lombardia
Link: https://www.facebook.com/111761572726593/photos/a.175790836323666/678781882691223/?type=3&theater
Posizione: 46.32211111111111 9.408611111111112 0 0
</yamldata></pre>

**Comment by michelerestuccia** [comment]
Superato
