### ISSUE TITLE
SOS compiti

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3558]
<pre><yamldata>Azione: "altro\u2026"
Comune: Civate
Descrizione: 'SOS compiti '
Destinatari: minori
Ente: Comune
Fonte: CSV Lombardia
Link: https://lecconotizie.com/societa/valmadrera-societa/civate-sos-compiti-iniziativa-rivolta-agli-studenti/
Posizione: 45.810111111111105 9.42311111111111 0 0
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente, #3560.
