### ISSUE TITLE
gruppo volontari

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3561]
<pre><yamldata>Azione: pulizia cimiteri
Comune: Cogliate
Descrizione: 'gruppo volontari '
Destinatari: cittadinanza
Ente: Volontari civici
Fonte: CSV Lombardia
Link: https://www.ilnotiziario.net/wp/2020/04/06/coronavirus-cogliate-volontari-tombe-cimitero/
Posizione: 45.646499999999996 9.081527777777778 0 0
</yamldata></pre>

**Comment by michelerestuccia** [comment]
Non pertinente
