### ISSUE TITLE
Pizzeria da Nia

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3566]
<pre><yamldata>Azione: donazioni (denaro,materiale,spazi)
Comune: Colico
Descrizione: Pizzeria da Nia offriva pizze ai volontari in servizio
Destinatari: "comunit\xE0"
Ente: Profit
Fonte: CSV Lombardia
Link: https://www.facebook.com/pizzeriadania/
Posizione: 46.13675 9.373138888888889 0 0
</yamldata></pre>

**Comment by michelerestuccia** [comment]
Superato
