### ISSUE TITLE
Comunità Pastorale Colichese: canale YouTube

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3570]
<pre><yamldata>Azione: sollievo/intrattenimento
Comune: Colico
Descrizione: "Comunit\xE0 Pastorale Colichese: canale YouTube "
Destinatari: "comunit\xE0"
Ente: Organizzazione
Fonte: CSV Lombardia
Link: https://www.comunitacolichese.it/?fbclid=IwAR0KhKj-utcsb3P6LD4aIJcLA0ySYF7FKjYexeT2tce--AhfPjFK-hVX9Zc
Posizione: 46.13333333333333 9.366666666666667 0 0
</yamldata></pre>

**Comment by michelerestuccia** [comment]
Informazioni mancanti
