### ISSUE TITLE
ANA Colico: operativi nell'allestimento di nuove strutture (Fiera Bergamo e Gravedona)

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3571]
<pre><yamldata>Azione: "altro\u2026"
Comune: Colico
Descrizione: 'ANA Colico: operativi nell''allestimento di nuove strutture (Fiera Bergamo
  e Gravedona) '
Destinatari: settore sanitario
Ente: Organizzazione
Fonte: CSV Lombardia
Link: ''
Posizione: 46.13333333333333 9.366666666666667 0 0
</yamldata></pre>

**Comment by michelerestuccia** [comment]
Superato e senza informazioni
