### ISSUE TITLE
Gruppo informale

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3613]
<pre><yamldata>Azione: donazioni (denaro,materiale,spazi)
Comune: Dubino
Descrizione: Gruppo informale realizzazione mascherine per operatori ospedali Lecco
  e Gravedona
Destinatari: settore sanitario
Ente: Cittadini
Fonte: CSV Lombardia
Link: ''
Posizione: 46.16116666666667 9.429916666666665 0 0
</yamldata></pre>

**Comment by michelerestuccia** [comment]
Informazioni non sufficienti
