### ISSUE TITLE
Gruppo informale

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3614]
<pre><yamldata>Azione: donazioni (denaro,materiale,spazi)
Comune: Dubino
Descrizione: Gruppo informale realizzazione cuffie per operatori ospedali Lecco e
  Gravedona
Destinatari: settore sanitario
Ente: Cittadini
Fonte: CSV Lombardia
Link: ''
Posizione: 46.15383333333333 9.434611111111112 0 0
</yamldata></pre>

**Comment by michelerestuccia** [comment]
Informazioni non sufficienti
