### ISSUE TITLE
Il tempo della gentilezza

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3615]
<pre><yamldata>Azione: consegne alimenti/farmaci
Comune: Galbiate
Descrizione: Il tempo della gentilezza promosso da Croce Rossa Italiana di Galbiate
  i
Destinatari: "comunit\xE0"
Ente: Organizzazione
Fonte: CSV Lombardia
Link: ''
Posizione: 45.81722222222223 9.37563888888889 0 0
</yamldata></pre>

**Comment by michelerestuccia** [comment]
Informazioni non sufficienti
