### ISSUE TITLE
Piulizia delle tombe

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3662]
<pre><yamldata>Azione: "altro\u2026"
Comune: Lierna
Descrizione: 'Piulizia delle tombe '
Destinatari: "altro\u2026"
Ente: Comune
Fonte: CSV Lombardia
Link: https://www.facebook.com/noiperlierna/photos/a.418551675568640/671496493607489/?type=3&theater
Posizione: 45.9581 9.305100000000001 0 0
</yamldata></pre>

**Comment by michelerestuccia** [comment]
superato
