### ISSUE TITLE
Coop. Sociale Incontro: ulivo di Pasqua al cimitero e preghiera

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3683]
<pre><yamldata>Azione: "altro\u2026"
Comune: Mandello del Lario
Descrizione: 'Coop. Sociale Incontro: ulivo di Pasqua al cimitero e preghiera '
Destinatari: "comunit\xE0"
Ente: Organizzazione
Fonte: CSV Lombardia
Link: https://www.facebook.com/cooperativasocialeincontro/
Posizione: 45.916666666666664 9.316666666666666 0 0
</yamldata></pre>

**Comment by michelerestuccia** [comment]
Non pertinente e senza informazioni
