### ISSUE TITLE
Gelateria Rolly: donazione ad Associazione Veronica Sacchi

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3689]
<pre><yamldata>Azione: donazioni (denaro,materiale,spazi)
Comune: Mandello del Lario
Descrizione: 'Gelateria Rolly: donazione ad Associazione Veronica Sacchi '
Destinatari: settore sanitario
Ente: Profit
Fonte: CSV Lombardia
Link: https://www.facebook.com/341582985941625/photos/a.504032196363369/2404054306361139/?type=3&theater
Posizione: 9.316666666666666 9.316666666666666 0 0
</yamldata></pre>

**Comment by michelerestuccia** [comment]
Superato
