### ISSUE TITLE
Bar Centrale: donazione torta a Soccorso Alpini

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3690]
<pre><yamldata>Azione: donazioni (denaro,materiale,spazi)
Comune: Mandello del Lario
Descrizione: 'Bar Centrale: donazione torta a Soccorso Alpini '
Destinatari: settore sanitario
Ente: Profit
Fonte: CSV Lombardia
Link: https://www.facebook.com/1690061191231277/photos/a.1690061274564602/2629004144003639/?type=3&theater
Posizione: 9.316666666666666 9.316666666666666 0 0
</yamldata></pre>

**Comment by michelerestuccia** [comment]
Superato
