### ISSUE TITLE
Ti tendo la mano - spesa sospesa

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3740]
<pre><yamldata>Azione: donazioni (denaro,materiale,spazi)
Comune: "Muggi\xF2"
Descrizione: 'Ti tendo la mano - spesa sospesa '
Destinatari: famiglie
Ente: Comune
Fonte: CSV Lombardia
Link: https://muggio-api.municipiumapp.it/system/attachments/attachment/attachment/1/1/7/7/5/1/titendolamano_volantino.jpg
Posizione: 45.5893 9.2273 0 0
</yamldata></pre>

**Comment by chiccap** [comment]
dal volantino non si capisce
