### ISSUE TITLE
Donazione occhiali da vista per anziani con Farmacie Comunali

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3742]
<pre><yamldata>Azione: donazioni (denaro,materiale,spazi)
Comune: "Muggi\xF2"
Descrizione: 'Donazione occhiali da vista per anziani con Farmacie Comunali '
Destinatari: anziani/malati
Ente: Comune
Fonte: CSV Lombardia
Link: https://www.facebook.com/pg/ComunediMuggio/posts/
Posizione: 45.5893 9.2273 0 0
</yamldata></pre>

**Comment by chiccap** [comment]
notizia datata
