### ISSUE TITLE
Distribuzione derrate alimentari e mascherine

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3743]
<pre><yamldata>Azione: donazioni (denaro,materiale,spazi)
Comune: "Muggi\xF2"
Descrizione: "Distribuzione derrate alimentari e mascherine Associazione Banco di\
  \ Solidariet\xE0 \u201CNoi, gli amici di Paolo\u201D"
Destinatari: famiglie
Ente: Organizzazione
Fonte: CSV Lombardia
Link: https://www.mbnews.it/2020/03/fondo-emergenza-coronavirus-mb-sostegno-concreto-ad-altre-sei-iniziative/
Posizione: 45.5893 9.2273 0 0
</yamldata></pre>

**Comment by chiccap** [comment]
notizia troppo datata
