### ISSUE TITLE
Racconti e letture online Asilo e Biblioteca

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3747]
<pre><yamldata>Azione: sollievo/intrattenimento
Comune: Nova Milanese
Descrizione: 'Racconti e letture online Asilo e Biblioteca '
Destinatari: famiglie
Ente: Comune
Fonte: CSV Lombardia
Link: https://www.facebook.com/1611316995774384/videos/247889713072656/
Posizione: 45.591300000000004 9.2006 0 0
</yamldata></pre>

**Comment by chiccap** [comment]
link non più attivo
