### ISSUE TITLE
Asta solidale di opere d'arte delle Associazioni della CAM - Casa Arti e Mestieri

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3748]
<pre><yamldata>
Comune: Nova Milanese
Descrizione: 'Ispirati da altre realtà lombarde e piemontesi, noi Associazioni della CAM, Casa Arti e Mestieri di Nova Milanese (Associazione Culturale Impronte, Libera Accademia di Pittura Vittorio Viviani, Centro Musica Insieme) abbiamo deciso di dare il nostro piccolo contributo raccogliendo fondi per la Caritas di Nova Milanese, che in questo momento si sta adoperando per offrire alle persone in difficoltà generi alimentari di prima necessità.
Gli artisti coinvolti hanno donato le proprie opere, che verranno messe a disposizione con una base d’asta simbolica, non corrispondente al reale valore della realizzazione artistica, dimostrando un grande gesto di solidarietà. 
Per partecipare all’asta solidale sarà sufficiente andare sulla pagina Facebook di Associazione Culturale Impronte, fare la propria offerta nei commenti delle singole immagini, taggando la persona che ha fatto l’ultima offerta più alta. '
Destinatari: famiglie
Ente: Organizzazione
Fonte: CSV Lombardia
Link: https://www.facebook.com/events/1912802738849787/
Posizione: 45.591300000000004 9.2006 0 0
</yamldata></pre>

**Comment by chiccap** [comment]
chiusa il 19/04
