### ISSUE TITLE
Raccolta fondi degli Alpini per Croce Rossa di Nova Milanese

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3749]
<pre><yamldata>Azione: donazioni (denaro,materiale,spazi)
Comune: Nova Milanese
Descrizione: 'Raccolta fondi degli Alpini per Croce Rossa Novese '
Destinatari: settore sanitario
Ente: Organizzazione
Fonte: CSV Lombardia
Link: https://www.facebook.com/photo.php?fbid=127740685521284&set=pcb.127740712187948&type=3&theater
Posizione: 45.591300000000004 9.2006 0 0
</yamldata></pre>

**Comment by chiccap** [comment]
chiusa il 30/04.
