### ISSUE TITLE
Donazione di lenti a contatto

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3751]
<pre><yamldata>Azione: donazioni (denaro, materiale, spazi)
Comune: Oggiono
Descrizione: Donazione di lenti a contatto promossa da Ottica Visus - donati anche
  a Forze dell'ordine e volontari CRI
Destinatari: settore sanitario
Ente: Profit
Fonte: CSV Lombardia
Link: ''
Posizione: 45.78936111111111 9.341722222222224 0 0
</yamldata></pre>

**Comment by chiccap** [comment]
non ci sono sufficienti info
