### ISSUE TITLE
Donazione di lenti a contatto da Ottica Visus #Oggiono

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3753]
<pre><yamldata>Azione: donazioni (denaro, materiale, spazi)
Comune: Oggiono
Descrizione: "Donazione di lenti a contatto promossa da Ottica Visus - donati anche\
  \ a Forze dell'ordine e volontari CRI - fino a met\xE0 aprile"
Destinatari: settore sanitario
Ente: Profit
Fonte: CSV Lombardia
Link: 'https://www.facebook.com/OtticaVisusOggiono/'
Posizione: 45.78936111111111 9.341722222222224 0 0
</yamldata></pre>

**Comment by chiccap** [comment]
conclusa ad aprile
