### ISSUE TITLE
Artein comune

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3755]
<pre><yamldata>Azione: donazioni (denaro,materiale,spazi)
Comune: Olgiate Molgora
Descrizione: 'Artein comune '
Destinatari: settore sanitario
Ente: Organizzazione
Fonte: CSV Lombardia
Link: https://www.merateonline.it/articolo.php?idd=100430&origine=1&t=Olgiate%3A+raccolti+2.650+euro+con+le+opere+di+Arteincomune
Posizione: '  0 0'
</yamldata></pre>

**Comment by chiccap** [comment]
notizia troppo datata
