### ISSUE TITLE
Arci La Loco

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3760]
<pre><yamldata>Azione: consegne alimenti/farmaci
Comune: Osnago
Descrizione: 'Arci La Loco '
Destinatari: "comunit\xE0"
Ente: Organizzazione
Fonte: CSV Lombardia
Link: ''
Posizione: '  0 0'
</yamldata></pre>

**Comment by chiccap** [comment]
non ci sono sufficienti informazioni
