### ISSUE TITLE
Tessitura Carlo Lamperti

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3761]
<pre><yamldata>Azione: donazioni (denaro,materiale,spazi)
Comune: Osnago
Descrizione: 'Tessitura Carlo Lamperti '
Destinatari: "comunit\xE0"
Ente: Profit
Fonte: CSV Lombardia
Link: ''
Posizione: '  0 0'
</yamldata></pre>

**Comment by chiccap** [comment]
non ci sono sufficienti informazioni
