### ISSUE TITLE
Auser

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3762]
<pre><yamldata>Azione: "altro\u2026"
Comune: Paderno D'Adda
Descrizione: 'Auser '
Destinatari: anziani/malati
Ente: Organizzazione
Fonte: CSV Lombardia
Link: ''
Posizione: '  0 0'
</yamldata></pre>

**Comment by chiccap** [comment]
non ci sono sufficienti informazioni
