### ISSUE TITLE
DECAR di Piantedo

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3769]
<pre><yamldata>Azione: donazioni (denaro,materiale,spazi)
Comune: Piantedo
Descrizione: DECAR di Piantedo mascherine
Destinatari: "comunit\xE0"
Ente: Profit
Fonte: CSV Lombardia
Link: https://www.facebook.com/decarpiantedo
Posizione: 46.23938888888889 9.731305555555556 0 0
</yamldata></pre>

**Comment by chiccap** [comment]
non ci sono sufficienti informazioni
