### ISSUE TITLE
Protezione Civile di Piantedo

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3770]
<pre><yamldata>Azione: consegne alimenti/farmaci
Comune: Piantedo
Descrizione: Protezione Civile di Piantedo mascherine
Destinatari: "comunit\xE0"
Ente: Organizzazione
Fonte: CSV Lombardia
Link: ''
Posizione: 46.13619444444444 9.430666666666665 0 0
</yamldata></pre>

**Comment by chiccap** [comment]
non ci sono sufficienti informazioni
