### ISSUE TITLE
Anonimo

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3771]
<pre><yamldata>Azione: donazioni (denaro,materiale,spazi)
Comune: Piuro
Descrizione: Anonimo donazione privata anonima
Destinatari: "comunit\xE0"
Ente: Cittadini
Fonte: CSV Lombardia
Link: https://www.facebook.com/watch/?v=219524069397208
Posizione: 46.330222222222226 9.420888888888888 0 0
</yamldata></pre>

**Comment by chiccap** [comment]
notizia troppo vecchia
