### ISSUE TITLE
Supporto psicologico - Sloworking

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3808]
<pre><yamldata>Azione: supporto psicologico
Comune: Provincia MB
Descrizione: 'L’arrivo del COVID-19 ha portato improvvisi stravolgimenti della quotidianità, lavorativa e non, presentandoci nuovi ostacoli nel conciliare i ritmi di vita e il benessere di ognuno di noi .

Ansia, preoccupazione, cambiamento radicale di abitudini, riorganizzazione di tempi e modalità di lavoro, coabitazione forzata e dinamiche familiari a dura prova. 

Affrontare questi cambiamenti può far emergere dubbi, incertezze e paure che possono mettere alla prova. 

In questa situazione così complessa, il team di psicologi psicoterapeuti, coach, counselor e pedagogisti di Sloworking mette a disposizione le proprie competenze e il proprio tempo per rispondere a bisogni specifici e trovare nuove soluzioni per affrontare l’isolamento.  '
Destinatari: "comunit\xE0"
Ente: Organizzazione
Fonte: CSV Lombardia
Link: http://www.sloworking.it/coronavirus-slowlistening/
Posizione: 45.583400000000005 9.2759 0 0
</yamldata></pre>

**Comment by chiccap** [comment]
concluso il 3 aprile.
