### ISSUE TITLE
ASST Valtellina e Alto Lario

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3820]
<pre><yamldata>Azione: donazioni (denaro,materiale,spazi)
Comune: Provincia SO
Descrizione: 'ASST Valtellina e Alto Lario '
Destinatari: settore sanitario
Ente: Organizzazione
Fonte: CSV Lombardia
Link: https://www.facebook.com/asstValtLario/https://www.asst-val.it/
Posizione: 46.171166666666664 9.880083333333333 0 0
</yamldata></pre>

**Comment by chiccap** [comment]
già presente #2988
