### ISSUE TITLE
ARCI IL CONTATTO servizio telefonico antistress #Sondrio

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3835]
<pre><yamldata>
Comune: Provincia SO
Descrizione: 'A partire da giovedì 12 marzo e sino al 3 aprile 2020 dalle 10.30 alle 12.30 e dalle 14.30 alle 16.30, il circolo Arci Il Contatto attiva il Progetto Sociale “La salute per tutte le età e in tutte le condizioni” con un primo servizio TELEFONICO ANTISTRESS rivolto alla popolazione della provincia di Sondrio.

Se ti senti solo e hai bisogno di una voce competente che ti ascolti e ti consigli telefona allo 0342 217568. '
Destinatari: famiglie
Ente: Organizzazione
Fonte: CSV Lombardia
Link: https://www.csvlombardia.it/wp-content/uploads/2020/03/locandina-servizio-telefonico-antistress-1-convertito.pdf
Posizione: 5.0  0 0
</yamldata></pre>

**Comment by chiccap** [comment]
conclusa il 3 aprile
