### ISSUE TITLE
LEGA TUMORI LILT SONDRIO

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3861]
<pre><yamldata>Azione: supporto psicologico
Comune: Sondrio
Descrizione: 'LEGA TUMORI LILT SONDRIO '
Destinatari: anziani/malati
Ente: Organizzazione
Fonte: CSV Lombardia
Link: segreteria@legatumoriso.it3921634510
Posizione: 46.16971944444444 9.870000000000001 0 0
</yamldata></pre>

**Comment by chiccap** [comment]
non ci sono sufficienti info

**Comment by chiccap** [comment]
non ci sono sufficienti info
