### ISSUE TITLE
Spazi Donna WeWorld aperti per attività individuali #Milano #Roma #Napoli 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#389]
<pre><yamldata>
Da_chi_offerta: WeWorld Onlus
Descrizione: 'Gli Spazi Donna WeWorld di Roma (San Basilio), Napoli (Scampia) e di
  Milano (Giambellino) in adempimento alle linee guida restano aperti per attività
  individuali e hanno potenziato servizi di sostegno e ascolto a distanza, via mail
  o telefono.

  Chi ha bisogno può contattarci scrivendo a: ascoltodonna@weworld.it.'
Destinatari: Donne
Link: https://www.weworld.it/donne-ancora-piu-isolate/?fbclid=IwAR0_aTaoq8X5437YpPER11ooiiOSyD5SjPHxJrbCJRsH2n6q_8TZQX_nvD0
Natura: solidale
Tipo_di_soggetto: privato
Titolo: 'Spazi Donna WeWorld presenti a Milano (Giambellino), Roma (San Basilio) #Napoli
  aperti per attività individuali'
</yamldata></pre>

**Comment by cristigalas** [comment]
Superata. Ne apro una nuova con gli aggiornamenti. Chiudo.
