### ISSUE TITLE
Raccolta fondi Lega Tumori LILT Sondrio

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3907]
<pre><yamldata>Azione: supporto psicologico
Comune: Sondrio
Descrizione: 'La LILT Sondrio ha deciso di fare la sua parte, ovvero ha lanciato una campagna di raccolta fondi: SOSTENIAMO IL NOSTRO OSPEDALE per supportare medici, infermieri, personale sanitario e tutti i pazienti a fronteggiare in sicurezza il Covid-19. '
Destinatari: anziani/malati
Ente: Organizzazione
Fonte: CSV Lombardia
Link: https://www.gofundme.com/f/sosteniamo-il-nostro-ospedale
Posizione: 46.16971944444444 9.870000000000001 0 0
</yamldata></pre>

**Comment by chiccap** [comment]
conclusa
