### ISSUE TITLE
GFB Onlus

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3909]
<pre><yamldata>Azione: sollievo/intrattenimento
Comune: Talamona
Descrizione: GFB Onlus "bar virtuali"
Destinatari: "comunit\xE0"
Ente: Organizzazione
Fonte: CSV Lombardia
Link: https://www.facebook.com/pages/category/Nonprofit-Organization/gfbonlus-1045732368903903/http://www.gfbonlus.it/sms/
Posizione: 46.13361111111111 9.609499999999999 0 0
</yamldata></pre>

**Comment by chiccap** [comment]
non ci sono sufficienti informazioni il link non è più valido
