### ISSUE TITLE
Azienda Usl #Parma cerca con urgenza medici da assumere

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#391]
<pre><yamldata>
Cosa: 'Azienda Usl # Parma cerca con urgenza medici da assumere'
Descrizione: 'Per rispondere alle necessità aziendali di cura e assistenza ai malati
  a causa dell’emergenza sanitaria da Covid-19, e fino al termine della situazione
  emergenziale, l’Azienda Usl di Parma ha emesso un bando urgente per ricercare medici
  con contratto di lavoro occasionale o libero professionale.

  E’ previsto il conferimento di incarichi di lavoro autonomo a professionisti medici
  nelle discipline di: medicina interna, malattie infettive, malattie dell’apparato
  respiratorio e anestesia e rianimazione, medicina e chirurgia d’accettazione e d’urgenza.'
Destinatari: Medici
Indirizzo: 44.801616 10.326888 0 0
Link: https://www.ausl.pr.it/comunicazione_stampa/archivio_3/coronavirus_azienda_parma_cerca_urgenza_medici.aspx?fbclid=IwAR36fXMoYLGz2kCz5M1MaGrM3DxwlMYLQCqU-UjAe_mZ5uUL4MXWAAlMXCA
</yamldata></pre>

**Comment by margheritapuca** [comment]
Comune: Parma
Provincia: Parma
Regione: Emilia-Romagna
Posizione: 44.80137 10.32808

**Comment by luciaroma** [comment]
il bando è chiuso
