### ISSUE TITLE
Raccolta fondi Ospedale #Camerino (MC)

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#392]
<pre><yamldata>
Comune: Camerino
Descrizione: Raccolta fondi per poter aiutare la struttura sanitaria di Camerino a
  fronteggiare l'emergenza del Covid-19
Link: https://www.gofundme.com/f/emergenza-covid19-camerino
Nome: Ospedale di Camerino
Posizione: 43.127619 13.050737 0 0
Provincia: Macerata
Regione: Marche
</yamldata></pre>

**Comment by luciaroma** [comment]
L'organizzatore ha momentaneamente disattivato le donazioni per questa campagna.
