### ISSUE TITLE
Amministrazione comunale Traona

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3931]
<pre><yamldata>Azione: supporto psicologico
Comune: Traona
Descrizione: 'Amministrazione comunale Traona '
Destinatari: anziani/malati
Ente: Comune
Fonte: CSV Lombardia
Link: https://www.facebook.com/comuneditraona/http://www.comune.traona.so.it/c014069/po/mostra_news.php?id=296&area=H
Posizione: 46.14941666666667 9.52752777777778 0 0
</yamldata></pre>

**Comment by cristigalas** [comment]
Link corrotto.
