### ISSUE TITLE
Donazione di mascherine, guanti e gel disinfettante

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3937]
<pre><yamldata>Azione: donazioni (denaro,materiale,spazi)
Comune: Valgreghentino
Descrizione: Donazione di mascherine, guanti e gel disinfettante promossa dal gruppo
  sportivo oratorio a favore del comune
Destinatari: "altro\u2026"
Ente: Organizzazione
Fonte: CSV Lombardia
Link: ''
Posizione: 45.810111111111105 9.42311111111111 0 0
</yamldata></pre>

**Comment by cristigalas** [comment]
Senza link.
