### ISSUE TITLE
Movement

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3958]
<pre><yamldata>Azione: sollievo/intrattenimento
Comune: Verderio
Descrizione: 'Movement '
Destinatari: "comunit\xE0"
Ente: Comune
Fonte: CSV Lombardia
Link: https://youtu.be/38sXfsav6JM
Posizione: '  0 0'
</yamldata></pre>

**Comment by cristigalas** [comment]
Non pertinente.
