### ISSUE TITLE
Luca Gusmeroli - CRAI

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#3959]
<pre><yamldata>Azione: donazioni (denaro,materiale,spazi)
Comune: Villa di Chiavenna
Descrizione: 'Luca Gusmeroli - CRAI '
Destinatari: famiglie
Ente: Profit
Fonte: CSV Lombardia
Link: https://www.facebook.com/111761572726593/photos/a.175790836323666/678781882691223/?type=3&theater
Posizione: 46.33261111111111 9.487972222222222 0 0
</yamldata></pre>

**Comment by cristigalas** [comment]
Superato.
