### ISSUE TITLE
BANDO “SAFE WORKING” – IO RIAPRO SICURO in #Lombardia #Confesercenti 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3972]
<pre><yamldata>
Da_chi_offerta: Confesercenti della Lombardia Orientale
Descrizione: "Contributo a fondo perduto, con intensità di aiuto fino al 60 per cento\
  \ per le piccole imprese e fino al 70 per cento per le micro imprese. L’investimento\
  \ minimo richiesto è pari a € 2.000 e nel limite massimo di € 25.000.\nLa domanda\
  \ di contributo, attraverso procedura telematica, deve essere presentata fino alle\
  \ 12.00 del 10 novembre 2020.\n\nSono ammessi interventi relativi ad attività tipo\
  \ le seguenti - acquisto di macchinari per la sanificazione e disinfezione, purificazione\
  \ dell’aria, realizzazione di interventi strutturali o temporanei, acquisto di arredi\
  \ per il distanziamento, acquisto di termoscanner e simili, strumenti relativi a\
  \ monitoraggio e controllo dell’affollamento dei locali, dispositivi di protezione\
  \ individuale, servizi di sanificazione e disinfezione degli ambienti, strumenti\
  \ di comunicazione e informazione, costi per i tamponi per il personale dipendente\
  \ o altri strumenti diagnostici, spese di formazione sulla sicurezza sanitaria,\
  \ prescrizioni e protocolli da adottare.\n\n TUTTE LE INFORMAZIONI AL LINK ALLEGATO"
Destinatari: Micro e piccole imprese lombarde 1) con sede operativa o un’unità locale   in
  Lombardia, iscritta e attiva al Registro Imprese delle Camere di Commercio della   Lombardia
  alla data dell 11 marzo 2020 2) operanti nel settore del commercio, pubblici esercizi,
  artigianato, manifatturiero, edilizia, servizi, istruzione e sport.
Link: https://www.comservizi.it/2020/05/26/bando-safe-working-io-riapro-sicuro/
Natura: sostegno-lavor
Titolo: 'Bando “SAFE WORKING” – IO RIAPRO SICURO in #Lombardia #Confesercenti'
Regione: Lombardia
</yamldata></pre>

**Comment by michelerestuccia** [comment]
già accettato in #3974
