### ISSUE TITLE
Brigata Basaglia Milano: se hai bisogno di aiuto lascia un messaggio in segreteria o invia una email

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3985]
<pre><yamldata>
Da_chi_offerta: Brigata Basaglia
Descrizione: 'Per tutto il mese di agosto la Brigata Basaglia risponderà alle vostre
  mail e messaggi in segreteria entro una settimana.

  📞 02 82396915

  💌 brigatabasagliamilano@gmail.com'
Destinatari: Tutte e tutti
Natura: solidale
Posizione: 45.490946 9.222336 0 0
Tipo_di_soggetto: privato
Titolo: 'Brigata Basaglia: lascia un messaggio in segreteria o invia una email'
</yamldata></pre>

**Comment by favoeva** [comment]
chiudo perchè e relativa a solo mese di agosto (inseriamo nuova segnalazione aggiornata a ottobre)
