### ISSUE TITLE
SIRT1 inhibitors can reduce replication of many viruses with certain similar characteristics to thos

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3987]
<pre><yamldata>
Cosa: Eradicate Coronavirus by blocking replication, counteracting its defense system
Descrizione: SIRT1 inhibitors can reduce replication of many viruses with certain
  similar characteristics to those of Coronaviruses, while p53 protein is another
  important factor in down-regulation of growth. There are some molecules that inhibit
  Sirtuin 1 and 2, in addition to activate p53 protein, by means of regulation of
  the interactions used by Coronaviruses as self-defense mechanism, degradating it.
  Even mTOR signal will be regulate, as well as autophagy will be inhibited, being
  this compound like a lysosomotropic agent. By blocking virus growth and continuous
  replication, associating the already tested Antiviral medicines, Covid-19 could
  be eradicated.
Fonte: Kira Smith
Link: https://osf.io/psz35/
</yamldata></pre>

**Comment by cristigalas** [comment]
Notizia scientifica, non accettiamo.

**Comment by MilMedCorp** [comment]
Salve,
sono io l'autrice dell'articolo. Vorrei sapere cosa ne pensate, grazie. Ho anche la versione nuova, ultima, che è la seguente:

https://doi.org/10.5281/zenodo.3988761

Grazie.

Dr. Kira Smith
Clinical and Experimental Medicine
