### ISSUE TITLE
Nell’  ambito    delle     attività     ludico-ricreative     “Estate Terme Bimbi”,      l’Associazi

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#3988]
<pre><yamldata>
Da_chi_offerta: Associazione Angeli sull'Asfalto
Descrizione: 'Nell’  ambito    delle     attività     ludico-ricreative     “Estate
  Terme Bimbi”,      l’Associazione “Angeli sull’Asfalto” propone “RACCONTIAMOCI”,
  attività di Laboratori creativi itineranti gratuiti rivolti a bambini e ragazzi
  di età compresa tra i 7 e i 14 anni, suddivisi per fasce d’età: 7-10 e 11-14.

  Questi gli appuntamenti al Parco Cattafi (Terme Centro) il 17, 21, 31 agosto e 2
  settembre alle ore 17:30 , presso gli spazi all’aperto della Stazione ferroviaria
  Novara-Montalbano-Furnari il 19, 24, 26, 28  agosto alle ore 17:30, ai  Vivai (Terme
  Vigliatore) il 19 agosto alle ore 17:30 ed a conclusione il 4 settembre nella Piazza
  Municipio di Terme Vigliatore sempre alla 17:30.

  Tutti gli spazi sono adeguati allo svolgimento delle attività, in coerenza con le
  Linee guida emanate dal Dipartimento per le Politiche della Famiglia – Presidenza
  del Consiglio dei Ministri.

  Per garantire il rispetto delle normative anti COVID, la partecipazione sarà regolamentata
  previa iscrizione contattando l’associazione al seguente recapito 3294211057.

  Al fine di implementare le possibilità di momenti ludico-creativi in favore di minori
  ma anche delle loro famiglie, nel dettaglio si intende avviare:

  –        1 Laboratorio fotografico itinerante:  “Spunti di creatività”, “Primi scatti”
  “Racconto in foto” e “Remake”, incontri destinati alla conoscenza degli spazi che
  rappresentano elementi storici e culturali del territorio, raccontati attraverso
  l’immagine, sperimentando la possibilità di cogliere, attraverso lo scatto fotografico,
  scorci e/o elementi ritenuti significativi e loro condivisione.

  –        1 laboratorio ludico/creativo: “Strada Amica, costruiamo giocando” e “Mi
  rendo visibile”,  improntato alla costruzione di percorsi di sicurezza stradale
  e di messa in sicurezza della persona.

  Tutte le attività proposte, oltre che seguire alla lettera  le misure di sicurezza
  dettate dal DPCM 17/5/2020 e Linee guida conseguenti,  saranno supportate dalla
  presenza di esperti professionisti e volontari dell’Associazione che guideranno
  i giovani partecipanti nel corso dell’esperienza.'
Destinatari: 'bambini e ragazzi di età compresa tra i 7 e i 14 anni, suddivisi per
  fasce d’età: 7-10 e 11-14'
Link: https://cesvmessina.org/notizie/cesv-news/raccontiamoci-estate-terme-bimbi-le-iniziative-dellassociazione-angeli-sullasfalto/
Natura: culturale-ricr
Titolo: RACCONTIAMOCI
</yamldata></pre>

**Comment by michelerestuccia** [comment]
Iniziativa di un'associazione locale che però non ha diretta pertinenza con la fase attuale: i laboratori sono dedicati a spazio pubblico, narrazione fotografica e sicurezza stradale; le attività, come descritto, sono realizzate coerentemente con le misure di sicurezza in vigore.

**Comment by michelerestuccia** [comment]
Ci siamo confrontati con il tema degli editors: non è pertinente.
