### ISSUE TITLE
Mappa con georeferenziazione casi Covid in Provincia di Latina
Drive-IN
Laboratori
link Dati Piano i

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4002]
<pre><yamldata>
Cosa: Censimento aggiornato  Covid 19 Comuni in Provincia di Latina
Descrizione: 'Mappa con georeferenziazione casi Covid in Provincia di Latina

  Drive-IN

  Laboratori

  link Dati Piano incremento P.L. a livello Regionale Lazio

  link Mappa regione Lazio dati aggiornati settimanalmente'
Link: http://u.osmfr.org/m/511811/
Posizione: 41.481833 12.908936 0 0
</yamldata></pre>

**Comment by cristigalas** [comment]
@favoeva @michelerestuccia @chiccap Che facciamo con questa? In passato non abbiamo raccolto segnalazioni con dati su casi Covid...

**Comment by michelerestuccia** [comment]
L'avevo aperta per sbaglio prima, mi aveva però lasciato perplesso la qualità e affidabilità delle fonti / dati.

Sul pregresso non so dire, ma ritengo poco utile un dato così specifico che è consultabile da fonti più aggiornate e verificabili. 

Il giorno 24 ott 2020, 20:47, alle ore 20:47, Cristina Galasso <notifications@github.com> ha scritto:

**Comment by cristigalas** [comment]
@michelerestuccia va bene, allora la chiudo.
