### ISSUE TITLE
#Piemonte: dati per mappa laboratori e punti prelievo per #tamponi

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4003]
<pre><yamldata>
Cosa: '#Piemonte, dati per mappa laboratori e punti prelievo per #tamponi'
Descrizione: "Dati relativi a \n- laboratori pubblici e privati validati presenti\
  \ [allegato A]\n- punti prelievo dei laboratori privati temporaneamente abilitati\
  \ (per tutta la durata dello stato di emergenza) [allegato B]"
Link: https://www.regione.piemonte.it/web/temi/sanita/accesso-ai-servizi-sanitari/tamponi-covid-19-molecolari-pagamento
</yamldata></pre>

**Comment by michelerestuccia** [comment]
@mfortini @cristigalas 

I laboratori autorizzati ai tamponi sono di due tipi, e sono elencati in due pdf distinti (allegati di seguito).
Ho estratto i pdf in formato .csv e ho sistematizzato i dati geografici, lasciando in campo giallo alcuni elementi dubbi. 

- Tabelle in formato csv [cartella compressa .zip] 
[reg_piemonte_laboratori_tamponi.zip](https://github.com/emergenzeHack/covid19italia_segnalazioni/files/5433153/reg_piemonte_laboratori_tamponi.zip)

- Elenchi di partenza [formato PDF]: 
[_reg_piemonte_elenco_laboratori_tamponi_B_20201023.pdf](https://github.com/emergenzeHack/covid19italia_segnalazioni/files/5433144/_reg_piemonte_elenco_laboratori_tamponi_B_20201023.pdf)
[_reg_piemonte_elenco_laboratori_tamponi_A_20201023.pdf](https://github.com/emergenzeHack/covid19italia_segnalazioni/files/5433146/_reg_piemonte_elenco_laboratori_tamponi_A_20201023.pdf)
