### ISSUE TITLE
Lazio: elenco info per mappa con punti drivein e #tamponi pediatrici

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4005]
<pre><yamldata>
Cosa: 'Lazio: dati per mappa drivein e #tamponi pediatrici'
Descrizione: 'Elenco di punti drivein e #tamponi pediatrici.

  Elenco ottenuto copiando a mano le tre voci presenti nella pagina.

  Informazioni aggiornate al 22 ottobre 2020.'
Link: https://www.salutelazio.it/elenco-tamponi-drive-in
</yamldata></pre>

**Comment by michelerestuccia** [comment]
@mfortini @chiccap @cristigalas 
Allego i dati aggironati al 22 ottobre 2020 in .csv ma in una cartella .zip (github non fa allegare .csv alla issue).
I dati li ho copiati a mano perchè non c'era la possibilità di scaricarli in formato pdf

[_reg_lazio_elenco_drivein_tamponi_20201022.csv.zip](https://github.com/emergenzeHack/covid19italia_segnalazioni/files/5433344/_reg_lazio_elenco_drivein_tamponi_20201022.csv.zip)

**Comment by cristigalas** [comment]
@michelerestuccia questa e le altre issue che hai aperto sui pdf da estrarre andrebbero spostate qui https://github.com/emergenzeHack/covid19italia/issues
