### ISSUE TITLE
Protezione Civile, avviso per 2mila unità di personale medico sanitario e amministrativo per contact tracing

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4012]
<pre><yamldata>
Cosa: Protezione Civile, avviso per 2mila unità di personale medico sanitario e amministrativo
  per contact tracing
Descrizione: "Sono aperte le procedure per l’individuazione di 1500 unità tra personale\
  \ medico e sanitario e di 500 addetti all’attività amministrativa da impiegare,\
  \ su base territoriale, per rafforzare l’attività di ricerca e gestione dei contatti\
  \ dei casi (contact tracing). \n\nSarà possibile partecipare alla selezione compilando\
  \ il form, già disponibile sul sito del Dipartimento della Protezione Civile, fino\
  \ alle ore 19 del 26 ottobre 2020.\n\nAlla manifestazione di interesse per 1500\
  \ unità di personale da impiegare a supporto delle strutture sanitarie territoriali\
  \ impegnate nell’esecuzione dei tamponi, potranno partecipare medici, infermieri,\
  \ assistenti sanitari, tecnici della prevenzione e studenti universitari in discipline\
  \ infermieristiche e sanitarie.\n\nLe 500 unità che saranno impiegate per il supporto\
  \ amministrativo delle attività di contact tracing, saranno invece scelte tra soggetti\
  \ di età compresa tra i 18 e i 30 anni, in possesso del diploma di scuola secondaria\
  \ di secondo grado e di patente europea ECDL.\n\nLa partecipazione per entrambe\
  \ le procedure è consentita solo per la Regione di residenza o dimora.\n\nAl termine\
  \ della procedura selettiva, il Dipartimento redigerà un apposito elenco su base\
  \ regionale che sarà pubblicato sul sito dipartimentale e trasmesso alle Regioni\
  \ e alla Province autonome che, previa verifica dei requisiti, provvederanno al\
  \ conferimento degli incarichi."
Link: https://medicinaterritorialecovid19.protezionecivile.it/index.html
regione_manuale: tutte
</yamldata></pre>

**Comment by cristigalas** [comment]
Scaduta, chiudo.
