### ISSUE TITLE
#Lazio, trasporto pubblico: bando Cotral per operatori privati servizi bus integrativi a supporto delle corse scolastiche

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4019]
<pre><yamldata>
Da_chi_offerta: Regione Lazio - Cotral
Descrizione: 'La Regione Lazio comunica che è online il bando per l’affidamento a
  operatori privati dei servizi bus integrativi per supportare le corse scolastiche
  di Cotral fino alla fine dell’anno scolastico.
 Nel capitolato di gara sono già definite le corse aggiuntive, oltre alla previsione
  di ulteriori quote che potranno essere attivate in via d’urgenza. Questi elementi
  di flessibilità permetteranno all’azienda di gestire le criticità che di volta in
  volta si dovessero configurare.
L’affidamento di servizi aggiuntivi e integrativi del trasporto scolastico, suddiviso
  in 8 lotti territoriali, si rivolge alle imprese che operano nel settore dei trasporti
  di tipo gran turismo. Il termine di presentazione delle offerte scadrà il prossimo
  26 ottobre 2020. Gli operatori interessati dovranno qualificarsi sulla piattaforma
  telematica disponibile sul sito web cotralspa.it. L’importo complessivo dell’affidamento è di 7 milioni e 200mila euro.'
Destinatari: operatori privati dei servizi bus
Link: http://www.regione.lazio.it/rl_main/?vw=newsDettaglio&id=5834&fbclid=IwAR2Alq6T_wTwuO73F2erzHvm3qrnRWUgW5OLe4oWt_BL_oFPG3vc6tYSsb8
Natura: sostegno-lavor
Titolo: 'Lazio, trasporto pubblico: online bando bando per l’affidamento a operatori
  privati dei servizi bus integrativi per supportare le corse scolastiche'
regione_manuale: Lazio
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 44.89912921 8.20414255 (Asti) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=44.89912921+8.20414255&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by cristigalas** [comment]
Scaduta, chiudo.
