### ISSUE TITLE
Centri antiviolenza

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#402]
<pre><yamldata>
Cosa: Centri antiviolenza
Descrizione: Si precisa che non solo i Centri di.re assicurano assistenza. Sarebbe
  corretto dare notizia di tutti i Centri che mantengono reperibilità. Centro Antiviolenza
  Eva onlus di busto Arsizio
</yamldata></pre>

**Comment by cristigalas** [comment]
Qui che facciamo @favoeva @chiccap? Io direi di non accettare e chiudere...

**Comment by favoeva** [comment]
arriva da form? come facciamo a contattarlo per chiedergli i dettagli della loro reperibilità? scusa @cristigalas sono un po' tanto arrugginita ;)

**Comment by cristigalas** [comment]
@favoeva ho visto che loro stesse hanno inviato segnalazione con loro servizi e recapiti. Quindi qui chiudo.
