### ISSUE TITLE
Divulga dati di dubbia provenienza

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4021]
<pre><yamldata>
Cosa: CANALE TELEGRAM
Descrizione: Divulga dati di dubbia provenienza
Link: https://t.me/covid19
</yamldata></pre>

**Comment by cristigalas** [comment]
È un canale Telegram attivo fin dai primi giorni della pandemia e divulga notizie da fonti considerate sicure (governo, regioni, media). Non accetto.
