### ISSUE TITLE
Regione #Lazio: bando per reclutamento personale medico in quiescenza

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4027]
<pre><yamldata>
Cosa: 'Regione Lazio: bando per reclutamento personale medico in quiescenza'
Descrizione: "L'Unità di Crisi Regione Lazio ha pubblicato il bando per il reclutamento\
  \ straordinario di personale medico in quiescenza. Per far fronte all'emergenza\
  \ Covid-19 la Regione Lazio ha bandito una manifestazione di interesse per il reclutamento\
  \ di personale medico in quiescenza nelle specializzazioni di:\n- Malattie Infettive\n\
  - Anestesia e Rianimazione\n- Malattie apparato respiratorio\n- Igiene e Medicina\
  \ preventiva \n- Medicina e Chirurgia d'accettazione d'Urgenza\n- Radiodiagnostica\n\
  - Patologia Clinica\n- Virologia e Microbiologia\n\nGli interessati devono compilare\
  \ entro il 29 ottobre la domanda online sul sito: https://www.hsangiovanni.roma.it/104013228-altre-tipologie-di-avvisi-e-selezioni-1.html."
Link: http://www.regione.lazio.it/rl_main/?vw=newsDettaglio&id=5840
regione_manuale: Lazio
</yamldata></pre>

**Comment by cristigalas** [comment]
Scaduto. Chiudo.
