### ISSUE TITLE
Elenco tamponi drive-in #Lazio

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4031]
<pre><yamldata>
Cosa: 'Elenco tamponi drive-in #Lazio'
Link: https://www.salutelazio.it/elenco-tamponi-drive-in
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente https://github.com/emergenzeHack/covid19italia_segnalazioni/issues/3995
