### ISSUE TITLE
Linea di ascolto e supporto sociale #Milano 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4033]
<pre><yamldata>
Da_chi_offerta: Brigate Volontarie per l'emergenza
Descrizione: "Da oggi, lunedì 26 ottobre, la linea della Brigata Basaglia torna completamente\
  \ attiva! \nNell'ottica di un'emergenza che è ormai diventata realtà, l'attività\
  \ della Brigata vuole tornare a essere telefonica e online per riuscire a essere\
  \ ovunque, per permettere a tutt* di raggiungerci senza rischi e senza vincoli.\
  \ \nVogliamo nuovamente attivare un'iniziativa di ascolto e costruire insieme strumenti\
  \ di supporto sociale per il benessere delle nostre menti, dei nostri corpi e delle\
  \ nostre vite. \nAbbiamo soprattutto in mente tuttx coloro che lavorano precariamente,\
  \ tuttx coloro che lavorano nella sanità, tuttx coloro che faticano ad adattarsi\
  \ alla realtà della pandemia, tuttx coloro che non hanno mura accoglienti o sicure\
  \ nel caso di una nuova chiusura. \nDA LUNEDÌ A VENERDÌ \n\U0001F449DALLE ORE 12\
  \ ALLE ORE 14:30 OPPURE DALLE ORE 19 ALLE ORE 21:30 \n☎️ 02 82396915\nbrigatabasagliamilano@gmail.com"
Destinatari: tutti
Link: https://www.facebook.com/brigatevolontarieMilano
Natura: solidale
Posizione: 45.466232 9.195179 0 0
Tipo_di_soggetto: privato
Titolo: Linea di ascolto e supporto sociale
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
