### ISSUE TITLE
Infermieri e infermiere per cure domiciliai di anziani soli e anziane sole

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#405]
<pre><yamldata>
Cosa: Infermieri e infermiere per cure domiciliai di anziani soli e anziane sole
Descrizione: 'Nel caso in cui  una o un anziano solo/a necessitasse di cure a casa
  (punture ad esempio) per sospette polmoniti, a chi ci si può rivolgere?

  Grazie'
Destinatari: Infermiere/i - Enti di volontariato
Email: Pugliesevi@gmail.com
</yamldata></pre>

**Comment by cristigalas** [comment]
Mi sembra una presa di giro. Chiudo.
