### ISSUE TITLE
ASL #Roma 3 domenica 8 e 22 novembre open day dedicati al vaccino antinfluenzale 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4058]
<pre><yamldata>
Da_chi_offerta: Asl Roma 3
Descrizione: 'Domenica 8 e 22 novembre, dalle ore 8:30 alle ore 19:30, la ASL Roma
  3 organizzerà open day dedicati alla vaccinazione antinfluenzale.
  Per i cittadini residenti nel territorio di competenza della ASL Roma 3, con età
  compresa tra i 6 e i 59 anni, privi di patologie di rischio, la prestazione sarà
  gratuita e senza prenotazione.
  Sono previste due postazioni di vaccinazione:
  1) Acilia struttura tensostatica dedicata – parcheggio di fronte presidio ASL Roma
  3 di via Casal Bernocchi n. 73;
  2) San Camillo Ex asilo ospedale - via Ramazzini n. 66;'
Link: https://www.facebook.com/ASLRoma3/photos/a.118601093190562/179455410438463/
Natura: solidale
Tipo_di_soggetto: pubblico
Titolo: OPEN DAY VACCINAZIONE ANTINFLUENZALE
Posizione: 41.8713278, 12.4669875
</yamldata></pre>

**Comment by cristigalas** [comment]
Scaduto. Chiudo.
