### ISSUE TITLE
Individuati dal Cert-AgID i preparativi per una campagna di malware via SMS volta ad ingannare i cit

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4066]
<pre><yamldata>
Cosa: 'SPID: attività di phishing su identità digitali di Poste Italiane.'
Descrizione: Individuati dal Cert-AgID i preparativi per una campagna di malware via
  SMS volta ad ingannare i cittadini che hanno attiva un'identità digitale con Poste
  Italiane.
Link: https://cert-agid.gov.it/news/attivita-di-phishing-su-spid-di-poste-italiane-attualmente-in-corso/
</yamldata></pre>

**Comment by cristigalas** [comment]
Questa non l’accetterei perché non c’entra con la pandemia. Che dite @favoeva @michelerestuccia?

**Comment by michelerestuccia** [comment]
Concordo 

Il giorno 6 nov 2020, 12:20, alle ore 12:20, Cristina Galasso <notifications@github.com> ha scritto:
