### ISSUE TITLE
𝗘𝗰𝗰𝗼 𝗶𝗹 𝗺𝗮𝗻𝘂𝗮𝗹𝗲 𝗰𝗵𝗲 𝗮𝘃𝗿𝗲𝗺𝗺𝗼 𝘃𝗼𝗹𝘂𝘁𝗼 𝗮𝘃𝗲𝗿𝗲 𝗮 𝗺𝗮𝗿𝘇𝗼 𝟮𝟬𝟮𝟬🔴
🔽🔽🔽
www.superbergamo.org/manuale_super
Abbiam

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4091]
<pre><yamldata>
Da_chi_offerta: SuperBergamo
Descrizione: "\U0001D5D8\U0001D5F0\U0001D5F0\U0001D5FC \U0001D5F6\U0001D5F9 \U0001D5FA\
  \U0001D5EE\U0001D5FB\U0001D602\U0001D5EE\U0001D5F9\U0001D5F2 \U0001D5F0\U0001D5F5\
  \U0001D5F2 \U0001D5EE\U0001D603\U0001D5FF\U0001D5F2\U0001D5FA\U0001D5FA\U0001D5FC\
  \ \U0001D603\U0001D5FC\U0001D5F9\U0001D602\U0001D601\U0001D5FC \U0001D5EE\U0001D603\
  \U0001D5F2\U0001D5FF\U0001D5F2 \U0001D5EE \U0001D5FA\U0001D5EE\U0001D5FF\U0001D607\
  \U0001D5FC \U0001D7EE\U0001D7EC\U0001D7EE\U0001D7EC\U0001F534\n\U0001F53D\U0001F53D\
  \U0001F53D\nwww.superbergamo.org/manuale_super\nAbbiamo pensato fosse importante\
  \ condividere il sistema con cui abbiamo lavorato durante il primo lockdown, in\
  \ modo da dare suggerimenti, informazioni e supporto a chi, oggi, vuole mettersi\
  \ in gioco per proporre un servizio simile.\nLa vera forza è stata l’immaginazione\
  \ e la creatività. Perché allora, manuali, non ce n’erano.\nAbbiamo organizzato\
  \ in tempo reale. \nQui trovate l’assetto migliore che abbiamo ottenuto.\nSenza\
  \ pretesa, ma sperando sia uno strumento utile.\nForse il miglior consiglio è essere\
  \ creativз, immaginare possibilità e trovare soluzioni. \nSi presenteranno problemi\
  \ in maniera costante. \nSta a voi elaborare strategie per risolverli.\nSiamo nella\
  \ seconda ondata, alcuni problemi saranno complessi e nuovi, altri speriamo siano\
  \ più facili da risolvere.\nQuesto vademecum contiene la nostra esperienza che non\
  \ è mai stata “solo” di servizi consegna, ma sempre attenta a lavorare sulle relazioni\
  \ e i rapporti tra le persone. \nQuesto modo, siamo certз, abbia saziato molto più\
  \ del cibo.\n\U0001D436\U0001D45C\U0001D460\U0001D44E \U0001D453\U0001D44E \U0001D462\
  \U0001D45B \U0001D45D\U0001D45C\U0001D45D\U0001D45C\U0001D459\U0001D45C \U0001D45E\
  \U0001D462\U0001D44E\U0001D45B\U0001D451\U0001D45C \U0001D452̀ \U0001D456\U0001D45B\
  \ \U0001D451\U0001D456\U0001D453\U0001D453\U0001D456\U0001D450\U0001D45C\U0001D459\
  \U0001D461\U0001D44È?\nPS: Stiamo tornando. Per info, per supporto, per idee, per\
  \ partecipare: supporto@superbergamo.org\nAll’indirizzo www.superbergamo.org/manuale_super\
  \ potete scaricare il manuale e gli allegati.\nAbbiamo creato un canale Telegram\
  \ che vuole essere di supporto e coordinamento. Se vi va di iscrivervi, questo l’indirizzo:\
  \ https://t.me/super_int"
Link: https://superbergamo.org/manuale_super.pdf
Natura: solidale
Tipo_di_soggetto: privato
Titolo: Manuale per l'attivazione in emergenza
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente, vedi #4076.
