### ISSUE TITLE
A #Roma, quartiere San Lorenzo, sabato 14 novembre raccolta di cibo e beni essenziali per le famiglie in difficoltà a causa dell’emergenza coronavirus 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4094]
<pre><yamldata>
Da_chi_offerta: Libera Repubblica di San Lorenzo
Descrizione: "Vi aspettiamo sabato dalle 10 alle 13 per una RACCOLTA di beni essenziali\
  \ per il programma QUARANTENA SOLIDALE! \n\U0001F310DOVE: Nuovo Cinema Palazzo \n\
  Piazza dei Sanniti 9a, San Lorenzo \n\U0001F55BQUANDO: sabato 14 novembre ore 10-13\n\
  \U0001F6D2COSA PORTARE? \nPacchi di mascherine chirurgiche per bambini e adulti\n\
  Pannolini (taglie dalla 3 alla 6) \nLatte in polvere (neonati numero 1 e 2 e latte\
  \ Mio per 1 anno)\nOmogeneizzati \nIgienizzante per mani \nIgienizzante per superfici\
  \ \nShampoo \nBagno schiuma \nDentifricio\n\U0001F3AFLa raccolta sarà distribuita\
  \ nei pacchi di cibo e beni essenziali per le famiglie del territorio che seguiamo\
  \ con il programma Quarantena Solidale. \nIl contributo di ciascuno/a di noi è\
  \ essenziale affinché nessuno/a resti indietro.\n\n\nLibera Repubblica di San Lorenzo\n\
  Nuovo Cinema Palazzo\nANPI San Lorenzo\nAtletico San Lorenzo\nCommunia\nEsc Atelier\n\
  Il Grande Cocomero\nLa GRU - Germogli di Rinascita Urbana"
Destinatari: tutti
Link: https://www.facebook.com/LiberaRepubblicaDiSanLo/photos/a.296490690525210/1753372321503699/
Natura: solidale
Tipo_di_soggetto: privato
Titolo: Quarantena Solidale
Posizione: 41.8987981, 12.5169243
</yamldata></pre>

**Comment by cristigalas** [comment]
Scaduto. Chiudo.
