### ISSUE TITLE
gruppi video tematici settimanali mirati al mantenimento delle relazioni, contrasto delle condizioni

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4116]
<pre><yamldata>
Cosa: iniziative culturali ricreative, supporto psicologico
Descrizione: 'gruppi video tematici settimanali mirati al mantenimento delle relazioni,
  contrasto delle condizioni di isolamento, stimolazione cognitiva

  Supporto psicologico telefonico'
Destinatari: rivolti ad adulti, giovani adulti con disabilità e rispettive famiglie
Email: info@amicidisilvia.it
Link: http://www.amicidisilvia.it/
Telefono: '3479305103'
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente #4115
