### ISSUE TITLE
Casa Espana Milano, lunedì 23 novembre lezioni di spagnolo in diretta Instagram

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4119]
<pre><yamldata>
Da_chi_offerta: Casa de Espana Milan - Samely Lab
Descrizione: 'Te esperamos en INSTAGRAM - Nuestra 20 ° Directa !!
  Lunes 23 Novembre 2020
  a las 19h30.
  Atención! necesario seguir las cuentas de Instagram de @School2u_Milan , @samely_lab
  y @casadeespanamilan para poder ver el directo.'
Destinatari: italiani o straniere con voglia di imparare lo spagnolo
Link: https://www.casadeespanamilan.it/%C3%BAltimas-noticias/
Natura: culturale-ricr
Titolo: Instagram Diretta spagnolo gramatica
</yamldata></pre>

**Comment by cristigalas** [comment]
Scaduto.
