### ISSUE TITLE
Associazione di volontariato shukran Somalia-onlus.  
                                         (Codi

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4124]
<pre><yamldata>
BIC_SWIFT: BIC   BCITITMX
CC_Postale: 1000 /  00076664
Causale: Progetto sostegno scuola in  Somalia
Descrizione: "Associazione di volontariato shukran Somalia-onlus.  \n            \
  \                             (Codice Fiscale : 97650510155)\nMilano;  21/11/2020\n\
  Oggetto; richiesta  di Donazione  progetto  Istruzione dedicato ai Minorenni e Orfani\
  \ svantaggiati.\nEgr. Direttore/e\nAssociazione  Shukran Somalia è impegnato il\
  \ settore della Istruzione  con professionalità  al fine  di erogare servizi alle\
  \ ragazzi e ragazze tale di rispondere puntualmente  ai bisogno  crescenti delle\
  \ persone bisognosi in particolare  minorenni orfani e  alle loro famiglie. \nll\
  \ diritto all'educazione e l’Istruzione  è la premessa fondamentale per lo sviluppo\
  \ ed è lo strumento più valido per combattere la povertà, la disuguaglianza, l’analfabetismo\
  \ , emarginazione e sfruttamento. I bambini e giovani  Senza  Istruzioni sono  come\
  \ Uccelli senza  le ali. Lavoriamo, in Italia  per garantire questo diritto a tutti\
  \ i bambini senza alcuna discriminazione a partire dalle ragazze e ragazzi . In\
  \ Somalia non esiste una scuola statale per 30  anni e in questo fase  ripartizione\
  \ e  di realtà il diritto  all’Educazione e fondamentale.\n-Effetto del (Covid-19)\
  \ in Somalia e in Italia: In questo anno , in cui la vita  di tutti noi è stata\
  \ stravolta, l’ Ass. shukran Somalia  ha cercato per quando fosse  possibile di\
  \  mantenere viva tutte le sue attività. le forti emozionante, paura ,dolore e i\
  \ grandi cambiamento  che  stiamo vivendo in Italia, hanno  colpito le nostre attività\
  \ nei paesi dove  operiamo ( Somalia e Italia). Somalia e uno dei paesi a ad alto\
  \  Rischio della Pandemia. I  tassi di malnutrizione  e( 40% ) dei bambini e di\
  \ immunodepressione sono   molte alti. la istituzioni locale non hanno risorse finanziarie\
  \ .  \n -Shukran Somalia  collabora con il suo partner-locale e sta lavorando  nel\
  \ quartiere  Werdhigley, precisamente cento- nord di Mogadiscio. In Italia sono\
  \ state bloccate tutte le nostre  attività tra ” Eventi e Raccolta fondi per sostenere\
  \ la scuola a Mogadiscio “ e  questo momento abbiamo la difficoltà di finanziamenti\
  \ per sostenere  la nostra attività di inserimento scolastico.  \n  \n“ Il progetto\
  \ Adotta un insegnante”. L'Associazione  Shukran Somalia,  nasce con l'obiettivo\
  \ di lavorare anche  in Somalia, attraverso il progetto intitolato “Adotta un insegnante”\
  \ \nL’associazione sta lavorando ormai da anni  ad un progetto di solidarietà  molto\
  \ ambizioso, che prevede per l’inserimento scolastico  dei bambini nella città di\
  \ Mogadiscio. L’attività consiste  nell’ Aiutare i  giovani  ad iniziare e continuare\
  \  i loro  studi con   un completo ed adeguato insegnamento svolto in luoghi sicuri\
  \ e confortevoli. \n-Nel 2014 abbiamo avviato  a ( Mogadiscio) questo programma\
  \ /progetto per sostenere gli  insegnanti  di una scuola  elementare per permettere\
  \   alle  nuove  generazioni  di studiare  e potere costruire  un futuro  migliore.\
  \ \nAdotta un insegnante è una forma  di sostegno  a lungo  termine per gli insegnanti\
  \  che possono così offrire  agli  studenti  un  programma  solido e duraturo. Oltre\
  \ il progetto “Adotta un insegnante” che tutt’oggi è in corso; vogliamo aggiungere\
  \ una scuola di Alfabetizzazione in un   quartiere disagiato  di Mogadiscio e l’inserimento\
  \ lavorativa i giovani. La nostra associazione ha la necessità di  soccorrere chi\
  \ ha più bisogno. \nLa Somalia, è un stato dell’Africa Orientale situato nel corno\
  \ d’Africa. Il  paese è soggetto a periodiche tra(alluvione e  siccità) che hanno\
  \ peggiorato  la già precaria, situazione di vita delle popolazione. La malnutrizione\
  \ è in crescita  acuta,  e colpisce il 40% della popolazione. La mancanza di Educazione\
  \ scolastica  è drammatica e tocca tutte le fasce di età; il tasso di alfabetizzazione\
  \ è fermo circa 30,5 % circa.\nDal 1991  ad oggi si sono susseguiti disordini e\
  \  scontri  tribali. L’azione dei signori della guerra   ha causato  in 27 anni\
  \ di guerra civile  milioni di perdite ed un numero indecifrabile di  sfollati.\
  \ Nel vuoto istituzionale  somalo, le organizzazione non  governative (ong), locali\
  \ ed internazionali  hanno acquistato  un ruolo di grande rilievo  nella vita del\
  \ paese .\n-Nel 2010 le diaspore con le loro associazioni ebbero un ruolo fondamentale\
  \ nelle attività di sostegno del paese ricorrendo all’ efficace metodo del  di micro\
  \ credito che permette  l’inserimento lavorativo di giovani nelle strutture che\
  \ il finanziamento crea.\n-Noi come associazione abbiamo partecipato un progetto\
  \ promosso dell’Organizzazione internazionale per la Migrazione ( OIM) e grazie\
  \ questi fondi abbiamo sostenuti  un gruppo di Giovani a Kismaio oltre i progetti\
  \ locale svolte in hinterland milanese.\n-In Somalia , quando una famiglia riceve\
  \ sostegno  dei parenti lontani  i beneficiari condividono l’aiuto con i propri\
  \ vicini . E’ un tradizione di solidarietà che accomuna  tutta la popolazione locale.\
  \ Ecco perchè le diaspore hanno un ruolo fondamentale per la collettività e sono\
  \ determinanti nell’ azione recupero civile del proprio paese d’origine.\n-Il nostro\
  \ obiettivo è quello di combattere la povertà  educativa, aumentando il tasso di\
  \ alfabetizzazione dal 20 al 30 % dei bambini o studenti  tra 6/17 anni in poi \
  \ e delle donne adulte.\n-Nel 2017 abbiamo ricevuto una richiesta  per 30   Giovani\
  \ ragazze e  ragazzi   svantaggiati che necessitano almeno di  imparare a leggere\
  \ e scrivere. L’istruzione è  una via per aprirsi al mondo e agli altri.  il nostro\
  \ sogno è quello di realizzare  qualche spazio  ed attrezzarlo per adibirlo ad aula\
  \ scolastiche con il materiale didattico necessario. \nIn effetti; il progetto di\
  \ inserimento gli  istruzione  è un elemento  importante  dell’intervento  educativo\
  \ per questi 30 ragazze/i e donne; è  per questo motivo  abbiamo bisogno di  partecipare\
  \ a piccoli progetti . i tempi  sono stretti; come associazione ne siamo consapevoli,\
  \  ma vorremmo proprio realizzare questo  sogno il prima possibile. - Per riuscirci\
  \ contiamo su tutti voi, che potete essere i Custodi delle speranze  dei nostri\
  \ bambini, ragazze/i , donne e famiglie fragili  \nAttività in Italia; ogni anno\
  \ svolgiamo il  programma annuale della  Settimana Culturale e Artistica  Somala\
  \    “Milan Somali Week”. Inoltre il  sette anni  di attività nel sociale, Ass.s\
  \  shukran  e stato  sempre il  fianco anche ai Rifugiati  attraverso il sostegno\
  \ di sistema linguistica, socializzazione e sensibilizzazione, grazi  i mediatrici\
  \ culturali volontari.\n\nContatti: email, info.associazione.shukran@gmail.com;\
  \ 3406023002\n         Nuurta2008@hotmail.com; FB:  Associazione shukran Somalia\
  \ –onlus ;  Fb: Milan Somali Week.\nSede Legale: Via Costantino Baroni 70°-CAP-20142\
  \ Milano;  email, Info.associazione.shukran@gmail.com; telef: 3406023002, \nSede\
  \ operativa: Via Saponaro 20- CAP- 20142 Milano."
Email: info.associazione.shukran@gmail.com
IBAN: IT39 Q033 5901 6001 000000 76664
Intestazione: 'Intestato A:  Shukran'
Link: https://www.youtube.com/
Nome: Associazione Shukran Somalia (onlus)
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 45.46679408 9.1903474 (Milano) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=45.46679408+9.1903474&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by cristigalas** [comment]
Non pare c’entrare nulla con l’emergenza...
