### ISSUE TITLE
All’interno della drammatica esperienza che stiamo vivendo in seguito alla pandemia di Covid-19 rite

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4126]
<pre><yamldata>
Da_chi_offerta: Associazione Psyché
Descrizione: 'All’interno della drammatica esperienza che stiamo vivendo in seguito
  alla pandemia di Covid-19 riteniamo essenziale fornire un supporto alle persone.

  Per la maggior parte della popolazione, l’emergenza sanitaria non si concretizza
  con un ricovero o una riduzione della salute fisica, ma ha un grande impatto psicologico:
  lutti e mancanza di elaborazione di questi, isolamento forzato, ritmi di lavoro
  estenuanti, blocco dei progetti lavorativi e di vita, problemi familiari legati
  alla convivenza forzata, possibili ricadute negative economiche. Tutti questi eventi
  rappresentano esperienze potenzialmente traumatiche e di difficile risoluzione per
  chi dovrà affrontarle da solo. Psyché c''è e fornisce gratuitamente consulenze psicologiche
  attraverso la sua rete di psicologi e psicoterapeuti. Chiamate al 328 5773217 o
  scriveteci: info@associazionepsyche.it'
Destinatari: tutta la cittadinanza, sia adulti che bambini e ovviamente gli operatori
  sanitari
Natura: solidale
Tipo_di_soggetto: privato
Titolo: Supporto psicologico emergenza Covid-19
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
