### ISSUE TITLE
SuperBergamo attiva il servizio di spesa solidale #Bergamo

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4140]
<pre><yamldata>
Da_chi_offerta: SuperBergamo
Descrizione: supporto alla città di bergamo...
Natura: solidale
Posizione: 45.75666 9.75422
Tipo_di_soggetto: privato
Titolo: Spesa solidale
</yamldata></pre>

**Comment by chiccap** [comment]
Ciao @Saraveg non so se inserire o meno.
