### ISSUE TITLE
Progetto di mutuo aiuto e sostegno alimentare, attraverso donazioni private sia di beni che di fondi

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4165]
<pre><yamldata>
Da_chi_offerta: Casa del Popolo Casal Bruciato
Descrizione: Progetto di mutuo aiuto e sostegno alimentare, attraverso donazioni private
  sia di beni che di fondi. E' possibile donare materiale, attivarsi con i/le volontari/e,
  richiedere un supporto.
Link: https://www.facebook.com/CasaDelPopoloCasalBruciato/photos/a.2034648463452088/2839285839655009/
Natura: solidale
Posizione: 41.904279 12.551034 0 0
Tipo_di_soggetto: privato
Titolo: Damose na mano! Attiviamo la solidarietà
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
