### ISSUE TITLE
Verrà realizzata, il 20 Dicembre, una giornata di distribuzione di pacchi della solidarietà destinat

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4166]
<pre><yamldata>
Da_chi_offerta: Don't Panic Organizziamoci - Bologna
Descrizione: 'Verrà realizzata, il 20 Dicembre, una giornata di distribuzione di pacchi
  della solidarietà destinati a quei nuclei familiari che più ne hanno bisogno grazie
  ad un sistema di consegne a domicilio e con la formula del “pacco regalo sospeso”.

  E'' stata infatti realizzata una piattaforma destinata alla cura e alla solidarietà
  come elementi essenziali del vivere comune e in quanto unici strumenti per superare
  tutti e tutte insieme questa drammatica crisi.'
Link: https://www.facebook.com/DontPanicBologna/
Natura: solidale
Posizione: 44.495342 11.342045 0 0
Tipo_di_soggetto: privato
Titolo: Consegna alimentare di Natale attraverso piattaforma rider
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
