### ISSUE TITLE
Una mappatura – a livello nazionale – dei servizi rivolti ai richiedenti asilo e titolari di protezi

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4167]
<pre><yamldata>
Da_chi_offerta: Arci nazionale con il supporto dell’ UNHCR Italia - Agenzia ONU per
  i Rifugiati ed il contributo di decine di organizzazioni
Descrizione: Una mappatura – a livello nazionale – dei servizi rivolti ai richiedenti
  asilo e titolari di protezione internazionale con contenuti disponibili in 15 lingue.
  Il progetto nasce dall’esigenza di offrire uno strumento che consenta ai richiedenti
  e titolari di protezione di orientarsi sul territorio e accedere ai servizi di cui
  hanno bisogno e per mettere in rete i vari attori della gestione del fenomeno migratorio.
Destinatari: Richiedenti asilo, titolari di protezione internazionale e associazioni
  del settore.
Link: https://www.jumamap.it/it/
Natura: solidale
Tipo_di_soggetto: privato
Titolo: JumaMap – Services for Refugees
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
