### ISSUE TITLE
Il vaccino ci farà diventare dei cyborg

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4185]
<pre><yamldata>
Cosa: Il vaccino ci farà diventare dei cyborg
Link: https://m.facebook.com/story.php?story_fbid=10224663605647933&id=1544408261&sfnsn=scwspwa
</yamldata></pre>

**Comment by cristigalas** [comment]
Non accetto. Il link non rimanda alla smentita di una bufala ma ad una bufala pubblicata su Facebook.
