### ISSUE TITLE
Incontro organizzato dal "safe space" mamme di Intersos, in collaborazione con ASL Roma 1 e progetto

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4187]
<pre><yamldata>
Da_chi_offerta: Intersos LAB - Centro di Formazione - Polo Territoriale
Descrizione: Incontro organizzato dal "safe space" mamme di Intersos, in collaborazione
  con ASL Roma 1 e progetto I.C.A.R.E. Necessaria la prenotazione
Link: http://www.intersos.org/
Natura: culturale-ricr
Posizione: 41.964787 12.402964 0 0
Titolo: Incontro sul tema "donne e salute"
</yamldata></pre>

**Comment by cristigalas** [comment]
Non accetto. Non c’è data dell’incontro e altre info, nemmeno sul sito.
