### ISSUE TITLE
Screening gratuito legato all'emergenza Corona Virus-19, dall'11 al 21 gennaio 2021. 
Per ulteriori 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4193]
<pre><yamldata>
Da_chi_offerta: Regione Abruzzo, Comune di Pescara, ASL di Pescara, Protezione Civile
Descrizione: "Screening gratuito legato all'emergenza Corona Virus-19, dall'11 al\
  \ 21 gennaio 2021. \nPer ulteriori informazioni il numero di telefono è 085 4283400."
Destinatari: Le cittadine ed i cittadini di Pescara
Link: http://www.comune.pescara.it/internet/index.php?codice=1076&fbclid=IwAR2poICnFIhYBTo78kYNoBKGJPWDc4aNYDv95Ec1nebZ38ufY6WE7rdQdwM
Natura: solidale
Posizione: 42.469147 14.205528 0 0
Tipo_di_soggetto: pubblico
Titolo: Screening gratuito della popolazione residente a Pescara
</yamldata></pre>

**Comment by cristigalas** [comment]
Praticamente è già scaduto. Chiudo.
