### ISSUE TITLE
Nell'istituto San Leo di Sessa Aurunca si è verificato un caso covid. Su questo caso circolano notiz

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4197]
<pre><yamldata>
Cosa: Caso covid in unità scolastica
Descrizione: Nell'istituto San Leo di Sessa Aurunca si è verificato un caso covid.
  Su questo caso circolano notizie molto contrastanti che farebbero pensare ad una
  non appropriata gestione del caso. Dalla dirigente scolastica arrivano solo rassicurazioni
  a mezzo stampa ma non vi è stato finora una presa di posizione certificata e a garanzia
  di un rientro a scuola degli alunni in tutta sicurezza. Urge fare luce sul caso
  che potrebbe estendersi a macchia d'olio per omissioni più o meno volontarie
Posizione: 41.23818 13.93459 0 0
</yamldata></pre>

**Comment by cristigalas** [comment]
Non pertinente e senza link o altri riferimenti.
