### ISSUE TITLE
Avviso pubblico manifestazione di interesse Medici Regione #Calabria

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#420]
<pre><yamldata>
Cosa: 'Avviso Pubblico Manifestazione di Interesse per Medici Regione #Calabria'
Descrizione: Avviso Pubblico Manifestazione di Interesse per Medici Specialisti, Medici
  Specializzandi e Medici Laureati disponibili a prestare attività Clinico Assistenziale
  nelle Aziende Sanitarie e Ospedaliere del S.S.R. della Regione Calabria necessaria
  a garantire l’erogazione delle prestazioni di assistenza sanitaria in ragione delle
  esigenze straordinarie ed urgenze derivati dalla diffusione del COVID-19.
Destinatari: Medici Specialisti, Medici Specializzandi e Medici Laureati
Indirizzo: 38.105943 15.659821 0 0
Link: https://portale.regione.calabria.it/website/portaltemplates/view/view.cfm?17056
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Avviso chiuso 19 marzo. Chiudo issue
