### ISSUE TITLE
Ho bisogno di aiuto per spesa - Milano

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4200]
<pre><yamldata>
Cosa: spesa
Descrizione: ho bisogno di un aiuto
Destinatari: milano
Email: sami.farag@libero.it
Nome: marina rezk
Telefono: '3515370825'
</yamldata></pre>

**Comment by cristigalas** [comment]
Provo ad inviarle una email segnalandole le Brigate Volontarie.

**Comment by cristigalas** [comment]
Ad oggi non abbiamo ricevuto nessuna risposta. Chiudo.
