### ISSUE TITLE
Un team del Laboratorio di psicologia dell'Università di G. D’Annunzio, in collaborazione con l’Univ

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4201]
<pre><yamldata>
Cosa: Ricerca sulle emozioni ed il corpo in rapporto alla pandemia Covid-19
Descrizione: 'Un team del Laboratorio di psicologia dell''Università di G. D’Annunzio,
  in collaborazione con l’Università di Bordeaux, sta conducendo uno studio online
  sull''impatto del Covid-19 sulle nostre emozioni. Tutti possono partecipare, se
  vuoi dare li tuo contributo clicca sul link:

  https://psysurvey.u-bordeaux.fr/limesurvey/index.php/519883?lang=it&fbclid=IwAR1Si_TcI6FKCYRaDDA0EZ-O8KE6xe4MIiENcMprGnhFbNIy2rQLm_1RsUs'
Fonte: Università di Bordeaux & Università degli studi Gabriele D'annunzio
Link: https://www.facebook.com/photo?fbid=10224774245207240&set=a.1094507326665
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente, vedi #4168
