### ISSUE TITLE
Lo spazio Sparwasser, circolo culturale e sociale del quartiere Pigneto, si trasforma da luogo ricre

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4204]
<pre><yamldata>
Cosa: Ospitalità per persone senza dimora nella città di Roma
Descrizione: Lo spazio Sparwasser, circolo culturale e sociale del quartiere Pigneto,
  si trasforma da luogo ricreativo e formativo a luogo di accoglienza per chi è costretto
  a vivere in strada. Un centro di accoglienza notturna e distribuzione pasti.
Destinatari: Senza dimora della città di Roma
Immagine: 142064600_1389144394760793_7553332450313720038_o-13_17_55.jpg
Link: https://www.facebook.com/ArciSparwasser/photos/a.186052468403331/1389144391427460
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 41.89277044 12.48366723 (Roma) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=41.89277044+12.48366723&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by cristigalas** [comment]
Già presente, vedi #4203.
