### ISSUE TITLE
Raggiunti i 100 milioni di casi Covid-19 in tutto il mondo

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4209]
<pre><yamldata>
Cosa: 100 milioni di casi Covi-19
Descrizione: Raggiunti i 100 milioni di casi Covid-19 in tutto il mondo
Link: https://www.facebook.com/curaitalia/photos/a.117476999896784/245229670454849/
</yamldata></pre>

**Comment by cristigalas** [comment]
Non pertinente.
