### ISSUE TITLE
In Italia il concorrere dell'emergenza sanitaria e della crisi economica ha determinato una forte ri

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4211]
<pre><yamldata>
Cosa: La crisi che colpisce la tutela alla salute
Descrizione: In Italia il concorrere dell'emergenza sanitaria e della crisi economica
  ha determinato una forte riduzione del volume di persone che si rivolgeva a cure
  pubbliche per altre patologie.
Link: https://www.dalsociale24.it/gli-italiani-hanno-rinunciato-a-curarsi/?fbclid=IwAR3-1sxMDm4PFNW38Oxi6txObetIbyDSJqHLMcRINwiuy-qGFhtIpsFyvUs
</yamldata></pre>

**Comment by cristigalas** [comment]
Non pertinente.
