### ISSUE TITLE
A cura della dott.ssa Barbara Gambadori è possibile prenotare sessioni di ascolto e sostegno psicolo

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4218]
<pre><yamldata>
Da_chi_offerta: Villetta Social Lab - Roma
Descrizione: A cura della dott.ssa Barbara Gambadori è possibile prenotare sessioni
  di ascolto e sostegno psicologico. Per info e prenotazioni è possibile scrivere
  alla mail villettagarbatella.info@gmail.com oppure chiamare il numero 348 648 5462
Link: https://www.facebook.com/VillettaSocialLab/photos/a.627648747362869/3641723239288723/
Natura: solidale
Posizione: 41.861946 12.487423 0 0
Tipo_di_soggetto: privato
Titolo: Sportello di consulenza e sostegno psicologico
</yamldata></pre>

**Comment by cristigalas** [comment]
Non specifica se è gratuito. Non accetto.
