### ISSUE TITLE
Cercasi volontari per commissioni a domicilio - Comune di #Bari

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#422]
<pre><yamldata>
Comune: Bari
Da_chi_offerta: Comune di Bari
Descrizione: "VORRESTI DIVENTARE VOLONTARIO/A per aiutare nelle consegne a domicilio\
  \ di beni alimentari, di prima necessit\xE0 e farmaci, per i cittadini in difficolt\xE0\
  \ che ne faranno richiesta?\n\nPossono aderire volontari appartenenti ad associazioni,\
  \ ma anche singoli cittadini, inviando la propria disponibilit\xE0 alla mail segreteriawelfarebari@comune.bari.it."
Destinatari: Associazioni, cittadine e cittadini Comune di Bari
Link: http://www.comune.bari.it/-/contenimento-e-gestione-dell-emergenza-epidemiologica-pronto-il-piano-di-azioni-e-misure-dell-assessorato-al-welfare-a-sostegno-delle-persone-fragili-?fbclid=IwAR0lceZqsTe1MY-_fVp9QhylEFQAF3UAuB_mPoosKzBxgQBhJIgF888WB4c
Natura: solidale
Posizione: 41.11588 16.856787 0 0
Provincia: Bari
Regione: Puglia
Tipo_di_soggetto: pubblico
Titolo: 'Ricerca volontari commissioni a domicilio Comune di #Bari'
</yamldata></pre>

**Comment by luciaroma** [comment]
@chiccap sentiamo Grazia se ha aggiornamenti su questo fronte?

**Comment by chiccap** [comment]
Ho scritto a Grazia.

**Comment by chiccap** [comment]
Chiudo perchè ne hanno trovati già un numero sufficiente.
