### ISSUE TITLE
Salve, vorrei poter fare una raccolta fondi per l'acquisto di libri da donare ai bambini.

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4232]
<pre><yamldata>
Cosa: Realizzare una raccolta fondi per regalare libri bambini
Descrizione: Salve, vorrei poter fare una raccolta fondi per l'acquisto di libri da
  donare ai bambini.
</yamldata></pre>

**Comment by cristigalas** [comment]
Non c’è nessun riferimento.
