### ISSUE TITLE
Misure valide sino al 27 marzo 2021

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4235]
<pre><yamldata>
Cosa: Nuovo decreto legge 23 febbraio 2021
Descrizione: Misure valide sino al 27 marzo 2021
Link: https://www.facebook.com/curaitalia/posts/263998308577985
</yamldata></pre>

**Comment by cristigalas** [comment]
Non è un link a sito istituzionale.
