### ISSUE TITLE
Salve,

Io vivo in Germania ma la mia ragazza è ancora in italia. Per il covid quasi tutti i mezzi d

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4239]
<pre><yamldata>
Cosa: Attraversamento di regione per ricongiungimento con partner all'estero
Descrizione: 'Salve,

  Io vivo in Germania ma la mia ragazza è ancora in italia. Per il covid quasi tutti
  i mezzi di trasporto sono stati soppressi, ma vi sono ancora dei bus da milano fino
  a vicino a dove abito io.

  Il problema è che la mia ragazza vive in piemonte, quindi dovrebbe attraversare
  la regione.

  La domanda è: è possibile attraversare la regione come tappa intermedia di un viaggio
  all''estero? il ricongiungimento con il partner è un viaggio motivato per necessità?

  Grazi e cordiali saluti.'
Email: a.dambrosioMD@gmail.com
Nome: Angelo D'Ambrosio
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 40.9730782 14.20627126 (Aversa) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=40.9730782+14.20627126&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by cristigalas** [comment]
Domanda che esula dalle nostre competenze, non accetterei.
