### ISSUE TITLE
Grafici e statistiche

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4240]
<pre><yamldata>
Cosa: Esplorazione dati covid Italia
Descrizione: Grafici e statistiche
Fonte: Protezione civile e Agenas
Link: https://www.kaggle.com/gianlab/esplorazione-dati-covid-19-italia
</yamldata></pre>

**Comment by cristigalas** [comment]
Non accetterei. Di queste elaborazioni dati ormai ne ce ne sono un mucchio.
