### ISSUE TITLE
La sentenza parla completamente di altro. Mi meraviglio dell'ANSA che ritenevo attendibile

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4241]
<pre><yamldata>
Cosa: Bufala
Descrizione: La sentenza parla completamente di altro. Mi meraviglio dell'ANSA che
  ritenevo attendibile
Link: https://www.google.com/amp/s/www.ansa.it/amp/veneto/notizie/2021/03/23/covid-niente-stipendio-senza-il-vaccino-decisione-di-un-giudice_536e58e2-6723-4ec6-beec-27dc462d77e6.html
</yamldata></pre>

**Comment by cristigalas** [comment]
Non mi pare una bufala ma solo un articolo confuso.
