### ISSUE TITLE
Salve, 
vi sto contattando per un sollecito di un vaccino ad una persona anziana con molte patologie

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4242]
<pre><yamldata>
Cosa: sollecito di vaccinazione
Descrizione: "Salve, \nvi sto contattando per un sollecito di un vaccino ad una persona\
  \ anziana con molte patologie non è grado di deambulare. Vi auguro buona giornata"
Email: mariadelpiano67@tiscali.it
Nome: maria del piano
Telefono: '3393773681'
</yamldata></pre>

**Comment by cristigalas** [comment]
Non indica dove risiede e altre informazioni utili. Che facciamo @chiccap?

**Comment by chiccap** [comment]
Proviamo a contattarla via mail?

**Comment by cristigalas** [comment]
@chiccap ok, mail inviata.

**Comment by cristigalas** [comment]
Mai risposto. Chiudo.
