### ISSUE TITLE
Articolo web con consigli per la gestione dello stress dovuto alla situazione pandemica

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#4243]
<pre><yamldata>
Da_chi_offerta: Matteo Rocca
Descrizione: Articolo web con consigli per la gestione dello stress dovuto alla situazione
  pandemica
Destinatari: Lavoratori
Link: https://www.stresscoach.it/2020/11/23/come-gestire-i-sintomi-dello-stress-da-quarantena/
Natura: sostegno-lavor
</yamldata></pre>

**Comment by cristigalas** [comment]
Articolo promozionale. Non accetto.
