### ISSUE TITLE
URGENTE - Donazione sangue #AVIS Regione #Lazio

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#428]
<pre><yamldata>
Cosa: Urge Donazione Sangue
Descrizione: 'Urge Donazione Sangue: è possibile prenotare per effettuare le donazioni in tutta la regione Lazio'
Destinatari: AVIS Regione Lazio
Link: https://www.facebook.com/groups/covid19italia/permalink/2928348280520673/
Posizione: 41.85223935 12.63103662
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente, #347
