### ISSUE TITLE
Inps proroga la scadenza dei pagamenti P.a.

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#431]
<pre><yamldata>
Cosa: Inps proroga la scadenza dei pagamenti P.a.
Descrizione: In un decreto legge di prossima emanazione, da parte del Consiglio dei
  Ministri, verrà differito il termine per i versamenti nei confronti delle pubbliche
  amministrazioni originariamente previsto per il 16 marzo.
Link: http://www.rainews.it/dl/rainews/articoli/coronavirus-inps-proroga-scadenza-pagamenti-pubblica-amministrazione-13cfc91c-f80a-4f5b-8622-72cb69880783.html
</yamldata></pre>

**Comment by chiccap** [comment]
non accetto e chiudo, gà presente #387
