### ISSUE TITLE
Dati Regione #Lazio al 14/02/20

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#435]
<pre><yamldata>
Cosa: 'Dati Regione #Lazio al 14/02/20'
Descrizione: 'Rispetto a ieri si registra un incremento di 80 casi di positività,
  più 3 rispetto a ieri. C’è anche un incremento delle persone guarite dal COVID-19,

  che sono 28. Escono oggi dalla sorveglianza in 745, ovvero hanno terminato la quarantena.
  Continua il potenziamento della rete delle terapie intensive. Lunedì parte COVID
  2 HOSPITAL” commenta l’Assessore D’Amato.

  La situazione nelle Asl e A.O:

  Asl Roma 1 – 5 nuovi casi positivi. 150 le persone che sono uscite dalla sorveglianza
  domiciliare. Dal 17 marzo disponibili ulteriori 8 posti di pneumologia al San Filippo
  Neri;

  Asl Roma 2 – 17 nuovi casi positivi. 59 le persone che sono uscite dalla sorveglianza
  domiciliare. Da lunedì 16 marzo disponibili ulteriori 6 posti di terapia intensiva
  al Sant''Eugenio e 9 posti di terapia intensiva dedicati al COVID-19;

  Asl Roma 3 – Nessun nuovo caso positivo. 92 le persone che sono uscite dalla sorveglianza
  domiciliare;

  Asl Roma 4 – 7 nuovi casi positivi. 2 i pazienti guariti. 99 le persone che sono
  uscite dalla sorveglianza domiciliare. Chiusa l’accettazione della RSA Madonna del
  Rosario di Civitavecchia in attesa esito indagine epidemiologica;

  Asl Roma 5 – 9 nuovi casi positivi. 116 le persone che sono uscite dalla sorveglianza
  domiciliare. Disponibili dal 28 marzo ulteriori 4 posti di terapia intensiva. Si
  stanno aprendo aree di stazionamento per pazienti in attesa di esito tampone;

  Asl Roma 6 – 12 nuovi casi positivi. 30 le persone che sono uscite dalla sorveglianza
  domiciliare;

  Asl di Latina – 13 nuovi casi positivi. 2 i pazienti che sono guariti. 78 le persone
  che sono uscite dalla sorveglianza domiciliare;

  Asl di Frosinone – 9 nuovi casi positivi. 13 le persone che sono uscite dalla sorveglianza
  domiciliare. 4 i casi positivi in trasferimento allo Spallanzani. Bloccata l’accettazione
  della RSA San Raffaele di Cassino in attesa dell’esito dell’indagine epidemiologica;

  Asl di Viterbo - 3 nuovi casi positivi. 79 le persone che sono uscite dalla sorveglianza
  domiciliare;

  Asl di Rieti – 1 nuovo caso positivo. 29 le persone che sono uscite dalla sorveglianza
  domiciliare. Disponibili dal 16 marzo ulteriori 11 posti di terapia intensiva dedicata
  al COVID-19;

  Policlinico Umberto I - da lunedì 16 marzo disponibili ulteriori 8 posti di terapia
  intensiva. Da subito disponibili 36 posti di malattie infettive; presso l’Eastman
  altri 26 posti da attivare da lunedì 16 marzo e altri 20 posti da mercoledì 18 marzo.
  Entro venerdì 20 marzo altri 48 posti di malattie infettive;

  Azienda Ospedaliera San Giovanni - 4 posti letto di terapia intensiva disponibili.
  Entro il 21 marzo disponibili ulteriori 4 posti di terapia intensiva;

  Azienda Ospedaliera Sant’Andrea - 4 nuovi casi positivi. Dal 20 marzo saranno disponibili
  ulteriori 10 posti di terapia intensiva;

  Policlinico Gemelli - Da lunedì 16 marzo ulteriori 32 posti di malattie infettive
  e ulteriori 21 posti di terapia intensiva al COVID-19 2 Hospital Columbus;

  IFO - Entra nella rete di emergenza per il COVID-19 con 2 posti di terapia intensiva
  disponibili;

  Ares 118 - implementate le postazioni del numero verde 800.118.800 dedicato all’emergenza
  COVID-19. Ieri gestite 1.800 telefonate;

  Policlinico Tor Vergata - Attivati ulteriori 8 posti di terapia intensiva. Lunedì
  16 marzo saranno attivati ulteriori 16 posti di terapia intensiva dedicati al COVID-19;

  Azienda Ospedaliera San Camillo - Ulteriori 7 posti letto di terapia intensiva disponibili
  da oggi. Dal 17 marzo disponibili ulteriori 3 posti di terapia intensiva. Dal 16
  marzo attivato reparto di sorveglianza pediatrica per pazienti in attesa esito tampone.'
Fonte: Regione Lazio
Link: https://www.facebook.com/RegioneLazio/posts/2792342587500982?__xts__%5B0%5D=68.ARC8w-owXt2qCIKdrnx0gREQcEIwyYG1M9bgsXQ0UErUCayxoxqL2jHnXlBgcdi37FDt25Auzpu9PSs5vXEEqm8Qd2vPUoueJXDztw7CoqreMMf4S56wjgWqD4b1kpOnjuf8nUdqh5rAUaX997w1uNDWjRW4OEkoKvFrtBUejHc9E_vC6I8ACGQL1zcA34z1tnpcznMmT9LxiKnevIlwGwt8b1fb-FjN4uEE192kuktt2vjXfyEGd-L6LAvQWBqtHFrtP34h2xE7lTnxhWsH9Wxp3unKp_ZQErqZftGNbd5cdb6mq2Glt8jaYODi-aTj8etjIBDSkCB49RqlzzVeLQ&__tn__=K-R
Posizione: 41.904082 12.493216 0 0
</yamldata></pre>

**Comment by cristigalas** [comment]
@chiccap questo tipo di notizie non le accetterei. Questi dati o notizie sono ovunque...
