### ISSUE TITLE
Avviso per incarichi a medici specializzandi #Avezzano #Sulmona #LAquila

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#437]
<pre><yamldata>
Cosa: 'Avviso per la manifestazione di disponibilità ad incarichi di lavoro autonomo
  anche co.co.co per medici specializzandi #Abruzzo #L''Aquila #Medici'
Descrizione: La Asl dell'Aquila ha emanato un avviso per sondare la disponibilità
  a incarichi di lavoro autonomo (anche co.co.co) per medici specializzandi. I contratti
  avranno la durata di 6 mesi (prorogabili), a partire da subito.
Destinatari: Iscritti all'ultimo e penultimo anno di corso delle specializzazioni
  di anestesia e rianimazione; medicina interna; malattie infettive; malattie dell'apparato
  respiratorio e radiodiagnostica
Indirizzo: 42.348933 13.398232 0 0
Link: http://www.asl1abruzzo.it/archivio2_notizie-ed-eventi_0_751.html
</yamldata></pre>

**Comment by chiccap** [comment]
avviso scaduto 16 marzo
