### ISSUE TITLE
Aiuto compiti

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#506]
<pre><yamldata>
Da_chi_offerta: Scuole European Campus
Descrizione: Aiuto e spiegazione compiti
Destinatari: Minori
Link: www.europenacampus.it
Natura: didattica
Posizione: 41.690643 15.381117 0 0
Titolo: Aiuto compiti
</yamldata></pre>

**Comment by cristigalas** [comment]
Troppo vaga, non accetto.
