### ISSUE TITLE
RICERCA MEDICI SPECIALISTI, SPECIALIZZANDI E LAUREATI PER SSR REGIONE #CALABRIA

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#514]
<pre><yamldata>
Cosa: DISPONIBILITA’ DI MEDICI SPECIALISTI, MEDICI SPECIALIZZANDI E MEDICI LAUREATI
  A PRESTARE ATTIVITA’ CLINICO ASSISTENZIALE NELLE AZIENDE DEL SSR DELLA REGIONE CALABRIA
Descrizione: AVVISO PUBBLICO PER MANIFESTAZIONE DI INTERESSE FINALIZZATA AD ACQUISIRE
  LA DISPONIBILITA’ DI MEDICI SPECIALISTI, MEDICI SPECIALIZZANDI E MEDICI LAUREATI
  A PRESTARE ATTIVITA’ CLINICO ASSISTENZIALE NELLE AZIENDE DEL SSR DELLA REGIONE CALABRIA
Destinatari: medici
Link: https://www.facebook.com/groups/covid19italia/permalink/2925493427472825/
</yamldata></pre>

**Comment by favoeva** [comment]
chiudo perchè già arrivata
