### ISSUE TITLE
Raccolta Fondi Ospedale di #Maddaloni - #Caserta

### ISSUE THREAD

**Issue by MicheleTurco** [emergenzeHack/covid19italia_segnalazioni#517]
È un momento difficile per tutti, mai come oggi l’unione deve fare la forza. Ho deciso di rivolgere questa donazione all’Ospedale di MADDALONI, più nello specifico al reparto di TERAPIA INTENSIVA.
Aiutiamoci!
La donazione sarà utilizzata per l’acquisto di ventilatori pressovolumetrici, unico strumento in grado di salvare vite in caso di polmoniti e complicazioni causate dal virus

https://www.gofundme.com/f/donazione-ospedale-civile-di-caserta

**Comment by avivace** [comment]
@favoeva Attenzione che Issues come questa si rompono e non vanno accettate. Si passa dal form, non si aprono direttamente qui

Le issues qui devono arrivare rispettando il formato descritto qui: https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#esempio-finale-di-segnalazione

**Comment by cristigalas** [comment]
Hai ragione @avivace! Metto label Non accettata e chiudo.

**Comment by MicheleTurco** [comment]
ok?

**Comment by cristigalas** [comment]
> ok?

Per segnalazioni usare web form Segnala che è sul sito https://covid19italia.help/segnala/

**Comment by MicheleTurco** [comment]
Sono arrivato al repository direttamente da Github, ho corretto secondo il formato indicato. Se la volete far diventare così complicata, lasciamo stare. Grazie ed in bocca al lupo a tutti voi
