### ISSUE TITLE
Byoblu: notizie false sul coronavirus (e non solo)

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#528]
<pre><yamldata>
Cosa: 'Byoblu: notizie false sul coronavirus (e non solo)'
Descrizione: Segnalo questa pagina che diffonde continuamente video e notizie false,
  da false cure, al fatto che l'epidemia non esiste, è solo un'influenza, ad altre
  amenità. Hanno una pagina fb e un canale you tube.
Link: https://www.facebook.com/groups/byoblu/
</yamldata></pre>

**Comment by chiccap** [comment]
già presente #529
