### ISSUE TITLE
Claudio Messora -Byoblu

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#529]
<pre><yamldata>
Cosa: Claudio Messora -Byoblu
Descrizione: Diffusione massiva di bufale antiscientiifiche e particolarmente sul
  coronavirus.
Indirizzo: 41.72008003 13.61362757
Link: https://www.facebook.com/byoblu/?eid=ARBb4cZdTUQjXAQnJYC__J325Oip8M1AkLyIAPVYO_2nXfHiVMNXiUV2r-VMHMXcGePOcDtwbltr1y9w
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 41.72008003 13.61362757 (Sora) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=41.72008003+13.61362757&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by chiccap** [comment]
@cristigalas @favoeva la geolocalizzazione è giusta ma non so cosa fare con la issue!

**Comment by cristigalas** [comment]
Aggiungo label Non accettato.
