### ISSUE TITLE
Cercasi volontari per consegne a domicilio Comune di #Latina

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#541]
<pre><yamldata>
Cosa: 'Cercasi volontari da affiancare alla rete istituzionale dei servizi sociali
  Comune di #Latina'
Descrizione: 'Si cercano volontari da affiancare alla rete istituzionale dei servizi
  sociali.

  I settori di intervento per i quali si richiede integrare il supporto ai volontari
  già attivi sono:

  - il servizio presso la mensa della Caritas;

  - la consegna di pacchi a domicilio per persone anziane, immunodepressi o nuclei
  familiari con bambini;

  - solo per gli studenti di medicina, l’affiancamento alle attività di accoglienza
  della Croce Rossa presso il dormitorio dell’emergenza freddo senza dimora.

  Per dare la propria disponibilità è possibile contattare: Croce Rossa Italiana -
  Comitato di Latina al numero verde 800065510 o all’indirizzo email latina@cri.it;
  Caritas al numero 3394560629.'
Destinatari: Persone che vogliano diventare volontarie
Email: latina@cri.it
Indirizzo: 41.467091 12.903395 0 0
Link: https://www.facebook.com/comunedilatina/photos/a.163242761144055/661295804672079/?type=3&theater&ifg=1
Telefono: '800065510'
</yamldata></pre>

**Comment by chiccap** [comment]
avviso scaduto il 16 marzo
