### ISSUE TITLE
Avviso pubblico manifestazione di interesse #Medici Asl #LAquila

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#546]
<pre><yamldata>
Cosa: 'Avviso pubblico manifestazione di interesse Medici Asl #LAquila'
Descrizione: La Asl dell'Aquila ha emanato un avviso per sondare la disponibilità
  a incarichi di lavoro autonomo (anche co.co.co) per medici specializzandi. I contratti
  avranno la durata di 6 mesi (prorogabili), a partire da subito. Possono fare domanda
  gli iscritti all'ultimo e penultimo anno di corso delle specializzazioni di anestesia
  e rianimazione; medicina interna; malattie infettive; malattie dell'apparato respiratorio
  e radiodiagnostica.
Destinatari: Medici specializzandi
Indirizzo: 42.349299 13.397677 0 0
Link: https://urlzs.com/QWttt
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Scaduto 16 marzo! Chiudo issue
