### ISSUE TITLE
piattaforma per inserire negozi con consegna a casa

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#549]
<pre><yamldata>
Da_chi_offerta: volontari
Descrizione: Piattaforma no profit realizzata da volontari che consente di visualizzare
  su mappa gli esercizi locali che consegnano a domicilio. Espandibile a tutti i territori
Destinatari: negozianti, cittadini
Link: https://vicinoesicuro.it/
Natura: sostegno-lavor
Posizione: 44.698916 10.627213 0 0
Titolo: piattaforma per inserire negozi con consegna a casa
</yamldata></pre>

**Comment by chiccap** [comment]
già segnalato #532
