### ISSUE TITLE
Mancato rispetto normativa

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#552]
<pre><yamldata>
Cosa: Mancato rispetto normativa
Descrizione: Sabato 14 marzo, ero in fila per entrare al supermercato Famila a Marina
  di Montemarciano. Davanti a me c'erano 2 persone insieme. Il piantone li ha fatti
  entrare dicendo "entrate, sparpagliatevi e fate finta che non siete inseme". Mi
  risulta che 1 sola persona per famiglia possa entrare a fare spesa. O no?? Questa
  è l'Italia. Come possiamo sconfiggere il virus se ci sono ancora persone che non
  si attengono alla normativa? Le restrizioni sono state emanate per tutelare tutti
  e onestamente con certe persone che controllano non mi sento tutelata
</yamldata></pre>

**Comment by avivace** [comment]
@cristigalas ci serve una politica per trattare "sfoghi" come questo

**Comment by cristigalas** [comment]
@avivace finora li abbiamo trattati così: label non accettato e chiusa issue. Di meglio non credo si possa fare.

**Comment by avivace** [comment]
@cristigalas Aggiungo in wiki

**Comment by cristigalas** [comment]
> @cristigalas Aggiungo in wiki

Ok grazie!
