### ISSUE TITLE
Il Centro Antiviolenza E.va onlus di Busto Arsizio mantiene una reperibilità telefonica da parte di 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#555]
<pre><yamldata>
Da_chi_offerta: Centro Antiviolenza E.va onlus di Busto Arsizio
Descrizione: 'Il Centro Antiviolenza E.va onlus di Busto Arsizio mantiene una reperibilità
  telefonica da parte di psicologa ed assistenti sociali H 24. Nessuna segreteria
  telefonica.

  Dal lunedì al venerdì ore 9-18 - Tel: 3345369630'
Destinatari: Donne
Link: https://www.evaonlus.it/
Natura: solidale
Posizione: 45.613887 8.850303 0 0
Tipo_di_soggetto: privato
</yamldata></pre>

**Comment by chiccap** [comment]
già presente #403
