### ISSUE TITLE
Sportello legale di orientamento

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#568]
<pre><yamldata>
Da_chi_offerta: IusTeam - Rete di avvocati
Descrizione: La rete di avvocati IusTeam riunisce avvocati di tutta Italia ed offre
  un servizio gratuito di orientamento per tutti quei soggetti destinatari dei provvedimenti
  adottati dal Governo italiano durante l'emergenza
Destinatari: Imprese e professionisti
Link: https://www.iusteam.net/iusteam-a-fianco-delle-piccole-imprese-delle-ditte-individuali-e-dei-professionisti-nellemergenza-coronavirus/
Natura: sostegno-lavor
Titolo: Sportello legale di orientamento
</yamldata></pre>

**Comment by chiccap** [comment]
già presente #567
