### ISSUE TITLE
Ecstatic Dance • free • online • djset

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#573]
<pre><yamldata>
Cosa: Ecstatic Dance • free • online • djset
Descrizione: '#notouchstillconnected

  17 MARZO • ore 18-19.30 ✨ ECSTATIC DANCE ✨

  free • online • djset ✨ Let''s keep on dancing ✨

  Un esperimento nuovo, chi vuole unirsi è benvenuto, accorciamo le distanze connettendoci
  al nostro ritmo, al nostro battito, a quello della musica 🌞

  Per partecipare segui queste semplici istruzioni:

  • Scarica il programma gratuito Zoom dal sito www.zoom.us

  • Invia una mail a ecstaticdance.ita@gmail.com

  per registrare la tua presenza

  • il giorno dell''evento, clicca sul link che ricevi,

  metti in "mute" e inizia a danzare!

  Esperienza gratuita, Posti illimitati, se ti piace l''idea, diffondi l''invito.
  La partecipazione è gratuita!

  #ecstaticdanceitaly'
Destinatari: Aperto a tutti, 0-99
Email: dancecstatic@gmail.com
Immagine: ED Online ITA-18_13_15.jpg
Link: www.facebook.com/ecstaticdance.it
Telefono: '+393389220917'
</yamldata></pre>

**Comment by Saraveg** [comment]
doppio
