### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#577]
<pre><yamldata>
Cosa: Email
Descrizione: Vorrei sapere dove è possibile recuperare mascherine buone del tipo ffp2.
  Grazie
Destinatari: Mauromongardi72@gmail.com
Email: mauromongardi72@gmail.com
Telefono: '3466818677'
</yamldata></pre>

**Comment by cristigalas** [comment]
Qui che facciamo @favoeva @chiccap @Saraveg? 
1. Rispondiamo, come al tempo di Tci, via email dicendo che non abbiamo info a riguardo? 
2. Oppure pubblichiamo come richiesta di aiuto? 
3. Non accettiamo e chiudiamo issue.

Io opterei per la 1.

**Comment by Saraveg** [comment]
anche io 1. (dopodiché la domanda è legittima. forse possiamo dire di chiedere alle farmacie?)

**Comment by cristigalas** [comment]
> anche io 1. (dopodiché la domanda è legittima. forse possiamo dire di chiedere alle farmacie?)

Sì certo, ma la vedo dura che le farmacie dispongano di queste mascherine. Le cercano gli ospedali di tutta Italia.
Comunque scrivo email da account Covid e chiudo.

**Comment by cristigalas** [comment]
> > anche io 1. (dopodiché la domanda è legittima. forse possiamo dire di chiedere alle farmacie?)
> 
> Sì certo, ma la vedo dura che le farmacie dispongano di queste mascherine. Le cercano gli ospedali di tutta Italia.
> Comunque scrivo email da account Covid e chiudo (non metto label accettata, altrimenti viene pubblicata).

**Comment by cristigalas** [comment]
Email inviata. Chiudo.

**Comment by cristigalas** [comment]
> > anche io 1. (dopodiché la domanda è legittima. forse possiamo dire di chiedere alle farmacie?)
> 
Sì certo, ma la vedo dura che le farmacie dispongano di queste mascherine. Le cercano gli ospedali di tutta Italia.
Comunque scrivo email da account Covid e chiudo (non metto label accettata, altrimenti viene pubblicata).
