### ISSUE TITLE
Modulo autocertificazione spostamenti in formato digitale

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#580]
<pre><yamldata>
Da_chi_offerta: Etinet
Descrizione: Il form permette di compilare on line il modulo di autocertificazione
  degli spostamenti scaricarlo in PDF o inviarlo ad una mail per poi stamparlo.
Destinatari: Tutti i cittadini
Link: https://www.modulospostamento.it/
Natura: solidale
Tipo_di_soggetto: pubblico
Titolo: Modulo autocertificazionie spostamenti on line
</yamldata></pre>

**Comment by cristigalas** [comment]
[Ci segnalano ](https://twitter.com/sonoclaudio/status/1239457707679244288?s=21)che il sito non è sicuro. Chiudo.
