### ISSUE TITLE
vocale su whatsapp

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#586]
<pre><yamldata>
Cosa: vocale su whatsapp
Descrizione: "Gira un vocale da parte di un soggetto donna la quale che parla del\
  \ covid-19, affermando che il virus in oggetto resta in vita sull'asfalto per 9\
  \ giorni: \n\nhttps://www.bufale.net/nuovo-audio-whatsapp-coronavirus-rimane-vivo-9-giorni-sullasfalto-lasciate-le-scarpe-fuori/"
</yamldata></pre>

**Comment by epoeta** [comment]
Notizia già inserita.
