### ISSUE TITLE
DaScuola.it - ECCO LA PIATTAFORMA PER SALVARE L'ANNO SCOLASTICO: UN APPELLO ALLE ISTITUZIONI

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#587]
<pre><yamldata>
Da_chi_offerta: WeStudents
Descrizione: "DaScuola.it - ECCO LA PIATTAFORMA PER SALVARE L'ANNO SCOLASTICO: UN\
  \ APPELLO ALLE ISTITUZIONI\n\nI ragazzi di WeStudents hanno sviluppato in una settimana\
  \ DaScuola.it, una piattaforma che risolve i problemi dello smart-schooling. \n\n\
  Chi ha provato a lavorare con le attuali modalità proposte dai vari enti si sarà\
  \ reso conto delle difficoltà tecniche, dovute a crash dei server e alle scarse\
  \ funzionalità. WeStudents S.r.l, unica Start-up italiana a permettere la sincronizzazione\
  \ dei principali registri elettronici del paese ad un unico access-point, ha deciso\
  \ di mettere a disposizione le proprie capacità di sviluppo al servizio del Sistema\
  \ Italia. La Startup è riuscita a coinvolgere gli influencer di House of Talent,\
  \ start-up di Matteo Altieri e la community di Starting Finance per far arrivare\
  \ a quante più persone possibile il loro messaggio. “Vogliamo salvare l’anno scolastico,\
  \ ascoltateci”. Perciò, si auspica una rapida risposta da parte delle istituzioni.\
  \ \n\n\nCome funziona DaScuola?\n\n“DaScuola è una piattaforma digitale, facile\
  \ da usare, e soprattutto gratuita. Che cos’è una scuola? Un edificio, con un ingresso\
  \ unico per professori ed alunni e delle aule dove si svolgono le lezioni. Semplice,\
  \ no? Abbiamo replicato la stessa dinamica”. Così Giorgio ed Edoardo ci raccontano\
  \ cos’ha sviluppato il loro team.\n\nUna volta effettuata la registrazione lo studente\
  \ o il professore, si ritrovano all’interno della “scuola”. I professori possono\
  \ scegliere in che classe entrare, e nel mentre gli alunni, sono in classe ad aspettarli.\
  \ Proprio come una vera scuola!\n\nPerché DaScuola è diversa dagli altri servizi?\
  \ Perché oltre ad essere un prodotto innovativo e gratuito, è anche l’unico servizio\
  \ scalabile e disponibile per ogni classe, di ogni scuola, di ogni comune che permette\
  \ un unico access-point. In altre parole? Ricostruiscono virtualmente tutte le scuole\
  \ del paese.\n\nChi li sostiene\n\nLa Startup è riuscita a coinvolgere gli influencer\
  \ di House of Talent, start-up di Matteo Altieri e la community di Starting Finance\
  \ per far arrivare a quante più persone possibile il loro messaggio. “Vogliamo salvare\
  \ l’anno scolastico, ascoltateci”.\n\nDi cosa hanno bisogno\n\nNon chiedono denaro.\
  \ Hanno vent'anni, hanno degli ideali: la scuola è fondamentale, e pensare a sei\
  \ mesi senza è devastante. L'unico aiuto di cui necessitano è quello delle istituzioni\
  \ e di Google. La piattaforma richiede un consumo di dati molto elevato. I costi\
  \ principali sono quindi legati all'hosting dei server in cloud. Con il vostro aiuto,\
  \ vogliono chiedere a Google e al Ministero di supportare i costi necessari per\
  \ mantenere i server. Insieme, possiamo salvare l'anno scolastico.\n\nPer chi, come\
  \ noi, sceglie di supportarli, la cosa migliore è firmare la loro petizione e condividere\
  \ il loro progetto.\n\nhttps://www.change.org/p/google-domani-a-scuola-salviamo-l-anno-scolastico?recruiter=1049330195&utm_source=share_petition&utm_medium=copylink&utm_campaign=share_petition\n\
  \n==================================================================\n\nCHI SIAMO\
  \ - \n\nhttps://www.linkedin.com/company/westudents/ \n\nhttps://www.westudents.it\
  \ \n\nElencata in 30Under30 Forbes Italia, WeStudents è una startup che sta sconvolgendo\
  \ l'industria EduTech con la sua app super innovativa per studenti delle scuole\
  \ superiori: + 100k download | 25 dipendenti | + 500k Iniezione di capitale | Valore\
  \ pre-money 4.0MLN\nWeStudents è il diario smart degli studenti delle scuole superiori\
  \ d'Italia. \nL' app permette agli studenti di gestire i propri impegni scolastici,\
  \ essere più connessi con i propri compagni, informarsi sulle ultime news dal mondo\
  \ e ricevere sconti dedicati online e su tutto il territorio nazionale. \n\nMEDIA\
  \ KIT - https://drive.google.com/drive/u/0/folders/1mTSUkXh85q1KlBPW5offKq-M2se8Djy2\n\
  =================================================================="
Destinatari: Studenti e professori in Italia
Indirizzo: 44.89912921 8.20414255
Link: https://da-scuola.web.app/
Natura: didattica
Titolo: 'DaScuola.it - ECCO LA PIATTAFORMA PER SALVARE L''ANNO SCOLASTICO: UN APPELLO
  ALLE ISTITUZIONI'
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 44.89912921 8.20414255 (Asti) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=44.89912921+8.20414255&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by chiccap** [comment]
@cristigalas non accetterei

**Comment by cristigalas** [comment]
> Da_chi_offerta: WeStudents
> Descrizione: "DaScuola.it - ECCO LA PIATTAFORMA PER SALVARE L'ANNO SCOLASTICO: UN\
>   \ APPELLO ALLE ISTITUZIONI\n\nI ragazzi di WeStudents hanno sviluppato in una settimana\
>   \ DaScuola.it, una piattaforma che risolve i problemi dello smart-schooling. \n\n\
>   Chi ha provato a lavorare con le attuali modalità proposte dai vari enti si sarà\
>   \ reso conto delle difficoltà tecniche, dovute a crash dei server e alle scarse\
>   \ funzionalità. WeStudents S.r.l, unica Start-up italiana a permettere la sincronizzazione\
>   \ dei principali registri elettronici del paese ad un unico access-point, ha deciso\
>   \ di mettere a disposizione le proprie capacità di sviluppo al servizio del Sistema\
>   \ Italia. La Startup è riuscita a coinvolgere gli influencer di House of Talent,\
>   \ start-up di Matteo Altieri e la community di Starting Finance per far arrivare\
>   \ a quante più persone possibile il loro messaggio. “Vogliamo salvare l’anno scolastico,\
>   \ ascoltateci”. Perciò, si auspica una rapida risposta da parte delle istituzioni.\
>   \ \n\n\nCome funziona DaScuola?\n\n“DaScuola è una piattaforma digitale, facile\
>   \ da usare, e soprattutto gratuita. Che cos’è una scuola? Un edificio, con un ingresso\
>   \ unico per professori ed alunni e delle aule dove si svolgono le lezioni. Semplice,\
>   \ no? Abbiamo replicato la stessa dinamica”. Così Giorgio ed Edoardo ci raccontano\
>   \ cos’ha sviluppato il loro team.\n\nUna volta effettuata la registrazione lo studente\
>   \ o il professore, si ritrovano all’interno della “scuola”. I professori possono\
>   \ scegliere in che classe entrare, e nel mentre gli alunni, sono in classe ad aspettarli.\
>   \ Proprio come una vera scuola!\n\nPerché DaScuola è diversa dagli altri servizi?\
>   \ Perché oltre ad essere un prodotto innovativo e gratuito, è anche l’unico servizio\
>   \ scalabile e disponibile per ogni classe, di ogni scuola, di ogni comune che permette\
>   \ un unico access-point. In altre parole? Ricostruiscono virtualmente tutte le scuole\
>   \ del paese.\n\nChi li sostiene\n\nLa Startup è riuscita a coinvolgere gli influencer\
>   \ di House of Talent, start-up di Matteo Altieri e la community di Starting Finance\
>   \ per far arrivare a quante più persone possibile il loro messaggio. “Vogliamo salvare\
>   \ l’anno scolastico, ascoltateci”.\n\nDi cosa hanno bisogno\n\nNon chiedono denaro.\
>   \ Hanno vent'anni, hanno degli ideali: la scuola è fondamentale, e pensare a sei\
>   \ mesi senza è devastante. L'unico aiuto di cui necessitano è quello delle istituzioni\
>   \ e di Google. La piattaforma richiede un consumo di dati molto elevato. I costi\
>   \ principali sono quindi legati all'hosting dei server in cloud. Con il vostro aiuto,\
>   \ vogliono chiedere a Google e al Ministero di supportare i costi necessari per\
>   \ mantenere i server. Insieme, possiamo salvare l'anno scolastico.\n\nPer chi, come\
>   \ noi, sceglie di supportarli, la cosa migliore è firmare la loro petizione e condividere\
>   \ il loro progetto.\n\nhttps://www.change.org/p/google-domani-a-scuola-salviamo-l-anno-scolastico?recruiter=1049330195&utm_source=share_petition&utm_medium=copylink&utm_campaign=share_petition\n\
>   \n==================================================================\n\nCHI SIAMO\
>   \ - \n\nhttps://www.linkedin.com/company/westudents/ \n\nhttps://www.westudents.it\
>   \ \n\nElencata in 30Under30 Forbes Italia, WeStudents è una startup che sta sconvolgendo\
>   \ l'industria EduTech con la sua app super innovativa per studenti delle scuole\
>   \ superiori: + 100k download | 25 dipendenti | + 500k Iniezione di capitale | Valore\
>   \ pre-money 4.0MLN\nWeStudents è il diario smart degli studenti delle scuole superiori\
>   \ d'Italia. \nL' app permette agli studenti di gestire i propri impegni scolastici,\
>   \ essere più connessi con i propri compagni, informarsi sulle ultime news dal mondo\
>   \ e ricevere sconti dedicati online e su tutto il territorio nazionale. \n\nMEDIA\
>   \ KIT - https://drive.google.com/drive/u/0/folders/1mTSUkXh85q1KlBPW5offKq-M2se8Djy2\n\
>   =================================================================="
> Destinatari: Studenti e professori in Italia
> Indirizzo: 44.89912921 8.20414255
> Link: https://da-scuola.web.app/
> Natura: didattica
> Titolo: 'DaScuola.it - ECCO LA PIATTAFORMA PER SALVARE L''ANNO SCOLASTICO: UN APPELLO
>   ALLE ISTITUZIONI'

**Comment by cristigalas** [comment]
@chiccap Non accetteresti perché sembra un po’ uno spottone?

**Comment by chiccap** [comment]
@cristigalas sì esatto! inoltre non so se abbiamo elementi per dire che davvero è la piattaforma che può salvare l'anno scolastico.

**Comment by cristigalas** [comment]
Ok @chiccap non accettiamo e chiudiamo.
