### ISSUE TITLE
Raccolta Fondi per Ospedale Metropolitano #ReggioCalabria per acquisto ventilatori polmonari

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#594]
<pre><yamldata>
Comune: Reggio di Calabria
Descrizione: "\xC8 stata istituita una raccolta fondi per l'acquisto di ventilatori\
  \ polmonari e per aumentare i posti in terapia intensiva"
Link: https://www.gofundme.com/f/terapia-intensiva-ospedale-reggio-calabria?utm_source=customer&utm_medium=copy_link-tip&utm_campaign=p_cp+share-sheet
Nome: 'Grande Ospedale Metropolitano #Reggio Calabria'
Posizione: 38.113821 15.65995 0 0
Provincia: Reggio di Calabria
Regione: Calabria
</yamldata></pre>

**Comment by cristigalas** [comment]
@luciaroma occhio allo spazio dopo Reggio, hashtag va su tutto #ReggioCalabria.

**Comment by luciaroma** [comment]
La raccolta fondi non accetta più donazioni
