### ISSUE TITLE
Croce Rossa cerca personale sanitario in #Lombardia

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#597]
<pre><yamldata>
Cosa: Croce Rossa cerca personale sanitario in Lombardia
Descrizione: Abbiamo necessità di personale sanitario per supporto in Regione Lombardia.
  Se vuoi fare anche tu la tua parte invia un SMS al numero 435 35 35 digitando “disponibilità
  immediata medico” o “disponibilità immediata infermiere”. Sarete ricontattati.
Destinatari: Personale sanitario
Link: https://www.cri.it/15-03-2020-coronavirus-croce-rossa-ricerca-medici-e-infermieri-con-disponibilita-immediata
Telefono: 435 35 35
Posizione: 45.6209 9.768893 0 0
</yamldata></pre>

**Comment by chiccap** [comment]
#643 più completa e su tutta zone più colpite non solo lombardia
