### ISSUE TITLE
Autocertificazione Spostamenti

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#599]
<pre><yamldata>
Da_chi_offerta: Cristian Pibia
Descrizione: 'Web-app che permette di creare e gestire tutti i moduli di spostamento
  da mostrare alle forze dell''ordine qualore fosse necessario.

  Potrà inoltre inviare al comando richiesto il documento compilato per il tuo spostamento.'
Destinatari: Pubblico
Link: https://autocertificazionespostamenti.it/
Natura: solidale
Tipo_di_soggetto: privato
Titolo: Autocertificazione Spostamenti
</yamldata></pre>

**Comment by cristigalas** [comment]
Non accettiamo questo tipo di segnalazioni che propongono piattaforme non ufficiali per documenti ufficiali. Rischio violazione privacy.
