### ISSUE TITLE
RACCOLTA FONDI OSPEDALE TRIGONA #NOTO (SR)

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#600]
<pre><yamldata>
Comune: Noto
Descrizione: Riapertura OSPEDALE TRIGONA DI NOTO(SR) tramite gofundme
Link: https://www.gofundme.com/f/raccolta-fondi-per-l039ospedale-trigona-di-noto?utm_source=facebook&utm_medium=social&utm_campaign=p_cp+share-sheet&fbclid=IwAR0xOxiELpKjxgFEcUGDxdSrju9wmZv_somPemTHjuk7VC0Rdv6-sE3alPs
Nome: Samuele Mazza
Posizione: 36.89089 15.07065 0 0
Provincia: Siracusa
Regione: Sicilia
</yamldata></pre>

**Comment by michelerestuccia** [comment]
La raccolta fondi non accetta più donazioni.
