### ISSUE TITLE
strumento di prevenzione

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#608]
<pre><yamldata>
Cosa: strumento di prevenzione
Descrizione: "Lavare il naso e la gola con acqua salata si è dimostrato un eccellente\
  \ sistema per impedire al virus di superare la barriera mucosale sulla quale ristagna\
  \ alcune ore prima di entrare in circolo. Se mi fornite un indirizzo elettronico\
  \ posso inviarvi il testo che propongo da anni ai miei pazienti, e che ha ricevuto\
  \ la vidimazione dell'autorevole gruppo fra pari www.listaippocrate.it. \nBuon lavoro\
  \ da Mario Frusi, medico"
Link: https://www.noosoma.it/mario-frusi/
</yamldata></pre>

**Comment by Polva13** [comment]
Il link rimanda al curriculum di una persona. La notizia non è supportata da basi scientifiche. Il progetto è un'iniziativa di due privati sul benessere generale. Io non lo accetterei.

**Comment by cristigalas** [comment]
Non accettiamo e chiudiamo.
