### ISSUE TITLE
Consegna a domicilio

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#625]
<pre><yamldata>
Da_chi_offerta: Bennati
Descrizione: Consegna di prodotti alimentari, pulizia casa, guanti monouso entro 48
  ore.
Destinatari: Alcuni comuni della provincia di Milano
Link: www.bennati.com
Natura: sostegno-lavor
Titolo: Consegna a domicilio
</yamldata></pre>

**Comment by favoeva** [comment]
si tratta di pubblicità servizio normale consegna a domicilio (tranne guanti)
