### ISSUE TITLE
Passatempo al Sud

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#627]
<pre><yamldata>
Da_chi_offerta: Regione Campania
Descrizione: Regione Campania, con il contributo di Scabec, ha voluto attivare sul
  proprio sito istituzionale questa sezione, una sorta di "catalogo" di siti, blog,
  link, pagine social e tutto quanto può essere utile ai genitori, ai nonni e ai ragazzi,
  per orientarsi e per raggiungere facilmente ciò che si cerca.
Destinatari: Cittadini Cmapani
Link: http://www.regione.campania.it/regione/it/news/regione-informa/passatempo-al-sud-giorni-pieni-di-libri-arte-musica-e-allegria?page=1&fbclid=IwAR0lrwXAXoXA_HWwz_WZaTx_97U968AzCYyMGW1ZjMBI95ZZd98JeTjwgK0
Natura: culturale-ricr
Titolo: Passatempo al Sud
</yamldata></pre>

**Comment by Saraveg** [comment]
Già presente https://www.covid19italia.help/issues/582/

**Comment by chiccap** [comment]
già presente #582
