### ISSUE TITLE
Le Favole di Giorgia

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#630]
<pre><yamldata>
Da_chi_offerta: Giorgia Staiano, scrittrice
Descrizione: Una favola al giorno contro il CoVid-19. Tante storie per intrattenere
  e supportare i più piccini!
Destinatari: Tutte le famiglie con bambini a casa
Link: https://www.facebook.com/Le-Favole-di-Giorgia-100139488284126/
Natura: culturale-ricr
Titolo: Le Favole di Giorgia
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Già presente in #631
