### ISSUE TITLE
Medici senza frontiere: servono aiuti urgenti per proteggere personale medico. Appello ai paesi europei

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#633]
<pre><yamldata>
Cosa: 'Medici senza frontiere: servono aiuti urgenti per proteggere personale medico.
  Appello ai paesi europei'
Descrizione: 'In questo momento di grave emergenza Medici senza frontiere Italia lancia
  un appello ai Paesi europei perché dimostrino solidarietà al di là dei propri confini
  nazionali.

  Forniture mediche essenziali, inclusi dispositivi di protezione individuale a partire
  dalle mascherine per proteggere gli operatori sanitari, devono essere inviate con
  urgenza dove sono più criticamente necessarie.

  In questo momento di crisi, nessun paese può farcela da solo, nessuno può produrre
  tutte le forniture di cui ha bisogno. Tutti gli Stati membri europei devono al più
  presto rendere operativi i meccanismi di solidarietà predisposti dall’Unione Europea
  e condividere le risorse necessarie per combattere la pandemia nelle aree in cui
  oggi è più violenta.'
Destinatari: Paesi europei
Link: https://t.co/2ZqQ9CWd2o?amp=1
</yamldata></pre>

**Comment by cristigalas** [comment]
Superata. Chiudo.
