### ISSUE TITLE
Urgente: mancanza DPI studio medico #Piemonte

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#634]
<pre><yamldata>
Comune: Torino
Cosa: Urgente mancanza DPI
Descrizione: "Sono un'infermiera del Piemonte e lavoro a Torino in uno studio medico\
  \ e ad oggi non abbiamo DPI (dispositivi di protezione individuale) forniti dall'Asl.\
  \ Abbiamo acquistato a nostre spese camici monouso, cuffie monouso, occhiali protettivi,\
  \ guanti, termometro a distanza, mascherine chirurgiche! Siamo sprovvisti di mascherine\
  \ FFP3, provate ad ordinare online senza successo ovviamente, senza contare i costi\
  \ proibitivi. Chi pu\xF2 aiutarci a trovare mascherine e altri DPI pu\xF2 scrivermi\
  \ a inf.martinelli@gmail.com grazie!"
Posizione: 45.080856 7.662103 314.3000183105469 13.381999969482422
Provincia: Torino
Regione: Piemonte
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Non ci sono info sullo studio medico e non ci sono contatti di riferimento

**Comment by cristigalas** [comment]
@claudiamazzantiact ha ragione, una richiesta di aiuto così non serve. Vedo se riesco a recuperare info... altrimenti va chiusa.

**Comment by cristigalas** [comment]
Ho trovato indirizzo email e l’ho quindi inserito.

**Comment by cristigalas** [comment]
Arrivata oggi email in cui ci comunicano che hanno tutti i Dpi necessari e che non hanno più bisogno di altro. Chiudo.
