### ISSUE TITLE
Design for Emergency, un insieme di iniziative per aiutare a fronteggiare l’emergenza COVID-19 attra

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#638]
<pre><yamldata>
Cosa: Design for Emergency, un insieme di iniziative per aiutare a fronteggiare l’emergenza
  COVID-19 attraverso il design
Descrizione: 'Abbiamo lanciato Design for Emergency, un insieme di iniziative per
  aiutare a fronteggiare l’emergenza COVID-19 attraverso il design.

  https://www.designforemergency.com

  Il primo passo per farlo è raccogliere informazioni su cosa stanno vivendo le persone
  che si trovano in zone colpite dal coronavirus, attraverso il questionario anonimo
  disponibile a questo link:

  https://tinyurl.com/designforemergency-survey

  Il nostro obiettivo è provare a creare, rapidamente, nuove soluzioni per rispondere
  ai problemi specifici di chi sta affrontando questa emergenza, per intrattenere,
  connettere e supportare in modo nuovo le persone e la comunità.

  Ci serve l''aiuto di tutti per raccogliere il maggior numero di informazioni, nel
  più breve tempo possibile. Grazie a chiunque vorrà contribuire e diffondere!'
Link: https://tinyurl.com/designforemergency-survey
</yamldata></pre>

**Comment by favoeva** [comment]
doppio
