### ISSUE TITLE
NON è vero che esiste questa raccolta fondi a favore del San Raffaele di #Milano

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#639]
<pre><yamldata>
Cosa: 'NON è vero che esiste questa raccolta fondi a favore del San Raffaele di #Milano'
Descrizione: Si tratta di una TRUFFA già denunciata dal IRCCS Ospedale San Raffaele
  alla polizia postale, non cascateci.
Indirizzo: 45.46679408 9.1903474
Link: https://www.facebook.com/robertoburioniMD/photos/a.2045888082303031/3271946743030486/
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 45.46679408 9.1903474 (Milano) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=45.46679408+9.1903474&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by chiccap** [comment]
@favoeva abbiamo verificato che non sia in raccolta fondi?

**Comment by favoeva** [comment]
> @favoeva abbiamo verificato che non sia in raccolta fondi?

Sul sito del San Raffaele non è presente

**Comment by chiccap** [comment]
> > @favoeva abbiamo verificato che non sia in raccolta fondi?
> 
> Sul sito del San Raffaele non è presente

No, scusa non mi sono spiegata bene, intendevo dire di controllare se l'avessimo accettata anche noi involontariamente come raccolta fondi ma ho verificato e c'è solo questa #138
