### ISSUE TITLE
Raccolta Fondi per Città della Salute #Torino

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#64]
<pre><yamldata>
Comune: Torino
Posizione: 45.0336035 7.6739743 0 0
Provincia: Torino
Regione: Piemonte
descrizione: Raccolta Fondi
destinatari: "Citt\xE0 della Salute di Torino "
fonte: https://www.gofundme.com/f/exfz34-insieme-contro-il-virus?utm_source=customer&utm_medium=copy_link-tip&utm_campaign=p_cp+share-sheet
provincia: Torino
regione: Piemonte
tag: Raccolta fondi
</yamldata></pre>

**Comment by Saraveg** [comment]
@mfortini sto facendo scomparire le issue. che sbaglio? se hai pazienza poi imparo e tiro dritta, giuro

**Comment by michelerestuccia** [comment]
La raccolta fondi non accetta più donazioni.
