### ISSUE TITLE
Trasmissione alla farmacia  via mail di prescrizione medicine

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#641]
<pre><yamldata>
Cosa: Trasmissione alla farmacia  via mail di prescrizione medicine
Descrizione: Potreste attivare l’invio diretto via mail di prescrizione sia rossa
  che bianca da parte dei medici di famiglia ASL alle farmacie loro indicate dai singoli
  assistiti in favore degli ultra 65enni in modo da evitare a queste persone , cui
  è particolarmente ordinato di non uscire da casa , di dover fare una evitabile triangolazione
  ? Così poi essi potranno organizzare la consegna a casa senza dover uscire . Grazie
  della considerazione.
Destinatari: Ultra 65enni e disabili
Email: alasorsa@libero.it
Indirizzo: 41.923412 12.497487 53.00901412963867 65
Telefono: '3333183982'
</yamldata></pre>

**Comment by chiccap** [comment]
@cristigalas vogliamo scrivergli per chiedergli la fonte?

**Comment by cristigalas** [comment]
Sta parlando di un servizio che adesso tutte le farmacie sono autorizzate a fare, in Toscana ad es. è attivo da qualche giorno (credo ci sia anche una segnalazione a riguardo). Evidentemente lo vorrebbe anche nella sua zona... Non so cosa possiamo fare noi...

**Comment by chiccap** [comment]
sì la #598. gli rispondiamo con il link alla nostra issue?

**Comment by cristigalas** [comment]
Ok, lo faccio nel pomeriggio.

**Comment by cristigalas** [comment]
Email inviata. Chiudo.
