### ISSUE TITLE
Raccolta fondi per ospedali della provincia di #Alessandria

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#642]
<pre><yamldata>
Causale: Emergenza covid ospedali Alessandria
Descrizione: "In un momento di emergenza sanitaria come quello che sta affrontando\
  \ ora il territorio della provincia di Alessandria a causa della diffusione del\
  \ coronavirus, è fondamentale il contributo di tutti noi perché ogni piccolo gesto\
  \ può fare la differenza e salvare delle vite.\n\nAiutiamo insieme gli ospedali\
  \ di Alessandria, Tortona, Casale Monferrato, Novi Ligure, Ovada e Acqui Terme attraverso\
  \ la raccolta fondi promossa dalla Fondazione SolidAl, Cassa di Risparmio di Alessandria,\
  \ Azienda Ospedaliera di Alessandria e ASL. Possiamo farlo in tre modi:\n\n\U0001F4CC\
  \ Con Bonifico intestato a PRO ASL-AO AL UNITI CONTRO COVID-19\nIBAN IT52 S 05034\
  \ 10408 000000005537\n\n\U0001F4CC Online con PayPal\nwww.fondazionesolidal.it \n\
  \n\U0001F4CC Piattaforma di fundraising GoFundMe\nhttps://bit.ly/2U6rsy4\n\nCosì\
  \ da casa, come consigliato dal Ministero, possiamo far sentire la nostra vicinanza\
  \ a tutti gli operatori sanitari che con impegno e dedizione si trovano in prima\
  \ linea.\n#fermiamoloinsieme #doniamodacasa"
Email: stampa@fondazionesolidal.it
IBAN: IBAN IT52 S 05034 10408 000000005537
Indirizzo: 44.91341 8.61462
Intestazione: PRO ASL-AO AL UNITI CONTRO COVID-19
Link: www.fondazionesolidal.it
Nome: Fondazione Solidal
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 41.22705031 16.29520624 (Andria) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=41.22705031+16.29520624&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by claudiamazzantiact** [comment]
Verifica coordinate eseguita. Ok

**Comment by chiccap** [comment]
già presente #556
