### ISSUE TITLE
Raccolta fondi per il GOM "Bianchi-Melacrino-Morelli" di #ReggioCalabria #RC

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#644]
<pre><yamldata>
Comune: Reggio di Calabria
Descrizione: "La Direzione Aziendale del Grande Ospedale Metropolitano \"Bianchi-Melacrino-Morelli\"\
  \ di Reggio Calabria ringrazia Francesco e Fabiana Gentile, Emanuele Ielo e Marco\
  \ Costantino, organizzatori della raccolta fondi sulla piattaforma GoFundMe.com,\
  \ al link https://www.gofundme.com/f/terapia-intensiva-ospedale-reggi\u2026, per\
  \ il nobile gesto di solidariet\xE0 che denota, inoltre, grande senso civico e vicinanza\
  \ alle istituzioni.\n **Venerd\xEC la raccolta fondi ha superato i 100.00,00 euro**,\
  \ e proprio in serata il G. O. M. ha completato l'iter procedurale per l'accettazione\
  \ delle donazioni.\nL'ospedale ringrazia tutti coloro che hanno donato anche individualmente\
  \ o in riferimento ad altre iniziative e comunica che tutti i fondi raccolti dalle\
  \ donazioni saranno impegnati per fronteggiare l'emergenza COVID-19 attraverso l'acquisto\
  \ di attrezzature e strumentazioni sanitarie.\nSecondo i principi di trasparenza\
  \ e legalit\xE0 che ispirano le pubbliche amministrazioni, ed al fine di alimentare\
  \ il clima di fiducia, l\u2019ospedale si impegna a rendicontare alla cittadinanza\
  \ quanto avr\xE0 ricevuto in termini di donazioni e come queste risorse saranno\
  \ state impiegate.\n\nStaff Direzione Generale"
Link: https://www.gofundme.com/f/terapia-intensiva-ospedale-reggio-calabria?fbclid=IwAR29I4CpnfvGvbE9ClMiZe8yqEP7gveSy-PNQ7bBg5_vV_CS_wfmdpOka6o
Nome: "Ospedale Bianchi-Malacrin\xF2-Morelli #ReggioCalabria #RC"
Posizione: 38.112713 15.659348 0 0
Provincia: Reggio di Calabria
Regione: Calabria
</yamldata></pre>

**Comment by chiccap** [comment]
@drizzt anche qui...

**Comment by marticorti** [comment]
@chiccap hanno segnalato una nuova raccolta fondi per l'ospedale metropolitano di Reggio che si trova anche sul sito italianonprofit.it issue #2958 . Si può chiudere questa issue? Per altro il link non risulta più valido.

**Comment by chiccap** [comment]
Sì chiudiamo pure questa!
