### ISSUE TITLE
Croce Rossa Italia: App gratuita per non udenti #Italia

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#669]
<pre><yamldata>
Da_chi_offerta: Croce Rossa Italiana
Descrizione: La sala operativa di CRI per le Persone si potenzia ulteriormente e da
  oggi gli operatori saranno in grado di soddisfare le richieste di aiuto anche delle
  persone non udenti. Grazie alla collaborazione con Pedius, infatti, gli utenti sordi
  potranno scaricare l’app gratuita “Pedius” (realizzata per iOS e Android) sul proprio
  smartphone, selezionare il servizio Croce Rossa Italiana per inviare la chiamata
  al numero verde CRI Per Le Persone, 800.065510.
Destinatari: Non udenti
Link: https://www.cri.it/16-03-2020-emergenza-covid-19-cri-vicina-persone-sorde-grazie-a-pedius?fbclid=IwAR0UshtJhxjVqmzJhio4eGSaLPsBeW0R8mfGZKoNsyRfIlMhTTMAEy2wwOA
Natura: solidale
Tipo_di_soggetto: privato
Titolo: App gratuita per non udenti
</yamldata></pre>

**Comment by cristigalas** [comment]
Doppia.
