### ISSUE TITLE
CasaOfficine - Iniziative culturali online da Catania

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#670]
<pre><yamldata>
Da_chi_offerta: Officine Culturali
Descrizione: 'Officine culturali risponde alla comunità creando appuntamenti culturali
  online sul canale YouTube di Officine Culturali a partire da martedì 17 marzo alle
  ore 18:00. Singoli progettisti o attivisti civici, altre associazioni e nuove imprese
  sociali sono invitati ad un video-incontro di mentorship che si terrà venerdì 20
  marzo. Tutti gli appuntamenti:

  - Mercoledì 18 marzo vi racconteremo del libro “Breve storia del Monastero dei Benedettini
  di Catania”

  - Venerdì 20 marzo attività per piccoli archeologi on line (5 - 8 anni).

  - lunedì 23 marzo vi racconteremo di alcune piante dell’Orto Botanico.

  - Martedì 24 marzo protagonista sarà il Museo di Archeologia dell’Università di
  Catania.

  Mercoledì 25 marzo nuovo appuntamento con il “Piccolo club di lettura” (on-line
  edition!).

  Giovedì 26 marzo sarà dedicato al Monastero dei Benedettini.

  Venerdì 27 marzo faremo i colori in casa per i disegni dei dei vostri bambini.

  Lunedì 30 marzo vi accompagniamo virtualmente tra i depositi del Museo della fabbrica
  del Monastero.

  Martedì 31 marzo costruiremo una piccola serra da casa.

  Mercoledì 1 aprile ascolteremo una storia direttamente dall’antichità.'
Destinatari: Tutti ma specialmente progettisti o attivisti civici, altre associazioni
  e nuove imprese sociali
Indirizzo: 37.50287801 15.08704738
Link: http://www.officineculturali.net/news/892-casaofficine-noicisiamo-ecco-la-programmazione-ldquo-casalingardquo-di-officine-culturali.htm?fbclid=IwAR1vMNrKXg05MFQMfjLFkKteCYcmJnZG3rTfN4QqOcRHlfE4h5O25iAfWBs
Natura: culturale-ricr
Titolo: CasaOfficine - Iniziative culturali online da Catania
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 37.50287801 15.08704738 (Catania) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=37.50287801+15.08704738&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by GabCruciata** [comment]
Per posizione credo sia meglio sede dell'ente (anche se evento è su YT). Posizione: 37.59057 14.98042

**Comment by cristigalas** [comment]
Scaduta.
