### ISSUE TITLE
Dona il tuo aperitivo: raccolta fondi a favore dell'ospedale Belcolle di #Viterbo

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#679]
<pre><yamldata>
Comune: Caprarola
Da_chi_offerta: Eco Sound Fest
Descrizione: "A Caprarola (VT) gli organizzatori del festival musicale Eco Sound Fest\
  \ promuovono una campagna di raccolta fondi per il reparto della terapia intensiva\
  \ dell'ospedale Belcolle di Viterbo. Alla campagna aderiscono il circolo ARCI \"\
  Le citt\xE0 invisibili\" e altre associazioni."
Destinatari: Terapia intensiva ospedale Belcolle
Link: https://www.gofundme.com/f/ud58d-il-tuo-aperitivo-contro-il-coronavirus?utm_medium=copy_link&utm_source=customer&utm_campaign=p_lico+share-sheet
Natura: solidale
Posizione: 42.32683 12.236344 0 0
Provincia: Viterbo
Regione: Lazio
Tipo_di_soggetto: privato
Titolo: Dona il tuo aperitivo
</yamldata></pre>

**Comment by michelerestuccia** [comment]
La raccolta fondi è conclusa
