### ISSUE TITLE
Richiesta aiuto trasporto per lavorare in ospedale a #Bergamo

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#682]
<pre><yamldata>
Comune: Bergamo
Cosa: trasporto per lavorare in ospedale
Descrizione: "Ho necessit\xE0 di arrivare al lavoro e tornare alla mia residenza al\
  \ termine del mio turno di lavoro presso ospedale Papa Giovanni XIII di Bergamo. Al momento sono costretta a muovermi in taxi. Ringrazio chiunque possa darmi una mano."
Destinatari: volontari
Email: piccolabambolina0@gmail.com
Posizione: 45.69449 9.66987 0 0
Provincia: Bergamo
Regione: Lombardia
Telefono: '3477034164'
</yamldata></pre>

**Comment by cristigalas** [comment]
Qualche giorno fa la signora ci ha detto che sta ancora cercando un aiuto perché continua ad andare a lavorare in taxi.

**Comment by cristigalas** [comment]
Con la ripresa del trasporto pubblico, la richiesta si può considerare chiusa.
