### ISSUE TITLE
Aiutiamoli ad aiutare: Raccolta fondi per Ospedale #Camerino

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#686]
<pre><yamldata>
Comune: Camerino
Da_chi_offerta: Chiara, Eleonora e Manuel
Descrizione: "Ciao,\nin questo momento purtroppo tutta l'Italia \xE8 ferma per il\
  \ Coronavirus ma tra le tante vicende che stanno accadendo, c'\xE8 una storia particolare\
  \ che magari \xE8 sfuggita ai pi\xF9.\n\nDalla scorsa domenica, in mezza giornata,\
  \ l'intero ospedale di Camerino (Macerata) \xE8 stato completamente smantellato\
  \ e riconvertito per accogliere pazienti contagiati Covid19. Una situazione come\
  \ tante altre, se non fosse che l\u2019ospedale di Camerino \xE8 (era) l\u2019unico\
  \ presidio di Livello 1 dell\u2019intero territorio terremotato, che sorge nel cuore\
  \ dei paesi pi\xF9 distrutti dell\u2019entroterra marchigiano. Per chi non lo sapesse,\
  \ nelle Marche c\u2019\xE8 il 62% dei danni causati dal sisma del Centro Italia\
  \ e Macerata \xE8 la provincia pi\xF9 colpita.\n\nSiamo fieri che il nostro piccolo\
  \ ospedale oggi sia fondamentale per salvare delle vite, seppure abbiamo ancora\
  \ le ossa rotte dal terremoto, con la ricostruzione ferma e le tante ingiustizie\
  \ che stiamo vivendo dopo essere stati considerati di \u201Cserie B\u201D, rispetto\
  \ ad altre emergenze per cui lo Stato ha avuto un trattamento pi\xF9 giusto. Ma\
  \ oggi non possiamo lasciare da solo il nostro ospedale con il rischio di non vederlo\
  \ ripristinato com\u2019era prima perch\xE9 in montagna siamo pochi e contiamo poco.\n\
  \nOggi possiamo fare la nostra parte, per aiutare i pazienti Covid19 e i tanti operatori\
  \ sanitari che, dalla sera alla mattina con tutte le difficolt\xE0 del caso, sono\
  \ impiegati a combattere questa malattia. Per questo abbiamo attivato una Raccolta\
  \ fondi per l'acquisto di presidi medici o di quanto ci diranno che potr\xE0 servire.\n\
  \nVi chiediamo con il cuore in mano di aiutarci a dare visibilit\xE0 a questa Raccolta\
  \ fondi attraverso i canali e le modalit\xE0 che voi riteniate pi\xF9 opportune.\
  \ In tanti possiamo fare tanto, aiutateci ad aiutarli!\n\nQuesto \xE8 il link alla\
  \ raccolta fondi sulla piattaforma gofundme: https://www.gofundme.com/f/emergenza-covid19-camerino\n\
  \nSe invece volete usare PayPal: https://paypal.me/ospedalecamerino\n\nOppure direttamente\
  \ all'IBAN: IT12O0306968830100000001246\n\nAiutiamoli ad aiutare.\n\nGrazie mille,\n\
  Chiara, Eleonora e Manuel"
Destinatari: Ospedale di Camerino
Link: https://www.gofundme.com/f/emergenza-covid19-camerino
Natura: solidale
Posizione: 43.134076 13.066031 0 0
Provincia: Macerata
Regione: Marche
Tipo_di_soggetto: privato
Titolo: Aiutiamoli ad aiutare -  Emergenza covid-19 Camerino
</yamldata></pre>

**Comment by luciaroma** [comment]
L'organizzatore ha momentaneamente disattivato le donazioni per questa campagna.
