### ISSUE TITLE
Fornitura e installazione fino a 5.000 Access Point WiFi negli ospedali pubblici

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#688]
<pre><yamldata>
Da_chi_offerta: Infratel Itala S.p.A. con MISE e in collaborazione con TIM e Ministero
  dell’Innovazione
Descrizione: Nell’ambito del progetto ‘’Piazza WiFi Italia’’ Infratel Itala S.p.A.
  in accordo con il MISE e in collaborazione con il partner tecnico TIM e il Ministero
  dell’Innovazione procederà alla fornitura e installazione fino a 5.000 Access Point
  WiFi negli ospedali pubblici che ne possono fare richiesta attraverso una comunicazione
  email a ospedaliwifitalia@infratelitalia.it
Destinatari: ospedali
Link: https://wifi.italia.it/it/newsit/13-wifi-italia-negli-ospedali.html
Natura: solidale
Tipo_di_soggetto: privato
Titolo: fornitura e installazione fino a 5.000 Access Point WiFi negli ospedali pubblici
</yamldata></pre>

**Comment by cristigalas** [comment]
@favoeva label Notizia va sempre tolta, la attribuisce automaticamente la web form ma per pubblicazione sul sito non funziona.

**Comment by favoeva** [comment]
> @favoeva label Notizia va sempre tolta, la attribuisce automaticamente la web form ma per pubblicazione sul sito non funziona.

Grazie @cristigalas 😘
