### ISSUE TITLE
Raccolta fondi Azienda provinciale per i servizi sanitari #Trento

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#702]
<pre><yamldata>
BIC_SWIFT: UNCRITM10IQ
Causale: Coronavirus
Comune: Trento
Descrizione: "L\u2019Azienda provinciale per i servizi sanitari ringrazia tutti coloro\
  \ che desiderano offrire contributi e donazioni per aiutare le nostre strutture\
  \ sanitarie in questo momento di emergenza."
Email: urp@apss.tn.it
IBAN: IT 96 J 02008 01802 000102416554
Intestazione: Azienda provinciale per i servizi sanitari di Trento Unicredit Banca
Link: https://www.apss.tn.it/-/emergenza-coronavirus-puoi-donare-anche-tu
Nome: Azienda Provinciale per i Servizi Sanitari - Trentino
Posizione: 46.050724 11.129837 0 0
Provincia: Trento
Regione: Trentino-Alto Adige
</yamldata></pre>

**Comment by GabCruciata** [comment]
Cambiarei titolo: Raccolta fondi strutture sanitarie Trento

**Comment by chiccap** [comment]
presente #723
