### ISSUE TITLE
Mascherine

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#704]
<pre><yamldata>
Cosa: Donazione mascherine
Descrizione: "A Siracusa,\nun'iniziativa del cuore messa in atto dall'associazione\
  \ sociale Astrea, nata in memoria di Stefano Biondo, in questo momento di emergenza\
  \ sanitaria data dal corona virus e dall’impossibilità di reperire mascherine.\n\n\"\
  Volontari uniti per la vita: al via la realizzazione e donazione di mascherine\"\
  .\n\nL'iniziativa nasce per contrastare la pandemia in atto nel nostro Paese e soprattutto\
  \ per aiutare le famiglie aretusee a contrastare - ognuno a livello personale -\
  \ la diffusione del virus. \"Abbiamo deciso - dichiara Rossana La Monica, presidente\
  \ dell'associazione - di metterci a lavoro per realizzare le mascherine utili a\
  \ prevenire la diffusione di questo virus. \nAbbiamo numerose volontarie che armate\
  \ di buona volontà, macchina da cucire, stoffa e carta da forno, stanno cucendo\
  \ centinaia di mascherine utili in questo momento di bisogno\". \nLe mascherine\
  \ saranno in cotone si potranno lavare e stirare per garantire maggiore igiene,\
  \ avranno un’apertura da cui si potrà cambiare all'esigenza la carta da forno “idrorepellente”\
  \ è stato dimostrato che non consente al virus di 'invadere' le vie respiratorie\
  \ di chi le indossa, impedendo la trasmissione tramite droplets.\nNaturalmente le\
  \ mascherine saranno donate.\nIn questo difficile momento che il mondo sta attraversando\
  \ si cerca di “esserci “ in tutti i modi, l’associazione Astrea, sta già collaborando\
  \ ad altre iniziative insieme ad altre associazioni come la Caritas per garantire\
  \ i pasti a chi è meno fortunato ed in difficoltà."
Destinatari: Cittadini
Email: Ass.astrea_sr@libero.it
Immagine: CBA6E885-036C-4E40-AA65-476B47DCE96D-14_50_1.jpeg
Indirizzo: 37.071581 15.291424 0 0
Link: https://www.siracusanews.it/siracusa-coronavirus-astrea-realizza-e-dona-mascherine-contro-la-pandemia/
Telefono: '3776927890'
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Non so se è una notizia verificata quella in cui si dice che è stato dimostrato che mascherine con stoffa e carta da forno proteggono dalla diffusione. Sarei per non accettarla anche se l'iniziativa di per se è lodevole.

**Comment by claudiamazzantiact** [comment]
@chiccap @cristigalas che ne dite?

**Comment by cristigalas** [comment]
Non accettiamo. Vedi qui https://www.fanpage.it/attualita/no-la-mascherina-fatta-con-la-carta-da-forno-non-funziona-contro-il-coronavirus/
