### ISSUE TITLE
App di telemedicina Lazio Doctor - Regione #Lazio

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#712]
<pre><yamldata>
Cosa: app di telemedicina LAZIODOCTOR
Descrizione: scaricabile al link  www.regione.lazio.it/DRcovid) per la telesorveglianza
  e il telemonitoraggio dei pazienti positivi e di quelli in isolamento domiciliare.
Link: https://www.regione.lazio.it/DRcovid/
Posizione: 41.894483 12.483147 0 0
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Già inserita #653
