### ISSUE TITLE
https://heritageexperience.it/

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#717]
<pre><yamldata>
Da_chi_offerta: https://heritageexperience.it/
Natura: solidale
Tipo_di_soggetto: pubblico
Titolo: https://heritageexperience.it/
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Segnalazione non contiene nessuna info e da verifica al link neanche. Non accettiamo?
