### ISSUE TITLE
Consulenza legale in materia penale

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#727]
<pre><yamldata>
Cosa: Consulenza legale in materia penale
Descrizione: 'Possiamo fornire consulenza preliminare in materia penale in riferimento
  a tutti quei provvedimenti emanati a seguito dell''emergenza Covid-19

  Basta inviare una mail a : info@studiobosaz.com  con la vostra domanda e i chiarimenti
  richiesti

  Rispondiamo celermente'
Destinatari: Tutti i soggetti interessati ad avere chiarimenti in materia penale
Email: info@studiobosaz.it
Link: https://www.studiobosaz.it/
Telefono: 05731782527
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Promozione allo studio legale. Non accetterei

**Comment by cristigalas** [comment]
No, infatti, non accettare e chiudi.
