### ISSUE TITLE
Passatempo (al Sud): giorni pieni di libri, arte, musica e allegria

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#729]
<pre><yamldata>
Da_chi_offerta: Regione Campania
Descrizione: 'Le iniziative in rete sono tantissime e di grande interesse, ogni ora
  ne arrivano di nuove. 

  È per questo che la Regione Campania, con il contributo di Scabec, ha voluto attivare
  sul proprio sito istituzionale una sorta di "catalogo" di siti, blog, link, pagine
  social e tutto quanto può essere utile ai genitori, ai nonni e ai ragazzi, per orientarsi
  e per raggiungere facilmente ciò che si cerca.'
Destinatari: Cittadini
Link: http://www.regione.campania.it/regione/it/news/regione-informa/passatempo-al-sud-giorni-pieni-di-libri-arte-musica-e-allegria
Natura: culturale-ricr
Titolo: 'Passatempo (al Sud): giorni pieni di libri, arte, musica e allegria'
</yamldata></pre>

**Comment by Saraveg** [comment]
Presente qui: https://www.covid19italia.help/issues/582/
