### ISSUE TITLE
Solidarietà Digitale

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#732]
<pre><yamldata>
Da_chi_offerta: Ministro per l’Innovazione tecnologica e la Digitalizzazione
Descrizione: 'È l’iniziativa del Ministro per l’Innovazione tecnologica e la Digitalizzazione,
  con supporto tecnico dell’Agenzia per l’Italia Digitale, per ridurre l’impatto sociale
  ed economico del Coronavirus grazie a soluzioni e servizi innovativi.

  Le iniziative, i servizi e le soluzioni disponibili hanno il comune obiettivo di
  migliorare la vita delle persone che in questo momento si vedono costrette a cambiare
  le loro abitudini permettendo di:

  - lavorare da remoto, attraverso connettività rapida e gratuita e l’utilizzo di
  piattaforme di smart working avanzate;

  - leggere gratuitamente un giornale anche senza andare in edicola o un libro senza
  andare in libreria sul proprio smartphone o tablet;

  - restare al passo con i percorsi scolastici e di formazione, grazie a piattaforme
  di e-learning.'
Destinatari: Cittadini e imprese
Link: https://solidarietadigitale.agid.gov.it
Natura: solidale
Tipo_di_soggetto: pubblico
Titolo: Solidarietà Digitale
</yamldata></pre>

**Comment by marco-acorte** [comment]
duplicato del #92

**Comment by cristigalas** [comment]
@marco-acorte visto. Non accetto e chiudo.
