### ISSUE TITLE
COVID-19 Open Research Dataset Challenge (CORD-19)

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#736]
<pre><yamldata>
Cosa: COVID-19 Open Research Dataset Challenge (CORD-19)
Descrizione: 'Il sito Kaggle propone dataset e challenge:

  In response to the COVID-19 pandemic, the White House and a coalition of leading
  research groups have prepared the COVID-19 Open Research Dataset (CORD-19). CORD-19
  is a resource of over 29,000 scholarly articles, including over 13,000 with full
  text, about COVID-19, SARS-CoV-2, and related coronaviruses. This freely available
  dataset is provided to the global research community to apply recent advances in
  natural language processing and other AI techniques to generate new insights in
  support of the ongoing fight against this infectious disease. There is a growing
  urgency for these approaches because of the rapid acceleration in new coronavirus
  literature, making it difficult for the medical research community to keep up.'
Fonte: https://www.kaggle.com/allen-institute-for-ai/CORD-19-research-challenge?utm_medium=email&utm_source=intercom&utm_campaign=CORD-19-research-chal-email#all_sources_metadata_2020-03-13.csv
Link: https://www.kaggle.com/allen-institute-for-ai/CORD-19-research-challenge/
</yamldata></pre>

**Comment by GabCruciata** [comment]
Manca posizione: metterei Seattle, sede del centro studi di riferimento. Posizione: 47.81903 121.71331

**Comment by cristigalas** [comment]
Non accettiamo segnalazioni di dati.
