### ISSUE TITLE
Raccolta Fondi - Fondazione Cassa di Risparmio # Firenze per 700 infermieri

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#739]
<pre><yamldata>
Causale: Sostieni un infermiere
Descrizione: 'La Fondazione Cassa di Risparmio di Firenze e la Fondazione Claudio
  Ciai lanciano una campagna di raccolta fondi per aiutare i 700 infermieri che arriveranno
  a Firenze da tutta Italia per far fronte all’emergenza Covid-19. L’obiettivo è raggiungere
  ventimila euro: la somma — si può donare sulla piattaforma GoFundMe.com verrà poi
  girata all’Ordine degli Infermieri di Firenze e Pistoia ed utilizzata per pagare
  gli affitti.'
IBAN: IT50 N 05034 02802 000000002751
Intestazione: Fondazione Claudio Ciai
Link: https://www.gofundme.com/f/sostieniuninfermiere
Nome: '#SostieniUnInfermiere, raccolta fondi di Fondazione Cassa di Risparmio Firenze
  e Fondazione Ciai'
Posizione: 43.769668 11.254342 0 0
</yamldata></pre>

**Comment by luciaroma** [comment]
L'organizzatore ha momentaneamente disattivato le donazioni per questa campagna.
