### ISSUE TITLE
Raccolta fondi online Croce Rossa #Pavia

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#74]
<pre><yamldata>
Comune: Pavia
Posizione: 45.1820226 9.1718868 0 0
Provincia: Pavia
Regione: Lombardia
chi: Croce Rossa Italiana- Pavia
comune: Pavia
contatti: ''
descrizione: Raccolta fondi su Facebook per dotare volontari e operatori Croce Rossa
  di dispositivi di protezione individuale (DPI) e materiale per la sanificazione.
destinatari: Croce Rossa
fonte: https://www.facebook.com/donate/492487048085274/?fundraiser_source=external_url
provincia: Pavia
regione: Lombardia
tag: Raccolta fondi
</yamldata></pre>

**Comment by michelerestuccia** [comment]
La raccolta fondi è terminata
