### ISSUE TITLE
Tim, Vodafone, Wind, Amazon, Mondadori e tante altre società aderiscono al piano di solidarietà digitale

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#754]
<pre><yamldata>
Cosa: Tim, Vodafone, Wind, Amazon, Mondadori e tante altre società aderiscono al piano
  di solidarietà digitale, offrendo servizi gratuiti a tutti gli italiani che restano
  a casa
Descrizione: Tim, Vodafone, Wind, Amazon, Mondadori e tante altre società aderiscono
  al piano di solidarietà digitale, offrendo servizi gratuiti a tutti gli italiani
  che restano a casa
Link: https://www.exibart.com/iorestoacasa/solidarieta-digitale-i-servizi-di-amazon-e-mondadori-per-chi-resta-a-casa/?fbclid=IwAR33J5vKgtB4ecwIBxg4CDDYtIwuMx1fqgDIr76GijOWXKNgKw5CYLO9Cwo
</yamldata></pre>

**Comment by FrancescaZambi89** [comment]
informazioni già inserite in #issue92
