### ISSUE TITLE
Le copie delle riviste Condé Nast gratis per tre mesi (Wired, Vogue, AD)

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#755]
<pre><yamldata>
Cosa: Le copie delle riviste Condé Nast gratis per tre mesi (Wired, Vogue, AD)
Descrizione: Le copie delle riviste Condé Nast gratis per tre mesi.
Link: https://www.exibart.com/iorestoacasa/solidarieta-digitale-le-copie-delle-riviste-conde-nast-gratis-per-tre-mesi/
</yamldata></pre>

**Comment by FrancescaZambi89** [comment]
già inserita in issue #482
