### ISSUE TITLE
Report Completo Aggiornato, Dati Covid19 - Power BI

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#757]
<pre><yamldata>
Cosa: Report Completo Aggiornato, Dati Covid19 - Power BI
Descrizione: "https://aka.ms/covidreport\n\nAndrea Benedetti: \"Sabato scorso, stufo\
  \ di leggere cose, decido di aprire Power BI, connettermi a un dataset ufficiale\
  \ (John Hopkins) e costruire una dashboard per vedere cosa sta succedendo nel mondo\n\
  \nIn 3 ore pubblico (gratuitamente per chiunque) il primo lavoro di 8 report\n\n\
  La sorpresa più grande arriva da Protezione Civile che rende pubblici i dati: un\
  \ lavoro straordinario\n\nPassano giorni, nottate sui numeri, misure d'interesse,\
  \ studi dei fenomeni, un modello di analisi sempre più ricco\n\nDopo 7 giorni, tra\
  \ ritagli di tempo e orari folli, (mentre il \"lavoro normale\" continua):\n- 23\
  \ report\n- 15 dataset\n- 1 repo GitHub\n- 85 commits\n- 9 collaboratori (amici\
  \ e straordinari professionisti) di 3 nazioni\n\nOgnuno mette a disposizione quello\
  \ che può\nNoi, qui, ci mettiamo un pò di testa, un pò di tempo, un pò di competenza\
  \ e, certamente, tanto cuore\n\nAnche perchè, come dice un'amica che cito testualmente:\
  \ \"la matematica e la statistica, pur con tutti i limiti dell'attendibilità e precisione\
  \ di alcuni dati sono il modo più intelligente di guardare a un fenomeno, limitandone\
  \ la soggettività interpretativa individuale ed emotiva.\"\n\n https://aka.ms/covidreport"
Fonte: https://www.linkedin.com/in/abenedetti/
Posizione: 45.465765 9.186905 0 0
</yamldata></pre>

**Comment by FrancescaZambi89** [comment]
@cristigalas  @chiccap ero in dubbio se approvare o meno questo progetto di opendata individuale. Come facciamo a verificare se è affidabile?

**Comment by cristigalas** [comment]
@FrancescaZambi89 infatti, lasciamo perdere. Non accettare e chiudi.

**Comment by FrancescaZambi89** [comment]
> @FrancescaZambi89 infatti, lasciamo perdere. Non accettare e chiudi.

ok! Grazie del supporto! @cristigalas
