### ISSUE TITLE
Informazioni tradotte per stranieri

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#758]
<pre><yamldata>
Cosa: Informazioni tradotte per stranieri
Descrizione: Video e pdf informativi tradotti in più lingue per stranieri che non
  parlano italiano. Riguardano sia la malattia che i numeri di emergenza che i decreti
  del governo.
Fonte: Il Grande Colibrì
Indirizzo: 41.27408726 16.41721938 0 0
Link: https://www.ilgrandecolibri.com/en/coronavirus-in-italy-videos-and-information-for-migrants/
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 41.27408726 16.41721938 (Trani) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=41.27408726+16.41721938&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by claudiamazzantiact** [comment]
Già inserita #339
