### ISSUE TITLE
Airbnb per medici e infermieri,

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#766]
<pre><yamldata>
Da_chi_offerta: AIR BNB
Descrizione: "Airbnb mette in comunicazione, in maniera semplice e diretta, gli host\
  \ che vogliono rendere disponibile la propria casa, senza compenso, in aiuto al\
  \ personale medico, con infermieri e dottori in trasferta che potranno scegliere\
  \ in pochi minuti l’alloggio più idoneo alle proprie esigenze. \nAirbnb si farà\
  \ carico dei costi dell’operazione, consentendo anche la copertura delle spese correnti\
  \ agli host.\nPer coordinare le richieste, che potranno venire avanzate dai singoli\
  \ operatori sanitari ma anche da parte delle stesse strutture ospedaliere, Airbnb\
  \ collaborerà con l’associazione OspitaMI nella gestione del processo di prenotazione,\
  \ entrando direttamente in contatto con medici e infermieri che compileranno il\
  \ modulo online."
Destinatari: Personale ospedaliero
Link: https://news.airbnb.com/it/airbnb-e-la-comunita-di-host-a-fianco-di-medici-e-infermieri-nellemergenza/
Natura: sostegno-lavor
Titolo: Airbnb per medici e infermieri,
</yamldata></pre>

**Comment by chiccap** [comment]
già presente #774
