### ISSUE TITLE
BOT Telegram @CovidITAbot

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#767]
<pre><yamldata>
Cosa: BOT Telegram @CovidITAbot
Descrizione: Questo bot fornisce i dati ufficiali sul contagio da Coronavirus. I dati
  sono forniti dalla Presidenza del Consiglio dei Ministri.
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Già presente qui #753 e non risolta

**Comment by floatingpurr** [comment]
Ciao @claudiamazzantiact, cosa intendi con non risolta?

**Comment by claudiamazzantiact** [comment]
Ciao, neanche l'altra segnalazione del bot è stata accettata/rifiutata.
