### ISSUE TITLE
L’A.O. Civico Benfratelli #Palermo seleziona con urgenza un #Biologo

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#780]
<pre><yamldata>
Cosa: L’A.O. “Civico Benfratelli” di Palermo seleziona con urgenza un Biologo
Descrizione: 'L’azienda Ospedaliera di Alta Specializzazione Civico Benfratelli di
  Palermo seleziona con urgenza un Biologo con Specializzazione in Microbiologia e
  Virologia per il conferimento di contratto a tempo determinato. Il concorso è bandito
  in urgenza ai sensi dell’Art. 2 Decreto Legislativo n.14/2020 per il contesto di
  emergenza e conseguente contenimento della pandemia da Covid-19.

  Si rammenta che trattandosi di un concorso emanato in regime di Urgenza, la scadenza
  per la presentazione della domanda di partecipazione è conseguentemente molto breve,
  essa è fissata per il 19 Marzo 2020.

  Il concorso è il primo in Sicilia, ed è prova dell’impegno della Delegazione Regionale
  Sicilia, nel sostenere ufficialmente l’urgenza di procedure concorsuale per i Biologi
  agendo con un interlocuzione istituzionale continua.

  Si invitano i colleghi interessati a prendere visione del bando al seguente all’indirizzo
  Arnascivico.it'
Destinatari: Biologi e biologhe
Indirizzo: 38.1109 13.352814 0 0
Link: https://www.onb.it/2020/03/18/la-o-civico-benfratelli-di-palermo-seleziona-con-urgenza-un-biologo/
</yamldata></pre>

**Comment by chiccap** [comment]
scaduto
