### ISSUE TITLE
Supporto e consulenza per lavoro a distanza

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#789]
<pre><yamldata>
Cosa: Supporto e consulenza per lavoro a distanza
Descrizione: Sono disponibile a supportare e consigliare le piccole imprese che hanno
  necessità a implementare il lavoro a distanza mediante sitemi informatici.
Destinatari: Piccole imprese.
Email: info@algasi.it
Indirizzo: 45.683402 13.127955 0 51
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Promozione personale e non a titolo gratuito. Non accetto.
