### ISSUE TITLE
Autocertificazione

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#794]
<pre><yamldata>
Cosa: Autocertificazione
Descrizione: Ma la vostra segnalazione di usare il sito a questo link https://www.modulospostamento.it/
  di alcuni giorni fa, alla luce della comunicazione di PalermoToday, è da ritenersi
  quindi non più attendibile ??
Posizione: 41.85813 12.440651 46.829246520996094 65
</yamldata></pre>

**Comment by cristigalas** [comment]
Salve, purtroppo dopo alcune segnalazioni e verifiche abbiamo scoperto che quel sito (e altri) non era sicuro e lo abbiamo rimosso...
