### ISSUE TITLE
Raccolta fondi per acquisto materiali di protezione per volontari Croce Rossa #Monza

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#80]
<pre><yamldata>
Comune: Monza
Posizione: 45.5765081 9.26791783339991 0 0
Provincia: Monza e della Brianza
Regione: Lombardia
chi: Croce Rossa Monza
comune: Monza
contatti: ''
descrizione: Raccolta fondi per acquisto di materiale di protezione per i volontari.
destinatari: tutti
fonte: https://www.gofundme.com/f/yqppre-cri-monza-coronavirus-2019
provincia: Monza
regione: Lombardia
tag: Raccolta fondi
</yamldata></pre>

**Comment by michelerestuccia** [comment]
L'organizzatore ha momentaneamente disattivato le donazioni per questa campagna.
