### ISSUE TITLE
Coronavirus: disposizioni e chiarimenti uso delle app mobile per autocertificazione cartacea

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#801]
<pre><yamldata>
Cosa: 'Coronavirus: disposizioni e chiarimenti uso delle app mobile per autocertificazione
  cartacea'
Descrizione: In relazione alla notizia riportata da alcuni organi di informazione
  riguardante applicazioni per smartphone che sostituirebbero la autocertificazione
  cartacea per coloro che escono da casa, la Polizia postale precisa che il ricorso
  a tali servizi, seppur motivato da esigenze di apparente semplificazione e velocizzazione
  delle procedure, si pone in contrasto con le prescrizioni attualmente vigenti ...
Link: https://www.poliziadistato.it/articolo/155e727296ce090693527218
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
