### ISSUE TITLE
Supporto telefonico

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#803]
<pre><yamldata>
Cosa: Supporto telefonico
Descrizione: Sarebbe bello fare qualcosa o dare una mano a chi aiuta anziani soli
  anche solo facendogli compagnia al telefono.
Destinatari: Anziani soli
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Segnalazione senza contatti
