### ISSUE TITLE
Raccolta fondi per aiutare l'ospedale di Cuneo ad affrontare l'emergenza covid-19

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#812]
<pre><yamldata>
Causale: Donazione Covid-19 con cognome, nome, codice fiscale, indirizzo mail e numero
  di telefono del benefattore
Descrizione: Raccolta fondi per aiutare l'ospedale di Cuneo ad affrontare l'emergenza
  covid-19
Email: aimale.r@ospedale.cuneo.it
IBAN: IT02D0845010200000000012922
Indirizzo: 44.39329624 7.55117163
Intestazione: Fondazione azienda ospedaliera Santa Croce e Carle Cuneo onlus
Link: http://www.ospedale.cuneo.it/index.php?id=1130
Nome: Fondazione azienda ospedaliera Santa Croce e Carle Cuneo onlus
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 44.39329624 7.55117163 (Cuneo) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=44.39329624+7.55117163&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by chiccap** [comment]
iban sbagliato e già presente in #811
