### ISSUE TITLE
Raccolta fondi a favore dell'Ospedale Niguarda di #Milano

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#846]
<pre><yamldata>
Link: https://www.ospedaleniguarda.it/news/leggi/emergenza-coronavirus-donazioni-allospedale
Nome: Ospedale Niguarda
Posizione: 45.509870750000005 9.186030699233626 0 0
</yamldata></pre>

**Comment by chiccap** [comment]
chiudo perchè #1362 più completa
