### ISSUE TITLE
Articoli scientifici su covid-19

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#848]
<pre><yamldata>
Cosa: Articoli scientifici su covid-19
Fonte: AIRIcerca, associazione ricercatori italiani all'estero
Link: https://informa.airicerca.org/it/category/airiclip
</yamldata></pre>

**Comment by chiccap** [comment]
@drizzt aiuto!

**Comment by GabCruciata** [comment]
Come sede proporrei sede legale dell'associazione che organizza l'iniziativa. 
Posizione: 45.52909 10.20755

**Comment by cristigalas** [comment]
Non accettiamo.
