### ISSUE TITLE
Raccolta fondi online Comunità di Sant’Egidio per persone senza dimora e anziani in difficoltà

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#85]
<pre><yamldata>
Comune: Roma
Posizione: 41.890213 12.4690343 0 0
Provincia: Roma
Regione: Lazio
chi: "Comunit\xE0 di Sant'Egidio"
comune: Roma
contatti: ''
descrizione: Raccolta fondi online per offrire generi utili, come alimentari, gel
  igienizzanti e fazzoletti di carta a senzatetto e anziani soli.
destinatari: persone senza dimora, anziani
fonte: https://www.facebook.com/donate/503579490301582/10221812290241438/
provincia: Roma
regione: Lazio
tag: Raccolta fondi
</yamldata></pre>

**Comment by michelerestuccia** [comment]
La raccolta fondi è conclusa
