### ISSUE TITLE
IoRestoACasa.work - Progetto open per rendere disponibili videoconferenze

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#858]
<pre><yamldata>
Da_chi_offerta: Progetto open per rendere disponibili dei server per videoconferenze
  gratis
Descrizione: 'Io Resto A Casa .work

  Il #covid19 ci obbliga a rimanere dentro casa. Questo non significa che dobbiamo
  smettere di lavorare, studiare, socializzare.

  Ci sono tanti strumenti che possiamo utilizzare per lo #smartworking, ma molti non
  sanno come fare. Abbiamo deciso di rimboccarci le maniche ed aiutare queste persone.

  Jitsi Meet

  E'' un progetto Open Source che permette di effettuare videochiamate, semplicemente
  aprendo un URL tramite browser, senza installare programmi, senza registrarsi.

  Browser supportati

  Jitsi funziona al meglio con Chromium o Google Chrome.

  Puoi anche usarlo da smartphone installando la app per Android o iOS'
Destinatari: Chiunque in Italia che abbia bisogno di videoconferenze gratis
Natura: sostegno-lavor
Titolo: Io Resto A Casa .work
</yamldata></pre>

**Comment by chiccap** [comment]
già presente in #731
