### ISSUE TITLE
Raccolta fondi online per sostenere Città della Salute di #Torino

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#86]
<pre><yamldata>chi: Francesco Pecco Bagnaia
comune: Chivasso
contatti: ''
descrizione: Raccolta fondi per sostenere Citt\xE0 della Salute di Torino
destinatari: "tutti"
fonte: https://www.gofundme.com/f/exfz34-insieme-contro-il-virus?utm_source=customer&utm_medium=copy_link-tip&utm_campaign=p_cp+share-sheet
provincia: Torino
regione: Piemonte
tag: Raccolta fondi
</yamldata></pre>

**Comment by michelerestuccia** [comment]
La raccolta fondi non accetta più donazioni.
