### ISSUE TITLE
Fundraising - Raccolta fondi Ospedale San Jacopo #Pistoia 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#861]
<pre><yamldata>
Descrizione: "Stiamo vivendo durante una delle emergenze sanitarie più gravi mai viste\
  \ e ciò sta producendo conseguenze in tutti gli ambiti. \nSicuramente le strutture\
  \ che più hanno bisogno di sostegno in questo momento sono gli ospedali, che ogni\
  \ giorno ricevono un numero elevato di pazienti nuovi, gravi e non.\n\nCon questa\
  \ campagna, organizzata dal Fondo Marco Mungai e un team di altre persone, vogliamo\
  \ raccogliere i soldi per l'Ospedale San Jacopo di Pistoia, l'ospedale della nostra\
  \ città, con all'interno medici e personale sanitario che giorno e notte danno il\
  \ massimo per salvare le nostre vite.\n\nOgni contributo è importante! La donazione\
  \ minima è di 5€ e se uniamo le nostre forze, anche con piccole somme, potremo fornire\
  \ un sostegno fondamentale per garantire, a chiunque si presenti in ospedale, le\
  \ cure e i servizi necessari.\n\nVi ringraziamo sinceramente.\n\nP.S. I fondi saranno\
  \ raccolti sul conto corrente del Fondo Marco Mungai, del quale Giulio Lotti ricopre\
  \ la carica di presidente e quindi beneficiario. Con i fondi verranno acquistati\
  \ beni di prima necessità che ci stanno già commissionando dall'ospedale.\n\n-----------------------------------------------------------------------------------------------------------\n\
  \nWe are facing one of the worst healthcare emergencies since records began. There\
  \ are severe consequences in all fields of life.\n\nHospitals definitely need more\
  \ support than other structures, with more patients in severe and non severe conditions\
  \ coming every day.\n\nThis campaign has been organized by the Marco Mungai Foundation\
  \ and by a team of volunteers willing to raise money for the San Jacopo hospital\
  \ in Pistoia, our city. Physicians and healthcare workers and giving their best\
  \ day and night, in order to save lives.\n\nEvery donation matters! The minimum\
  \ donation is 5€. If we join our forces -even with small amounts of money- we will\
  \ be able to give support, treatments and services to all those who will come to\
  \ seek help in our hospital.\n\nThank you very much.\n\nP.S. The funds will be collected\
  \ on the current account of the Marco Mungai Fund, of which Giulio Lotti holds the\
  \ position of president and therefore beneficiary. With the funds will be purchased\
  \ basic necessities that are already commissioning us from the hospital.\n-"
Email: zaira2mae@yahoo.it
Posizione: 43.933465 10.91734146 0 0
Link: https://www.gofundme.com/f/covid19-sosteniamo-l039ospedale-di-pistoia
Nome: Fondo Marco Mungai e altre 10 persone gestiscono questa raccolta fondi in favore
  di Giulio Lotti.
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 43.933465 10.91734146 (Pistoia) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=43.933465+10.91734146&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by luciaroma** [comment]
La raccolta fondi non accetta più donazioni
