### ISSUE TITLE
Raccolta fondi per Ospedale di #Merate

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#865]
<pre><yamldata>
Da_chi_offerta: Massimiliano B.
Destinatari: Ospedale Mandic Merate
Link: https://www.gofundme.com/f/ospedale-mandic-merate?viewupdates=1&rcid=r01-158400690223-79297d5d50234b14&utm_medium=email&utm_source=customer&utm_campaign=p_email%2B1137-update-supporters-v5b
Natura: solidale
Posizione: 45.698327 9.427428 0 0
Tipo_di_soggetto: privato
Titolo: gofundme Ospedale di Merate
</yamldata></pre>

**Comment by luciaroma** [comment]
L'organizzatore ha disattivato le donazioni per questa campagna.
