### ISSUE TITLE
La Fondazione comunitaria del Lecchese, in collaborazione con le testate giornalistiche locali, lanc

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#867]
<pre><yamldata>
Da_chi_offerta: Fondazione Comunitaria Del Lecchese
Descrizione: "La Fondazione comunitaria del Lecchese, in collaborazione con le testate\
  \ giornalistiche locali, lancia una raccolta fondi a sostegno dell’Azienda Socio\
  \ Sanitaria Territoriale di Lecco che gestisce i presidi ospedalieri di Lecco e\
  \ Merate, per potenziare l’operatività dei reparti ospedalieri impegnati nel contrasto\
  \ all’epidemia da coronavirus.\n\nLa Fondazione invita cittadini, aziende ed enti\
  \ del territorio a partecipare alla raccolta Fondi.\n\nAnche una piccola donazione\
  \ può fare la differenza.\n\nLe somme raccolte verranno comunicate quotidianamente\
  \ sulle pagine dei giornali locali e saranno destinate all’acquisto di attrezzature\
  \ e materiali per l’emergenza coronavirus, in accordo con la direzione generale\
  \ dell’ASST di Lecco.\n\nPer il lancio della campagna la Fondazione comunitaria\
  \ mette a disposizione proprie risorse per un totale di 100.000 euro.\n\nSi potrà\
  \ donare anche tramite Bonifico sul conto corrente intestato a: Fondazione comunitaria\
  \ del Lecchese presso Intesa Sanpaolo\nIBAN: IT28 Z030 6909 6061 0000 0003 286\n\
  Causale: AIUTIAMOCI\nN.B. Le donazioni tramite bonifico daranno diritto ai benefici\
  \ fiscali previsti dalla normativa vigente. \n\nInformazioni complete sul sito \n\
  \nPer ulteriori informazioni: http://www.fondazionelecco.org/   oppure Fondazione\
  \ comunitaria del Lecchese - 0341 353123"
Destinatari: Ospedali di Lecco e Merate
Link: https://www.gofundme.com/f/aiutiamoci-emergenza-coronavirus-lecco
Natura: solidale
Posizione: 45.852448 9.415069 0 0
Tipo_di_soggetto: privato
</yamldata></pre>

**Comment by chiccap** [comment]
Già presente #866
