### ISSUE TITLE
La Regione Emilia-Romagna ha deciso di mettere a disposizione di chiunque voglia dare un contributo 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#874]
<pre><yamldata>
BIC_SWIFT: UNCRITM1BA2
Causale: 'Insieme si può: l''Emilia-Romagna contro il Coronavirus'
Descrizione: La Regione Emilia-Romagna ha deciso di mettere a disposizione di chiunque
  voglia dare un contributo per la gestione dell’emergenza sanitaria il conto corrente
  della Protezione civile regionale dell’Emilia-Romagna. Anche in questa circostanza,
  come è stato fatto per la ricostruzione post sisma, ogni euro raccolto e il suo
  utilizzo verranno resocontati pubblicamente.
IBAN: IT69G0200802435000104428964
Indirizzo: 41.89277044 12.48366723
Nome: Protezione civile regionale dell’Emilia-Romagna
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 41.89277044 12.48366723 (Roma) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=41.89277044+12.48366723&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by chiccap** [comment]
Già presente #595
