### ISSUE TITLE
Richiesta informazioni servizi di consegna a domicilio #Ostia #Roma

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#876]
<pre><yamldata>
Cosa: '#Ostia Consegna a domicilio frutta e verdura'
Descrizione: Ho bisogno di sapere se ci sono negozi che consegnano frutta e verdura
  a Ostia, che posso pagare online. Mi serve rifornire i miei genitori (vivo a Milano).
  Grazie.
Destinatari: Famiglia di anziani
Posizione: 41.75365 12.28574
</yamldata></pre>

**Comment by chiccap** [comment]
@cristigalas non ha lasciato recapiti purtroppo. non abbiamo ancora ricevuto segnalazioni per il municipio X cerco e quello che possiamo fare è pubblicarlo in bollettino sperando riesca ad intercettare l'informazione.

**Comment by chiccap** [comment]
trovato e inserito #907

**Comment by cristigalas** [comment]
@chiccap ma senza email non ha senso pubblicare la richiesta di aiuto, semmai ripubblichiamo segnalazione su Municipio X su Telegram, Twitter e Facebook...

**Comment by cristigalas** [comment]
La tolgo dalla piattaforma.
