### ISSUE TITLE
Folding@Home

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#881]
<pre><yamldata>
Da_chi_offerta: The Folding@home Consortium (FAHC)
Descrizione: Folding@home (FAH or F@h) is a distributed computing project for simulating
  protein dynamics, including the process of protein folding and the movements of
  proteins implicated in a variety of diseases. It brings together citizen scientists
  who volunteer to run simulations of protein dynamics on their personal computers.
  Insights from this data are helping scientists to better understand biology, and
  providing new opportunities for developing therapeutics.
Destinatari: Possessori di un computer
Link: https://foldingathome.org/
Natura: solidale
Tipo_di_soggetto: pubblico
Titolo: Folding@Home
</yamldata></pre>

**Comment by chiccap** [comment]
@cristigalas non so se accettare. in potenza potrebbe essere pertinente allo scopo della piattaforma ma al momento non saprei nemmeno che label assegnare!

**Comment by cristigalas** [comment]
Lasciamo perdere...
