### ISSUE TITLE
Rosetta@Home

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#882]
<pre><yamldata>
Da_chi_offerta: University of Washington
Descrizione: Rosetta@home needs your help to determine the 3-dimensional shapes of
  proteins in research that may ultimately lead to finding cures for some major human
  diseases. By running the Rosetta program on your computer while you don't need it
  you will help us speed up and extend our research in ways we couldn't possibly attempt
  without your help. You will also be helping our efforts at designing new proteins
  to fight diseases such as HIV, Malaria, Cancer, and Alzheimer's. Please join us
  in our efforts! Rosetta@home is not for profit.
Destinatari: Possessori di un computer
Link: http://boinc.bakerlab.org/rosetta/
Natura: solidale
Tipo_di_soggetto: pubblico
Titolo: Rosetta@Home
</yamldata></pre>

**Comment by chiccap** [comment]
@cristigalas come #881

**Comment by cristigalas** [comment]
Non accettiamo e chiudiamo.
