### ISSUE TITLE
Grafici aggiornati dati coronavirus in Italia per Regione e Provincia

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#885]
<pre><yamldata>
Cosa: Grafici aggiornati dati coronavirus in Italia per Regione e Provincia
Descrizione: Visualizzatore su base regionale e su base provinciale, che consente di confrontare l'andamento dei dati sul coronavirus tra provincia e provincia. Fonte dei dati: Protezione civile nazionale.
Fonte:
Link: https://covid-19.netseven.it/regioni-province
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Non ricordo se avevamo detto di accettare questo tipo di segnalazioni...

**Comment by GabCruciata** [comment]
Per posizione metterei sede legale di sviluppatori. Posizione: 43.706941 10.421053

**Comment by cristigalas** [comment]
Non accettiamo.
