### ISSUE TITLE
Raccolta fondi Fondazione Arca per servizi alle persone senza dimora 

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia_segnalazioni#89]
<pre><yamldata>
Comune: Milano
Posizione: 45.4770487 9.2011876 0 0
Provincia: Milano
Regione: Lombardia
chi: Fondazione Arca
comune: Tutta Italia
contatti: ''
descrizione: Raccolta fondi per dotare di dispositivi e materiali protettivi gli operatori
  dei servizi alle persone senza dimora.
destinatari: 'Operatori servizi persone senza dimora '
fonte: https://www.facebook.com/donate/543942392915387/
provincia: ''
regione: ''
tag: Raccolta fondi
</yamldata></pre>

**Comment by michelerestuccia** [comment]
La raccolta fondi è conclusa
