### ISSUE TITLE
ZonaVerde - monitoraggio di finanziamenti a sostegno di imprese, professionisti e enti no profit 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#895]
<pre><yamldata>
Da_chi_offerta: Excursus srl
Descrizione: Monitoraggio dei finanziamenti (bandi nazionali e internazionali ed erogazioni
  a sportello) e sostegni economici pubblici a favore di imprese, professionisti,
  organizzazioni del Terzo Settore che stanno pagando gli effetti dell’emergenza sanitaria
  Covid-19.
Destinatari: imprese, professionisti, organizzazioni del Terzo Settore che stanno
  pagando gli effetti dell’emergenza sanitaria Covid-19
Link: https://www.excursusplus.it/italia-zonaverde/
Natura: sostegno-lavor
Titolo: '#ZonaVerde'
Posizione: 45.4865583 9.1869688 0 0
</yamldata></pre>

**Comment by cristigalas** [comment]
Mah, lascerei perdere... se volevano davvero condividere potevano mettere online i bandi e invece bisogna inviare una email e poi sotto c’è rimando ad una prova gratuita dell’app... insomma operazione poco chiara, secondo me.
