### ISSUE TITLE
Portale assistenza PMI

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#903]
<pre><yamldata>
Da_chi_offerta: Federterziario
Descrizione: Federterziario associazione datoriale rappresenta PMI su tutto il territorio
  nazionale e mette a disposizione delle aziende la propria rete territoriale di consulenti
  per aiutare le aziende ad accedere alle misure previste dal Decreto Salva Italia.
Destinatari: Micro piccole e medie imprese
Link: https://www.federterziario.it/covid19italia
Natura: sostegno-lavor
Titolo: Portale assistenza PMI
</yamldata></pre>

**Comment by FrancescaZambi89** [comment]
@cristigalas che facciamo con questa? offrono un servizio a pagamento... la policy da indicazioni su casi come questi?

**Comment by cristigalas** [comment]
No, lasciamo perdere... e poi le imprese sanno che esistono queste associazioni di categoria che offrono consulenze...

**Comment by FrancescaZambi89** [comment]
> No, lasciamo perdere... e poi le imprese sanno che esistono queste associazioni di categoria che offrono consulenze...

d'accordo, grazie @cristigalas . inserisco la label "non accettata"?

**Comment by cristigalas** [comment]
@FrancescaZambi89 si e poi chiudi. Vedi bottone sotto close .
