### ISSUE TITLE
#Lecco Campagna di raccolta fondi "Aiutiamoci" a favore dell'Azienda Sanitaria Locale per il reperimento di materiali e attrezzature

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#908]
<pre><yamldata>
Causale: AIUTIAMOCI
Descrizione: Campagna di raccolta fondi denominata "Aiutiamoci" volta a reperire risorse
  per sostenere l'acquisto di materiali e attrezzature  a favore dell'ASST di Lecco,
  destinate a potenziare i presidi ospedalieri di Lecco e Merate nella loro azione
  di contrasto e cura del virus Covid-19
Email: segreteria@fondazionelecco.org
IBAN: IT28Z0306909606100000003286
Intestazione: Fondazione comunitaria del Lecchese Onlus
Nome: Fondazione comunitaria del Lecchese Onlus
Link: https://www.fondazionelecco.org/raccolta-fondi-aiutiamoci-aggiornamento-del-20-marzo-ore-16/
Posizione: 
</yamldata></pre>

**Comment by FrancescaZambi89** [comment]
già inserita in #issue866
