### ISSUE TITLE
STUDENTI INFERMIERISTICA IMPOSSIBILITATI A LAUREARSI

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#924]
<pre><yamldata>
Cosa: STUDENTI INFERMIERISTICA IMPOSSIBILITATI A LAUREARSI
Descrizione: Gli studenti e le studentesse del corso di "Laurea in Infermieristica
  (abilitante alla professione sanitaria di Infermiere) del Policlinico Umberto I
  di Roma / Università Uniroma 1 La Sapienza" riportano il fatto che la facoltà non
  abbia ancora attivato alcuna modalità di didattica a distanza, non sa se e come
  potrà farlo e fornisce risposte incomplete agli studenti. Gli studenti sono ansiosi
  di laurearsi per poter dare una mano subito, molti di loro hanno anche già svolto
  il tirocinio in terapia intensiva e potrebbero essere impiegati immediatamente negli
  ospedali italiani in difficoltà.
</yamldata></pre>

**Comment by luciaroma** [comment]
è una polemica/sfogo interna al Policlinico Umberto / Roma 1; non si è tradotta in un appello più esteso o in una proposta alternativa, nè in una richiesta di aiuto specifica. Per queste ragioni non l'ho accettata

**Comment by cristigalas** [comment]
Brava! Quelle non accettate vanno anche chiuse.
