### ISSUE TITLE
 Protezione Civile: online bando per task force di 300 medici

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#938]
<pre><yamldata>
Cosa: Online bando Protezione Civile per costituire task force di 300 medici
Descrizione: "Online il bando per formare la taskforce di 300 medici volontari.\n\
  Compila il form per dare la disponibilità a prestare la tua attività presso le Regioni\
  \ maggiormente colpite dall’emergenza coronavirus. \nE’ stata avviata la costituzione\
  \ della task force di 300 medici che opereranno a supporto delle strutture sanitarie\
  \ regionali per l’attuazione delle misure necessarie al contenimento e contrasto\
  \ dell’emergenza COVID -19.\nLa partecipazione alla task force sarà obbligatoria\
  \ per il datore di lavoro fatta eccezione per le strutture convenzionate per le\
  \ quali la possibilità di far parte della task force avviene su base consensuale\
  \ con il proprio datore di lavoro. La partecipazione alla task force prevede, inoltre,\
  \ il rimborso delle spese di viaggio ed una indennità forfettaria per ciascuna giornata\
  \ prestata, nella misura indicata nella Ordinanza allegata. Infine si evidenzia\
  \ che le Regioni provvederanno alla sistemazione alloggiativa."
Link: https://medicipercovid.protezionecivile.it/
</yamldata></pre>

**Comment by cristigalas** [comment]
Bando scaduto. Chiudo.
