### ISSUE TITLE
Regione Lazio: disponibile app LazioDrCovid

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#939]
<pre><yamldata>
Cosa: 'Regione Lazio: disponibile app LazioDrCovid'
Descrizione: La App della Regione Lazio LazioDrCovid è disponibile per utenti apple
  e android. Ad oggi hanno scaricato la app 9920 cittadini e 829 medici di medicina
  generale hanno avuto almeno un accesso alla piattaforma.
Link: https://www.facebook.com/101319221288183/posts/-coronavirus-la-app-laziodrcovid-disponibile-anche-per-gli-utenti-apple-oltre-ch/195367291883375/
Posizione: 41.903283 12.49506 0 0
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Già inserita qui #653
