### ISSUE TITLE
Bando task force 300 medici volontari per Nord Italia

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#949]
<pre><yamldata>
Cosa: Bando task force 300 medici volontari per Nord Italia
Descrizione: 'E’ stata avviata la costituzione della task force di 300 medici che
  opereranno a supporto delle strutture sanitarie regionali per l’attuazione delle
  misure necessarie al contenimento e contrasto dell’emergenza COVID -19.

  Se vuoi dare il tuo contributo, compila il form per dare la disponibilità a prestare
  la tua attività presso le Regioni maggiormente colpite.

  Se il tuo profilo sarà ritenuto idoneo verrai contattato da Dipartimento per definire
  nel dettaglio le modalità di impiego.

  Ti ricordiamo che la partecipazione alla task force sarà obbligatoria per il datore
  di lavoro fatta eccezione per le strutture convenzionate per le quali la possibilità
  di far parte della task force avviene su base consensuale con il proprio datore
  di lavoro.

  La partecipazione alla task force prevede, inoltre, il rimborso delle spese di viaggio
  ed una indennità forfettaria per ciascuna giornata prestata, nella misura indicata
  nella Ordinanza allegata.

  Infine si evidenzia che le Regioni provvederanno alla sistemazione alloggiativa.'
Link: https://medicipercovid.protezionecivile.it/index.php?r=survey%2Findex&sid=136947&fbclid=IwAR2TOctezKtDwLLmzapRFV2o4P7AbDe9S6Yg8FvOhjWgJiNNXfLONwzlGmY
</yamldata></pre>

**Comment by Saraveg** [comment]
Già presente: https://github.com/emergenzeHack/covid19italia_segnalazioni/issues/938
