### ISSUE TITLE
Sul quotidiano Suddeutsche Zeitung numeri dei contagi per Paese (Deutsch)

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#950]
<pre><yamldata>
Cosa: osservatorio nr giorni raddoppio infetti per Paese
Descrizione: "Il quotidiano tedesco pubblica in prima pagina da alcuni giorni uno\
  \ specchietto in cui si evidenza in quanto tempo si raddoppia il numero di infetti\
  \ per Paese e se la tendenza sia in fase di rallentamento / stabile / o accelerazione.\
  \  \n\nMi pare molto utile per avere un senso dell'efficacia delle misure prese.\
  \  \n\nQui il link alla sottopagina (più elaborata della sintesi in prima): https://www.sueddeutsche.de/wissen/coronavirus-zahlen-daten-1.4844448\
  \  \n\nDa qui è possibile anche accedere ai dati in forma grezza."
Fonte: Sueddeutsche Zeitung / John Hopkins University
Link: https://www.sueddeutsche.de/
</yamldata></pre>

**Comment by cristigalas** [comment]
Non accettiamo questo tipo di notizie, sono ovunque...
