### ISSUE TITLE
Un ciclo di formazione e webinar gratuiti.

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#961]
<pre><yamldata>
Da_chi_offerta: Produzioni dal basso
Descrizione: Un ciclo di formazione e webinar gratuiti.
Destinatari: Aperto a tutti senza nessuna distinzione, ma il focus degli argomenti
  è particolarmente indicato per soggetti del terzo settore e del non profit, mondo
  del volontariato, freelance, lavoratori cognitivi, associazioni culturali, artisti,
  organizzatori di eventi, formatori, imprese sociali e cooperative.
Link: https://www.attiviamoenergiepositive.it
Natura: didattica
Posizione: 0 0 0 0
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Già inserita in #824
