### ISSUE TITLE
Filaindiana.it - monitora le file dei supermercati in Lombardia

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#966]
<pre><yamldata>
Da_chi_offerta: Filaindiana.it
Descrizione: Filaindiana.it ti permette di dare un'occhiata allo stato di affollamento
  dei supermercati della tua zona, per aiutarti a scegliere quello con la coda più
  breve e fare la spesa in tutta sicurezza!
Destinatari: Abitanti della regione Lombardia
Link: https://filaindiana.it/
Natura: solidale
Tipo_di_soggetto: privato
Titolo: Filaindiana.it - monitora le file dei supermercati in Lombardia
</yamldata></pre>

**Comment by GabCruciata** [comment]
Impossibile inserire una posizione precisa, propongo Milano --> Posizione: 45.53828 9.38922

**Comment by chiccap** [comment]
presente in 904
