### ISSUE TITLE
Osservatorio su Covid19

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#971]
<pre><yamldata>
Da_chi_offerta: Iovengoacasa.it
Destinatari: Cittadini
Link: https://iovengoacasa.it/covid19italia/
Natura: solidale
Tipo_di_soggetto: privato
Titolo: Osservatorio su Covid19
</yamldata></pre>

**Comment by GabCruciata** [comment]
Info su posizione non disponibili

**Comment by luciaroma** [comment]
la fonte è DPC e quei dati li diffondiamo già. Non accetterei perché non è una fonte primaria.
