### ISSUE TITLE
Vademecum del Viminale sull'uso e la scelta delle mascherine

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#973]
<pre><yamldata>
Cosa: Vademecum del Viminale sull'uso e la scelta delle mascherine
Descrizione: Attenzione all'utilizzo di dispositivi di protezione personale non idonei
  alla funzione che si svolge o all'uso che se ne fa. Dal ministero dell'Interno alcune
  indicazioni fondamentali per la scelta del modello più giusto e per il suo corretto
  utilizzo.
Link: http://www.rainews.it/dl/rainews/articoli/coronavirus-vademecum-viminale-uso-scelta-mascherine-aebf14ab-529a-4996-a611-3259bb23fdff.html
</yamldata></pre>

**Comment by luciaroma** [comment]
non ho trovato riscontri sul sito del Viminale, nè su quello del Ministero della Salute. Ci sono le linee guida dell'OMS e sono almeno di inizio Marzo.
Il link inserito inoltre risulta "non sicuro"
