### ISSUE TITLE
Indicazioni cui possono attenersi i sindaci per la pulizia degli spazi esterni

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#977]
<pre><yamldata>
Cosa: Indicazioni cui possono attenersi i sindaci per la pulizia degli spazi esterni
Descrizione: Il Consiglio del Sistema Nazionale per la Protezione dell'Ambiente -
  SNPA, composto dalle Agenzie Regionali e Provinciali per la Protezione Ambientale
  e da Ispra (Istituto Superiore per la Protezione e la Ricerca Ambientale) il 18
  marzo 2020 ha approvato un documento con indicazioni tecniche relativamente agli
  aspetti ambientali della pulizia degli ambienti esterni e dell’utilizzo di disinfettanti
  nel quadro dell’emergenza Covid-19 rifacendosi anche al parere sanitario dell'Istituto
  Superiore di Sanità (ISS) "Disinfezione degli ambienti esterni e utilizzo di disinfettanti
  (ipoclorito di sodio) su superfici stradali e pavimentazione urbana per la prevenzione
  della trasmissione dell'infezione da SARS-CoV-2”
Indirizzo: 42.56071258 12.64668751
Link: http://www.arpa.piemonte.it/arpa-comunica/file-notizie/2020/faq-aslarpasindacipuliziaesterni.pdf
</yamldata></pre>

**Comment by ehack-italy** [comment]
Sembra che questa segnalazione non sia geolocalizzata. Ho automaticamente aggiunto 42.56071258 12.64668751 (Terni) come coordinate. Per favore, controlla <a href='https://nominatim.openstreetmap.org/search.php?q=42.56071258+12.64668751&polygon_geojson=1&viewbox='>qui</a> se sono corrette. In caso positivo, rimuovi pure la label 'Posizione da verificare' da questa Issue, altrimenti, procedi a correggere o rimuovere la posizione come spiegato <a href='https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione'>qui</a>.

**Comment by luciaroma** [comment]
è doppio
