### ISSUE TITLE
farmaco giapponese AVIGAN

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#982]
<pre><yamldata>
Cosa: farmaco giapponese AVIGAN
Descrizione: "GIRA QUESTO MESSAGGIO IN FACEBOOK: \n- ATTENZIONE  CONDIVIDETE  documento\
  \ e notizia da verificare che gira da qualche giorno, di un farmaco giapponese AVIGAN\
  \ in Italia noto all'AIFA con altro nome in grado di contrastare il 90 % dei corona\
  \ virus - credo a questo punto sia il nostro Governo e  L'AIFA che debbano accertare\
  \ in fretta se ci sono fondamenti sulla veridicità, sull'efficacia del farmaco interpellando\
  \ sia Cina che Giappone, oppure aspettiamo la burocrazia e altri morti? oppure aspettiamo\
  \ che stabiliscano quale casa farmaceutica italiana o europea debba accaparrarsi\
  \ l'appalto magari con esclusiva per la distribuzione?"
Link: https://www3.nhk.or.jp/nhkworld/en/news/20200317_48/?fbclid=IwAR1dqMg357FPSA-l6HigZ-XAjWFzVp4aqvmE_bT_bBWmJsDiKK5_8ylXTFk
</yamldata></pre>

**Comment by cristigalas** [comment]
In realtà non c’è certezza che sia una bufala, anzi... vedi qui https://www.bufale.net/la-speranza-in-italia-si-chiama-avigan-farmaco-favipiravir-dal-giappone-contro-il-coronavirus/
