### ISSUE TITLE
Raccolta fondi per l'Ospedale di #Camerino organizzata dai tifosi Boys Settempeda - #SanSeverinoMarche

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#984]
<pre><yamldata>
Descrizione: Raccolta fondi per l'Ospedale di Camerino - Boys Settempeda organizza
  questa raccolta fondi
Link: https://www.gofundme.com/f/raccolta-fondi-coronavirus-marche
Nome: Ospedale Camerino
Posizione: 43.22902 13.17797 0 0 
</yamldata></pre>

**Comment by luciaroma** [comment]
raccolta fondi chiusa
