### ISSUE TITLE
Video complottista

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#985]
<pre><yamldata>
Cosa: Video complottista
Descrizione: Video pubblicato sulla piattaforma YouTube che invita i cittadini a violare
  la quarantena e uscire di casa adducendo a strampalate teorie complottiste.
Link: https://youtu.be/F50aEv_j9_Y
</yamldata></pre>

**Comment by cristigalas** [comment]
Questo tipo di segnalazioni non le accetterei, non è una vera e propria bufala... Youtube è pieno di questi video. E poi nella segnalazione c’è il link al video e non eventualmente alla notizia che denuncia il video e ci siamo detti di non promuovere i link delle bufale...
