### ISSUE TITLE
Corona Data Scraper

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#986]
<pre><yamldata>
Cosa: Corona Data Scraper
Descrizione: Good source of worldwide corona patients/infected data in usable formatshttps://coronadatascraper.com/#home
Fonte: Citizen Science discussion group
Link: https://coronadatascraper.com/#home
</yamldata></pre>

**Comment by FrancescaZambi89** [comment]
@luciaroma @chiccap c'è qualche indicazione per segnalazioni di iniziative legate ai dati promosse da altri? non saprei come verificare l'affidabilità... lascio a voi!

**Comment by chiccap** [comment]
> @luciaroma @chiccap c'è qualche indicazione per segnalazioni di iniziative legate ai dati promosse da altri? non saprei come verificare l'affidabilità... lascio a voi!

Se non sono dati ufficiali non li accettiamo.
