### ISSUE TITLE
nelle chat gira questo, pare bufala ma non sono riuscita a verificare

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#989]
<pre><yamldata>
Cosa: nelle chat gira questo, pare bufala ma non sono riuscita a verificare
Descrizione: "Ti giro messaggio da vicecomandante dei carabinieri manda questo appello\
  \      * Urgente molto urgente ... *\n\nSi prega di passare a tutti !!!\n\nNon rispondere\
  \ ai seguenti numeri:\n+375602605281,\n+37127913091\n+37178565072\n+56322553736\n\
  +37052529259\n+255901130460\n o qualsiasi numero che inizi con il:\n +375, +371,\
  \ +381, +255 ecc. ecc.\nNon dovete rispondere. Se rispondete dovete riagganciare\
  \ subito. Non dovete assolutamente richiamare. Potrebbero copiare l'elenco dei vostri\
  \ contatti in 3 secondi.\n Se avete dati sensibili come quelli del conto banca o\
  \ i \ndati della carta di credito sul telefono, possono copiarli.\nChiamano da paesi\
  \ stranieri..\n+375 È dalla Bielorussia.\n +371 È il codice per Lativa.\n +381 Serbia\n\
  + 563- Valparaiso\n+ 370- Vilnius\n+ 255- Tanzania\nInoltre, non bisogna assolutamente\
  \ premere\n # 90 o # 09\n sul vostro cellulare se  chiesto da qualsiasi chiamante.\n\
  Si tratta di un nuovo trucco per accedere alla scheda SIM, effettuare chiamate a\
  \ vostre spese e f potrebbero farvi incorrere in problemi con la giustizia.\nInoltrare\
  \ questo messaggio a tutti gli amici, fermiamoli.\n+39 338 858 7824 ha abbandonato"
</yamldata></pre>

**Comment by favoeva** [comment]
Non è collegata a emergenza coronavirus . Non accetterei
