### ISSUE TITLE
#Regione Lombardia: ordinanza del 21/3/2020

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#990]
<pre><yamldata>
Cosa: '#Regione Lombardia: ordinanza del 21/3/2020'
Descrizione: 'ULTERIORI MISURE PER LA PREVENZIONE E GESTIONE DELL’EMERGENZA EPIDEMIOLOGICA
  DA COVID-19. ORDINANZA AI SENSI DELL’ART. 32, COMMA 3, DELLA LEGGE 23 DICEMBRE 1978,
  N. 833 IN MATERIA DI IGIENE E SANITÀ PUBBLICA: LIMITAZIONE DEGLI SPOSTAMENTI SU
  TUTTO IL TERRITORIO REGIONALE'
Fonte: Regione Lombardia
Link: https://www.regione.lombardia.it/wps/wcm/connect/7cffa84f-f4b2-4558-9092-99c6571f5a3d/Ordinanza+514.pdf?MOD=AJPERES&CACHEID=ROOTWORKSPACE-7cffa84f-f4b2-4558-9092-99c6571f5a3d-n3-Pa3e
</yamldata></pre>

**Comment by FrancescaZambi89** [comment]
Tra le fonti istituzionali in piattaforma c'è già un link che rimanda alla sezione CoronaVirus della Regione Lombardia; è la #issue208. 
Per questo ho messo label "non accettato" e chiuso la issue
