### ISSUE TITLE
#RegionePiemonte: decreto nº34 del 21/3/2020

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#993]
<pre><yamldata>
Cosa: '#RegionePiemonte: decreto nº34 del 21/3/2020'
Descrizione: Ordinanza che contiene un’ulteriore stretta delle misure per il contenimento
  del Coronavirus per il periodo che va dal 22 marzo al 3 aprile 2020.
Fonte: Regione Piemonte
Link: https://www.regione.piemonte.it/web/sites/default/files/media/documenti/2020-03/decreto_n._34_del_21_marzo_2020.pdf.pdf
</yamldata></pre>

**Comment by FrancescaZambi89** [comment]
già inserito link istituzionale in #issue211, non accettata e chiusa
