### ISSUE TITLE
VIDEO YouTube

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#994]
<pre><yamldata>
Cosa: VIDEO YouTube
Descrizione: Parla di una teoria secondo la quale durante dei Giochi militari che
  si sono svolti a Wuhan, gli americani abbiano deliberatamente liberato un virus
  bio-ingegnerizzato. Come giornalismo d'inchiesta sembra approssimativo, visto che
  come fonte cita quasi esclusivamente video di YouTube o articoli che non esistono
  più. Non lo so, magari voi avete più strumenti di me per fare chiarezza
Link: https://youtu.be/t_ub8R5l73w
</yamldata></pre>

**Comment by chiccap** [comment]
presente #1016
