### ISSUE TITLE
#RIMANETE A CASA - CI SONO LORO PER TUTTO

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/covid19italia_segnalazioni#995]
<pre><yamldata>
Da_chi_offerta: ELENA LUISI, Consigliere del Comune di Seravezza
Descrizione: 'Al link elenco in aggiornamento degli ESERCIZI COMMERCIALI che consegnano
  la spesa a domicilio.

  Anche alcune ASSOCIAZIONI DI VOLONTARIATO disponibili con i loro volontari, a consegnare
  a casa beni di prima necessità, per anziani, malati o persone costrette a rimanere
  a casa per il CORONAVIRUS.

  Su tutto il territorio della VERSILIA'
Destinatari: TUTTI
Link: https://www.facebook.com/elena.luisi.12/posts/1477980665713976
Natura: solidale
Tipo_di_soggetto: privato
Titolo: '#RIMANETE A CASA - CI SONO LORO PER TUTTO'
</yamldata></pre>

**Comment by FrancescaZambi89** [comment]
già inserita in issue #992 - non accettata e chiusa
